### DISCUSSION TITLE
LabelSelector design principle ?

### DISCUSSION THREAD

**Discussion by XMingG99** [karmada-io/karmada#3069] [Q&A] [answered]
My PropagationPolicy looks like this. 
```
apiVersion: policy.karmada.io/v1alpha1
...
spec:
...
  placement:
  clusterAffinity:
    labelSelector:
      matchLabels:
        type: local
```
Then, when deploying, the cluster with label `type: local` will be deployed resources. In this case, when I label other clusters without labels, the cluster will also be deployed with the same resources. However, when the cluster with deployed resources has removed its label, the deployed resources of the cluster will not be deleted. What is the consideration here? (Why not delete the deployed resources?)
