### DISCUSSION TITLE
types有哪些取值范围，配置错误不提示取值范围，除了CrossCluster还有哪些

### DISCUSSION THREAD

**Discussion by 13567436138** [karmada-io/karmada#4630] [Q&A]
```
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
   name: nginx-service
spec:
   types:
   - aa
   serviceProvisionClusters:
   - cluster1
   - cluster2
   serviceConsumptionClusters:
   - cluster1
```
