### DISCUSSION TITLE
Support for running Multi-Cluster Argo Workflows

### DISCUSSION THREAD

**Discussion by dmildh-absci** [karmada-io/karmada#5232] [Q&A]
Hello Karmada Gurus!  I am in the process of seeing if I can get Karmada working to support a Multi-Cluster setup similar to how one of the Kubestellar folks documented this [here](https://dettori.medium.com/harnessing-the-power-of-multi-cluster-argo-workflows-with-kubestellar-9dd5582e76bb).  So far I have the kind cluster setup from your repo that stood up the control cluster with the Karmada api components and the 3 member servers. I have also installed Argo workflows on the member clusters and the Karama-host and current am able to submit the below sample workflow and see it get created on the member servers but what I am trying to do is similar to the Kubesteller article in which you would preferably have a single workflow UI that can show you the status of all of the member cluster's workflows and not quite sure if this is supported.  I think this could be a really useful use case for those that are trying to set this up along with some supporting docs and some example code.  

I have diagrammed out the design below to help clarify what I think it would looks like but not sure yet about the Argo Workflows server component and where that sits.

![Multi-Cluster Overview](https://github.com/user-attachments/assets/de824a7a-dfee-47eb-afeb-493f419bf2f0)

Here is the example workflow and propagation policy I am using.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    app: sample0
  name: sample0
  namespace: argo
spec:
  parallelism: 1
  serviceAccountName: default
  entrypoint: volumes-existing-example
  tolerations:
  - key: 'key'
    operation: 'Equal'
    value: 'value'
    effect: 'NoSchedule'

  templates:
  - name: volumes-existing-example
    steps:
    - - name: hello
        template: whalesay

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 1Mi

---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: sample0
  namespace: argo
  labels:
    app: sample0
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      name: sample0
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
```

If anyone can provide any guidance on this or can help please let me know.
