### ISSUE TITLE
Add more information for `rb` and `work` when executing `kubectl get`

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1101]
**What would you like to be added**:
Add more message for `resourcebinding` and `work` when executing `kubectl get`
Like
```bash
[root@master67 yaml]# kubectl get work -A
NAMESPACE          NAME                    TYPE       APPLIED    AGE
karmada-es-bj-47   nginx-config-fcc485d5   ConfigMap  True       125m
```
```bash
[root@master67 yaml]# kubectl get rb -A
NAMESPACE   NAME                     FULLYAPPLIED    AGE
default     nginx-config-configmap   True            133m
```
Specific presentation information needs to be discussed.

**Why is this needed**:
Although `resourcebinding` and `work` are intermediate resources, they are also benefited for multi-clusters manager. We can check if resources are deployed successfully and status of resource.

We can't ops only depending template resource, as a multi-cluster user, we must understand these concepts of `rb` and `work` to better manage the clusters.

For `work`, because it corresponds to a resource in a member cluster, we can access to single resource of member cluster from this portal.

By reason of the foregoing, if necessary, I would like to enhance it.

**Comment by RainbowMango** [comment]
For `RB`/`CRB`:
We've introduced `Scheduled` and `FullyApplied` conditions, so it's reasonable to show the conditions just like the what we did on `Clusters`: https://github.com/karmada-io/karmada/blob/0f49852ad5fc16a04bf1c32e2bb81023cfdfd368/pkg/apis/cluster/v1alpha1/types.go#L15

**Comment by RainbowMango** [comment]
For `Work`, we can show the `Applied` condition too. 
But for `TYPE`, It'll be a little bit involved since there may be more than one `Workload`s in a `Work` object. How to deal with that?

**Comment by lonelyCZ** [comment]
> But for `TYPE`, It'll be a little bit involved since there may be more than one `Workload`s in a `Work` object. How to deal with that?

It is a question. But now, how do we set more than one `Workload`s in a `Work`? I found there is a one-to-one correspondence between work and workload from below codes.
https://github.com/karmada-io/karmada/blob/0f49852ad5fc16a04bf1c32e2bb81023cfdfd368/pkg/controllers/binding/common.go#L141-L147

**Comment by RainbowMango** [comment]
Yes, for now, we only set one workload to each `Work`, I'm not sure if this would change in the future.

By the way, how to show the types out? Is there a solution?

**Comment by lonelyCZ** [comment]
> By the way, how to show the types out? Is there a solution?

It is required to be researched.

I consider another solution that is adding workload type in `work` name that is more convenient for debuging  `work`, but I worry the name is too long referring to #509

**Comment by RainbowMango** [comment]
> I consider another solution that is adding workload type in work name that is more convenient for debuging work, but I worry the name is too long referring to #509

Yeah, that does not work.

**Comment by lonelyCZ** [comment]
> > By the way, how to show the types out? Is there a solution?
> 
>It is required to be researched.

It seems to get Workload type by `.status.manifestStatuses`, but it is a list, so we need to decide to if show the Workload type firstly.

```yaml
apiVersion: work.karmada.io/v1alpha1
kind: Work
metadata:
  annotations:
    resourcebinding.karmada.io/name: nginx-config-configmap
    resourcebinding.karmada.io/namespace: default
  creationTimestamp: "2021-12-13T20:52:46Z"
......
status:
  conditions:
  - lastTransitionTime: "2021-12-13T20:52:46Z"
    message: Manifest has been successfully applied
    reason: AppliedSuccessful
    status: "True"
    type: Applied
  manifestStatuses:
  - identifier:
      kind: ConfigMap
      name: nginx-config
      namespace: default
      ordinal: 0
      resource: ""
      version: v1
```
