### ISSUE TITLE
ERROR: failed to get Karmada API server IP after creating service 'karmada-apiserver' (host cluster type: remote)

### ISSUE THREAD

**Issue by lokichoggio** [karmada-io/karmada#1118]
hack/remote-up-karmada.sh ~/.kube/config xxxxxxxx

```
Generating a 2048 bit RSA private key
................................................................+++
...........................+++
writing new private key to '/home/infra-test-1/.karmada/server-ca.key'
-----
2021/12/16 08:28:00 [INFO] generate received request
2021/12/16 08:28:00 [INFO] received CSR
2021/12/16 08:28:00 [INFO] generating key: rsa-2048
2021/12/16 08:28:00 [INFO] encoded CSR
2021/12/16 08:28:00 [INFO] signed certificate with serial number 463513430843397203906026891263135242193120249292
namespace/karmada-system created
serviceaccount/karmada-controller-manager created
serviceaccount/karmada-scheduler created
serviceaccount/karmada-webhook created
clusterrole.rbac.authorization.k8s.io/karmada-controller-manager unchanged
clusterrolebinding.rbac.authorization.k8s.io/karmada-controller-manager unchanged
secret/karmada-cert-secret created
secret/kubeconfig created
secret/webhook-cert created
statefulset.apps/etcd created
service/etcd-client created
service/etcd created
wait the etcd ready...
pod/etcd-0 condition met

Apply dynamic rendered apiserver service in /tmp/tmp.Bx3mZUefE7/karmada-apiserver.yaml.
deployment.apps/karmada-apiserver created
service/karmada-apiserver created
wait the karmada-apiserver ready...
pod/karmada-apiserver-658699dff-d9qcn condition met
Get service external IP: <no value>, wait to check network connectivity

ERROR: failed to get Karmada API server IP after creating service 'karmada-apiserver' (host cluster type: remote), please verify
```

my karmada-apiserver.yaml as follow
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: karmada-apiserver
  namespace: karmada-system
  labels:
    app: karmada-apiserver
spec:
  ports:
    - name: karmada-apiserver-kubectl
      port: 5443
      protocol: TCP
      targetPort: 5443
  selector:
    app: karmada-apiserver
  type: {{service_type}}

```
