### ISSUE TITLE
introduce configuration profile to manage plugins

### ISSUE THREAD

**Issue by kerthcet** [karmada-io/karmada#1139]
**What would you like to be added**:
Introduce a new struct named `KubeSchedulerProfile` to manage plugins
something like kubernetes:
```
type KubeSchedulerProfile struct {
	Plugins *Plugins
	PluginConfig []PluginConfig
}
```
**Why is this needed**:
Now, plugins in karmada are locked by source code which is unextensible, and the power of plugins haven't been exploitted.
Besides, if we don't set any configuration, default profile will take over, it's backwards compatible.

**Comment by RainbowMango** [comment]
Is it the same profile thing we discussed before @Garrybest ?
Also cc @dddddai .

**Comment by dddddai** [comment]
> Is it the same profile thing we discussed before?

I think it's irrelevant to the previous discussion, and I'm ok with it, which makes the scheduler more extensible

**Comment by kerthcet** [comment]
Yep, I'll work on it then.

**Comment by RainbowMango** [comment]
Thanks @kerthcet, but I didn't get it yet, how to use this `KubeSchedulerProfile` to extend plugins?

**Comment by kerthcet** [comment]
sorry, I didn't explain it clearly. Let's see some implementations in kubernetes. 
Now we can configure our scheduler like this:
```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/kube-scheduler/kubeconfig.yaml"
leaderElection: true
profiles:
- plugins:
    filter:
      enabled:
      - name: "A-plugin"
      - name: "B-plugin"
      - name: "C-plugin"
      disabled:
      - name: "D-plugin"
    score:
      enabled:
      - name: "A-plugin"
  pluginConfig:
  - name: "A-plugin"
    args:
      xxx: "yyy"
```
My concern is about the field profiles, it's named `KubeSchedulerProfile`. In this file, we enabled Plugin A,B,C and disabled plugin D in filter extension point, and we enabled Plugin A in score extension point. (just ignore other fields since not necessary now e.g. pluginConfig)

 If we introduce this feature into karmada, then we can control the karmada intree plugins on/off/order with this configuration file. What's more, we can migrate other configuration fields to this file too if needed.
 
@RainbowMango
