### ISSUE TITLE
The karmada scheduler cannot perform accurate rescheduling work after the cluster recovers from a failure.

### ISSUE THREAD

**Issue by hansedong** [karmada-io/karmada#1189]
**What you expected to happen**:

I am testing the failover capability of karmada. I have 2 clusters (member1 and member2), and the scheduling strategy is devided with equal weights. The expected situation is:
1. If a cluster (called member1) fails, the pods on this member1 will be distributed to other clusters (member2) to meet the total expected number of the Deployment in Karmada.
2. After the member1 recovers from the failure, the scheduler of karmada can perform rescheduling, and member2 restores the number of Pods.

**What happened**:

When the replicas of Deployment is 4 and the cluster weights are equal, there are 2 Pods in member1 and 2 Pods in member2, which matches the expected result.

When member1 failed, the Pods in member2 changed from 2 to 4, which met the expected result.

However, when member1 recovers from the failure, there are still 4 Pods in member2, and the number of Pods in member1 is 0, which does not match the expected result.Because the distribution strategy I configured before is equal, so when all clusters are in a normal state, the final result should be consistent with the distribution strategy.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create Deploymewnt in karmada cluster

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - image: nginx
        name: nginx
```

2. Create a PropagationPolicy in the karmada cluster

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-test
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
```

3. Simulate the loss of connection between Karmada and member1 cluster (assuming that the cluster address of member1 is 10.72.8.8).

```shell
ip route add blackhole 10.72.8.8/32
```

4. Wait for a while and let Karmada scheduler perform rescheduling work until the number of Pods in the member1 cluster can be observed to change from 2 to 4.

5. Restore the network connection between Karmada and the member1 cluster.

```shell
ip route del blackhole 10.72.8.8/32
```

6. Wait for a while (Karmada resumes the communication of member2), and observe whether the number of Pods in the member2 cluster is 2 and is the same as the number of Pods in the member1 cluster.

**Anything else we need to know?**:

I saw other people mentioned similar issues before（#744）, but it was not the same as mine. 

I'm not sure if this is a bug. In addition, Karmada's README.md mentions that it supports failover, but it doesn't explain what its specific capabilities are.

**Environment**:
- Karmada version: v0.10.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):v0.10.1
- Others:
K8s version: 1.22.4
