### ISSUE TITLE
Deploy `karmada-aggregated-apiserver` fllowing the upgrading doc but failed.

### ISSUE THREAD

**Issue by 1285yvonne** [karmada-io/karmada#1214]
**Please provide an in-depth description of the question you have**:

When I deployed the `karmada-aggregated-apiserver` following this documents  https://github.com/karmada-io/karmada/blob/master/docs/upgrading/v0.10-v1.0.md, I found the `APIService` couldn't work because of a wrong serivce type.

```yaml
status:
    conditions:
    - lastTransitionTime: "2022-01-04T11:29:32Z"
      message: unsupported service type "ExternalName"
      reason: FailedDiscoveryCheck
      status: "False"
      type: Available
```

I should modify the Yaml like this to make it work:

```yaml
apiVersion: v1
kind: Service
metadata: 
  name: karmada-aggregated-apiserver
  namespace: karmada-system
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: karmada-aggregated-apiserver
  namespace: karmada-system
subsets:
- addresses:
  - ip: x.x.x.x
  ports:
  - port: 443
```

**What do you think about this question?**:

Is that situation is expected? Or it's a doc error? Or Did I made any mistake during the process?

**Environment**:
- Karmada version: v1.0.0
- Kubernetes version: karmada-host: v1.21.1, karmada-apiserver: v1.21.7
- Others:

**Comment by XiShanYongYe-Chang** [comment]
I think that's what caused it: `message: unsupported service type "ExternalName"`.

**Comment by XiShanYongYe-Chang** [comment]
Hi @1285yvonne, are there any settings that make the service of the `ExternalName` type unavailable?

**Comment by RainbowMango** [comment]
> unsupported service type "ExternalName"

Never met this issue before. 

Can you help test if the following yaml could be applied to your system(karmada-apiserver)?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: default
spec:
  type: ExternalName
  externalName: example.com
```
