### ISSUE TITLE
OverridePolicy should not allowed override namespace

### ISSUE THREAD

**Issue by weilaaa** [karmada-io/karmada#1215]
What happened?
- **operate**: I create a cr in default namespace, and use PropagationPolicy spread it, then I use OverridePolicy to Override namespace of cr.
- **result**：there are two Works with different namespace prefix, when delete OverridePolice I got an error:
```log
E0105 09:22:03.523151       1 workstatus.go:87] Failed to get manifestIndex of workload in work.Spec.Workload.Manifests. Error: no such manifest exist.
E0105 09:22:03.523162       1 binding_controller.go:103] Failed to aggregate workStatuses to resourceBinding(default/zk-pythia-zookeepercluster). Error: no such manifest exist.
```

Version
v0.8.0

Why this?
GetManifestIndex() cloud not find manifest index when namespace changed, same as kind/name/apiversion. 
So If we need add validation in override policy webhook to avoid user to override those field? 

https://github.com/karmada-io/karmada/blob/9f68b793e7efe9c9e80536a13df432ebb4b9a931/pkg/util/helper/workstatus.go#L179-L196

**Comment by RainbowMango** [comment]
Long time no see @weilaaa :)

**Comment by weilaaa** [comment]
Nice to see ya, I will reopen it after make it more details

**Comment by RainbowMango** [comment]
Hi @weilaaa ,

Why are you trying to override the namespace? What is the use case?

Does this issue still exist on the latest v1.0? Can you post the related yaml here by the way?

**Comment by weilaaa** [comment]
Yes, still in head.

Related yamls bellows:
```
# nginx deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

```
# deployment PropagationPolicy
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
```

```
# deployment override
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: nginx-override
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  overrideRules:
    - targetCluster:
        clusterNames:
          - member1
      overriders:
        plaintext:
          - path: "/metadata/namespace"
            operator: replace
            value: ns-1
```

After you Applied, you will get ResourceBinding bellow:
```
spec:
  clusters:
  - name: member1
    replicas: 1
  - name: member2
    replicas: 1
  replicas: 2
  resource:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
    namespace: default # not be override here
    resourceVersion: "5717"
    uid: 01a8be03-2f1c-49a4-9b64-97b83e728f8b
```

Meanwhile, you will get two works for member1(I expected there is one work)

```
➜  demo kubectl get work -n karmada-es-member1 | grep nginx
nginx-687f7fb96f                    True      8m58s
nginx-85545677f9                  True      4m57s
```

The one with ns-1 namepsace of identifier

```
  - identifier:
      group: apps
      kind: Deployment
      name: nginx
      namespace: ns-1
      ordinal: 0
      resource: ""
      version: v1
```

The another with default namespace of identifier

```
  - identifier:
      group: apps
      kind: Deployment
      name: nginx
      namespace: default
      ordinal: 0
      resource: ""
      version: v1
```

What's more, you can find error log in karmada-controller-manager as bellow:

```
E0107 07:28:03.360120       1 workstatus.go:124] Failed to get manifestIndex of workload in work.Spec.Workload.Manifests. Error: no such manifest exist.
E0107 07:28:03.366217       1 binding_controller.go:130] Failed to aggregate workStatuses to resourceBinding(default/nginx-deployment). Error: no such manifest exist.
```

Going member1 cluster, you will see two nginx deployment in different namespace(I expected one in ns-1)

```
Switched to context "member1".
➜  demo kubectl get deploy -A | grep nginx               
default              nginx                    0/1     1            0           12m
ns-1                 nginx                     0/1     1            0           8m50s
```

When you try to delete OverridePolicy, you will get error again, and work would not be deleted, neither deployments.

```
➜  demo kubectl delete -f overridepolicy.yaml       
overridepolicy.policy.karmada.io "nginx-override" deleted
➜  demo kubectl get work -n karmada-es-member1 | grep nginx
nginx-687f7fb96f                    True      14m
nginx-85545677f9                  True      10m
```
