### ISSUE TITLE
karmadactl output format with more information such as -owide

### ISSUE THREAD

**Issue by Chenhb123** [karmada-io/karmada#1219]
**Please provide an in-depth description of the question you have**:
After I added multiple external clusters in Karmada, I can view cluster resource information using the karmadactl command without having to switch contexts or specify configuration files,This becomes more and more useful👍 when there are more and more clusters:
```bash
root@stor01[karmada]# export KUBECONFIG=/root/.kube/karmada.config
root@stor01[karmada]# karmadactl get po
The karmadactl get command now only supports Push mode, [ karmada-apiserver ] are not push mode

NAME                                      CLUSTER               READY   STATUS    RESTARTS   AGE
nfs-client-provisioner-788786ff4d-5wznv   kubernetes-admin144   1/1     Running   0          7d1h
web-0                                     kubernetes-admin144   1/1     Running   0          85m
web-1                                     kubernetes-admin144   1/1     Running   0          85m
nginx-86c57db685-4t2ks                    localhost             1/1     Running   0          42m
nginx-86c57db685-9gdn9                    localhost             1/1     Running   0          42m
nginx-86c57db685-dnc85                    localhost             1/1     Running   0          42m
nginx-789fb764bf-5qvgj                    member1               0/1     Pending   0          42m
nginx-789fb764bf-k24tb                    member1               0/1     Pending   0          42m
nginx-789fb764bf-xx6gh                    member1               0/1     Pending   0          42m
root@stor01[karmada]# karmadactl get po -C=localhost
NAME                     CLUSTER     READY   STATUS    RESTARTS   AGE
nginx-86c57db685-4t2ks   localhost   1/1     Running   0          42m
nginx-86c57db685-9gdn9   localhost   1/1     Running   0          42m
nginx-86c57db685-dnc85   localhost   1/1     Running   0          42m
```
However, when I tried to use Karmadactl to get resource details, I ran into a problem. In k8s, you can use specific commands to query resource details:
```bash
root@stor01[karmada]# kubectl --kubeconfig=/root/.kube/config get po -owide
NAME                     READY   STATUS    RESTARTS   AGE   IP            NODE     NOMINATED NODE   READINESS GATES
nginx-86c57db685-4t2ks   1/1     Running   0          55m   10.244.1.25   stor02   <none>           <none>
nginx-86c57db685-9gdn9   1/1     Running   0          55m   10.244.2.59   stor03   <none>           <none>
nginx-86c57db685-dnc85   1/1     Running   0          55m   10.244.1.26   stor02   <none>           <none>
root@stor01[karmada]# kubectl --kubeconfig=/root/.kube/config describe po nginx-86c57db685-4t2ks
Name:         nginx-86c57db685-4t2ks
Namespace:    default
Priority:     0
Node:         stor02/10.10.236.173
Start Time:   Wed, 05 Jan 2022 16:00:49 +0800
Labels:       app=nginx
              pod-template-hash=86c57db685
Annotations:  <none>
Status:       Running
IP:           10.244.1.25
IPs:
  IP:           10.244.1.25
Controlled By:  ReplicaSet/nginx-86c57db685
Containers:
  nginx:
    Container ID:   docker://39424deee113cc8e909f7f7719654ff6839fcf15f2f00913e440161b84002fdc
    Image:          nginx
    Image ID:       docker-pullable://nginx@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c9b31
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 05 Jan 2022 16:01:05 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kbfjf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-kbfjf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kbfjf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  55m   default-scheduler  Successfully assigned default/nginx-86c57db685-4t2ks to stor02
  Normal  Pulling    55m   kubelet, stor02    Pulling image "nginx"
  Normal  Pulled     55m   kubelet, stor02    Successfully pulled image "nginx"
  Normal  Created    55m   kubelet, stor02    Created container nginx
  Normal  Started    55m   kubelet, stor02    Started container nginx
root@stor01[karmada]#
```
Therefore, I want to know whether karmadactl will increase the function of viewing resource details to avoid complex command operations under multiple clusters. thanks.
**What do you think about this question?**:
Hope it will increase  the function of viewing resource details such as `karmadactl describe po web-0  -C=member1 -n default`
**Environment**:
- Karmada version:
```bash
root@stor01[karmada]# karmadactl version
karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
root@stor01[/home/chb/karmada/samples/nginx]#
```
- Kubernetes version:
```bash
root@stor01[karmada]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:

**Comment by RainbowMango** [comment]
Good question! I think it's a very useful feature. 

cc @lonelyCZ @lfbear  Any comments?

**Comment by lonelyCZ** [comment]
Greate! I consider we could enhance `karmadactl get` that `aggregate apiserver` has been merged and provide more subcommands.

**Comment by lfbear** [comment]
@QAQ-rookie How about this feature :)

**Comment by Chenhb123** [comment]
@RainbowMango Thank you very much for your reply and look forward to the update of this function☀️

**Comment by RainbowMango** [comment]
You are welcome! Thanks for reaching us though.

**Comment by GitHubxsy** [comment]
- step1: Granting karmada-user authorization  access member cluster，refer to #1187 
- step2: Generating the kubeconfig File，The format is as follows:
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.0.1:5443
  name: karmada-apiserver
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.0.1:5443/apis/cluster.karmada.io/v1alpha1/cluster/member1/proxy
  name: member1
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.0.1:5443/apis/cluster.karmada.io/v1alpha1/cluster/member2/proxy
  name: member2
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.0.1:5443/apis/cluster.karmada.io/v1alpha1/cluster/member3/proxy
  name: member3
contexts:
- context:
    cluster: karmada-apiserver
    user: karmada-user
  name: karmada-user
current-context: karmada-apiserver
kind: Config
preferences: {}
users:
- name: karmada-user
  user:
    client-certificate-data: data
    client-key-data: data
```
- step3：use
Get nodes in member1 cluster : `kubectl get node -owide --cluster=member1`
Get pods in member2 cluster: `kubectl get pod -owide --cluster=member2`

The above we currently have capabilities.We can further optimize:
1. **User does not need to generate kubeconfig**
2. **use karmadactl to obtain objects from multiple clusters at the same time, such as:**
`karmadactl get pod -owide --cluster=member1,member2`
`karmadactl get pod --all-clusters`
