### ISSUE TITLE
hpa not work

### ISSUE THREAD

**Issue by merryzhou** [karmada-io/karmada#1273]
hpa scale up replicas deployment， but karmada will change it back immediately

### how to reproduce:

**PropagationPolicy 如下**：
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - member1
          weight: 1
        - targetCluster:
            clusterNames:
            - member2
          weight: 1
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx
    namespace: default
```

**deployment 如下**：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
```

**hpa如下**：
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 20
```

after create resources as above, both member1 and member2 cluster have same hpa:
```
[root@host ~]# karmadactl get hpa | grep nginx
nginx   member1     Deployment/nginx   <unknown>/20%   2         4         1          41m   N
nginx   member2   Deployment/nginx   <unknown>/20%   2         4         1          41m   N
```

then run cpu benchmark in member1 pod, and the events will like:
```
[root@member1 ~]# kubectl describe hpa nginx
...
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  99% (997m) / 20%
Min replicas:                                          1
Max replicas:                                          4
Deployment pods:                                       1 current / 4 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    SucceededRescale  the HPA controller was able to update the target scale to 4
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
Events:
  Type    Reason             Age               From                       Message
  ----    ------             ----              ----                       -------
  Normal  SuccessfulRescale  7s (x7 over 98s)  horizontal-pod-autoscaler  New size: 4; reason: cpu resource utilization (percentage of request) above target

 
[root@member1 ~]# kubectl describe deploy nginx
...
Events:
  Type    Reason             Age                   From                   Message
  ----    ------             ----                  ----                   -------
  Normal  ScalingReplicaSet  7m28s                 deployment-controller  Scaled up replica set nginx-6d9796ff77 to 1
  Normal  ScalingReplicaSet  4m (x2 over 4m15s)    deployment-controller  Scaled up replica set nginx-6d9796ff77 to 2
  Normal  ScalingReplicaSet  3m45s                 deployment-controller  Scaled up replica set nginx-6d9796ff77 to 3
  Normal  ScalingReplicaSet  89s (x12 over 4m15s)  deployment-controller  Scaled down replica set nginx-6d9796ff77 to 1
  Normal  ScalingReplicaSet  74s (x10 over 3m30s)  deployment-controller  Scaled up replica set nginx-6d9796ff77 to 4
```
and when run:
kubectl get pod --watch :
```
[root@member1 ~]# kubectl get pod --watch
NAME                          READY   STATUS             RESTARTS   AGE
nginx-6d9796ff77-z5kq7     1/1     Running            0          37m
nginx-6d9796ff77-ldj4k     0/1     Pending            0          0s
nginx-6d9796ff77-ldj4k     0/1     Pending            0          0s
nginx-6d9796ff77-ldj4k     0/1     Terminating        0          0s
nginx-6d9796ff77-ldj4k     0/1     Terminating        0          0s
nginx-6d9796ff77-ldj4k     0/1     Terminating        0          0s
nginx-6d9796ff77-ldj4k     0/1     Terminating        0          0s
nginx-6d9796ff77-997w2     0/1     Pending            0          0s
nginx-6d9796ff77-997w2     0/1     Pending            0          0s
nginx-6d9796ff77-997w2     0/1     ContainerCreating   0          0s
nginx-6d9796ff77-997w2     0/1     Terminating         0          0s
nginx-6d9796ff77-997w2     0/1     Terminating         0          4s
nginx-6d9796ff77-997w2     0/1     Terminating         0          4s

```
