### ISSUE TITLE
spreadconstraints[i].MaxGroups invalidate when scaleup replicas

### ISSUE THREAD

**Issue by huone1** [karmada-io/karmada#1323]
**What happened**:
spreadconstraints[i].MaxGroups invalidate when scaleup replicas and the target cluster number  is 3 > MaxGroups(2)
**What you expected to happen**:
the cluster number is in [minGroups, maxGroups]

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
step1: kubectl apply -f deploy.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 110
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```
step 2: kubectl apply -f pp.yaml and check the resource binding
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    spreadConstraints:
      - spreadByField: cluster
        maxGroups: 2
        minGroups: 1
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
```
```
spec:
    clusters:
    - name: member1
      replicas: 56
    - name: member3
      replicas: 54
    replicas: 110
```
step 3: kubectl scale deployment nginx --replicas=180
            check the resouce binding and the cluster number is 3 > maxGroups
```
spec:
    clusters:
    - name: member3
      replicas: 76
    - name: member2
      replicas: 48
    - name: member1
      replicas: 56
    replicas: 180
```
**Environment**:
hack/local-up-karmada.sh and  add a cluster member4
```
[root@esc-hwx yaml]# kubectl get cluster
NAME      VERSION   MODE   READY   AGE
member1   v1.22.0   Push   True    6d3h
member2   v1.22.0   Push   True    6d3h
member3   v1.22.0   Pull   True    6d3h
member4   v1.21.1   Push   True    5d14h
```
- Karmada version: make images in branch master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- 
- Others:
