### ISSUE TITLE
Replica set by overridepolicy will be reset by ReviseReplica interpreterhook

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#1347]
**What happened**:
Replica set by overridepolicy in its `Plaintext` will be reset by ReviseReplica interperterhook

**What you expected to happen**:
Use the replica value after applied override policy as the replica passed to ReviseReplica interpreterhook request, not the original value from targetclusters.

**How to reproduce it (as minimally and precisely as possible)**:
Set an overridepolicy for an deploy which contains replica info in its `Plaintext`, the replica in override policy will not effect.

**Anything else we need to know?**:
If it is a bug, I can work on it.

**Environment**:
- Karmada version: 1.0.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
> Set an overridepolicy for an deploy which contains replica info in its Plaintext, the replica in override policy will not effect.

Can you provide the steps to reproduce it? E.g. the yamls.

cc @XiShanYongYe-Chang @iawia002 

/assign @likakuli 
Feel free to take it once get confirmed by the owners. Thanks!

**Comment by likakuli** [comment]
deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    test: "test"
    test2: "test2"
  name: nginx
  labels:
    app: nginx
    test: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        test: test
    spec:
      containers:
      - image: nginx
        name: nginx
```

override.yaml
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: example-override
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  targetCluster:
    clusterNames:
      - member1
      - member2
  overriders:
    plaintext:
      - path: "/metadata/annotations"
        operator: add
        value:
          foo: foo
      - path: "/spec"
        operator: replace
        value:
          replicas: 1
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
                test: test
            spec:
              containers:
              - image: nginx
                name: nginx
```
propagetion.yaml
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```

First apply the above yaml to cluster
```
kubectl create -f deployment.yaml
kubectl create -f override.yaml
kubectl create -f propagation.yaml
```

then edit the rb object, set replicas for each targetcluster like below.
```
spec:
  clusters:
  - name: member1
    replicas: 3
  - name: member2
    replicas: 3
```

Because the revisereplica operation only be called when replicascheduling if true. After set replicas for targetclusters, the deployment in member cluster will be the same as the deploy's replicas in the karmada cluster, the replicas set by override will be reset which is not expected.

![image](https://user-images.githubusercontent.com/12692304/153196478-197d61cb-1bd4-4881-9e02-ad94da24f659.png)
