### ISSUE TITLE
The karmada scheduler cannot work properly when concurrency

### ISSUE THREAD

**Issue by merryzhou** [karmada-io/karmada#1385]
**What happened**:
 I have 2 clusters (member1 and member2), both allocatable resources are 2C2G. 
And i try to create 20 deployments and 20 propagationpolicies concurrently. All deployments require 1C1G resource, and propagationpolicy spec are all like:
```
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
```
According to the allocatable resources, both member1 and member2 clusters can running 2 deployments, other deployments should not scheduled successfully.  But after testing, 4 deployment scheduled to member2 cluster,  and the pods info:
```
[root@member2 ~]# kubectl get pod
NAME                            READY   STATUS    RESTARTS   AGE
nginx-1-75b946d8f7-kkzzh    1/1     Running   0          62m
nginx-10-6cd59b6d4f-75n9x   0/1     Pending   0          62m
nginx-12-6f7555c7df-52jhv   1/1     Running   0          62m
nginx-14-844c4b4797-q5xhz   0/1     Pending   0          62m
```

**What you expected to happen**:

2 deployments scheduled to member1 cluster， 2 deployments  scheduled to member2 cluster，the remaining deployments should waiting until member cluster has enough resources.

**Environment**:
- Karmada version: v1.0.1
