### ISSUE TITLE
the status FULLYAPPLIED in the resource binding  is true while the resource obj is not scheduled successfully

### ISSUE THREAD

**Issue by huone1** [karmada-io/karmada#1511]
**What happened**:
the rb status FULLYAPPLIED is true while the resource obj is not scheduled successfully
**What you expected to happen**:
the status FULLYAPPLIED in the resource binding  is  false
**How to reproduce it (as minimally and precisely as possible)**:
it can apply the following yaml to reproduce it

the workload yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

the  pp yaml select a cluster which is no existed
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - none
```

the result is 
![image](https://user-images.githubusercontent.com/71266853/159261707-125b04be-c34d-4746-8076-9e62256bbb45.png)

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
