### ISSUE TITLE
How to add or remove targetCluster in  propagationpolicy dynamically?

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#1573]
**Please provide an in-depth description of the question you have**:
Some deployment's replicas be managed by cronhpa, but podtemplates should be managed by karmada; When  cronhpa object is created,  the cronhpa cluster should be added to targetCluster in propagationpolicy dynamically, vice versa; Only in this way, When deployment is updated By karmada, deployment in cronhpa cluster will also be updated
**What do you think about this question?**:
Is it possible to add a new interpreter webhook type that allows users to dynamically add or remove targetCluster in propagationpolicy, and webhook should be called when karmada deployment be updated
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by GitHubxsy** [comment]
When the number of deployment replicas is managed by hpa or cronhpa, Karmada should not update the replicas.When updating other fields such as image, Karmada needs to update it.
Is my understanding correct?

**Comment by CharlesQQ** [comment]
@GitHubxsy correct

**Comment by CharlesQQ** [comment]
@GitHubxsy @RainbowMango 
it seems that workload can only be propagated to  member cluster in replicaScheduling field; like following propagationpolicy spec,workload only can be  propagated to a and b; however, workload should be updated in cluster c when it is updated, Karmada should not update the replicas in cluster c, replicas can be retain by interpreter webhook
```
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - a
      - b
      - c
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - a
            - b
          weight: 1
```
