### ISSUE TITLE
Add a doc guide user propagate namespace by ClusterPropagationPolicy

### ISSUE THREAD

**Issue by hanweisen** [karmada-io/karmada#1760]
**What would you like to be added**:
Add a doc guide user propagate namespace to member cluster manually
**Why is this needed**:
Karmada propagate namespace to all member cluster automatically. Some times user may want to propagate namespace to subset of member cluster. This requirement also mentioned in the last part of this artical [云原生多云应用利器--Karmada 总览篇](https://zhuanlan.zhihu.com/p/455389554).  I have tested Karmada support this requirement but related doc is missing. 
Propagate namespace by `ClusterPropagationPolicy`
1. disable namespacecontroller
`kubectl edit deployment karmada-controller-manager  -n karmada-system`
add `--controllers=-namespace,*` in start command
2. create `ClusterPropagationPolicy`
```
apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: example
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: example
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```
