### ISSUE TITLE
The PULL mode cluster cannot be deleted immediately

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1847]
**What happened**:
When the status of PULL mode cluster is `Unknow`

```
[root@master67 karmada]# kubectl get clusters
NAME      VERSION   MODE   READY     AGE
member1   v1.22.3   Pull   Unknown   5d18h
member2   v1.19.1   Push   True      14d
```

The deleting process is stuck.
```
[root@master67 karmada]# kubectl delete clusters member1
cluster.cluster.karmada.io "member1" deleted
^C
```

Then needing to remove manually `finalizers` filed of `cluster` and all `work` objects, the cluster can be deleted.
```
[root@master67 karmada]# kubectl get work -A
NAMESPACE            NAME                              APPLIED   AGE
karmada-es-member1   cert-manager-674b866f4c           True      5d18h
karmada-es-member1   karmada-impersonator-7cbb6bd5c9   True      5d18h
karmada-es-member1   karmada-impersonator-84f8c8f8c6   True      5d18h
karmada-es-member1   nginx-687f7fb96f                  True      5d18h
```

```
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: "2022-05-05T04:12:42Z"
  finalizers:
  - karmada.io/cluster-controller
```

```
apiVersion: work.karmada.io/v1alpha1
kind: Work
metadata:
  creationTimestamp: "2022-05-05T04:12:42Z"
  finalizers:
  - karmada.io/execution-controller
```

**What you expected to happen**:
The PULL mode cluster can be deleted immediately, not need to remove `finalizers` manually.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): master
- kubectl version: 1.23.5
- Others:
