### ISSUE TITLE
ReplicaSchedulingPolicy Feature

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#192]
**User case**:
- As a user, I have 2 clusters(cluster1, cluster2), I want to run 100 replicas for my deployment, each cluster has a `static` weight preference.
- As a user, I have 2 clusters(cluster1, cluster2), I want to run 100 replicas for my deployment, each cluster has a `dynamic` weight preference, the system manages the weight according to cluster capacity, load.

**Proposal**:
- API:
``` golang
// ReplicaSchedulingPolicy represents the policy that propagates total number of replicas for deployment.
type ReplicaSchedulingPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec represents the desired behavior of ReplicaSchedulingPolicy.
	Spec ReplicaSchedulingSpec `json:"spec"`
}

// PropagationSpec represents the desired behavior of ReplicaSchedulingPolicy.
type ReplicaSchedulingSpec struct {
	// ResourceSelectors used to select resources.
	// +required
	ResourceSelectors []ResourceSelector `json:"resourceSelectors"`

	// TotalReplicas represents the total number of replicas across member clusters.
	// The replicas(spec.replicas) specified for deployment template will be discarded.
	// +required
	TotalReplicas int32 `json:"totalReplicas"`

	// Preferences describes weight for each cluster or for each group of cluster.
	// +required
	Preferences ClusterPreferences `json:"preferences"`
}

// ClusterPreferences describes weight for each cluster or for each group of cluster.
type ClusterPreferences struct {
	// StaticWeightList defines the static cluster weight.
	// +optional
	StaticWeightList []StaticClusterWeight `json:"staticWeightList,omitempty"`

	// DynamicWeightList defines the dynamic cluster weight which maintained by system according to cluster capacity
	// or load, etc.
	// +optional
	DynamicWeightList []DynamicClusterWeight `json:"dynamicWeightList,omitempty"`
}

// StaticClusterWeight defines the static cluster weight.
type StaticClusterWeight struct {
	// TargetCluster describes the filter to select clusters.
	// +required
	TargetCluster ClusterAffinity `json:"targetCluster,omitempty"`

	// Weight expressing the preference to the cluster(s) specified by 'TargetCluster'.
	// Defaults to 0.
	// +optional
	Weight int64 `json:"weight,omitempty"`
}

// DynamicClusterWeight defines the dynamic cluster weight which maintained by system according to cluster capacity
// or load, etc.
type DynamicClusterWeight struct {
	// TODO
}
```

- Example:  specify static weight by cluster names:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
  namespace: foons
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: foons
      name: deployment-1
  totalReplicas: 100
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: [cluster1]
        weight: 1
      - targetCluster:
          clusterNames: [cluster2]
        weight: 3
```
clusters in the `[cluster1]` get `25%` replicas, that is 25.
clusters in the `[cluster2]` get `75%` replicas, that is 75.

- - Example:  specify static weight by cluster labels:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
  namespace: foons
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: foons
      name: deployment-1
  totalReplicas: 100
  preferences:
    staticWeightList:
      - targetCluster:
          labelSelector:
            matchLabels:
              location: us
        weight: 1
      - targetCluster:
          labelSelector:
            matchLabels:
              location: cn
        weight: 3
```
clusters with label `location=us` get `25%` replicas, that is 25.
clusters with label `location=cn` get `75%` replicas, that is 75.

**Iteration Items**
TBD
