### ISSUE TITLE
NodePort provided port is already allocated

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1942]
**What happened**:

 Failed to create resource(kind=Service, default/serve) in cluster member1, err is Service "serve" is invalid: spec.ports[0].nodePort: Invalid value: 30685: provided port is already allocated

![image](https://user-images.githubusercontent.com/17962021/171372350-2abdb765-2054-4566-9451-f49e76515ba6.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. create a svc of NodePort type 
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: serve
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: serve
  type: NodePort
```
2. create PropagationPolicy
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mcs-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: serve
    - apiVersion: v1
      kind: Service
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1

```
3.  restart karmada-controller-manager and check karmada-controller-manager log

**Anything else we need to know?**:

https://github.com/karmada-io/karmada/blob/master/pkg/util/objectwatcher/objectwatcher.go#L76

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
