### ISSUE TITLE
 watch of *v1alpha1.ResourceRegistry ended with: an error on the server

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1943]
**What happened**:
![image](https://user-images.githubusercontent.com/17962021/171382358-a9d9f17a-6ed6-4d88-999f-08658225ef16.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

check karmada-search log

**Anything else we need to know?**:

**Environment**:
- Karmada version: master 
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
@liys87x Could you please take a look?

Seems it's not the same issue I mentioned at https://github.com/karmada-io/karmada/pull/1865#issuecomment-1136670343.

**Comment by liys87x** [comment]
@RainbowMango #1865 Caused by no availabled karmada-search instance when informer starts. This problem doesn't look the same.

**Comment by liys87x** [comment]
@chaunceyjiang You can confirm that subsequent work is OK by adjusting the log level to -v=4

**Comment by chaunceyjiang** [comment]
![image](https://user-images.githubusercontent.com/17962021/171539329-3772e754-a852-436f-b552-8e0dec185c9c.png)

**Comment by liys87x** [comment]
@chaunceyjiang Sorry I couldn't reproduce the problem. Here is an example of `ResourceRegistry`. Can you post your `ResourceRegistry`?
```
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: members
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Pod
    - apiVersion: v1
      kind: Event
  backendStore:
    openSearch:
      addresses:
        - http://10.240.0.100:9200
      secretRef:
        namespace: default
        name: opensearch-account
```

**Comment by chaunceyjiang** [comment]
I can't reproduce it now,maybe my local VM disk is too slow.

my `ResourceRegistry`
``` yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: nginx
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
  targetCluster:
    clusterNames:
    - member1
    - member2
```

**Comment by liys87x** [comment]
I still haven't reproduced the problem, and will keep an eye on it in the future. Adjusting the log level to "-v=4" helps to see more details
```
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - /bin/karmada-search
        - --kubeconfig=/etc/kubeconfig
        - --authentication-kubeconfig=/etc/kubeconfig
        - --authorization-kubeconfig=/etc/kubeconfig
        - --etcd-servers=https://etcd-client.karmada-system.svc.cluster.local:2379
        - --etcd-cafile=/etc/kubernetes/pki/server-ca.crt
        - --etcd-certfile=/etc/kubernetes/pki/karmada.crt
        - --etcd-keyfile=/etc/kubernetes/pki/karmada.key
        - --tls-cert-file=/etc/kubernetes/pki/karmada.crt
        - --tls-private-key-file=/etc/kubernetes/pki/karmada.key
        - --audit-log-path=-
        - --feature-gates=APIPriorityAndFairness=false
        - --audit-log-maxage=0
        - --audit-log-maxbackup=0
        - -v=4
        image: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-search:latest
        imagePullPolicy: IfNotPresent
        name: karmada-search
```
