### ISSUE TITLE
Override supports the sed syntax replace value.

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#199]
**What would you like to be added**:

We suggest adding an OverriderOperator type：

```go
OverriderOpSed     OverriderOperator = "sed"
```

With this type, user can replace part of value in different member cluster.

**Why is this needed**:

User may set different values for the same field in the resource with overridepolicy in different member clusters. For example, the image url of deployment resources varies depending on clusters.

```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: example-override
  namespace: default
spec:
  # restrict resource types that this override policy applies to
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment     # dc-1.registry.io/nginx:1.17.0-alpine
  targetCluster:
    clusterNames:           
      - dc-2-cluster-1
  overriders:
    plaintext:
    - path: "/spec/template/spec/containers/0/image"
      operator: sed
      value: "s/.*.registry.io/dc-2.registry.io/g"    #  sed string
```

**One implementation demo**:

```go
import "github.com/rwtodd/Go.Sed/sed"

// obj is target resource
func parseJSONPatch(obj *unstructured.Unstructured, overriders []policyv1alpha1.PlaintextOverrider) ([]overrideOption, error) {
	patches := make([]overrideOption, 0, len(overriders))
	for _, overrider := range overriders {
		switch overrider.Operator {
		case policyv1alpha1.OverriderOpSed:
			overrideValue, ok, err := unstructured.NestedString(obj.Object, overrider.Path)
			if err != nil {
				return nil, err
			}
			if !ok {
				return nil, fmt.Errorf("path %s is not found in obj", overrider.Path)
			}

			engine, _ := sed.New(strings.NewReader(overrider.Value.String()))
			replaceValue, _ := engine.RunString(overrideValue)

			patches = append(patches, overrideOption{
				Op:    string(policyv1alpha1.OverriderOpReplace),
				Path:  overrider.Path,
				Value: replaceValue,
			})
		default:
			patches = append(patches, overrideOption{
				Op:    string(overrider.Operator),
				Path:  overrider.Path,
				Value: overrider.Value,
			})
		}
	}

	return patches, nil
}
```

The regular expression rquires two fields to implements the replacement function, one is for match, and the other is for replace. However, only one "value" field can be used, so wo use sed syntax for replacement.
