### ISSUE TITLE
Resources cannot delete annotations

### ISSUE THREAD

**Issue by mathlsj** [karmada-io/karmada#1991]
**What happened**:

Deploy a deployment that has two annotations: key1, key2. then propagation to member cluster

In the host cluster:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    key1: value1
    key2: value2
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"key1":"value1","key2":"value2"},"name":"nginx","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.17.0","name":"nginx"}]}}}}
  creationTimestamp: "2022-06-12T12:41:46Z"
  generation: 1
  labels:
    propagationpolicy.karmada.io/name: nginx-propagation
    propagationpolicy.karmada.io/namespace: default
  name: nginx
  namespace: default
  ... ...
```

Going into the member cluster:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    key1: value1
    key2: value2
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"key1":"value1","key2":"value2"},"name":"nginx","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.17.0","name":"nginx"}]}}}}
    resourcebinding.karmada.io/name: nginx-deployment
    resourcebinding.karmada.io/namespace: default
  creationTimestamp: "2022-06-12T12:42:49Z"
  generation: 1
  labels:
    propagationpolicy.karmada.io/name: nginx-propagation
    propagationpolicy.karmada.io/namespace: default
    resourcebinding.karmada.io/key: 687f7fb96f
    work.karmada.io/name: nginx-687f7fb96f
    work.karmada.io/namespace: karmada-es-member1
  name: nginx
  namespace: default
  ... ...
```

Now, we add annotation key3 and delete annotation key2

In the host cluster:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    key1: value1
    key3: value3
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"key1":"value1","key3":"value3"},"name":"nginx","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.17.0","name":"nginx"}]}}}}
  creationTimestamp: "2022-06-12T12:41:46Z"
  generation: 2
  labels:
    propagationpolicy.karmada.io/name: nginx-propagation
    propagationpolicy.karmada.io/namespace: default
  name: nginx
  namespace: default
  ... ...
```

Going into the member cluster, we can see that it dose not delete the annotation key2:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    key1: value1
    key2: value2
    key3: value3
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"key1":"value1","key3":"value3"},"name":"nginx","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.17.0","name":"nginx"}]}}}}
    resourcebinding.karmada.io/name: nginx-deployment
    resourcebinding.karmada.io/namespace: default
  creationTimestamp: "2022-06-12T12:42:49Z"
  generation: 2
  labels:
    propagationpolicy.karmada.io/name: nginx-propagation
    propagationpolicy.karmada.io/namespace: default
    resourcebinding.karmada.io/key: 687f7fb96f
    work.karmada.io/name: nginx-687f7fb96f
    work.karmada.io/namespace: karmada-es-member1
  name: nginx
  namespace: default
  ... ...
```

**What you expected to happen**:

We can delete annotation

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a resource and delete annotation

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
