### ISSUE TITLE
The default storage path for ETCD is inconsistent between the init installation and helm installation

### ISSUE THREAD

**Issue by Momeaking** [karmada-io/karmada#2001]
**What happened**:

Default storage  path of etcd in helm installation mode
```
apiVersion: apps/v1
kind: StatefulSet`
......
          volumeMounts:
            - mountPath: /var/lib/etcd
              name: etcd-data
            - mountPath: /etc/kubernetes/pki/etcd
              name: etcd-certs
          command:
......
      volumes:
        - hostPath:
            path: /var/lib/karmada-etcd
            type: DirectoryOrCreate
          name: etcd-data
        - name: etcd-certs
          secret:
            secretName: karmada-cert-secret
```

Default storage  path of etcd in kubectl-karmada init installation mode

```
#karmada/pkg/karmadactl/cmdinit/kubernetes/statefulset.go

const (
   etcdStatefulSetAndServiceName      = "etcd"
   etcdStatefulSetAPIVersion          = "apps/v1"
   etcdStatefulSetKind                = "StatefulSet"
   etcdContainerClientPortName        = "client"
   etcdContainerClientPort            = 2379
   etcdContainerServerPortName        = "server"
   etcdContainerServerPort            = 2380
   etcdContainerDataVolumeMountName   = "etcd-data"
   **etcdContainerDataVolumeMountPath   = "/var/lib/etcd"**      // etcd path
   etcdContainerConfigVolumeMountName = "etcd-config"
   etcdContainerConfigDataMountPath   = "/etc/etcd" 
   etcdConfigName                     = "etcd.conf"
   etcdEnvPodName                     = "POD_NAME"
   etcdEnvPodIP                       = "POD_IP"
   //secrets name
   etcdCertName = "etcd-cert"
)
```
**What you expected to happen**:

The default storage path is the same 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
**Environment**:
- Karmada version: v1.2.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.2.0
- Others:
