### ISSUE TITLE
Report more detail shceduler event information

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#2026]
**What would you like to be added**:
When I deploy the Resource Interpreter Example

```
apiVersion: workload.example.io/v1alpha1
kind: Workload
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
```

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-workload-propagation
spec:
  resourceSelectors:
    - apiVersion: workload.example.io/v1alpha1
      kind: Workload
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```

The RB's `SCHEDULED` is false.

```
[root@master67 customresourceinterpreter]# kubectl get rb
NAME             SCHEDULED   FULLYAPPLIED   AGE
nginx-workload   False       False          5m52s
```

And the information of `RB` only reports `no clusters fit`, don't find why result in it.

```
Status:
  Conditions:
    Last Transition Time:  2022-06-18T16:33:55Z
    Message:               Failed to apply all works, see status.aggregatedStatus for details
    Reason:                FullyAppliedFailed
    Status:                False
    Type:                  FullyApplied
    Last Transition Time:  2022-06-18T16:33:55Z
    Message:               no clusters fit
    Reason:                BindingFailedScheduling
    Status:                False
    Type:                  Scheduled
Events:
  Type     Reason                  Age                    From                Message
  ----     ------                  ----                   ----                -------
  Normal   SyncWorkSucceed         7m27s (x3 over 7m27s)  binding-controller  Sync work of resourceBinding(default/nginx-workload) successful.
  Normal   AggregateStatusSucceed  7m27s (x3 over 7m27s)  binding-controller  Update resourceBinding(default/nginx-workload) with AggregatedStatus successfully.
  Warning  ScheduleBindingFailed   2m30s (x4 over 7m27s)  karmada-scheduler   no clusters fit
```

Then, I check the logs of  `karmada-scheduler`, I found the reasons.

```
I0618 16:33:55.386789       1 api_installed.go:38] Cluster(member1) not fit as missing API(workload.example.io/v1alpha1, kind=Workload)
I0618 16:33:55.386808       1 generic_scheduler.go:107] cluster "member1" is not fit, reason: no such API resource
I0618 16:33:55.386827       1 generic_scheduler.go:107] cluster "member2" is not fit, reason: cluster had taint {dedicated: }, that the propagation policy didn't tolerate
```

**Why is this needed**:

So, I hope to add more detail event information to `karmada control plane` to rapid position error.
