### ISSUE TITLE
aggregated API  cannot impersonate resource "groups" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#2075]
**What happened**:
When testing an aggregated API, an error is reported using the user in the specified namespace

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/31637804/176161855-f071ae6a-edf1-4282-964f-6480d4bc2c94.png)

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dy-cluster-proxy-clusterrole
rules:
  - apiGroups:
    - 'cluster.karmada.io'
    resources:
    - clusters/proxy
    resourceNames:
    - member4
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dy-cluster-proxy-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dy-cluster-proxy-clusterrole
subjects:
  - kind: ServiceAccount
    name: sa-dy-test
    namespace: ns-dy
  # The token generated by the serviceaccount can parse the group information. Therefore, you need to specify the group information below.
  - kind: Group
    name: "system:serviceaccounts:ns-dy:sa-dy-test"
  - kind: Group
    name: "system:serviceaccounts:ns-dy"
```
member：
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-dy-test
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-dy-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sa-dy-test
subjects:
  - kind: ServiceAccount
    name: sa-dy-test
    namespace: ns-dy
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:  1.1.2

**Comment by XiShanYongYe-Chang** [comment]
Hi @luoMonkeyKing 
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dy-cluster-proxy-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dy-cluster-proxy-clusterrole
subjects:
  - kind: ServiceAccount
    name: sa-dy-test
    namespace: ns-dy
  # The token generated by the serviceaccount can parse the group information. Therefore, you need to specify the group information below.
  - kind: Group
    name: "system:serviceaccounts:ns-dy:sa-dy-test"
  - kind: Group
    name: "system:serviceaccounts:ns-dy"
```
replace to:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dy-cluster-proxy-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dy-cluster-proxy-clusterrole
subjects:
  - kind: ServiceAccount
    name: sa-dy-test
    namespace: ns-dy
  # The token generated by the serviceaccount can parse the group information. Therefore, you need to specify the group information below.
  - kind: Group
    name: "system:serviceaccounts"
  - kind: Group
    name: "system:serviceaccounts:ns-dy"
```
