### ISSUE TITLE
Cluster affinity weight

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#2085]
**What would you like to be added**:

I want to propagate a workload to `member1` cluster firstly, and when `member1` cluster is unhealthy, it can trigger `Failover` to reschedule the workload to `member2`. 

I try to below policy, but it can't prioritize scheduling the workload to `member1` cluster.

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mci-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: web
    - apiVersion: v1
      kind: Service
      name: web
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
    replicaScheduling:
      replicaSchedulingType: Duplicated
```

I research the kubernetes scheduler, there is a [Node affinity weight](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity-weight) function that can implement `Node level` priority scheduling.

```
apiVersion: v1
kind: Pod
metadata:
  name: with-affinity-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - antarctica-east1
            - antarctica-west1
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: label-1
            operator: In
            values:
            - key-1
      - weight: 50
        preference:
          matchExpressions:
          - key: label-2
            operator: In
            values:
            - key-2
```

We also need these `affinity weight` in `Cluster level`.

**Why is this needed**:

Enhance scheduling policy to meet more scenes.

**Comment by lonelyCZ** [comment]
cc @RainbowMango @XiShanYongYe-Chang @Garrybest

**Comment by Garrybest** [comment]
Cool, I have some ideas long time ago, but this API change is obsolete. https://github.com/karmada-io/karmada/pull/842

My plan is to add a new field `propagatePriority []corev1.PreferredSchedulingTerm`, the weight could determine the sequence that we propagate objects.

```yaml
propagatePriority:
- weight: 5
  preference:
    matchExpressions:
    - key: label-1
      operator: In
      values:
      - key-1
- weight: 3
  preference:
    matchExpressions:
    - key: label-2
      operator: In
      values:
      - key-2
```

The weight is used for **sort** instead of **calculating the ratio**. So we could propagate objects towards clusters with label `label-1:key-1`. But if the constraint is not satisfied, e.g. `spreadConstraints` or  `availableReplicas`, then we propagate the rest replicas or resources towards clusters with label `label-2:key-2`.
