### ISSUE TITLE
ingress-nginx does not support MCI derived-service

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#2172]
**What would you like to be added**:
I don't know if other users in the community have this requirement, that is to do 4-layer load access through ingress.
I want derived-service to be able to add endpoint

**Why is this needed**:
When I load the tcp or udp layer 4 network of ingress, I find that it will look for the endpoint of the configuration service. The derived service of karmada mci has no endpoint, only endpoint slices, so the following error will be reported when doing layer 4 network load:
```Service "default/derived-serve" does not have any active Endpoint for TCP port 80```

**Comment by chaunceyjiang** [comment]
>  The derived service of karmada mci has no endpoint, only endpoint slices

 Yes.

https://github.com/karmada-io/karmada/blob/a50e31ddaf2f5f1db8db051e933829af7166f929/pkg/controllers/mcs/service_export_controller.go#L158-L163

> do 4-layer load access through ingress. I want derived-service to be able to add endpoint

Can you give me a minimum reproduce step?

**Comment by luoMonkeyKing** [comment]
> > The derived service of karmada mci has no endpoint, only endpoint slices
> 
> Yes.
> 
> https://github.com/karmada-io/karmada/blob/a50e31ddaf2f5f1db8db051e933829af7166f929/pkg/controllers/mcs/service_export_controller.go#L158-L163
> 
> > do 4-layer load access through ingress. I want derived-service to be able to add endpoint
> 
> Can you give me a minimum reproduce step?



> > The derived service of karmada mci has no endpoint, only endpoint slices
> 
> Yes.
> 
> https://github.com/karmada-io/karmada/blob/a50e31ddaf2f5f1db8db051e933829af7166f929/pkg/controllers/mcs/service_export_controller.go#L158-L163
> 
> > do 4-layer load access through ingress. I want derived-service to be able to add endpoint
> 
> Can you give me a minimum reproduce step?

If you deploy MCI, you can directly modify the deployment of ingress-nginx and add the following configuration to args:
```
     54         - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
     55         - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
```
tcp-service configmap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/component: controller

```
udp-service configmap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/component: controller
```
For details, please refer to this article on the Internet：[ingress-tcp-udp](https://www.likecs.com/show-305332017.html)
