### ISSUE TITLE
an interesting bug

### ISSUE THREAD

**Issue by prodanlabs** [karmada-io/karmada#2173]
**What happened**:
##### First, I created two `Deployment` and one `Service` in the karmada control panel.

<details>
<summary>yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  labels:
    app: helloworld
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v2
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```
</details>

```bash
~# kubectl get deploy,svc -l app=helloworld
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/helloworld-v1   0/1     0            0           51s
deployment.apps/helloworld-v2   0/1     0            0           51s

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/helloworld   ClusterIP   10.102.175.153   <none>        5000/TCP   51s
```

#####  Then, I propagate the `v2` version of Deployment and Service to `dev-cluster-02`
<details>
<summary>yaml</summary>

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: helloworld-v2
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: helloworld
    - apiVersion: apps/v1
      kind: Deployment
      name: helloworld-v2
  placement:
    clusterAffinity:
      clusterNames:
        - dev-cluster-02
```
</details>

good, everything works.
```bash
~# ./kubectl-karmada get po,svc -C dev-cluster-02  -l app=helloworld
NAME                                 CLUSTER          READY   STATUS    RESTARTS   AGE
pod/helloworld-v2-5b46bc9f84-c2fr5   dev-cluster-02   1/1     Running   0          20m

NAME                 CLUSTER          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/helloworld   dev-cluster-02   ClusterIP   10.96.177.86   <none>        5000/TCP   20m
```

#####  Now, I propagate `v1` version of Deployment and Service to `helloworld-v1`
<details>
<summary>yaml</summary>

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: helloworld-v1
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: helloworld
    - apiVersion: apps/v1
      kind: Deployment
      name: helloworld-v1
  placement:
    clusterAffinity:
      clusterNames:
        - dev-cluster-01
```
</details>

Unfortunately, Service did not propagate to `dev-cluster-01`
```bash
~# ./kubectl-karmada get po,svc -C dev-cluster-01  -l app=helloworld
NAME                                CLUSTER          READY   STATUS    RESTARTS   AGE
pod/helloworld-v1-fdb8c8c58-x24nj   dev-cluster-01   1/1     Running   0          26m
```
Unlike `dev-cluster-02`, `dev-cluster-01` does not create Service work
```bash
~# kubectl get works -n karmada-es-dev-cluster-02
NAME                              APPLIED   AGE
helloworld-65955fbf67             True      32m
helloworld-v2-79b557c764          True      32m
karmada-impersonator-7cbb6bd5c9   True      37m
karmada-impersonator-84f8c8f8c6   True      37m
~# kubectl get works -n karmada-es-dev-cluster-01
NAME                              APPLIED   AGE
helloworld-v1-5c658d7767          True      31m
karmada-impersonator-7cbb6bd5c9   True      37m
karmada-impersonator-84f8c8f8c6   True      37m
```
**What you expected to happen**:

Deployment `helloworld-v1` and Service `helloworld` propagated to `dev-cluster-01` cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.2.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.2.0
- Others:

**Comment by prodanlabs** [comment]
I don't know if you have encountered it.
I will debug tomorrow.

**Comment by RainbowMango** [comment]
I'd say, It works as expected. The service has been claimed by PropagationPolicy named `helloworld-v2`, so the following PropagationPolicy can't propagate it.
And the reason is that a `resource template` should only be propagated by one propagation policy.

**Comment by prodanlabs** [comment]
> And the reason is that a resource template should only be propagated by one propagation polic

Why is it designed this way? I don't understand something.

**Comment by RainbowMango** [comment]
For example, the PropagationPolicy(named 1) declares it propagates a `resource template` to cluster `member1`, and in the meantime, another PropagationPolicy(named 2) declares the same `resource template` can't propagate to cluster `member1`.
Then, what can Karmada do with the inconsistent declarations?

**Comment by prodanlabs** [comment]
When the same resource template, when there are two or more PropagationPolicy propagating it to the same member cluster. can be handled like this

However, when there are two or more PropagationPolicy for the same resource template and it is propagated to different member clusters, it is unreasonable to do so.

**Comment by RainbowMango** [comment]
> However, when there are two or more PropagationPolicy for the same resource template and it is propagated to different member clusters, it is unreasonable to do so.

Yes, it's not supported in this scenario. But we have ways to achieve that, like creating another resource template or propagating it with a single PropagationPolicy.

**Comment by prodanlabs** [comment]
> like creating another resource template or propagating it with a single PropagationPolicy.

But doing this is somewhat unacceptable to me, and the user experience is not good.

Of course, everyone's operating habits are different, and I may be an exception.

**Comment by prodanlabs** [comment]
>  propagating it with a single PropagationPolicy.

I tested it and it didn't work.

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: helloworld-test
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: helloworld
  placement:
    clusterAffinity:
      clusterNames:
        - dev-cluster-01
```

```bash
~# kubectl get pp
NAME              AGE
helloworld-test   111s
helloworld-v1     3m54s
helloworld-v2     3m57s
~# ./kubectl-karmada get po,svc -A  -l app=helloworld
NAMESPACE   NAME                                 CLUSTER          READY   STATUS    RESTARTS   AGE
default     pod/helloworld-v2-5b46bc9f84-zctxl   dev-cluster-02   1/1     Running   0          3m59s
default     pod/helloworld-v1-fdb8c8c58-kzvd7    dev-cluster-01   1/1     Running   0          3m55s

NAMESPACE   NAME                 CLUSTER          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
default     service/helloworld   dev-cluster-02   ClusterIP   10.96.151.232   <none>        5000/TCP   3m59s
~# kubectl get works -n karmada-es-dev-cluster-01
NAME                              APPLIED   AGE
helloworld-v1-5c658d7767          True      4m51s
karmada-impersonator-7cbb6bd5c9   True      11h
karmada-impersonator-84f8c8f8c6   True      11h
```

**Comment by RainbowMango** [comment]
Please check the annotation/label if the Service(default/helloworld) has been claimed by other policies.

**Comment by prodanlabs** [comment]
I took a look at the code and maybe I know why.

First we create the resource template, then create the PropagationPolicy to propagate it to the member cluster.If you don't need to propagate to member clusters now, you need to delete the resource template instead of PropagationPolicy.

If a resource template has multiple PropagationPolicy, one PropagationPolicy is propagated to member cluster A, and one PropagationPolicy is propagated to member cluster B. When the resource template does not need to be propagated to member cluster A, it is useless to delete the corresponding PropagationPolicy, and the resource needs to be deleted. template, however, if the resource template is deleted, then member cluster B will be affected.

I don't know if I understand it right.

**Comment by RainbowMango** [comment]
> First we create the resource template, then create the PropagationPolicy to propagate it to the member cluster.If you don't need to propagate to member clusters now, you need to delete the resource template instead of PropagationPolicy.

Why not remove the legacy PropogationPolicy as well?

**Comment by RainbowMango** [comment]
> If a resource template has multiple PropagationPolicy, one PropagationPolicy is propagated to member cluster A, and one PropagationPolicy is propagated to member cluster B

Can not happen as a resource template can only be claimed by `a` PropagationPolicy.

**Comment by prodanlabs** [comment]
> Why not remove the legacy PropogationPolicy as well?

That was not what I meant.

For example, I create a deployment `foo` resource template, then create a PropogationPolicy and propagate it to member cluster A. If `foo` does not need to be propagated to member cluster A now, it is useless to delete the PropogationPolicy. You need to delete the deployment `foo` resource template to achieve the purpose.

**Comment by prodanlabs** [comment]
E.g

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  labels:
    app: helloworld
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v2
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: helloworld-v2
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: helloworld-v2
  placement:
    clusterAffinity:
      clusterNames:
        - dev-cluster-02
```

```bash
~# ./kubectl-karmada get po,svc -C dev-cluster-02 -l app=helloworld   
NAME                                 CLUSTER          READY   STATUS    RESTARTS   AGE
pod/helloworld-v2-5b46bc9f84-xc78m   dev-cluster-02   1/1     Running   0          35s
~# kubectl get pp
NAME            AGE
helloworld-v2   37s
~# kubectl get works -n karmada-es-dev-cluster-02 
NAME                              APPLIED   AGE
helloworld-v2-79b557c764          True      55s
karmada-impersonator-7cbb6bd5c9   True      12h
karmada-impersonator-84f8c8f8c6   True      12h
```

Now, I remove the `PropagationPolicy`, as you can see, the `work` still exists

```bash
~# kubectl get deployments.apps                                       
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
helloworld-v2   1/1     1            1           4m12s
~# kubectl get pp
No resources found in default namespace. 
~# kubectl get works -n karmada-es-dev-cluster-02 
NAME                              APPLIED   AGE
helloworld-v2-79b557c764          True      4m24s
karmada-impersonator-7cbb6bd5c9   True      12h
karmada-impersonator-84f8c8f8c6   True      12h
```

So some conclusions can be drawn:
A resource template can only have one PropagationPolicy.  Because if the resource template has multiple PropagationPolicy, if you need to delete one of the PropagationPolicy, but `works` has not been deleted, you need to delete the resource template to achieve this purpose.
