### ISSUE TITLE
Resources cannot be rescheduled

### ISSUE THREAD

**Issue by first-sight12** [karmada-io/karmada#2188]
**What happened**:
member3集群（两个节点，每个节点CPU为16核）
member4集群（1个节点，每个节点CPU为16核）

deployment.yaml文件如下：
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "9"`

PropagationPolicy文件如下：
`apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member3`

修改后的PropagationPolicy文件如下：
`apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member3
        - member4
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas`

发现资源无法调度：
`[root@master ldy]# kubectl karmada get po
NAME                          CLUSTER   READY   STATUS      RESTARTS   AGE
busybox                       member3   1/1     Running     0          16d
nginx-6468549c48-jmxtr        member3   1/1     Running     0          20m
nginx-6468549c48-t5cjv        member3   1/1     Running     0          20m
nginx-6468549c48-tg258        member3   0/1     Pending     0          20m
`
**What you expected to happen**:
能够根据资源情况自动非配，进行重新调度，一个pod在member4集群，另外两个pod在member3集群

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaunceyjiang** [comment]
你是否部署了`karmada-scheduler-estimator`?

**Comment by RainbowMango** [comment]
第一次提交PropagationPolicy时，使用的策略是：
```
  placement:
    clusterAffinity:
      clusterNames:
        - member3
```
此时是`复制`的，也就是3个副本都分到了member3中。

第二次提交的PropagationPolicy时，使用的策略是：
```
    clusterAffinity:
      clusterNames:
        - member3
        - member4
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
```
此时指示`拆分`副本，因为3个副本都已经分配到`member3`，没有触发重新调度，应该是预期行为。

这种情况，把deployment删除重建是可以的。或者，告诉我们你的场景，看下如何做？
