### ISSUE TITLE
ArgoCD can not assess Deployment health status

### ISSUE THREAD

**Issue by xuqianjins** [karmada-io/karmada#2218]
**What happened**:
`APP HEALTH` is always in `Progressing` state when deploying multi-cluster `DEPLOYMENT` through Argo CD based on Karmada. However, it is normal to deploy `DEPLOYMENT` on a single cluster.

**What you expected to happen**:
`APP HEALTH` should be in `Healthy` state normally.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 7
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:1.23.0
        ports:
        - containerPort: 80
---
kind: PropagationPolicy
apiVersion: policy.karmada.io/v1alpha1
metadata:
  name: nginx
spec:
  resourceSelectors:
  - kind: Deployment
    apiVersion: apps/v1
    name: nginx
  placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - member1
          weight: 5
        - targetCluster:
            clusterNames:
            - member2
          weight: 2
```

**Anything else we need to know?**:
The `status.observedGeneration` field is missing when checking the `DEPLOYMENT` status on the Karmada control plane.

**Environment**:
- Karmada version: 1.2.1
- karmadactl version: 1.2.1
- Kubernetes: 1.21.13
- Argo CD: 2.4.2
