### ISSUE TITLE
使用search查询资源失败（资源存在）

### ISSUE THREAD

**Issue by first-sight12** [karmada-io/karmada#2226]
**What happened**:
转发到单个集群能够查到资源，结果如下：
![image](https://user-images.githubusercontent.com/88825053/179931489-b44a7356-c7b2-4ad2-9d38-3de06ffc49a0.png)

使用search查询为空，结果如下：
![image](https://user-images.githubusercontent.com/88825053/179931693-9e6cfd9e-a163-4e5d-a61d-0ec7cd9fd7b1.png)

karmada-search 日志如下：
![image](https://user-images.githubusercontent.com/88825053/179931900-1d3d4b90-d974-4973-9e6f-4f2a1feb3d6a.png)

**What you expected to happen**:
期望search查询结果与单集群转发结果一致

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by first-sight12** [comment]
> > 有时能查到结果 有时查询为空
> 
> like this issue #1940 

使用的是push模式不是pull模式
```
[root@node1 ~]# kubectl get cluster
NAME      VERSION   MODE   READY   AGE
master    v1.21.5   Push   True    27h
member1   v1.21.5   Push   True    9d
member2   v1.21.5   Push   True    5d2h
```

**Comment by liys87x** [comment]
@first-sight12   
- Please provide the `ResourceRegistry`,  e.g `kubectl get ResourceRegistry xxx -o yaml`
- Please provide more karmada-search logs

**Comment by first-sight12** [comment]
> @first-sight12
> 
> * Please provide the `ResourceRegistry`,  e.g `kubectl get ResourceRegistry xxx -o yaml`
> * Please provide more karmada-search logs

yaml文件如下：
```
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: test
spec:
  targetCluster:
    exclude:
      - master
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Service
    - apiVersion: v1
      kind: Namespace
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
    - apiVersion: v1
      kind: ResourceQuota
    - apiVersion: quota.kubesphere.io/v1alpha2
      kind: ResourceQuota

```
如下资源非kubernetes原生为自定义crd资源
```
- apiVersion: quota.kubesphere.io/v1alpha2
      kind: ResourceQuota ：
```

日志如下：
![image](https://user-images.githubusercontent.com/88825053/180111223-192ef429-e265-484d-8e4e-a33a493ee4ae.png)

![image](https://user-images.githubusercontent.com/88825053/180111277-964ff9db-1adc-4966-9836-bbb458523fe2.png)
