### ISSUE TITLE
Karmada not propagate resources to new member cluster

### ISSUE THREAD

**Issue by liuchintao** [karmada-io/karmada#2261]
**What happened**:

I just want to propagate my deployment to all member clusters automatically, when they join.

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx
```

After creating this PP, I find nginx deployment in cluster-1 and cluster-2.

But when I join a new member cluster-3, I find nginx deployment is not propagated to cluster-3

**What you expected to happen**:

Deployment should be propagated to new member cluster.

```golang
type Placement struct {
	// ClusterAffinity represents scheduling restrictions to a certain set of clusters.
	// If not set, any cluster can be scheduling candidate.
	// +optional
	ClusterAffinity *ClusterAffinity `json:"clusterAffinity,omitempty"`
}
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
