### ISSUE TITLE
Error: [cluster(member1) is inaccessible, please check authorization or network, cluster(member2) is inaccessible, please check authorization or network]

### ISSUE THREAD

**Issue by 631068264** [karmada-io/karmada#2291]
根据https://github.com/karmada-io/karmada/issues/1880 ，用helm安装好

```
kubectl get cluster --kubeconfig karmada-config

NAME      VERSION        MODE   READY   AGE
member1   v1.19.5+k3s2   Pull   True    47h
member2   v1.19.5+k3s2   Pull   True    47h
```

测试demo，想测试分发情况
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---

apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 2
```

收到错误
```
karmadactl get pod --kubeconfig karmada-config
Error: [cluster(member1) is inaccessible, please check authorization or network, cluster(member2) is inaccessible, please check authorization or network]
```

分发效果正常，现在只能跳到对应的节点看效果karmadactl根本用不了

**Environment**:
- Karmada version: 1.2.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): karmadactl version: version.Info{GitVersion:"v1.2.1", GitCommit:"de4972b74f848f78a58f9a0f4a4e85f243ba48f8", GitTreeState:"clean", BuildDate:"2022-07-14T09:33:33Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
- Others:
