### ISSUE TITLE
Cleanup labels from resource template after policy removed

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#243]
**What would you like to be added**:
Once a resource template propagated by a policy, such as PropagationPolicy, we would add labels on the resource template. e.g.
```yaml
- labels:
    propagationpolicy.karmada.io/name: nginx-propagation
    propagationpolicy.karmada.io/namespace: default
```

We should remove the labels after the policy been removed as tracked here:
https://github.com/karmada-io/karmada/blob/d69f65479d2fa0a425661c86b0298025f1381d63/pkg/util/detector/detector.go#L654

https://github.com/karmada-io/karmada/blob/d69f65479d2fa0a425661c86b0298025f1381d63/pkg/util/detector/detector.go#L683

**Why is this needed**:
1. Cleanup the relationship between resource template and policy.
2. Give the resource template a chance to match another policy.
