### ISSUE TITLE
How to implement ArgoRollout Pod resource multi-cluster deploy

### ISSUE THREAD

**Issue by wxuedong** [karmada-io/karmada#2441]
Submit an Argo Rollout CRD definition to Karmada ApiServer

`  kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml `

Deploy nginx image with Rollout workload：

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: nginx-2
  name: nginx-2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  selector:
    matchLabels:
      app: nginx-2
  strategy:
    canary:
      steps:
      - setWeight: 100
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - image: nginx
        name: nginx-2
```

Submit PropagationPolicy definition

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy-rollout
spec:
  resourceSelectors:
    - apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      name: nginx-2 
  placement:
      clusterAffinity:
        clusterNames:
        - member1
        - member2
      replicaScheduling:
        replicaDivisionPreference: Weighted
        replicaSchedulingType: Divided
        weightPreference:
          staticWeightList:
          - targetCluster:
              clusterNames:
              - member1
            weight: 1
          - targetCluster:
              clusterNames:
              - member2
            weight: 2
```

I hope the Rollout strategy implementation is the same as Deployment ，actually only applied to one cluster（member2）

The actual state of the Rollout resource is also not synchronized to the Karmada ApiServer

How to set up multi-cluster scheduling management like Deployment

**Comment by wxuedong** [comment]
> Submit an Argo Rollout CRD definition to Karmada ApiServer
> 
> ` kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml`
> 
> Deploy nginx image with Rollout workload：
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: Rollout
> metadata:
>   labels:
>     app: nginx-2
>   name: nginx-2
>   namespace: default
> spec:
>   progressDeadlineSeconds: 600
>   replicas: 5
>   selector:
>     matchLabels:
>       app: nginx-2
>   strategy:
>     canary:
>       steps:
>       - setWeight: 100
>   template:
>     metadata:
>       labels:
>         app: nginx-2
>     spec:
>       containers:
>       - image: nginx
>         name: nginx-2
> ```
> 
> Submit PropagationPolicy definition
> 
> ```
> apiVersion: policy.karmada.io/v1alpha1
> kind: PropagationPolicy
> metadata:
>   name: example-policy-rollout
> spec:
>   resourceSelectors:
>     - apiVersion: argoproj.io/v1alpha1
>       kind: Rollout
>       name: nginx-2 
>   placement:
>       clusterAffinity:
>         clusterNames:
>         - member1
>         - member2
>       replicaScheduling:
>         replicaDivisionPreference: Weighted
>         replicaSchedulingType: Divided
>         weightPreference:
>           staticWeightList:
>           - targetCluster:
>               clusterNames:
>               - member1
>             weight: 1
>           - targetCluster:
>               clusterNames:
>               - member2
>             weight: 2
> ```
> 
> I hope the Rollout strategy implementation is the same as Deployment ，actually only applied to one cluster（member2）
> 
> The actual state of the Rollout resource is also not synchronized to the Karmada ApiServer
> 
> How to set up multi-cluster scheduling management like Deployment

After reading the introduction, can the following configuration be solved?

```
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterWebhookConfiguration
metadata:
  name: examples
webhooks:
  - name: workloads.example.com
    rules:
      - operations: [ "InterpretReplica","ReviseReplica","Retain","AggregateStatus", "InterpretHealth", "InterpretStatus" ]
        apiGroups: [ "workload.example.io" ]
        apiVersions: [ "v1alpha1" ]
        kinds: [ "Workload" ]
    clientConfig:
      url: https://{{karmada-interpreter-webhook-example-svc-address}}:443/interpreter-workload
      caBundle: {{caBundle}}
    interpreterContextVersions: [ "v1alpha1" ]
    timeoutSeconds: 3

```

[webhook] ( https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml)

Is the webhook-example in the documentation the same as deploying the Karmada APIServer cluster webhook?

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/15843627/187188550-38cd0e1b-74aa-4c05-a24d-b194785ca2fd.png">
