### ISSUE TITLE
About the ResourceInterpreterWebhookConfiguration configuration property definition

### ISSUE THREAD

**Issue by wxuedong** [karmada-io/karmada#2446]
Configure as follows：

```
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterWebhookConfiguration
metadata:
  name: examples
webhooks:
  - name: workloads.example.com
    rules:
      - operations: [ "InterpretReplica","ReviseReplica","Retain","AggregateStatus", "InterpretHealth", "InterpretStatus" ]
        apiGroups: [ "workload.example.io" ]
        apiVersions: [ "v1alpha1" ]
        kinds: [ "Workload" ]
    clientConfig:
      url: https://{{karmada-interpreter-webhook-example-svc-address}}:443/interpreter-workload
      caBundle: {{caBundle}}
    interpreterContextVersions: [ "v1alpha1" ]
    timeoutSeconds: 3

```

`clientConfig:
      url: https://{{karmada-interpreter-webhook-example-svc-address}}:443/interpreter-workload `  

‘{{karmada-interpreter-webhook-example-svc-address}} ’   Is it a webhook installed by default in the karmada cluster? 

‘/interpreter-workload ’   What is the relationship between this path and workload?

‘ {{caBundle}}’   Is this configuration generated by the user in Karmada ApiServer?
