### ISSUE TITLE
How to get Karmada ApiServer certificate

### ISSUE THREAD

**Issue by wxuedong** [karmada-io/karmada#2452]
I submit a resource in a way supported by K8s：

```
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
```

In fact, this resource has never really taken effect，view an event   `  Warning  ApplyPolicyFailed  10m (x2 over 10m)  resource-detector  No policy match for resource`

In this scenario, how can I use the CertificateSigningRequest resource to obtain the Karmada ApiSever certificate, or there are other ways to obtain the certificate.
