### ISSUE TITLE
mcs  服务不能通过derived-serve访问另一个集群

### ISSUE THREAD

**Issue by 631068264** [karmada-io/karmada#2460]
**What happened**:
根据 这个https://karmada.io/docs/userguide/service/multi-cluster-service

应用部署到member1 ,运行正常
```
kubectl --kubeconfig member1-config run tmp-shell --rm -i --tty --image submariner/nettest:0.12.2 -- /bin/bash

curl serve

'hello from cluster 1 (Node: server-605ae265-df2b-4e91-9efa-19069d84f2d0 Pod: serve-59994d98f6-9bzxj Address: 10.44.0.25)'
```

但是member2 访问不了
```
kubectl --kubeconfig member2-config run tmp-shell --rm -i --tty --image submariner/nettest:0.12.2 -- /bin/bash

curl derived-serve
curl: (7) Failed to connect to derived-serve port 80 after 1003 ms: Connection refused
```

```
kubectl --kubeconfig member2-config  get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
derived-serve   ClusterIP   10.47.135.147   <none>        80/TCP    16h
kubernetes      ClusterIP   10.47.0.1       <none>        443/TCP   33d
```

**What you expected to happen**:

mcs.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - name: serve
        image: xxxxx/library/serve:0a40de8
        args:
        - "--message='hello from cluster 1 (Node: {{env \"NODE_NAME\"}} Pod: {{env \"POD_NAME\"}} Address: {{addr}})'"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---      
apiVersion: v1
kind: Service
metadata:
  name: serve
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mcs-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: serve
    - apiVersion: v1
      kind: Service
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1

---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: serve-export-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1


---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: serve
spec:
  type: ClusterSetIP
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: serve-import-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member2

```
部署

```
karmadactl --kubeconfig karmada-apiserver.config apply -f mcs.yaml
```

submariner 已经安装好了实际上也通过了https://submariner.io/operations/usage/#2-export-services-across-clusters测试
部署到member1然后
```
m1=/root/karmada/member1-config

kubectl --kubeconfig ${m1} create deployment nginx --image=nginx
kubectl --kubeconfig ${m1} expose deployment nginx --port=80
subctl export service --kubeconfig ${m1} --namespace default nginx
```
在member2 curl 是通的
```
kubectl --kubeconfig member2-config run tmp-shell --rm -i --tty --image submariner/nettest:0.12.2 -- /bin/bash

bash-5.1# curl nginx.default.svc.clusterset.local
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
```

Environment:
Karmada version: 1.2.1
kubectl-karmada or karmadactl version (the result of kubectl-karmada version or karmadactl version): karmadactl version: version.Info{GitVersion:"v1.2.1", GitCommit:"de4972b74f848f78a58f9a0f4a4e85f243ba48f8", GitTreeState:"clean", BuildDate:"2022-07-14T09:33:33Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Others:

**Comment by 631068264** [comment]
解决了，https://karmada.io/docs/userguide/service/multi-cluster-service/  这里面写得有问题

**Comment by XiShanYongYe-Chang** [comment]
哪里有问题，可以指出来或者提个pr

**Comment by 631068264** [comment]
https://submariner.io/getting-started/architecture/service-discovery/  根据这里面说的关于
Lighthouse Agent和Lighthouse DNS Server的一些工作方式

- service import 根本不用手动部署，Lighthouse Agent已经帮你做了
  ```
kubectl --kubeconfig member2-config get svcim -A
NAMESPACE             NAME                    TYPE           IP                  AGE
submariner-operator   serve-default-member1   ClusterSetIP   ["10.45.84.26"]     13m
```
- 跨集群访问得通过domain `clusterset.local`，需要访问这个curl serve.default.svc.clusterset.local

**Comment by XiShanYongYe-Chang** [comment]
Submarine和Karmada都对MCS API进行了实现，你所指的是Submarine中的实现，与Karmada的实现不冲突。

**Comment by 631068264** [comment]
反正我按照官网走不下去，要不然就是Karmada有bug。

**Comment by 631068264** [comment]
@XiShanYongYe-Chang 所以为什么不行呢？

**Comment by XiShanYongYe-Chang** [comment]
成员集群版本是多少呢？karmada MCS特性当前收集的EndpointSlice v1版本资源，可以到集群`member2`上看下是否有endpointSlice从`member1`上同步过来。

**Comment by 631068264** [comment]
集群版本host member都是: v1.19.5+k3s2

kubectl --kubeconfig member2-config  get endpointSlice -A
NAMESPACE             NAME                                          ADDRESSTYPE   PORTS        ENDPOINTS               AGE
default               nginx-member1                                 IPv4          80           10.44.0.27              5d
default               serve-member1                                 IPv4          8080         10.44.0.29              25h

**Comment by XiShanYongYe-Chang** [comment]
看上去没有同步成功，如果成功同步的化，会有`imported-`开头的endpointSlice，如：
![image](https://user-images.githubusercontent.com/78244870/188583071-b7f05921-badd-4ed7-ad15-0603060b3d8f.png)

EndpointSlice版本确认下是不是v1的呢（k8s集群1.21开始使用v1版本EndpointSlice）。

**Comment by 631068264** [comment]
不是
```yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1beta1
endpoints:
- addresses:
  - 10.44.0.27
  conditions:
    ready: true
  hostname: nginx-6799fc88d8-b7xmw
  topology:
    kubernetes.io/hostname: server-605ae265-df2b-4e91-9efa-19069d84f2d0
kind: EndpointSlice
metadata:
```
