### ISSUE TITLE
mci 遇到504问题， service 部分是正常的

### ISSUE THREAD

**Issue by 631068264** [karmada-io/karmada#2479]
**What happened**:
根据https://karmada.io/docs/userguide/service/multi-cluster-ingress

```
karmada]# kubectl get pods -n ingress-nginx
NAME                                       READY   STATUS    RESTARTS   AGE
ingress-nginx-controller-5b8b6d64d-b4kqn   1/1     Running   0          3h59m
```

在host集群执行

```
curl -H 'Host:demo.localdev.me' http://127.0.0.1/web/
```

nginx-controller log

```
2022/09/07 07:04:14 [error] 289#289: *58621 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.42.0.1, server: demo.localdev.me, request: "GET /web/ HTTP/1.1", upstream: "http://10.44.0.33:8080/web/", host: "demo.localdev.me"
2022/09/07 07:04:19 [error] 289#289: *58621 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.42.0.1, server: demo.localdev.me, request: "GET /web/ HTTP/1.1", upstream: "http://10.44.0.33:8080/web/", host: "demo.localdev.me"
2022/09/07 07:04:24 [error] 289#289: *58621 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.42.0.1, server: demo.localdev.me, request: "GET /web/ HTTP/1.1", upstream: "http://10.44.0.33:8080/web/", host: "demo.localdev.me"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - name: serve
        image: harbor.uniin.cn:20000/library/serve:0a40de8
        args:
        - "--message='hello from cluster 1 (Node: {{env \"NODE_NAME\"}} Pod: {{env \"POD_NAME\"}} Address: {{addr}})'"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---      
apiVersion: v1
kind: Service
metadata:
  name: serve
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mcs-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: serve
    - apiVersion: v1
      kind: Service
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1

---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: serve-export-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1


---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: serve
spec:
  type: ClusterSetIP
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: serve-import-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member2


---
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterIngress
metadata:
  name: demo-localhost
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: demo.localdev.me
    http:
      paths:
      - backend:
          service:
            name: serve
            port:
              number: 80
        path: /web
        pathType: Prefix
```

mcs部分是正常的
<img width="996" alt="image" src="https://user-images.githubusercontent.com/8144089/188813597-b5c56eca-c033-4b5a-8124-30c6587de006.png">

到ingress就不正常了

host member 集群都是 v1.22.10+k3s1

**Anything else we need to know?**:

Environment:
Karmada version: 1.2.1
kubectl-karmada or karmadactl version (the result of kubectl-karmada version or karmadactl version): karmadactl version: version.Info{GitVersion:"v1.2.1", GitCommit:"de4972b74f848f78a58f9a0f4a4e85f243ba48f8", GitTreeState:"clean", BuildDate:"2022-07-14T09:33:33Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Others:

**Comment by XiShanYongYe-Chang** [comment]
Host集群的网络与成员集群网络有打通么？

**Comment by 631068264** [comment]
三个都是互通的，不过用pull模式

```
kubectl get cluster --kubeconfig karmada-apiserver.config
NAME      VERSION         MODE   READY   AGE
member1   v1.22.10+k3s1   Pull   True    39d
member2   v1.22.10+k3s1   Pull   True    39d
```

**Comment by XiShanYongYe-Chang** [comment]
确认下ingress-nginx-controller中nginx的配置，后端信息有没有正确刷上去。
可以和@luoMonkeyKing 交流下。

**Comment by 631068264** [comment]
[nginx.log](https://github.com/karmada-io/karmada/files/9504774/nginx.log)
nginx的配置

**Comment by luoMonkeyKing** [comment]
你的multi-ingress-controller是怎么部署的，自己构建的镜像吗？

**Comment by 631068264** [comment]
参考dev-env.sh
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/8144089/188846502-25e4e137-583f-45b9-ab4d-7e5e3893072e.png">




```yaml
controller:
  name: controller
  image:
    registry: "harbor.xxx.cn:xxx"
    image: ingress-nginx/multi-cluster-controller  # 替换
    tag: "v1.1.1"
    digest: ""
  admissionWebhooks:
    patch:
      image:
        registry: "xxxxx"
        image: ingress-nginx/kube-webhook-certgen
        tag: v1.1.1
        digest: ""
  config:
    worker-processes: "1"
  podLabels:
    deploy-date: "1662515412"
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  hostPort:
    enabled: true
  terminationGracePeriodSeconds: 0
  service:
    type: NodePort

defaultBackend:
  image:
    registry: "xxxxx"
    image: ingress-nginx/defaultbackend-amd64
    tag: "1.5"
```


```
helm install ingress-nginx -n ingress-nginx --create-namespace ingress-nginx-4.0.15.tgz -f ingress_values.yaml
```
