### ISSUE TITLE
support elastic cluster

### ISSUE THREAD

**Issue by qiankunli** [karmada-io/karmada#2583]
there are two k8s cluster in our company: k8s in idc, tke/k8s in cloud company(like tencent cloud).  we use cluster autoscaler in tke, if there are pending pod, tke will scale up a new node into cluster. so we can see the tke cluster is elastic.

in this scenario, our scheduler requirements is
1.  the pods of a deployment can only be  deployed in one cluster
2.  the priority of idc is bigger than tke,  if the idc have the enough resources, we deploy the deployment in idc first.
3.  if there is no free resource in idc, and no free resources in tke(such as 10 nodes at the moment). we deploy the deployment in tke so that the pending pod can trigge the scaling up.

we may need to take elastic cluster into consideration.

**Comment by RainbowMango** [comment]
It's a reasonable use case for me. And I think it requires two abilities:
- Set cluster priority for the scheduler to prefer to cluster(s) in IDC
- Give the `scalable cluster` lower priority but always with sufficient resources.

@Garrybest any idea about the case and ways to achieve that?

**Comment by Garrybest** [comment]
1. Scheduling based on priority
We have already designed a API here https://github.com/karmada-io/karmada/pull/842, when some clusters have high priority, karmada prefer to divide replicas between these clusters.

2. Max clusters
Now we can't set max clusters when scheduling. In your scenario, you don't want workloads separated to multiple clusters. Actually, I think this is a really common case since many workloads in offline computing, like AI or big data, are not allowed to be divided in multiple clusters. It would be nice in the future to add a `MaxCluster` field in API.

3. Cluster autoscaling
This is really interesting. Unfortunately we care about how many available replicas in dynamic scheduling, if a cluster could not accommodate so many replicas, the scheduler will fail to schedule them and publish an error event, this is a little bit like `gang-scheduling`. So I think we could introduce a `MinReadyReplicas` API to tell scheduler in which circumstances that a workload could be scheduled when resource is not enough.

**Comment by qiankunli** [comment]
@Garrybest  my department is machine learning platforms. and my workload is tfjob/pytorchjob/vcjob(volcano).

is is useful to make sure that the workload can not be separated to multiple clusters.?
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    spreadConstraints:	## 限定调度结果只能在 1 个cluster 上
    - spreadByField: cluster
      maxGroups: 1
      minGroups: 1
```
in my opinion, it may be better to add a filed for `cluster.spec`, such as `elastic=true` or `backup=true`, and change the logic of scheduler: if there is no cluster which has enough resources to run the workload, we can use backup/elastic cluster to run it , no matter if it has resources or not.
