### ISSUE TITLE
The result of replace/remove the Registry in ImageOverrider is incorrect

### ISSUE THREAD

**Issue by ranzhouol** [karmada-io/karmada#2585]
**What happened**:
First I distributed a deployment with ` image: ubuntu/nginx`, 
![image](https://user-images.githubusercontent.com/67987211/192487373-b1000c83-d403-4c1c-8d08-1cb32f319fb9.png)
  and then created an ImageOverrider to `remove the Registry`, i.e
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: myapp-overridepolicy1
  namespace: test
spec:
  resourceSelectors:
    ...
  overrideRules:
    ...
      overriders:
        imageOverrider:
          - component: Registry
            operator: remove
```
   I expected to get `image: nginx`, but the result didn't change. It was still `image: ubuntu /nginx`.
  Similarly, I created an ImageOverrider to `replace the Registry`:
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: myapp-overridepolicy2
  namespace: test
spec:
  resourceSelectors:
    ```
  overrideRules:
    ```
      overriders:
        imageOverrider:
          - component: Registry
            operator: replace
            value: bitnami
```
  and I expected to get `image: bitnami/nginx`, but the result was
![image](https://user-images.githubusercontent.com/67987211/192664674-db3d6d49-d08c-4dff-b59f-fe95db645bcf.png)

**What you expected to happen**:
I want to get the result I expect
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.2.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.2.0
- Others:

**Comment by RainbowMango** [comment]
For the first case, you are trying to `remove` the `registry`, but there is no `registry` in `ubuntu/nginx`, the implied registry is `https://hub.docker.com`.  The rule of how we recognize `registry/repository/tag` is [present at the API](https://github.com/karmada-io/karmada/blob/fc196abf894fb271a8d2e9aba4440fcfc48db199/pkg/apis/policy/v1alpha1/override_types.go#L121-L132).
```yaml
imageOverrider:
  - component: Registry
    operator: remove
```

> I expected to get image: nginx, but the result didn't change. It was still image: ubuntu /nginx.

We shouldn't expect that, in my opinion, it works as expected.
I wonder is there a real use case that wants to override `ubuntu/nginx` to `nginx`?
