### ISSUE TITLE
PP's ResourceSelector is empty

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#2618]
**Please provide an in-depth description of the question you have**:

When I use the following yaml file to create PP, it can be created successfully, but when I look at the api definition of PP, [ ResourceSelector cannot be empty](https://github.com/karmada-io/karmada/blob/master/pkg/apis/policy/v1alpha1/propagation_types.go#L42-L46). Is this normal?

``` yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors: []
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1

```

<img width="605" alt="image" src="https://user-images.githubusercontent.com/17962021/194683183-12d13d9f-8cc9-4dc2-9741-771a1c8cb897.png">

**What do you think about this question?**:

If this is not the expected behavior, should the user be prevented from creating a PP with an empty ResourceSelector?

**Environment**:
- Karmada version: v1.3.0
- Kubernetes version: v1.24.0
- Others:
