### ISSUE TITLE
使用submariner的globalnet，mcs功能使用不正常

### ISSUE THREAD

**Issue by 631068264** [karmada-io/karmada#2657]
**What happened**:

member集群的cidr都是一样，所以使用globalnet
```
  clusterCidr: "10.42.0.0/16"
  serviceCidr: "10.43.0.0/16"
```

apply 下面的mcs.yaml
```
kubectl apply -f mcs.yaml --kubeconfig karmada-apiserver.config 
```
mcs.yaml 
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - name: serve
        image: harbor.uniin.cn:20000/library/serve:0a40de8
        args:
        - "--message='hello from cluster 1 (Node: {{env \"NODE_NAME\"}} Pod: {{env \"POD_NAME\"}} Address: {{addr}})'"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---      
apiVersion: v1
kind: Service
metadata:
  name: serve
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mcs-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: serve
    - apiVersion: v1
      kind: Service
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1

---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: serve-export-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1


---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: serve
spec:
  type: ClusterSetIP
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: serve-import-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member2
```

应用部署在member1， serviceimport 在member2
```
kubectl --kubeconfig member2-config get endpointSlice

NAME                           ADDRESSTYPE   PORTS   ENDPOINTS      AGE
imported-member1-serve-4hgmf   IPv4          8080    10.42.0.14     28m
serve-member1                  IPv4          8080    10.42.0.14     3m1s


kubectl --kubeconfig member2-config get svc

NAME            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
derived-serve   ClusterIP   10.43.3.60   <none>        80/TCP    54m
kubernetes      ClusterIP   10.43.0.1    <none>        443/TCP   61m
```

但是在member2 访问derived-serve失败
```
kubectl --kubeconfig member2-config run tmp-shell --rm -i --tty --image submariner/nettest:0.12.2 -- /bin/bash

curl derived-serve
curl: (7) Failed to connect to derived-serve port 80 after 0 ms: Connection refused
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:  1.3
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:  k3s集群版本 **v1.22.10+k3s1**
