### ISSUE TITLE
Deployment deployed in all cluster members

### ISSUE THREAD

**Issue by mrequena** [karmada-io/karmada#2689]
**Please provide an in-depth description of the question you have**:
I have 2 clusters in Karmada. When I apply a deployment, the deployment is deployed in both clusters. I use a simple nginx deployment as the one in samples/nginx/deployment.yaml. I use propagationpolicy.yaml (from samples/nginx) without the block "replicaScheduling" because I only have 1 replica.
I want to deploy the deployment in only one cluster (randomly chosen by karmada/k8s or depending on the "load" of the cluster).
Is this possible? I guess I can to configure correctly propagationpolicy.yaml, right? What options there exists for the scheduler of Karmada?

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.3.0
- Kubernetes version: v1.24.6
- Others:

**Comment by RainbowMango** [comment]
> I want to deploy the deployment in only one cluster (randomly chosen by karmada/k8s or depending on the "load" of the cluster).
Is this possible?

For now, the number of selected clusters can be restricted by [SpreadConstraint](https://github.com/karmada-io/karmada/blob/5d42e82b7b92812a04aaade4b77e66556aa20d66/pkg/apis/policy/v1alpha1/propagation_types.go#L157), a simple example would be:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: deployment-1
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
   spreadConstraints:
      - spreadByField: cluster
        maxGroups: 1  ## only one cluster would be selected.
```

Karmada scheduler will select one cluster, but for now, it doesn't consult the `load` of the cluster. We are working on it at #780.
