### ISSUE TITLE
The pp/cpp can preempt the matching resource template

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#2727]
**What happened**:

When a low-priority pp is created and a resource profile is matched,
```yaml
# deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
# pp-label.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation-label
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```
Deployment will be propagated to `member1`, and then create a high-priority pp to match deployment nginx:
```yaml
# pp-name.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation-name
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member2
```
And Update Deployment nginx's replicas to 3, Deployment nginx will be propagated to `member2`.

**What you expected to happen**:

The pp/cpp can not preempt the matching resource template.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: master branch
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
