### ISSUE TITLE
After the faulty cluster recovers, the number of scheduled pods is greater than expected

### ISSUE THREAD

**Issue by Fish-pro** [karmada-io/karmada#2769]
**Please provide an in-depth description of the question you have**:

After I set "--feature-gates=Failover=true" to the scheduler, I deliver the following choreographed applications
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 2
```

The scheduling results are as follows, which are found to be in line with expectations
<img width="990" alt="image" src="https://user-images.githubusercontent.com/47143494/200979639-2203ea83-57b7-4c5e-b232-81140a46ca97.png">

When I simulated a cluster fault and suspended member1, I found that the replicas of member2 changed to 3, which met the fault recovery expectation
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/47143494/200980212-952eb7f8-eb6d-41c3-aed1-2314534b23be.png">

When I restored cluster member1, I found the following phenomenon: the actual number of running replicas was 4, but the expected replicas was 3. My question is whether this situation is consistent with the design expectations, and whether frequent cluster failure recoveries in the case of large member clusters will result in an increasing number of actual pods?
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/47143494/200980818-525fa22c-f699-4db3-91bd-1358fd31dbd8.png">

**What do you think about this question?**:

If the cluster recovers, determine whether to trigger rescheduling to ensure that the actual scheduling result meets the expectation.

**Environment**:
Karmada version: 1.3
kubectl-karmada or karmadactl version (the result of kubectl-karmada version or karmadactl version): 1.3
Others:
