### ISSUE TITLE
Can not remove obj finalizers on member cluster

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#2810]
**What happened**:

Finalizers can not be removed from obj on member cluster. I tried edit the obj on management cluster directly and apply a cluster override policy.

**What you expected to happen**:

Management cluster can remove finalizers from obj on member cluster.

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply the following yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ns-test
  finalizers:
  - example.com/test
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: ns-test
spec:
  placement:
    clusterAffinity:
      labelSelector:
        matchExpressions:
        - key: id
          operator: In
          values:
          - 5011e344-2f08-4cc5-9825-d4f56563922d
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 30
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 30
  resourceSelectors:
  - apiVersion: v1
    kind: Namespace
    name: ns-test
```

2. edit the namespace, remove the finalizers from metadata.
3. The finalizers can not be removed on member cluster.

**Anything else we need to know?**:

The culprit may be:

https://github.com/gy95/karmada/blob/master/pkg/util/objectwatcher/objectwatcher.go#L132

It retains finalizers from cluster obj.

**Environment**:
- Karmada version: v1.3.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
   kubectl karmada version: version.Info{GitVersion:"v1.1.1-20-g922ee798", GitCommit:"922ee798f7e187f754d03f2a02fc91ba903a003d", GitTreeState:"clean", BuildDate:"2022-04-24T03:23:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

- Others:

**Comment by RainbowMango** [comment]
Yes, I think you've pointed out the root cause which is:
https://github.com/karmada-io/karmada/blob/a16710a94ec70345d16cdbb1f557e0ab19b1a68f/pkg/util/objectwatcher/objectwatcher.go#L129-L132

I see you set a finalizer in your example:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ns-test
  finalizers:
  - example.com/test
```
Can you share with us why you need to set a finalizer? I wonder to know the use case.
