### ISSUE TITLE
Helm charts v1.3.0 and v1.3.1 do not default to docker.io/karmada images, nor do they obey explicit assignment

### ISSUE THREAD

**Issue by bcarlock-emerge** [karmada-io/karmada#2842]
**What happened**: Installed Karmada Host via Helm. Images are being puled from swr.ap-southeast-1.myhuaweicloud.com/docker.io/karmada even after explicitly setting the repository and image version for all of the images defined in my values.yaml.
values.yaml:
```
aggregatedApiServer:
  image:
    repository: docker.io/karmada/karmada-aggregated-apiserver
    tag: v1.3.0
apiServer:
  hostNetwork: true
controllerManager:
  image:
    repository: docker.io/karmada/karmada-controller-manager
    tag: v1.3.0
scheduler:
  image:
    repository: docker.io/karmada/karmada-scheduler
    tag: v1.3.0
webhook:
  image:
    repository: docker.io/karmada/karmada-webhook
    tag: v1.3.0
```
```
Rendered object:
Name:                   karmada-controller-manager
Namespace:              karmada-system
CreationTimestamp:      Mon, 21 Nov 2022 14:40:01 -0600
Labels:                 app=karmada-controller-manager
                        app.kubernetes.io/managed-by=Helm
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: karmada
                        meta.helm.sh/release-namespace: karmada-system
Selector:               app=karmada-controller-manager
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  0 max unavailable, 50% max surge
Pod Template:
  Labels:           app=karmada-controller-manager
  Service Account:  karmada-controller-manager
  Containers:
   karmada-controller-manager:
    Image:      swr.ap-southeast-1.myhuaweicloud.com/docker.io/karmada/karmada-controller-manager:v1.3.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/karmada-controller-manager
      --kubeconfig=/etc/kubeconfig
      --bind-address=0.0.0.0
      --cluster-status-update-frequency=10s
      --secure-port=10357
      --leader-elect-resource-namespace=karmada-system
      --v=2
    Liveness:     http-get http://:10357/healthz delay=15s timeout=5s period=15s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/kubeconfig from kubeconfig-secret (rw,path="kubeconfig")
  Volumes:
   kubeconfig-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  karmada-kubeconfig
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   karmada-controller-manager-864994c89 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  10m   deployment-controller  Scaled up replica set karmada-controller-manager-864994c89 to 1

```

**What you expected to happen**:  Image is installed from the documented default or at least obeys explicit assignment.

**How to reproduce it (as minimally and precisely as possible)**: Install version 1.3.0 or 1.3.1 via helm and specify any of the images on docker.io

**Anything else we need to know?**: I noticed that the helm templates changed between version [1.2.0 ](https://github.com/karmada-io/karmada/blob/v1.2.0/charts/templates/karmada_controller_manager.yaml#L56) and [1.3.0](https://github.com/karmada-io/karmada/blob/v1.3.0/charts/karmada/templates/karmada-controller-manager.yaml#L53) 

**Environment**:
- Karmada version: v1.3.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): N/A
- Others:
