### ISSUE TITLE
How to setup RBAC for Karmada API server?

### ISSUE THREAD

**Issue by DraganDjuric94** [karmada-io/karmada#2941]
**Please provide an in-depth description of the question you have**:

We have installed Karmada version 1.4.0 to our Kubernetes cluster.
Everything is working as intended, but we would like to limit access to Karmada API server using RBAC.
We are doing this by generating a user kubeconfig file using Role, RoleBinding and ServiceAccount.
All of the resources are applied to the Karmada API server, but RBAC is not doing its job - generated kubeconfig has access to all resources on Karmada API server.
We have tried with both Service account and OIDC, but with no success.

Steps used:
1. Apply Role, RoleBinding, ServiceAccount and token Secret to Karmada API server:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pes-write
  namespace: pes
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pes
  namespace: pes
secrets:
  - name: pes-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pes-write
  namespace: pes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pes-write
subjects:
  - kind: ServiceAccount
    name: pes

---
apiVersion: v1
kind: Secret
metadata:
  name: pes-token
  namespace: pes
  annotations:
    kubernetes.io/service-account.name: pes
type: kubernetes.io/service-account-token
```
2. Generate kubeconfig from applied token
3. Try to access resources outside of `pes` namespace

Expected behavior: API server rejects requests for resources outside of the `pes` namespace.

The same configuration is working as intended on the Kubernetes API server.

**Question: How to limit access to the resources applied to the Karmada API server, as well as applying resources to a certain namespace?**

**Environment**:
- Karmada version: 1.4.0
- Kubernetes version: 1.23.14
- Karmada API server version: 1.25.2

**Comment by RainbowMango** [comment]
Hi @DraganDjuric94 Thanks for spotting.

> We have installed Karmada version 1.4.0 to our Kubernetes cluster.

How you installed Karmada? By Helm chart, `karmadactl init`, or just `hack/local-up-karmada.sh`? 
I want to reproduce it on my side.

This is unlikely because the `karmada-apiserver` is now essentially using the same image as the `kube-apiserver`.

**Comment by DraganDjuric94** [comment]
@RainbowMango Thanks for replying.
We have installed it using the Helm chart:
```
dependencies:
  - name: karmada
    version: 0.0.5
```

Taken from your GitHub repo.

**Comment by RainbowMango** [comment]
Hi @Poor12, could you please help with it? try to reproduce it locally.

**Comment by Poor12** [comment]
I have tried by both `local-up-karmada` and Helm chart. Both is ok.

**Comment by DraganDjuric94** [comment]
@Poor12 
Thanks for checking it.
Have you used the default Helm values for your tests (the only thing we changed is the image tag: from `latest` to `v1.4.0`)?
If that's the case, we'll continue to do tests on our side and try to find what's causing the issue.

**Comment by Poor12** [comment]
Yeah, I do not change the default Helm values. You might check whether the generated kubeconfig is created from the seviceaccount in `pes` namespace of `karmada-apiserver` context.

**Comment by RainbowMango** [comment]
> The issue arises when we try to target the API server with our custom domain through the Ingress controller.
Strangely, the same domain works fine when we add it to /etc/hosts and do a port forward to Karmada API service.

Sorry I didn't get it. I can help to cc Ingress experts here, please give us some more details.

By the way, are you using Karmada now? Or in the progress of evaluation?

**Comment by DraganDjuric94** [comment]
> By the way, are you using Karmada now? Or in the progress of evaluation?

We are currently in the evaluation / test phase. If everything goes according to plan, we will most likely be switching over (from Kubefed).

More details:
Our kubeconfig looks something like this:
```
apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://karmada-api.our.domain.com
    name: karmada.our.cluster.com
contexts:
  - context:
      cluster: our.cluster.com
      namespace: pes
      user: karmada-apiserver-pes-token-user
    name: pes-karmada-dev
current-context: pes-karmada-dev
kind: Config
preferences: {}
users:
  - name: karmada-apiserver-pes-token-user
    user:
      token: [REDACTED]
```

We have exposed the domain using Ingress with:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: karmada
  namespace: karmada-system
spec:
  kube:
    serviceName: karmada-apiserver
    serviceNamespace: karmada-system
    servicePort: 5443
  sslConfig:
    secretRef:
      name: karmada-tls
      namespace: karmada-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: karmada
  namespace: karmada-system
spec:
  sslConfig:
    secretRef:
      name: our-cert
      namespace: cert-namespace
    sniDomains:
    - karmada-api.our.domain.com
  virtualHost:
    domains:
    - karmada-api.our.domain.com
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: karmada
            namespace: karmada-system
```

When we set it up like this, we can access resources in all namespaces - service account privileges are not used.

When we do a port forward to the Karmada API server (localhost: 5443) and add the domain to `/etc/hosts` (direct access):
```
127.0.0.1           karmada-api.our.domain.com
```
and target `https://karmada-api.our.domain.com:5443` in our Kubeconfig file, we can access resources only in the `pes` namespace (it's working as intended)

**Comment by RainbowMango** [comment]
I'm not familiar with [solo.io], but I'd love to investigate a little bit, it seems like a powerful system.

```yaml
    secretRef:
      name: karmada-tls
      namespace: karmada-system
```
This secret is suspicious, is the certificate in the secret issued to user `pes`? Just a guess, if the gateway is using an administrator's configuration, then I won't be surprised that it can access resources in all namespaces.

**Comment by DraganDjuric94** [comment]
`name: karmada-tls` contains certificate for Karmada API server, so we can have a secure connection with the API server (without it we were getting: "Client sent an HTTP request to an HTTPS server").

We had similar thoughts about the gateway proxies, but it's still a http connection and it should use passed user token (but this might not be the case, since it's working through port forward).

**Comment by RainbowMango** [comment]
cc ingress expert @XiShanYongYe-Chang for help.

@DraganDjuric94 I'm not sure we can help here, so no guarantees here. But I'll get back to you once I get a clue.

**Comment by DraganDjuric94** [comment]
@RainbowMango You've already done more than we expected :)
As this looks like an issue on our side, not Karmada issue.

**Comment by RainbowMango** [comment]
OK. Let's keep this issue open for a while. (it's an interesting case).

**Comment by XiShanYongYe-Chang** [comment]
IMOP, when the route provided by the ingress is used to access the `karmada-apiserver`, the authentication information is secret `karmada-system/karmada-tls`, during the access, the authentication information is not the same as that when kubeconfig is used, so `karmada-apiserver` don't know the user is `karmada-apiserver-pes-token-user`.

**Comment by DraganDjuric94** [comment]
As we all suspected the issue is with the HTTP gateway, and it looks like it cannot be done with it.
We managed to make it work in the following ways:
- Direct access (in cluster)
- Port forward with /etc/hosts
- Node port exposure (without Gloo)
- With a Gloo TCP gateway.

We created a TCP gateway that has direct access to the Karmada API server Upstream and it's working as intended.
Leaving a sample configuration if anyone searches for it later and closing the issue.
Thank you again @RainbowMango @XiShanYongYe-Chang @Poor12 

```yaml
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: tcp
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 5443
  tcpGateway:
    tcpHosts:
      - name: karmada-api
        destination:
          single:
            upstream:
              name: karmada
              namespace: karmada-system
  proxyNames:
    - gateway-proxy # Needs to have port 5443 with name tcp
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: karmada
  namespace: karmada-system
spec:
  kube:
    serviceName: karmada-apiserver
    serviceNamespace: karmada-system
    servicePort: 5443
```
