### ISSUE TITLE
Keep creating namespaces

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#2981]
**What happened**:
After this https://github.com/karmada-io/karmada/pull/2825 merged, the namespace will be continued creating.

**What you expected to happen**:
Not continue creating.

**How to reproduce it (as minimally and precisely as possible)**:
I checked the code, and the function `EnsureNamespaceExist` is only invoked when cluster init(karmada-agent init and karmadactl init).

And I tested release-1.4 branch, init clusters with `local-up-karmada.sh` and` karmadactl init`, both works correctly, but the problem is not reproduced.
@yizhang-zen, can you give more information about this? how to reproduce this problem?

**Anything else we need to know?**:
none

**Environment**:
- Karmada version: release-1.4 branch
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):release-1.4 branch
- Others: none

**Comment by yizhang-zen** [comment]
Hi @jwcesign:
The reason why we see this issue is because we have opa-gatekeeper policies that check the compliance of resources (e.g. namespace, clusterrole, clusterrolebinding).
The code is attempting to create a namespace (which our gatekeeper validation webhook catches). Even if we create the namespace prior to the agent init, it will still attempt to create the namespace when apply the deployment below (but it is a normal deployment with no major tweaks).
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmada
  namespace: karmada-system
  labels:    
    app: karmada-agent 
    team: compute
    project: sfn_kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:      
      app: karmada-agent
  strategy:
        rollingUpdate:
          maxSurge: 50%
          maxUnavailable: 0
        type: RollingUpdate
  template:
    metadata:
      labels:        
        app: karmada-agent    
        team: compute
        project: sfn_kubernetes    
    spec:
      serviceAccountName: karmada
      containers:
        - name: karmada
          image: docker.io/karmada/karmada-agent:latest
          imagePullPolicy: Always
          command:
            - /bin/karmada-agent
            - --karmada-kubeconfig=/etc/kubeconfig/kubeconfig
            - --cluster-name=hub
            - --cluster-api-endpoint=https://kubernetes.default.svc.cluster.local/
            - --cluster-status-update-frequency=10s
            - --leader-elect-resource-namespace=karmada-system
            - --bind-address=0.0.0.0
            - --secure-port=10357
            - --v=4
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10357
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/kubeconfig
          resources:
            {}
      volumes:
        - name: kubeconfig
          secret:
            secretName: karmada-kubeconfig
```

agent initialization error:
```
I1221 17:13:19.965615       1 agent.go:115] karmada-agent version: version.Info{GitVersion:"v1.4.0-104-g80e5bd9e", GitCommit:"80e5bd9ee9646154fda36250adbcf6719a336290", GitTreeState:"clean", BuildDate:"2022-12-21T06:37:11Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
 "command failed" err="ensure namespace failed due to create failed. namespace: karmada-cluster, error: admission webhook \"validation.gatekeeper.sh\" denied the request: [globals-must-meet-compliance] zendesk/opa-gatekeeper Namespace  karmada-cluster: you must provide labels {\"compliance\"}. See <REDACTED>."
```
Creating the Namespace upfront (i.e. prior to agent initialization) and using version [docker.io/karmada/karmada-agent:v1.3.3](http://docker.io/karmada/karmada-agent:v1.3.3), it will not attempt to create the namespace and all good
