### ISSUE TITLE
Karmada can't update resource status when cluster is false

### ISSUE THREAD

**Issue by xu1257** [karmada-io/karmada#2989]
**What happened**:
When cluster false, Karmada can't update the resource status, which be deployed in cluster.

I had done an experiment to test if Karmada can monitor the resource status, which was deployed by Karmada.
The experiment as follow:

First of all, I deployed a Deployment resource by Karmada. And my target cluster is cluster1 and cluster3. Karmada scheduled all replicas to cluster3.

Then I killed cluster3, because I want to know if Karmada can monitor resource deployed by itself, and rebuild the resource, which status is notready.

But I got the output as follow:
 ```
root@host: ~# kubectl --kubeconfig=/etc/karmada/karmada-apiserver.config get clusters

NAME         VERSION        MODE        READY        AGE
cluster1     v1.25.0        Push        True         11d
cluster1     v1.25.0        Push        False        11d
cluster1     v1.25.0        Push        False        14h

root@host: ~# kubectl --kubeconfig=/etc/karmada/karmada-apiserver.config get deployment nginx

NAMESPACE      NAME       READY       UP-TO-DATE      AVAILABLE      AGE
default        nginx      2/2         2               2              23m   
```
Its status is Ready still. And the Deployment will not be re-schedule to cluster1.

**What you expected to happen**:
The resource status should be changed to notReady, when cluster False.
And re-schedule the resource to other target cluster.

**Anything else we need to know?**:
After discussion，if we want karmada to re-schedule resource, we need open the feature 'Failover'. But status will not change still. 

**Environment**:
- Karmada version: 1.3.2
- Kubernetes: 1.25.0

**Comment by chaunceyjiang** [comment]
Can you share your `PropagationPolicy`?

**Comment by chaunceyjiang** [comment]
```
root@host: ~# kubectl --kubeconfig=/etc/karmada/karmada-apiserver.config get clusters

NAME         VERSION        MODE        READY        AGE
cluster1     v1.25.0        Push        True         11d
cluster1     v1.25.0        Push        False        11d
cluster1     v1.25.0        Push        False        14h

```
Do you have three clusters with the same name?

**Comment by XMingG99** [comment]
> ```
> root@host: ~# kubectl --kubeconfig=/etc/karmada/karmada-apiserver.config get clusters
> 
> NAME         VERSION        MODE        READY        AGE
> cluster1     v1.25.0        Push        True         11d
> cluster1     v1.25.0        Push        False        11d
> cluster1     v1.25.0        Push        False        14h
> ```
> 
> Do you have three clusters with the same name?

No, I'm not copy from shell, just a type error

**Comment by XMingG99** [comment]
> Can you share your `PropagationPolicy`?

```
apiVersion: policy.karmada.io/v1a1pha1
kind: PropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster3
 ```

**Comment by Fish-pro** [comment]
@XMingG99 
I used karmada1.3.2 and got the following results, which I understand are as expected
```sh
➜  demo k --kubeconfig ~/.kube/karmada.config get cluster
NAME      VERSION   MODE   READY   AGE
member1   v1.23.4   Push   True    14m
member2   v1.23.4   Push   True    14m
member3   v1.23.4   Pull   True    13m
```
According to the policy you provided, the resource status after delivery is as follows
```sh
➜  demo k --kubeconfig ~/.kube/karmada.config get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   4/2     4            4           7m58s
```
The result is as follows after cluster `member2` is suspended
```sh
➜  demo k --kubeconfig ~/.kube/karmada.config get cluster
NAME      VERSION   MODE   READY   AGE
member1   v1.23.4   Push   True    21m
member2   v1.23.4   Push   False   21m
member3   v1.23.4   Pull   True    21m
➜  demo k --kubeconfig ~/.kube/karmada.config get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   2/2     2            2           14m
```
Based on the propagation strategy you provide, I understand that the results will be propagated to `cluster1` and `cluster3` that meet the requirements. If one of the clusters fails, then the 2/2 status is expected.

Whether you're going to test failover, if it is, you can reference documentation at https://karmada.io/docs/next/userguide/failover/failover-analysis/#failover

By the way, the apiVersion of the communication strategy you provided was incorrectly written(policy.karmada.io/v1a`1`pha1), the correct apiVersion is policy.karmada.io/v1alpha1

This is the test result according to the information you provided. If you have more detailed information to provide, we will keep communicating with you

**Comment by XMingG99** [comment]
> @XMingG99 I used karmada1.3.2 and got the following results, which I understand are as expected
> 
> ```shell
> ➜  demo k --kubeconfig ~/.kube/karmada.config get cluster
> NAME      VERSION   MODE   READY   AGE
> member1   v1.23.4   Push   True    14m
> member2   v1.23.4   Push   True    14m
> member3   v1.23.4   Pull   True    13m
> ```
> 
> According to the policy you provided, the resource status after delivery is as follows
> 
> ```shell
> ➜  demo k --kubeconfig ~/.kube/karmada.config get deploy
> NAME    READY   UP-TO-DATE   AVAILABLE   AGE
> nginx   4/2     4            4           7m58s
> ```
> 
> The result is as follows after cluster `member2` is suspended
> 
> ```shell
> ➜  demo k --kubeconfig ~/.kube/karmada.config get cluster
> NAME      VERSION   MODE   READY   AGE
> member1   v1.23.4   Push   True    21m
> member2   v1.23.4   Push   False   21m
> member3   v1.23.4   Pull   True    21m
> ➜  demo k --kubeconfig ~/.kube/karmada.config get deploy
> NAME    READY   UP-TO-DATE   AVAILABLE   AGE
> nginx   2/2     2            2           14m
> ```
> 
> Based on the propagation policy you provide, I understand that the results will be propagated to `cluster1` and `cluster3` that meet the requirements. If one of the clusters fails, then the `2/2` status is expected.
> 
> Whether you're going to test failover, if it is, you can reference documentation at https://karmada.io/docs/next/userguide/failover/failover-analysis/#failover
> 
> By the way, the `apiVersion` of the propagation policy you provided was incorrectly written(policy.karmada.io/v1a`1`pha1), the correct `apiVersion` is `policy.karmada.io/v1alpha1`
> 
> This is the test result according to the information you provided. If you have more detailed information to provide, we will keep communicating with you，thanks.

OK, thank you,  policy.karmada.io/v1a`1`pha1 is my mistake on github. In experiment, that's right. And I did the experiment again. Got the result as follow:
```
root@host: ~# kubectl --kubeconfig=/etc/karmada/karmada-apiserver.config get clusters
NAMESPACE      NAME       READY       UP-TO-DATE      AVAILABLE      AGE
default        nginx      4/2         2               2              10m  
```
Based on the results， can we assume that the default `ReplicaSchedulingType` policy is `Duplicated`?
As for why `READY 2/2` is displayed for the first time, it may be due to my negligence that I set Cluster 1 as non-schedulable.
Then I use a new `propagationpolicy` like this:
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster3
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - cluster1
            weight: 1
          - targetCluster:
              clusterNames:
                - cluster3
            weight: 1
```
This time shows:
```
root@host: ~# kubectl --kubeconfig=/etc/karmada/karmada-apiserver.config get clusters
NAMESPACE      NAME       READY       UP-TO-DATE      AVAILABLE      AGE
default        nginx      2/2         2               2              10m  
```
Every cluster have one deployment, and I test the `Failover`, It's work.
Thank you. But there still have a problem, after `Failover`, field `replicas` in cluster1's `work`(nginx-687f7b96f) is 2, but `work` for cluster3 is still True, which will not be deleted, until cluster3 is True. So, I think this is a bug.
