### ISSUE TITLE
built-in interpreter support statefulset

### ISSUE THREAD

**Issue by WulixuanS** [karmada-io/karmada#3007]
**What would you like to be added**:
I hope Karmada's built-in Interpreter can support statefulset

**Why is this needed**:
In our scenario, some statefulset workloads also want to be managed by karmada
PropagationPolicy is as follows
```
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
```

**Comment by chaunceyjiang** [comment]
> In our scenario, some statefulset workloads also want to be managed by karmada

It should be support.

**Comment by chaunceyjiang** [comment]
``` yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
```
