### ISSUE TITLE
invalid propagation policy creates successfully but does not schedule deployments

### ISSUE THREAD

**Issue by a7i** [karmada-io/karmada#3013]
**What happened**:
1. Apply the following propagation policy (notice the `replicaDivisionPreference` setting is missing):
    ```yaml
    apiVersion: policy.karmada.io/v1alpha1
    kind: PropagationPolicy
    metadata:
      name: deployment-propagation-divided
    spec:
      resourceSelectors:
        - apiVersion: apps/v1
          kind: Deployment
      placement:
        clusterAffinity:
          clusterNames:
            - member-1
            - member-2
        replicaScheduling:
          replicaSchedulingType: Divided
    ```
2. Observe that it was created successfully
   ```bash
   propagationpolicy.policy.karmada.io/deployment-propagation-divided created
    ```
3. Create a Deployment in the namespace that the pp was created
    ```bash
    kubectl create deployment --image=nginx demo-invalid-pp --replicas=4
    ```
4. Observe that Deployment reconciliation fails
    ```bash
    kubectl describe deploy demo-invalid-pp
    ```
    ```bash
    ...
    Events:
      Type     Reason                  Age                From                Message
      ----     ------                  ----               ----                -------
      Normal   ApplyPolicySucceed      19s                resource-detector   Apply policy(pp/deployment-propagation-divided) succeed
      Normal   SyncWorkSucceed         18s (x4 over 19s)  binding-controller  Sync work of resourceBinding(pp/demo-invalid-pp-deployment) successful.
      Normal   AggregateStatusSucceed  18s (x4 over 19s)  binding-controller  Update resourceBinding(pp/demo-invalid-pp-deployment) with AggregatedStatus successfully.
      Warning  ScheduleBindingFailed   9s (x12 over 19s)  karmada-scheduler   failed to assignReplicas: unsupported replica scheduling strategy, replicaSchedulingType: Divided, replicaDivisionPreference: , please try another scheduling strategy
      ```
5. Observe that ResourceBinding is not fully applied
    ```bash
    kubectl get resourcebinding
    NAME                         SCHEDULED   FULLYAPPLIED   AGE
    demo-invalid-pp-deployment   False       False          5m18s
    ```
      

**What you expected to happen**:
Creation of an invalid PropagationPolicy is blocked

**How to reproduce it (as minimally and precisely as possible)**:
See steps above

**Anything else we need to know?**:
Ideally this can be prevented using a `ValidatingWebhookConfiguration`

**Environment**:
- Karmada version: v1.4.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
```
karmadactl version: version.Info{GitVersion:"v1.4.0", GitCommit:"fe5880886451a61334357aa8d10c85ef7af5e4e1", GitTreeState:"clean", BuildDate:"2022-11-30T11:59:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
```
- Others:
