### ISSUE TITLE
Scheduling framework extensions

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3032]
Does the Karmada now support extensions to scheduling plugins, for example via webhooks? If the Karmada doesn't, I'd like to provide a webhook support for scheduling plugins cause it's been stable tested up to more than a month.

**Comment by RainbowMango** [comment]
Please check if this is what we are talking about. https://github.com/karmada-io/website/pull/286

**Comment by whitewindmills** [comment]
> Please check if this is what we are talking about. [karmada-io/website#286](https://github.com/karmada-io/website/pull/286)

I understand that this is an extension of the built-in plugin, but what I would like to offer is an external extension, for example via a webhook.

**Comment by RainbowMango** [comment]
Yes, that's the doc for extending the built-in plugin by a hack way.

> I'd like to provide a webhook support for scheduling plugins cause it's been stable tested up to more than a month.

I like the idea! Would you like to make a demo for your work? 
The [next community meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.yrs5d1w97tdg) is 2023-01-17 2:30 PM Tuesday. Please add an agenda if it is available for you.

**Comment by whitewindmills** [comment]
@RainbowMango 
Yes, I'd like. But I can simply show you now. If you agree with the extension, I will be ready to submit a PR and prepare a detailed demo.
The webhook configuration for scheduling plugins looks like this:
```
apiVersion: config.karmada.io/v1alpha1
kind: SchedulingPluginWebhookConfiguration
metadata:
  name: examples
webhooks:
- clientConfig:
    caBundle: {{caBundle}}
    url: https://example-scheduler.karmada-system.svc.cluster.local:443/scheduling-plugin
  name: schedulingplugin1.example.com
  timeoutSeconds: 10
  pluginFrameworkVersions:
  - v1alpha1
  verbs:
  - 'filter'
  - 'score'
```
These logs of karmada-scheduler indicate that your scheduling plugin webhook does work, and the cluster named `local` was filtered by the scheduling plugin webhook.
![image](https://user-images.githubusercontent.com/89241565/211486770-20dc1195-b936-416c-8d87-6e2d1969c397.png)
