### ISSUE TITLE
Can it support cross-cluster rollouts?

### ISSUE THREAD

**Issue by machine3** [karmada-io/karmada#3054]
The effect I want is that users do not perceive how many clusters there are when publishing in canary.

For example:
I have a workload with 2 replicas in member1 and 3 replicas in member2,
Then I need to do cross-cluster canary publishing, 5 replicas are released in 3 batches, and the number of replicas in each batch is: 1, 2, 2
I hope to do canary support in `PropagationPolicy` crd, like this:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: my-nginx-propagation
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: my-nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 2
          - targetCluster:
              clusterNames:
                - member2
            weight: 3
    canary:    // here
      steps:
        - weight: 1
          pause: {}
        - weight: 50
          pause: {}
```
Is this reasonable?
