### ISSUE TITLE
ImageOverrider Implementation

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#313]
_Originally posted by @RainbowMango in https://github.com/karmada-io/karmada/issues/199#issuecomment-815435935_

Given our original requirement is to override the image registry. So, I propose another overrider, named `ImageOverrider`, which dedicated to handling images. Hope this will be easier and more user-friendly.

Note: The `ImageOverrider` didn't mean to reject the solutions we discussed above like `RegexOverrider` or `PrefixOverrider`, we still can continue the discussion when there is a clear requirement in the future, such as override arbitrary fields with string type.

```golang
// OverrideSpec defines the desired behavior of OverridePolicy.
type OverrideSpec struct {
	// ResourceSelectors restricts resource types that this override policy applies to.
	ResourceSelectors []ResourceSelector `json:"resourceSelectors,omitempty"`

	// TargetCluster defines restrictions on this override policy
	// that only applies to resources propagated to the matching clusters
	TargetCluster ClusterAffinity `json:"targetCluster,omitempty"`

	// Overriders represents the override rules that would apply on resources
	Overriders Overriders `json:"overriders,omitempty"`
}

// Overriders offers various alternatives to represent the override rules.
//
// If more than one alternatives exist, they will be applied with following order:
// - ImageOverrider
// - Plaintext
type Overriders struct {
	// Plaintext represents override rules defined with plaintext overriders.
	// +optional
	Plaintext []PlaintextOverrider `json:"plaintext,omitempty"`

	// ImageOverrider represents the rules dedicated to handling image overrides.
	// +optional
	ImageOverrider []ImageOverrider `json:"imageOverrider,omitempty"`
}

// ImageOverrider represents the rules dedicated to handling image overrides.
type ImageOverrider struct {
	// Predicate filters images before applying the rule.
	//
	// Defaults to nil, in that case, the system will automatically detect image fields if the resource type is
	// Pod, ReplicaSet, Deployment or StatefulSet by following rule:
	//   - Pod: spec/containers/<N>/image
	//   - ReplicaSet: spec/template/spec/<N>/image
	//   - Deployment: spec/template/spec/<N>/image
	//   - StatefulSet: spec/template/spec/<N>/image
	// In addition, all images will be processed if the resource object has more than one containers.
	//
	// If not nil, only images matches the filters will be processed.
	// +optional
	Predicate *ImagePredicate `json:"predicate,omitempty"`

	// Component is part of image name.
	// Basically we presume an image can be make of '[registry/]repository[:tag]'.
	// The registry could be:
	// - k8s.gcr.io
	// - fictional.registry.example:10443
	// The repository could be:
	// - kube-apiserver
	// - fictional/nginx
	// The tag cloud be:
	// - latest
	// - v1.19.1
	// - @sha256:dbcc1c35ac38df41fd2f5e4130b32ffdb93ebae8b3dbe638c23575912276fc9c
	//
	// +kubebuilder:validation:Enum=Registry;Repository;Tag
	// +required
	Component ImageComponent `json:"component"`

	// Operator represents the operator which will apply on the image.
	// +kubebuilder:validation:Enum=add;remove;replace
	// +required
	Operator OverriderOperator `json:"operator"`

	// Value to be applied to image.
	// Must not be empty when operator is 'add' or 'replace'.
	// Defaults to empty and ignored when operator is 'remove'.
	// +optional
	Value string `json:"value,omitempty"`
}

// Predicate describes images filter.
type ImagePredicate struct {
	// Path indicates the path of target field
	// +required
	Path string `json:"path"`
}

// ImageComponent indicates the components for image.
type ImageComponent string

const (
	// Registry is the registry component of an image with format '[registry/]repository[:tag]'.
	Registry ImageComponent = "Registry"

	// Repository is the repository component of an image with format '[registry/]repository[:tag]'.
	Repository ImageComponent = "Repository"

	// Tag is the tag component of an image with format '[registry/]repository[:tag]'.
	Tag ImageComponent = "Tag"
)
```

**Comment by pigletfly** [comment]
consider we have this crd

```
apiVersion: core.test.com/v1beta1
kind: Application
metadata:
  name: test-rolling
  namespace: default
spec:
  components:
  - name: webserver
     properties:
       image: test.com/busybox:lastest
       replicas: 10
     type: webservice
  - name: frontend
     properties:
      image: test.com/busybox:lastest
      replicas: 20
     type: webservice
```
how do we override image in each component?

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang maybe could give an example.

Another idea brought to my mind that we can support other well-known `Replica resources` like native k8ss'. Or give a chance to user define `Replica resource` list, such as configuration from command line parameters.

**Comment by RainbowMango** [comment]
@pigletfly 
According to current API, that would be define overrider like this:
```yaml
  overriders:
    imageOverrider:
      - component: Registry
        operator: replace
        value: fictional.registry.us
        predicate: spec/components/0/image
      - component: Registry
        operator: replace
        value: fictional.registry.us
        predicate: spec/components/1/image
```

This is ugly, let's see how to improve the API.
