### ISSUE TITLE
install karmada-search can not apply resourceRegistry

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3152]
**What happened**:
install karmada-search can not apply resourceRegistry
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
first install karmada:
cd karmada-1.4.2/charts/karmada/
host模式
helm install karmada -n karmada-system --create-namespace --dependency-update .

then install search:
helm upgrade --install karmada -n karmada-system \
     --cleanup-on-fail . \
     --set components={"search"}

then apply resourceRegistry:
```
### deployment-search.yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: deployment-search
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
```
![49db5113c5f93d7e8402d63671435f4](https://user-images.githubusercontent.com/31508490/218686478-d6dc2895-eb48-4c30-ab1f-43048ba0083d.jpg)

**Anything else we need to know?**:

**Environment**:
- Karmada version:1.4.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
