### ISSUE TITLE
spreadConstraints 不生效，是不是replicaDivisionPreference必须是Aggregated的

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3184]
**Please provide an in-depth description of the question you have**:
```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - cluster1
          weight: 2
        - targetCluster:
            clusterNames:
            - cluster2
          weight: 8
    spreadConstraints:
    - maxGroups: 1
      minGroups: 1
      
```
部署了上面cr后，发现两个集群都有pod？
**What do you think about this question?**:

**Environment**:
- Karmada version: 1.4.0
- Kubernetes version: 1.23
- Others:
