### ISSUE TITLE
提个功能点需求：karmada 控制面支持给特定集群的特定node 打标签

### ISSUE THREAD

**Issue by dmulizhihui** [karmada-io/karmada#3185]
可不可以支持下，karmada 控制面给特定集群的特定node 打标签

**Comment by RainbowMango** [comment]
请分享下使用场景？

**Comment by dmulizhihui** [comment]
我们要频繁的给member cluster的node 打标签，想直接通过karmada控制面来操作；

**Comment by RainbowMango** [comment]
> 根据我们的业务，我们要频繁的给member cluster的node 打标签

为什么会频繁的打标签呢？这个场景不太常见

**Comment by dmulizhihui** [comment]
> > 根据我们的业务，我们要频繁的给member cluster的node 打标签
> 
> 为什么会频繁的打标签呢？这个场景不太常见

我们特定CDN场景的需要：
1，比如监控、日志，一般我们要全网部署的，一次都是给上万个节点打标签
2，AB部署场景
3，

**Comment by lonelyCZ** [comment]
你可以使用这种方式，直接在kubectl中设置聚合API地址，然后应该可以操作集群

https://karmada.io/docs/userguide/globalview/aggregated-api-endpoint/#step3-access-member-clusters

```
- cluster:
    certificate-authority-data: XXX
    server: https://10.10.103.67:32443/apis/cluster.karmada.io/v1alpha1/clusters/member67/proxy
  name: member67
```
```
[root@master67 ~]# kubectl label nodes master67 b=a --cluster member67 --kubeconfig /etc/karmada/karmada-apiserver.config
node/master67 labeled
```
