### ISSUE TITLE
overrideRules 不生效

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3186]
**What happened**:
```
overridepolicy/op-overrideRules-targetCluster-fieldSelector.yaml

kubectl apply -f op-overrideRules-targetCluster-fieldSelector.yaml -n karmada


apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: nginx
  namespace: karmada
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  overrideRules:
    - targetCluster:
        fieldSelector:
          matchExpressions:
          - key: metadata.name
            operator: In
            values: 
            - cluster1
      overriders:
        plaintext:
          - path: "/metadata/annotations"
            operator: add
            value:
              foo: bar
    - targetCluster:
        clusterNames:
          - cluster2
      overriders:
        annotationsOverrider:
          - operator: add
            value:
              testanno: testanno


overridepolicy/pp-placement-clusterAffinity.yaml

kubectl apply -f pp-placement-clusterAffinity.yaml -n karmada


apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2


overridepolicy/nginx-deploy.yaml

kubectl apply -f nginx-deploy.yaml -n karmada


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx



```
部署这个cluster deploy 没有加annotation
```
[root@member1-153 ~]# kubectl get deploy -n karmada nginx -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"nginx","namespace":"karmada"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx","name":"nginx"}]}}}}
    resourcebinding.karmada.io/name: nginx-deployment
    resourcebinding.karmada.io/namespace: karmada
    resourcetemplate.karmada.io/uid: 2171b05f-ea0a-468c-8b58-c425fe056e8b
  creationTimestamp: "2023-02-21T08:58:38Z"
```

```
[root@localhost overridepolicy]# kubectl get --kubeconfig ~/kube-karmada  clusters.cluster.karmada.io cluster1 -o yaml
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: "2023-02-14T06:12:06Z"
  finalizers:
  - karmada.io/cluster-controller
  name: cluster1
  resourceVersion: "392795"
  uid: 49b16d2b-05d2-41bc-a7ce-1a39d392a514
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:1.4.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
I guess the reason why the annotations weren't added to `cluster1` is `fieldSelector` only supports `.spec.provider/.spec.region/.spec.zone`. 
https://github.com/karmada-io/karmada/blob/ea497819f0ee883c8f46fbb390ac540df27f2b0b/pkg/util/selector.go#L113-L116

If you want to match clusters by name, you can use `--names`:
```yaml
        clusterNames:
          - cluster1
```

**Comment by RainbowMango** [comment]
In addition, I'm still thinking if it is reasonable to restrict the field selector to `provider/region/zone` and if there is something we can do to improve the user experience. 

Sorry for the inconvenience, at least we can update the document.

**Comment by 13567436138** [comment]
I want use field selector how do i need to modify

**Comment by 13567436138** [comment]
how to get a cluster‘s ’provider/region/zone

**Comment by RainbowMango** [comment]
This probably helps.
```yaml
          matchExpressions:
          - key: provider
            operator: In
            values: 
            - aws
```
