### ISSUE TITLE
spreadByLabel报错

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3187]
**What happened**:
```
#### 


kubectl label cluster cluster1 stage=dev --overwrite --kubeconfig ~/kube-karmada
kubectl label cluster cluster2 stage=prod --overwrite --kubeconfig ~/kube-karmada

[root@localhost propagationPolicy]# kubectl get cluster --show-labels --kubeconfig ~/kube-karmada 
NAME       VERSION   MODE   READY   AGE     LABELS
cluster1   v1.23.1   Push   True    7d18h   stage=dev
cluster2   v1.23.1   Push   True    7d18h   stage=prod


propagationPolicy/pp-placement-spreadConstraints-spreadByLabel.yaml

kubectl apply -f pp-placement-spreadConstraints-spreadByLabel.yaml -n karmada


apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      labelSelector:
        matchExpressions:
        - key: stage
          operator: In
          values:
          - dev
          - prod
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        dynamicWeight: AvailableReplicas
    spreadConstraints:
    - maxGroups: 2
      minGroups: 2
      spreadByLabel: stage
      


propagationPolicy/nginx-deploy-replicas.yaml

kubectl apply -f nginx-deploy-replicas.yaml -n karmada

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx


清理：


kubectl delete deploy nginx -n karmada
kubectl delete PropagationPolicy nginx -n karmada



```

 Warning  ScheduleBindingFailed   50s (x17 over 6m15s)   karmada-scheduler   failed to select clusters: just support cluster and region spread constraint
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
