### ISSUE TITLE
failover rb 没有生成gracefulEvictionTasks

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3194]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
```



kubectl apply -f nginx-failover-Duplicated.yaml -n karmada --kubeconfig ~/kube-karmada



apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-failover-duplicated
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx

apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-failover-duplicated
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
    replicaScheduling:
      replicaSchedulingType: Duplicated


资源被调度到cluster1


[root@member1-153 ~]# kubectl get pod -n karmada
NAME                                         READY   STATUS    RESTARTS   AGE
nginx-failover-duplicated-85b98978db-f79bn   1/1     Running   0          15s
nginx-failover-duplicated-85b98978db-fw6hs   1/1     Running   0          15s




停掉cluster1


  Conditions:
    Last Transition Time:  2023-02-17T06:36:19Z
    Message:               cluster is not reachable
    Reason:                ClusterNotReachable
    Status:                False
    Type:                  Ready




cluster2


[root@member2-156 ~]# kubectl get pod -n karmada -w
NAME                                         READY   STATUS    RESTARTS   AGE
nginx-failover-duplicated-85b98978db-dqlqx   0/1     Pending   0          0s
nginx-failover-duplicated-85b98978db-qq68v   0/1     Pending   0          0s
nginx-failover-duplicated-85b98978db-dqlqx   0/1     Pending   0          0s
nginx-failover-duplicated-85b98978db-qq68v   0/1     Pending   0          0s
nginx-failover-duplicated-85b98978db-dqlqx   0/1     ContainerCreating   0          0s
nginx-failover-duplicated-85b98978db-qq68v   0/1     ContainerCreating   0          0s
nginx-failover-duplicated-85b98978db-dqlqx   1/1     Running             0          4s
nginx-failover-duplicated-85b98978db-qq68v   1/1     Running             0          8s



```

```
spec:
  clusters:
  - name: cluster2
    replicas: 2
  replicas: 2
  resource:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-failover-duplicated
    namespace: karmada
    resourceVersion: "472394"
    uid: 4bbdf546-3ac2-4c97-9caf-8eb80d7e3d61
```

rb 没有生成## gracefulEvictionTasks

### creationTimestamp,fromCluster,message,producer,reason,replicas

是瞬间生成的么，迁移成功就删除了么
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:
