### ISSUE TITLE
ClusterPropagationPolicy调度不正确

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3195]
**What happened**:
```
clusterResourceBinding/cpp-placement-replicaScheduling-staticWeightList.yaml

kubectl apply -f cpp-placement-replicaScheduling-staticWeightList.yaml -n karmada

apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - cluster1
          weight: 2
        - targetCluster:
            clusterNames:
            - cluster2
          weight: 3


clusterResourceBinding/nginx-deploy-replica.yaml

kubectl apply -f nginx-deploy-replica.yaml -n karmada


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx




```

cluster1
[root@member1-153 ~]# kubectl get pod -n karmada
NAME                     READY   STATUS    RESTARTS      AGE
nginx-85b98978db-66tdm   1/1     Running   0             6m10s
nginx-85b98978db-dgcfs   1/1     Running   0             6m10s
nginx-85b98978db-gkc82   1/1     Running   0             6m10s
nginx-85b98978db-j8684   1/1     Running   0             6m10s
nginx-85b98978db-vd8qm   1/1     Running   0             6m10s

cluster2
[root@member2-156 ~]# kubectl get pod -n karmada
NAME                                         READY   STATUS    RESTARTS      AGE
my-nginx-5b5cffb444-8dx8x                    1/1     Running   0             20m
my-nginx-5b5cffb444-jr56c                    1/1     Running   0             41m
nginx-85b98978db-8kn9b                       1/1     Running   0             6m26s
nginx-85b98978db-dnkwh                       1/1     Running   0             6m26s
nginx-85b98978db-fkghh                       1/1     Running   0             6m26s
nginx-85b98978db-ws2l9                       1/1     Running   0             6m26s
nginx-85b98978db-xhk2d                       1/1     Running   0             6m26s

cluster1和cluster2都生成了5个副本，并没有静态分割

也没有生成clusterresourcebinding,只生成了resourcebinding
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:1.4.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
