### ISSUE TITLE
when type is Headless no derived svc generated

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3200]
**What happened**:
```
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: nginx
spec:
  type: Headless
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-import-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
```

[root@member1-153 ~]# kubectl get svc -n karmada 
NAME    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
serve   ClusterIP   10.69.255.59   <none>        80/TCP    5d22h
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
