### ISSUE TITLE
Support scheduler plugin to pass in custom parameters

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3205]
**What would you like to be added**:
We may need to provide a config to record custom parameters.

**Why is this needed**:
Users need to configure parameters when customizing the scheduler plugin, especially the complex scoring plugin.

Reference:
k8s: https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1/#kubescheduler-config-k8s-io-v1-KubeSchedulerProfile
Volcano: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
---
```

Maybe it's time to provide a `karmada-scheduler-conf` thing.
