### ISSUE TITLE
doc need to update

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3206]
**What happened**:
https://karmada.io/zh/docs/userguide/cicd/working-with-flux
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
spec:
  interval: 1m
  url: https://stefanprodan.github.io/podinfo  
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: podinfo
```
https://stefanprodan.github.io/podinfo   this url is 404
![image](https://user-images.githubusercontent.com/31508490/221121008-a52f1877-a044-4dd6-8dc7-e9775d59c734.png)

can update the doc

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
