### ISSUE TITLE
Unauthenticated desc = authentication failure，karmada 结合istio多集群

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3227]
**What happened**:
2023-03-01T01:58:18.002417Z	info	xdsproxy	connected to upstream XDS server: istiod-remote.istio-system.svc:15012
2023-03-01T01:58:18.027915Z	warn	xdsproxy	upstream [84] terminated with unexpected error rpc error: code = Unauthenticated desc = authentication failure
2023-03-01T01:58:18.028820Z	warning	envoy config external/envoy/source/common/config/grpc_stream.h:163	StreamAggregatedResources gRPC config stream to xds-grpc closed: 16, authentication failure	thread=13

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
### 

```
kubectl create namespace istio-system --kubeconfig ~/kube-karmada
kubectl create secret generic cacerts  --kubeconfig ~/kube-karmada -n istio-system \
    --from-file=certs/primary/ca-cert.pem \
    --from-file=certs/primary/ca-key.pem \
    --from-file=certs/primary/root-cert.pem \
    --from-file=certs/primary/cert-chain.pem
```

serviceGovernance/istio-host-primary-remote-single-network/pp-cacerts-propagation.yaml

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: cacerts-propagation
  namespace: istio-system
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      name: cacerts
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
```

```
kubectl apply -f pp-cacerts-propagation.yaml -n istio-system --kubeconfig ~/kube-karmada
```

Run the following command to install istio CRDs on karmada apiserver:

**image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/pilot**

```
cat <<EOF | istioctl install --kubeconfig ~/kube-karmada -y --set profile=minimal -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: primary
      network: network1
EOF
```

Karmada apiserver will not deploy a real istiod pod, you should press `ctrl+c` to exit installation when `Processing resources for Istiod`.

```bash
✔ Istio core installed                                                                                                                                                         
- Processing resources for Istiod.
```

**Install Istio on karmada host**

```
kubectl create namespace istio-system
kubectl create secret generic cacerts -n istio-system \
    --from-file=certs/primary/ca-cert.pem \
    --from-file=certs/primary/ca-key.pem \
    --from-file=certs/primary/root-cert.pem \
    --from-file=certs/primary/cert-chain.pem
```

Create istio-kubeconfig on karmada-host

```
kubectl create secret generic istio-kubeconfig --from-file=config=/root/kube-karmada -nistio-system
```

Install istio control plane

```
cat <<EOF | istioctl install -y --set profile=minimal -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: primary
      network: network1
EOF
```

Expose istiod service

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: istiod-elb
  namespace: istio-system
spec:
  ports:
  - name: https-dns
    port: 15012
    protocol: TCP
    targetPort: 15012
  selector:
    app: istiod
    istio: pilot
  sessionAffinity: None
  type: LoadBalancer
EOF
```

Export DISCOVERY_ADDRESS:

```bash
export DISCOVERY_ADDRESS=$(kubectl get svc istiod-elb -nistio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
# verify
echo $DISCOVERY_ADDRESS
```

Prepare member cluster secret

```
istioctl x create-remote-secret --name=cluster1 --kubeconfig ~/.kube/147config > istio-remote-secret-cluster1.yaml

istioctl x create-remote-secret --name=cluster2 --kubeconfig ~/.kube/159config  > istio-remote-secret-cluster2.yaml

```

Apply istio remote secret

```
kubectl apply -f istio-remote-secret-cluster1.yaml --kubeconfig ~/kube-karmada

kubectl apply -f istio-remote-secret-cluster2.yaml --kubeconfig ~/kube-karmada
```

Install istio remote cluster1

image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/proxyv2

**需要注意的是 ctr 是 containerd 自带的工具，有命名空间的概念。Kubernetes 下使用的 containerd 默认命名空间是 k8s.io。所以在导入镜像时需要指定命令空间为 k8s.io，否则使用 crictl images 无法查询到。**

```
cat <<EOF | istioctl install --kubeconfig ~/.kube/147config -y -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
      remotePilotAddress: ${DISCOVERY_ADDRESS}
EOF
```

Install istio remote cluster2

```
cat <<EOF | istioctl install  --kubeconfig ~/.kube/159config -y -f -
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: true
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network1
      remotePilotAddress: ${DISCOVERY_ADDRESS}
EOF
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.14.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
- k8s 1.26.1
- istio 1.17.1
