### ISSUE TITLE
Region selection algorithm optimization

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3253]
**What would you like to be added**:
There are some problems with the current region selection algorithm, and I think it should be further optimized.

**Why is this needed**:
I will give the following two examples to illustrate why the region selection algorithm needs to be optimized.

**Example-1: those regions that meet the cluster's the quantity requirements(`[minGroups, maxGroups]`) and have higher score should be selected**
Assuming that there is the following region distribution:

![regions-1](https://user-images.githubusercontent.com/89241565/224004081-381825fd-e242-4d83-bc55-dd60625cb54b.png)

and we use those spread constraints:
```
    spreadConstraints:
    - maxGroups: 3
      minGroups: 2
      spreadByField: region
    - maxGroups: 6
      minGroups: 4
      spreadByField: cluster
```
they will be sorted by score first:
```
R3 -> R1 -> R2 -> R4
```
then according to the existing karmada algorithm, `R3` and `R4` will eventually be selected. But `R2` and `R3` are the best choice because the score of `R2` is higher than `R4` and they can both meet the cluster's the quantity requirements.

**Example-2: if the quantity of any `minGroups` regions’ clusters cannot meet the cluster's the quantity requirements(`[minGroups, maxGroups]`), we should try to increase the number of regions to meet the requirements instead of giving up**
Assuming that there is the following region distribution:

![region-2](https://user-images.githubusercontent.com/89241565/224010972-4af2f0a8-99e8-4ae1-9117-e4ca439d286d.png)

and we use those spread constraints:
```
    spreadConstraints:
    - maxGroups: 3
      minGroups: 1
      spreadByField: region
    - maxGroups: 8
      minGroups: 6
      spreadByField: cluster
```
they will be sorted by score first:
```
R4 -> R1 -> R3 -> R5 -> R2
```
then according to the existing karmada algorithm, no region will eventually be selected. But `R2`, `R3` and `R4` are the best choice because the score of `R4` is higher than `R1` and `R5`, `R2` and `R3` are required.
