### ISSUE TITLE
ResourceInterpreterCustomization not work

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3263]
**What happened**:
resourceInterpreter/cloneset-updateStrategy-type-InPlaceIfPossible.yaml

kubectl apply -f cloneset-updateStrategy-type-InPlaceIfPossible.yaml -n karmada --kubeconfig ~/kube-karmada

```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        test: mytest
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: test
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['test']
  updateStrategy:
    type: InPlaceIfPossible
```

resourceInterpreter/pp-placement-clusterAffinity-clusterNames.yaml

kubectl apply -f pp-placement-clusterAffinity-clusterNames.yaml -n karmada --kubeconfig ~/kube-karmada

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps.kruise.io/v1alpha1
      kind: CloneSet
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
```

cluster1:

```
status:
  availableReplicas: 3
  collisionCount: 0
  currentRevision: nginx-75b64b796d
  expectedUpdatedReplicas: 5
  labelSelector: app=nginx
  observedGeneration: 1
  readyReplicas: 3
  replicas: 5
  updateRevision: nginx-75b64b796d
  updatedReadyReplicas: 3
  updatedReplicas: 5
```

cluster2:

```
status:
  availableReplicas: 5
  collisionCount: 0
  currentRevision: nginx-75b64b796d
  expectedUpdatedReplicas: 5
  labelSelector: app=nginx
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
  updateRevision: nginx-75b64b796d
  updatedReadyReplicas: 5
  updatedReplicas: 5
```

karmada-apiserver:

没有status

```
[root@localhost resourceInterpreter]# kubectl get --kubeconfig ~/kube-karmada clonesets.apps.kruise.io -n karmada nginx -o yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.kruise.io/v1alpha1","kind":"CloneSet","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"nginx","namespace":"karmada"},"spec":{"replicas":5,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx","test":"mytest"}},"spec":{"containers":[{"env":[{"name":"test","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['test']"}}}],"image":"nginx:alpine","name":"nginx"}]}},"updateStrategy":{"type":"InPlaceIfPossible"}}}
  creationTimestamp: "2023-03-10T23:54:22Z"
  generation: 1
  labels:
    app: nginx
    propagationpolicy.karmada.io/name: nginx
    propagationpolicy.karmada.io/namespace: karmada
  name: nginx
  namespace: karmada
  resourceVersion: "1210014"
  uid: b1de2643-e341-4055-aff4-cdbd6e8690bf
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        test: mytest
    spec:
      containers:
      - env:
        - name: test
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['test']
        image: nginx:alpine
        name: nginx
  updateStrategy:
    type: InPlaceIfPossible
```

resourceInterpreter/ric-cloneset.yaml

kubectl apply -f ric-cloneset.yaml -n karmada --kubeconfig ~/kube-karmada

```
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: ric-cloneset
spec:
  target:
    apiVersion: apps.kruise.io/v1alpha1
    kind: CloneSet
  customizations:
    replicaResource:
      luaScript: >
        function GetReplicas(obj)
          replica = obj.spec.replicas
          requirement = {}
          return replica, requirement
        end
    replicaRevision:
      luaScript: >
        function ReviseReplica(obj, desiredReplica)
          obj.spec.replicas = desiredReplica
          return obj
        end
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          desiredObj.spec.paused = observedObj.spec.paused
          return desiredObj
        end
    statusAggregation:
      luaScript: >
        function AggregateStatus(desiredObj, statusItems)
          if statusItems == nil then
            return desiredObj
          end
          if desiredObj.status == nil then
            desiredObj.status = {}
          end
          replicas = 0
          for i = 1, #statusItems do
            if statusItems[i].status ~= nil and statusItems[i].status.replicas ~= nil then
              replicas = replicas + statusItems[i].status.replicas
            end
          end
          desiredObj.status.replicas = replicas
          return desiredObj
        end
    statusReflection:
      luaScript: >
        function ReflectStatus (observedObj)
          return observedObj.status
        end
    healthInterpretation:
      luaScript: >
        function InterpretHealth(observedObj)
          return observedObj.status.readyReplicas == observedObj.spec.replicas
        end
    dependencyInterpretation:
      luaScript: >
        function GetDependencies(desiredObj)
          dependentSas = {}
          refs = {}
          if desiredObj.spec.template.spec.serviceAccountName ~= '' and desiredObj.spec.template.spec.serviceAccountName ~= 'default' then
            dependentSas[desiredObj.spec.template.spec.serviceAccountName] = true
          end
          local idx = 1
          for key, value in pairs(dependentSas) do
            dependObj = {}
            dependObj.apiVersion = 'v1'
            dependObj.kind = 'ServiceAccount'
            dependObj.name = key
            dependObj.namespace = desiredObj.metadata.namespace
            refs[idx] = dependObj
            idx = idx + 1
          end
          return refs
        end

```

[root@localhost resourceInterpreter]# kubectl get --kubeconfig ~/kube-karmada clonesets.apps.kruise.io -n karmada nginx 
NAME    DESIRED   UPDATED   UPDATED_READY   READY   TOTAL   AGE
nginx   5                                                   19m
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
@13567436138 Have you checked the ResourceBinding? The first thing we need to figure out is if the status will be collected to ResourceBinding.

Then, please check the log of `karmada-controller-manager` if there is any error message, especially the following one:
https://github.com/karmada-io/karmada/blob/83c7862289ac3884985cee2a10f023ffb8f925b2/pkg/controllers/status/common.go#L77-L81

**Comment by 13567436138** [comment]
```
status:
  aggregatedStatus:
  - applied: true
    clusterName: cluster1
    health: Healthy
    status:
      availableReplicas: 5
      collisionCount: 0
      currentRevision: nginx-75b64b796d
      expectedUpdatedReplicas: 5
      labelSelector: app=nginx
      observedGeneration: 1
      readyReplicas: 5
      replicas: 5
      updateRevision: nginx-75b64b796d
      updatedReadyReplicas: 5
      updatedReplicas: 5
  - applied: true
    clusterName: cluster2
    health: Healthy
    status:
      availableReplicas: 5
      collisionCount: 0
      currentRevision: nginx-75b64b796d
      expectedUpdatedReplicas: 5
      labelSelector: app=nginx
      observedGeneration: 1
      readyReplicas: 5
      replicas: 5
      updateRevision: nginx-75b64b796d
      updatedReadyReplicas: 5
      updatedReplicas: 5
```
貌似rb没问题
