### ISSUE TITLE
error: result type 0 is not number(集成kruise错误)

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3271]
**What happened**:
controller manager error:
```
E0313 09:30:59.802805       1 detector.go:632] Failed to customize replicas for apps.kruise.io/v1alpha1, Kind=DaemonSet(nginx), result type 0 is not number
E0313 09:30:59.802883       1 detector.go:397] Failed to build resourceBinding for object: apps.kruise.io/v1alpha1, kind=DaemonSet, karmada/nginx. error: result type 0 is not number
I0313 09:30:59.802914       1 worker.go:127] Dropping resource "apps.kruise.io/v1alpha1, kind=DaemonSet, karmada/nginx" out of the queue: result type 0 is not number
I0313 09:30:59.802950       1 recorder.go:103] "events: Apply policy(karmada/nginx-propagation) failed: result type 0 is not number" type="Warning" object={Kind:DaemonSet Namespace:karmada Name:nginx UID:5e9b2348-8523-407b-8a5b-4925212c4323 APIVersion:apps.kruise.io/v1alpha1 ResourceVersion:1271215 FieldPath:} reason="ApplyPolicyFailed"
```
**What you expected to happen**:
部署成功，并且把依赖一并部署过去。
**How to reproduce it (as minimally and precisely as possible)**:
应用如下yaml:
resourceInterpreter/ads-updateStrategy-rollingUpdate-paused.yaml

kubectl apply -f ads-updateStrategy-rollingUpdate-paused.yaml -n karmada --kubeconfig ~/kube-karmada

```
apiVersion: v1
data:
  num: ”1“
kind: ConfigMap
metadata:
  name: game-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        test: test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: test
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['test']
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: NUM
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: num
      serviceAccountName: mysa 
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      partition: 2
      paused: true
      rollingUpdateType: InPlaceIfPossible
```

resourceInterpreter/pp-nginx.yaml

kubectl apply -f pp-nginx.yaml -n karmada --kubeconfig ~/kube-karmada

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: apps.kruise.io/v1alpha1
      kind: DaemonSet
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - cluster1
            weight: 1
          - targetCluster:
              clusterNames:
                - cluster2
            weight: 1
```

resourceInterpreter/ric-daemonset.yaml

kubectl apply -f ric-daemonset.yaml -n karmada --kubeconfig ~/kube-karmada

```
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: ric-daemonset
spec:
  target:
    apiVersion: apps.kruise.io/v1alpha1
    kind: DaemonSet
  customizations:
    replicaResource:
      luaScript: >
        function GetReplicas(obj)
          replica = obj.spec.replicas
          requirement = {}
          return replica, requirement
        end
    replicaRevision:
      luaScript: >
        function ReviseReplica(obj, desiredReplica)
          obj.spec.replicas = desiredReplica
          return obj
        end
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          desiredObj.spec.paused = observedObj.spec.paused
          return desiredObj
        end
    statusAggregation:
      luaScript: >
        function AggregateStatus(desiredObj, statusItems)
          if statusItems == nil then
            return desiredObj
          end
          if desiredObj.status == nil then
            desiredObj.status = {}
          end
          replicas = 0
          availableReplicas = 0
          readyReplicas = 0
          updatedReadyReplicas = 0
          updatedReplicas = 0 
          for i = 1, #statusItems do
            if statusItems[i].status ~= nil and statusItems[i].status.replicas ~= nil then
              replicas = replicas + statusItems[i].status.replicas
            end
            if statusItems[i].status ~= nil and statusItems[i].status.availableReplicas ~= nil then
              availableReplicas = availableReplicas + statusItems[i].status.availableReplicas
            end
            if statusItems[i].status ~= nil and statusItems[i].status.readyReplicas ~= nil then
              readyReplicas = readyReplicas + statusItems[i].status.readyReplicas
            end
            if statusItems[i].status ~= nil and statusItems[i].status.updatedReadyReplicas ~= nil then
              updatedReadyReplicas = updatedReadyReplicas + statusItems[i].status.updatedReadyReplicas
            end
            if statusItems[i].status ~= nil and statusItems[i].status.updatedReplicas ~= nil then
              updatedReplicas = updatedReplicas + statusItems[i].status.updatedReplicas
            end
          end
          desiredObj.status.replicas = replicas
          desiredObj.status.availableReplicas = availableReplicas
          desiredObj.status.readyReplicas = readyReplicas
          desiredObj.status.updatedReadyReplicas = updatedReadyReplicas
          desiredObj.status.updatedReplicas = updatedReplicas
          return desiredObj
        end
    statusReflection:
      luaScript: >
        function ReflectStatus (observedObj)
          return observedObj.status
        end
    healthInterpretation:
      luaScript: >
        function InterpretHealth(observedObj)
          return observedObj.status.readyReplicas == observedObj.spec.replicas
        end
    dependencyInterpretation:
      luaScript: >
        function GetDependencies(desiredObj)
          dependentSas = {}
          refs = {}
          if desiredObj.spec.template.spec.serviceAccountName ~= '' and desiredObj.spec.template.spec.serviceAccountName ~= 'default' then
            dependentSas[desiredObj.spec.template.spec.serviceAccountName] = true
          end
          local idx = 1
          for key, value in pairs(dependentSas) do
            dependObj = {}
            dependObj.apiVersion = 'v1'
            dependObj.kind = 'ServiceAccount'
            dependObj.name = key
            dependObj.namespace = desiredObj.metadata.namespace
            refs[idx] = dependObj
            idx = idx + 1
          end
          for v in desiredObj.spec.template.spec.containers do
             for e in v.env do
               if e.valueFrom ~= '' and e.valueFrom.secretKeyRef ~= '' then
                 dependObj = {}
                 dependObj.apiVersion = 'v1'
                 dependObj.kind = 'Secret'
                 dependObj.name = e.valueFrom.secretKeyRef.name
                 dependObj.namespace = desiredObj.metadata.namespace
                 refs[idx] = dependObj
                 idx = idx + 1
                end
               if e.valueFrom ~= '' and e.valueFrom.configMapKeyRef ~= '' then
                 dependObj = {}
                 dependObj.apiVersion = 'v1'
                 dependObj.kind = 'ConfigMap'
                 dependObj.name = e.valueFrom.configMapKeyRef.name
                 dependObj.namespace = desiredObj.metadata.namespace
                 refs[idx] = dependObj
                 idx = idx + 1
                end
             end
          end
          
          return refs
        end

```

rb也没生成。cloneset是成功的了，AdvancedDaemonSet不知为啥不行

**Anything else we need to know?**:

**Environment**:
- Karmada version:1.4.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
