### ISSUE TITLE
Can karmada ensure that replicas are stable across member clusters during updates?

### ISSUE THREAD

**Issue by 906798724** [karmada-io/karmada#3272]
**Please provide an in-depth description of the question you have**:
in our scenarios, let's say:
1. member cluster A has a deployment-1 that replicas is 10
2. then we update deployment-1 by Karmada control plane to our expectation result, which is: member cluster A has deployment-1 with 5 replicas, and member cluster B has deployment-1 with 5 replicas

**What do you think about this question?**:
will the Karmada ensure the total replicas count will always greater than 10?
because if the total replicas count less than 10, will cause service downgrade

**Environment**:
- Karmada version: the latest verion
- Kubernetes version:
- Others:

**Comment by chaunceyjiang** [comment]
> then we update deployment-1 by Karmada control plane to our expectation result, 

What method did you use to update?

**Comment by 906798724** [comment]
> > then we update deployment-1 by Karmada control plane to our expectation result,
> 
> What method did you use to update?

like change the stratgy of scheduler, or change the status of member cluster
you may think every factors can cause the replicas changed in member clusters

**Comment by RainbowMango** [comment]
:) I don't think you answered @chaunceyjiang's question.
Could you please share your whole process in detail? so that we can understand your question easily.

**Comment by 906798724** [comment]
for the samples 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 10 // we have 10 replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```
 
at the first, we use this `PropagationPolicy`
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
```
all of the 10 replicas will be create in member1 cluster

then we change the `PropagationPolicy` to 
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member2 // new member 2
        - member3 // new member 3
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
          - targetCluster:
              clusterNames:
                - member3
            weight: 1
```
i think both member2 and member3 cluster will have 5 replicas, and the 10 replicas in member1 will be deleted

here is my question:
**during this update, will Karmada ensure the total count of replicas not less than 10?**
