### ISSUE TITLE
Scheduling behavior is inconsistent when replicaScheduling is not filled

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3289]
Assume there are two policies which the meaning is exactly the same:
```
placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
    replicaScheduling:
      replicaSchedulingType: Duplicated
   spreadConstraints:
      - maxGroups: 1
         minGroups: 1
```

```
placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
     spreadConstraints:
      - maxGroups: 1
         minGroups: 1
```

Now the scheduler schedules the workload to member1. But I edit the spec.clusters of resourceBinding and hope it will schedule to member2. For the first policy, it will schedule to member2. For the second policy, it will not.

Through analysis, we find that `clusterLocality` does not work for the second policy because replicas == 0.
```
func (p *ClusterLocality) Score(ctx context.Context, placement *policyv1alpha1.Placement,
	spec *workv1alpha2.ResourceBindingSpec, cluster *clusterv1alpha1.Cluster) (int64, *framework.Result) {
	if len(spec.Clusters) == 0 {
		return framework.MinClusterScore, framework.NewResult(framework.Success)
	}

	replicas := util.GetSumOfReplicas(spec.Clusters)
	if replicas <= 0 {
		return framework.MinClusterScore, framework.NewResult(framework.Success)
	}

	if spec.TargetContains(cluster.Name) {
		return framework.MaxClusterScore, framework.NewResult(framework.Success)
	}

	return framework.MinClusterScore, framework.NewResult(framework.Success)
}
```

I think when I don't fill in the strategy it's implied that we are using duplicated strategy, so the number of replicas is necessary if the workload has.
