### ISSUE TITLE
collect full status info when propagate pods to only one cluster

### ISSUE THREAD

**Issue by neteric** [karmada-io/karmada#3304]
**What would you like to be added**:

According to [#1913](https://github.com/karmada-io/karmada/pull/1913#issuecomment-1152839172),  We can collect full status information when propagate pod to only one cluster

**Why is this needed**:

When we get full status information about a pod, we can run  StatefulSet controller on Karmada control panel (karmada-controller-manager skipped-propagating-apis need include statefulset)

In this way, we can transparently propagate pods of stateful services to multiple clusters

/assign

**Comment by chaunceyjiang** [comment]
> karmada-controller-manager skipped-propagating-apis need include statefulset

Can you explain more details? Why do you need to do this?

**Comment by RainbowMango** [comment]
> We can collect full status information when propagate pod to only one cluster

Maybe I didn't get it. What do you mean `collect full status infomation`?

**Comment by neteric** [comment]
> > We can collect full status information when propagate pod to only one cluster
> 
> Maybe I didn't get it. What do you mean `collect full status infomation`?

Now, the status of pod resource in Karmada control panel not include  `HostIP`、`PodIP` 、`QOSClass`、`PodIPs` 、`Conditions`  when we propagate a pod to multi cluster, reason as say[#1913](https://github.com/karmada-io/karmada/pull/1913#issuecomment-1152839172)

But, we can save this field to pod’s status on AggregateStatus if a pod only propagate to one cluster, That is to say,len(aggregatedStatusItems)==1

**Comment by chaunceyjiang** [comment]
> But, we can save this field to pod’s status on AggregateStatus if a pod only propagate to one cluster, That is to say,len(aggregatedStatusItems)==1


Maybe you can use a configurable interpreter to do the work.

Just like:


``` yaml

apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-example
spec:
  target:
    apiVersion: v1
    kind: Pod
  customizations:
        statusAggregation:
      luaScript: >
        function AggregateStatus(desiredObj, statusItems)
          if statusItems == nil then
            return desiredObj
          end
          if desiredObj.status == nil then
            desiredObj.status = {}
          end

         -- do something

          return desiredObj
        end

```
