### ISSUE TITLE
The logic of karmada-scheduler judging whether the placement has changed could be optimized

### ISSUE THREAD

**Issue by 1285yvonne** [karmada-io/karmada#3361]
**What would you like to be added**:

A while ago we had a problem when updating karmada. We restarted karmada-agent in member cluster and karmada-controller-manager in master cluster, then all resourceBindings were re-enqueued in karmada-scheduler (I understand this was normal behavior). But we found that **some of**(not all) our deployments were rescheduled, and karmada-scheduler will have a corresponding log "Start to schedule ResourceBinding(xxx/xxx) as placement changed". In addition, the status of some clusters changed during the change process, resulting in changes in the scheduling results, and some Pods were rebuilt. 

Because we actually did not enable the feature gates of Failover, we thought that the rescheduling was actually not as expected. So we checked the log and karmada-scheduler, and found that a judgment in karmada-scheduler was not very reasonable.

Our PropagationPolicy is:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: deploy
  namespace: test-test
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - clusterA
      - clusterB
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
```

but the placement in the resourceBinding's annotations is

```json
{
  "clusterAffinity": {
    "clusterNames": [
      "clusterA",
      "clusterB"
    ]
  },
  "replicaScheduling": {
    "replicaSchedulingType": "Divided",
    "replicaDivisionPreference": "Weighted",
    "weightPreference": {
      "staticWeightList": [
        {
          "targetCluster": {
            "clusterNames": [
              "clusterA"
            ]
          },
          "weight": 1
        },
        {
          "targetCluster": {
            "clusterNames": [
              "clusterB"
            ]
          },
          "weight": 1
        }
      ]
    }
  }
}
```

The karmada-scheduler compares the strings of the placement of pp and the placement in the annotation. In this case, they must be unequal and will be rescheduled.

```go
// file: pkg/scheduler/scheduler.go
	policyPlacement, policyPlacementStr, err := s.getPlacement(rb)
	if err != nil {
		return err
	}
	appliedPlacement := util.GetLabelValue(rb.Annotations, util.PolicyPlacementAnnotation)
	if policyPlacementStr != appliedPlacement {
		// policy placement changed, need schedule
		klog.Infof("Start to schedule ResourceBinding(%s/%s) as placement changed", namespace, name)
		err = s.scheduleResourceBinding(rb)
		metrics.BindingSchedule(string(ReconcileSchedule), utilmetrics.DurationInSeconds(start), err)
		return err
	}
```

I'm not sure if this can be considered a bug, but at least it's an optimization. 

**Why is this needed**:

**Comment by chaunceyjiang** [comment]
> We restarted karmada-agent in member cluster and karmada-controller-manager in master cluster, 

Have you restarted  karmada-scheduler  before?

**Comment by 1285yvonne** [comment]
> Have you restarted karmada-scheduler before?

No, karmada-scheduler has no need to be updated, so we didn't restart it.

**Comment by RainbowMango** [comment]
Thanks @1285yvonne for spotting. Before answering and looking into this case, I might need to ask some questions to understand this.

> A while ago we had a problem when updating karmada.

Do you mean upgrade Karmada? From which version to which version?

> In addition, the status of some clusters changed during the change process, resulting in changes in the scheduling results, and some Pods were rebuilt.

`the status of some clusters changed` I wonder did Karmada changed the cluster's status?

**Comment by whitewindmills** [comment]
@1285yvonne Hi
Could you share your karmada-schduler's log? It is better to pack it into a compressed file.

**Comment by 1285yvonne** [comment]
> Could you share your karmada-schduler's log? It is better to pack it into a compressed file.

Sorry, this incident violates our company guidelines.I can only copy part of the desensitized data in the issue.

**Comment by chaunceyjiang** [comment]
Hi, can you provide the version of Karmada, and more detail logs.

> We restarted karmada-agent in member cluster and karmada-controller-manager in master cluster,
> Cluster's status changed, Ready --> Unknow --> Ready

I used the latest version but it didn't reproduce.

My reproduce step:
1. create a deployment and a PP 
2. stop karmada-controller-manager 
3. shutdown clusterA cluster and wait 2 mins
4. start karmada-controller-manager  
5. start  clusterA cluster
6. watch karmada-scheduler log and annotations of RB

There are no logs such as "Start to schedule ResourceBinding(xxx/xxx) as placement changed".

**Comment by 1285yvonne** [comment]
OK，We reproduced it at Karmada 1.2.2 and Karmada 1.4. There is our reproduce step:

1.  create a deployment and a pp, like this one:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-deploy
  namespace: test-test
spec:
  placement:
    clusterAffinity:
      clusterNames:
        - clusterA
        - clusterB
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: test-test
```
2. In fact, after the RB is created, you can see that the placement in the annotation of the RB already has a list of weight configurations (the default weight configuration that does not exist in the pp configuration) already
2. stop karmada-agent and karmada-controller-manager, wait for the cluster's status to UNKNOW
3. start karmada-agent in turn
4. start karmada-controller-manager
5. watch karmada-scheduler, will see logs like this:
```
{"log":"I0328 04:03:52.471393 1 event_handler.go:155] Requeue ResourceBinding(xxx/xxx) as placement changed.\n","stream":"stderr","time":"2023-03-28T04:03:52.471437891Z"}
```

Or very simply, after the deployment and pp are created, wait for the distribution to complete, restart the karmada-scheduler, and you will see this log.
