### ISSUE TITLE
how to add/replace container env in OverridePolicy and keep other envs alive？

### ISSUE THREAD

**Issue by mkloveyy** [karmada-io/karmada#3362]
This is part of my deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: CPUS
          value: "1"
```
This is part of my OverridePolicy:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
spec:
  overrideRules:
  - targetCluster:
        clusterNames:
          - sharb-x
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env
            operator: add
            value:
              - name: TEST
                value: captain-test
```
I wish my cluster sharb-x deployment may be:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: CPUS
          value: "1"
        - name: TEST
          value: captain-test
```
But actual is:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: TEST
          value: captain-test
```
`CPUS` env is missing.

So how can I add or replace container env in OverridePolicy and keep other envs alive？
Thanks!

**Environment**:
- Karmada version: v1.4.1-with-lua
- Kubernetes version: 1.19
- Others:

**Comment by RainbowMango** [comment]
@chaunceyjiang Could you please help? How can we `add` an item to a slice?

I'm thinking if we need another overrider dedicated for container env, just like what we did for [ImageOverrider ](https://github.com/karmada-io/karmada/blob/7502b2507f3c4004d94e272f5e03e1dfde83d0e2/pkg/apis/policy/v1alpha1/override_types.go#L96).

**Comment by XiShanYongYe-Chang** [comment]
This is more like a issue of json-patch using, how about testing with the below op:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
spec:
  overrideRules:
  - targetCluster:
        clusterNames:
          - sharb-x
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/0
            operator: add
            value:
              - name: TEST
                value: captain-test
```

**Comment by Poor12** [comment]
> This is more like a issue of json-patch using, how about testing with the below op:
> 
> ```yaml
> apiVersion: policy.karmada.io/v1alpha1
> kind: OverridePolicy
> spec:
>   overrideRules:
>   - targetCluster:
>         clusterNames:
>           - sharb-x
>       overriders:
>         plaintext:
>           - path: /spec/template/spec/containers/0/env/0
>             operator: add
>             value:
>               - name: TEST
>                 value: captain-test
> ```

Yes. Another optional overridepolicy is like:
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
spec:
  overrideRules:
  - targetCluster:
        clusterNames:
          - sharb-x
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/-
            operator: add
            value:
              - name: TEST
                value: captain-test
```

**Comment by RainbowMango** [comment]
@chaunceyjiang Can you help add an agenda to the community meeting? Let's gather some feedback there, I'm not sure if this(override envs) is a common case. 

@mkloveyy Can you confirm if the suggestion shared by @XiShanYongYe-Chang and @Poor12 works for you?

**Comment by mkloveyy** [comment]
@RainbowMango Thank for help. I've tried both two suggestions but still didn't work and got same response:
```sh
admission webhook xxx denied the request: xxxx Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|],"env":[[{"name":"T|..., bigger context ...|=128","-threadCount=1","-waitSeconds=10"],"env":[[{"name":"TEST","value":"captain-test"}]
```

**Comment by mkloveyy** [comment]
> @chaunceyjiang Could you please help? How can we `add` an item to a slice?
> 
> I'm thinking if we need another overrider dedicated for container env, just like what we did for [ImageOverrider ](https://github.com/karmada-io/karmada/blob/7502b2507f3c4004d94e272f5e03e1dfde83d0e2/pkg/apis/policy/v1alpha1/override_types.go#L96).

Agreed. Maybe an EnvOverrider which can support add/replace/delete env as env operation is a bit complicated.

**Comment by chaunceyjiang** [comment]
> @chaunceyjiang Can you help add an agenda to the community meeting? Let's gather some feedback there

ok.

> Agreed. Maybe an EnvOverrider which can support add/replace/delete env as env operation is a bit complicated.

Yes, if users directly use json-patch to modify the env, it is a very complex operation. And it's very easy to make mistakes.

**Comment by RainbowMango** [comment]
> Thank for help. I've tried both two suggestions but still didn't work and got same response:

@XiShanYongYe-Chang @Poor12 Could you please take a look? I'm curious about how complex it is when using plaintext overrider.

**Comment by chaunceyjiang** [comment]
>  Thank for help. I've tried both two suggestions but still didn't work and got same response:

```
      overriders:
        plaintext:
          - path: /spec/template/spec/containers/0/env/0
            operator: add
            value:
              name: TEST
              value: captain-test

```

You can try this.

![image](https://user-images.githubusercontent.com/17962021/229731566-db32eedc-3096-4f9b-8bed-c7893521f9e2.png)

**Comment by mkloveyy** [comment]
> > Thank for help. I've tried both two suggestions but still didn't work and got same response:
> 
> ```
>       overriders:
>         plaintext:
>           - path: /spec/template/spec/containers/0/env/0
>             operator: add
>             value:
>               name: TEST
>               value: captain-test
> ```
> 
> You can try this.
> 
> ![image](https://user-images.githubusercontent.com/17962021/229731566-db32eedc-3096-4f9b-8bed-c7893521f9e2.png)

@chaunceyjiang  Still not work. I just override all envs temporarily now for use. 
@RainbowMango I wonder if can support an EnvOverrider in future as its very useful for users like me. Thx!

**Comment by RainbowMango** [comment]
> I wonder if can support an EnvOverrider in future as its very useful for users like me. Thx!

@mkloveyy we are going to talk about this feature at [the community meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit) next week, will you present the meeting then? We are glad to hear about your use case there.

**Comment by mkloveyy** [comment]
@RainbowMango Of course. Its my honor to join the meeting.

**Comment by mkloveyy** [comment]
@RainbowMango Hello, I've found correct ways to use json patch to add/replace/remove container env:
```yaml
- path: /spec/template/spec/containers/0/env/-
  operator: add
  value:
    name: zone
    value: a
- path: /spec/template/spec/containers/0/env/11
  operator: replace
  value: 
    name: K8S_CLUSTER
    value: rb-a
- path: /spec/template/spec/containers/0/env/0
  operator: remove
```
However it's still not very easy as we must know its index in env list. So an EnvOverrider may still be helpful I think.
Thanks for you help!
