### ISSUE TITLE
ServiceAccounts deployed to the Karmada Control Plane don't cause Tokens to be created

### ISSUE THREAD

**Issue by Laevos** [karmada-io/karmada#3367]
**Please provide an in-depth description of the question you have**:

We need to create a `ServiceAccount` on the Karmada control plane to allow Spinnaker to deploy to the clusterset backed by Karmada. We do this by creating a `ServiceAccount` and `ClusterRoleBinding` on the Karmada cluster. However, we expect the `serviceaccount-token` controller of the `kube-controller-manager` to create a Token for the `ServiceAccount`. This unfortunately does not happen. 

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker-remote
  namespace: spinnaker
  labels:
    project: spinnaker
    team: eng-productivity
    role: remote-permissions
    app.kubernetes.io/managed-by: samson
    app.kubernetes.io/name: spinnaker
  annotations:
    samson/force_update: 'true'
    samson/keep_name: 'true'
    samson/deploy_url: https://samson.zende.sk/projects/spinnaker/deploys/1979792
    samson/updateTimestamp: '2023-04-04T23:00:31Z'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spinnaker-cluster-admin
 roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: spinnaker
  name: spinnaker-remote
- kind: User
  name: spinnaker.client.k8s
```

Initially, applying the above manifest, we got an `ApplyPolicyFailed` error saying that there was no `PropagationPolicy` present (specifically the error was `No policy match for resource`; we didn't expect this because we wanted the `ServiceAccount` to live in the Karmada control plane, not be propagated to the member clusters. Applying the following blank `PropagationPolicy` allows us to deploy the above resources without the error:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: spinnaker-propagation
  namespace: spinnaker
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ServiceAccount
  placement:
    clusterAffinity:
      clusterNames: []
```

However, no Token is created. Is it possible that there's another endpoint that we should be hitting to apply changes to the Karmada control plane directly? The endpoint we're currently hitting is `/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy`, but perhaps there's an endpoint we can add to create these resources directly on the control plane? Or is it possible that this issue is related to #3286, where the `karmada-controller-manager` doesn't run the `serviceaccount-token` controller (per the [docs](https://karmada.io/docs/administrator/configuration/configure-controllers#serviceaccount-token) that's delagated to `kube-controller-manager`)? 

Cc: @a7i 

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version: v1.25.2
- Others:
