### ISSUE TITLE
can let Karmada only auto generate Resource Binding but not work？

### ISSUE THREAD

**Issue by mkloveyy** [karmada-io/karmada#3375]
Is there a config can support this:
Let Karmada auto generate Resource Binding but not create work. 
Like Part of `--skipped-propagating-apis`

**Environment**:
- Karmada version: v1.4.1-with-lua
- Kubernetes version: 1.19
- Others:

**Comment by XiShanYongYe-Chang** [comment]
If work is not created, resources will not be synchronized in the member cluster.

Can you share your use case?

**Comment by mkloveyy** [comment]
This is our user case:
In karmada，we use op to maintain zone-related and cluster's diff deploy steps info and need to update them first in every deploy. But when user update resource template, we want to update op first before karmada schedule resource template update to works.

Currently we consider use webhook to listen update events with  resource template and update op first then allow the update continue.

Hope you can give us a better proposal. Thanks a lot!

**Comment by mkloveyy** [comment]
Or is there any way to force update overriders in op before resourceBinding update works.

**Comment by XiShanYongYe-Chang** [comment]
Sorry, I don't understand your use case. Do you need to modify op every time you modify a resource template?

**Comment by mkloveyy** [comment]
> Sorry, I don't understand your use case. Do you need to modify op every time you modify a resource template?
Yes.

This is part of our demo op:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
spec:
  overrideRules:
    - targetCluster:
        clusterNames:
          - zone-x
      overriders:
        plaintext:
          - path: /spec/strategy/canary/steps
            operator: add
            value:
              - properties:
                  delay: "-1"
                  pull: "false"
                type: Fort
              - properties:
                  delay: "-1"
                  pull: "true"
                type: Fort
              - properties:
                  delay: "-1"
                  maxUnavailable: "0"
                  replicas: 50%
                  timeout: "5"
                type: Batch
              - properties:
                  delay: "-1"
                  maxUnavailable: "0"
                  replicas: 100%
                  timeout: "5"
                type: Batch
    - targetCluster:
        clusterNames:
          - zone-z
      overriders:
        plaintext:
          - path: /spec/strategy/canary/steps
            operator: add
            value:
              - properties:
                  delay: "-1"
                  pull: ""
                type: Fort
              - properties:
                  delay: "-1"
                  pull: ""
                type: Fort
              - properties:
                  delay: "-1"
                  maxUnavailable: "0"
                  replicas: 50%
                  timeout: "5"
                type: Batch
              - properties:
                  delay: "-1"
                  maxUnavailable: "0"
                  replicas: 100%
                  timeout: "5"
                type: Batch
```
We need to specify `/spec/strategy/canary/steps` for our custom resource template in different member clusters, but `/spec/strategy/canary/steps` need to change every time when resource template updated.

Is it not suitable to put `/spec/strategy/canary/steps` specification into op？Maybe retain/prune hook in an custom ResourceInterpreterWebhook is better?
