### ISSUE TITLE
Fix karmada-bot /retest

### ISSUE THREAD

**Issue by helen-frank** [karmada-io/karmada#3421]
**What would you like to be added**:
Fix karmada-bot /retest
**Why is this needed**:
Accelerated PR test

**Comment by helen-frank** [comment]
@RainbowMango Do you have time to repair the karmada-bot `/retest` function? It has been broken for a long time.😂

**Comment by RainbowMango** [comment]
It's not broken, it's never working~

The robot command `/retest` is used to trigger the tests managed by `prombot`, but Karmada's tests are managed by `GitHub Action`, I don't think a robot can do that.

**Comment by helen-frank** [comment]
> It's not broken, it's never working~
> 
> The robot command `/retest` is used to trigger the tests managed by `prombot`, but Karmada's tests are managed by `GitHub Action`, I don't think a robot can do that.

emmm, I haven't actually used `github action`, so I'm not quite sure what's going on here, except to see that other communities are available

**Comment by whitewindmills** [comment]
+1
It's cool if the command `/retest` is available.

**Comment by RainbowMango** [comment]
I'm going to close this issue for now as we don't have an ideal solution yet.

Now we should focus on building a stable testing environment.
/close

**Comment by liangyuanpeng** [comment]
After my testing on prow, the current prow already supports the retest operation on github. 

here is my config for it:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: plugins
data:
  plugins.yaml: |
    triggers:
    - repos:
      - liangyuanpeng/liangyuanpeng.github.io
      - liangyuanpeng/jxline 
      only_org_members: true
      trigger_github_workflows: true
...
```

Just add configuration of `trigger_github_workflows: true` and it's working.

Check the PR of prow: https://github.com/kubernetes/test-infra/pull/25736

@RainbowMango
