### ISSUE TITLE
Fix: func retainPodFields not include initContainer'volumeMounts

### ISSUE THREAD

**Issue by neteric** [karmada-io/karmada#3424]
**What happened**:
When I propagation a Pod with initContainer, I found that the status of the pod was not reflected to rb.Status

**What you expected to happen**:
Propagate a Pod with initContainer, pod's status can reflect to rb and pod resourceTemplate's status

**How to reproduce it (as minimally and precisely as possible)**:
Run a pod with initContainer in control panel，and create a propagationPolicy to propagation it to member cluster

**Anything else we need to know?**:
**Environment**:
- Karmada version:
v1.5.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

/assign

**Comment by RainbowMango** [comment]
> Run a pod with initContainer in control panel，and create a propagationPolicy to propagation it to member cluster

Could you please share the yamls?

**Comment by chaunceyjiang** [comment]
Yes, I also noticed this issue. The volumesMounts of the initContainer should be retained.

**Comment by chaunceyjiang** [comment]
![image](https://user-images.githubusercontent.com/17962021/232717654-f02b28c9-cc22-4534-a000-6d90526d39fd.png)

**Comment by chaunceyjiang** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/17962021/232719432-9bc7a0c4-3a5e-4b08-81c8-7009e5405b22.png">

**Comment by neteric** [comment]
> > Run a pod with initContainer in control panel，and create a propagationPolicy to propagation it to member cluster
> 
> Could you please share the yamls?
just like this: 
``` 
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
  - name: init-mydb
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]

```
