### ISSUE TITLE
How to handle dynamic parameters which need to be changed every time before generating works for member cluster?

### ISSUE THREAD

**Issue by mkloveyy** [karmada-io/karmada#3436]
**Please provide an in-depth description of the question you have**:
Below is a basic scenario in our release process:

![image](https://user-images.githubusercontent.com/19920146/233246072-61fee206-232d-4b88-9f2a-0c3c60e196ba.png)

We've implement a `deploy CRD called Rollout` based on [openkruise](https://github.com/openkruise/kruise) to handle the whole process. Part of rollout's definition for above case is as follows:
```yaml
apiVersion:
kind: Rollout
metadata:
  name:
  namespace:
spec:
  fortPull: false
  replicas: 4
  selector:
    matchLabels:
      app: 
  strategy:
    canary:
      steps:
      - properties:  # fort
          delay: "-1"
          pull: "false"
        type: Fort
      - properties:  # canary
          delay: "-1"
          pull: "true"
        type: Fort
      - properties:  # first batch of rolling
          delay: "-1"
          maxUnavailable: "0"
          replicas: 50%
          timeout: "5"
        type: Batch
      - properties:  # second batch of rolling
          delay: "-1"
          maxUnavailable: "0"
          replicas: 100%
          timeout: "5"
        type: Batch
  subsetType: CloneSet
  template:
    ...
```

So in multi-cluster case, what we need to do every time are:
1. Generate `canary.steps` for all member clusters when users start their releases.
2. Allocate a `fort pod` to one of member clusters (values in steps are different between fort and non-fort clusters).

For example, above rollout need to be updated in two clusters: `cluster-x` and `cluster-z`. The differences between two cluster are as follows:
```yaml
# cluster-x.yaml, fort pod in this cluster
strategy:
    canary:
      steps:
      - properties:  # fort
          delay: "-1"
          pull: "false"  # pull out fort
        type: Fort
      - properties:  # canary
          delay: "-1"
          pull: "true"  # pull out fort
        type: Fort
      ...

# cluster-z.yaml, no fort pod
strategy:
    canary:
      steps:
      - properties:  # fort
          delay: "-1"
          pull: nil  # skip
        type: Fort
      - properties:  # canary
          delay: "-1"
          pull: nil  # skip
        type: Fort
      ...
```

So, is there any suitable ways to implement such differentiated configuration? And where is the appropriate place to put the code? 

**What do you think about this question?**:
Related issue is #3375

**Environment**:
- Karmada version: v1.4.1-with-lua
- Kubernetes version: 1.19
- Others:

**Comment by chaunceyjiang** [comment]
> For example, above rollout need to be updated in two clusters: cluster-x and cluster-z. The differences between two cluster are as follows:

``` 
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
spec:
  overrideRules:
    - targetCluster:
        clusterNames:
          - cluster-x
      overriders:
        plaintext:
          - path: /spec/strategy/canary/steps/0/pull
            operator: replace
            value:  "false"
          - path: /spec/strategy/canary/steps/1/pull
            operator: replace
            value:  "true"
    - targetCluster:
        clusterNames:
          - cluster-z
      overriders:
        plaintext:
          - path: /spec/strategy/canary/steps/0/pull
            operator: replace
            value:  nil
          - path: /spec/strategy/canary/steps/1/pull
            operator: replace
            value:  nil
```

Can this help you?
