### ISSUE TITLE
Support scheduling according to member cluster resources

### ISSUE THREAD

**Issue by lynnsong** [karmada-io/karmada#344]
**What would you like to be added**:
Support scheduling according to member cluster resources

**Why is this needed**:
### Background
As Kubernetes is used in more and more scenarios, a single cluster sometimes cannot meet a large task (such as the AI training scenario). Therefore, we need multiple clusters to provide resources for a task at the same time.
During the research process, we found that the ‘karmada’ project is the multi-cluster project that best meets our needs. However, karmada is still relatively simple in scheduling implementation, and cannot handle the above-mentioned demand for splitting tasks based on member cluster resources.

### Proposal
Karama supports a richer scheduling strategy through plug-ins: supports split scheduling and Re-balance of tasks based on the available resources of the Member cluster.

### High-level design

1. Provide more accurate and real-time NodeSummary for scheduler. For example, using the Informer method to monitor resource changes instead of regular List; adding the 'Pending' resource statistics in the Member cluster in the NodeSummary;
2. Support new scheduling strategy: Scheduling workload according to the amount of available resources of the Member clusters, and the aggregation/balance (scheduling to as few clusters as possible OR balanced scheduling to each cluster) mode is supported for scheduling.
3. Improve the Re-balance capability: When partial resource exceptions occur in the Member cluster, or the Manager cluster scheduling is not accurate enough, the exception can be found and re-balanced.

**Comment by RainbowMango** [comment]
For now, we just collected the member cluster's resources but haven't provided a schedule strategy about that yet. Your idea is awesome and totally matches our plan.

The next step would be provide a more detailed design and split it into some small iteration items.
Would you like to keep analyzing this and leading this feature?

**Comment by lynnsong** [comment]
Thanks for the reply, I am willing to continue to analyze this problem, and I will submit a detailed design later

**Comment by lynnsong** [comment]
# Design
## expected result
1. Schedule according to the replicas in the user workload, not the replicas in ReplicaSchedulingPolicy
2. If the strategy of scheduling according to the available resources of the Member cluster is configured, the workload will be split and scheduled according to the resource aggregation strategy.

Scheduling diagram：
![Image of schedule](https://raw.githubusercontent.com/lynnsong/pictures/main/schedule-1.png)

## Member cluster available resources
In order to use Memeber cluster resources for scheduling, it is necessary to provide an accurate total amount of available resources in the cluster;
Therefore, we record the cluster resources info in the 'cluster' CR，such as：
```
status：
  clusterResources:
    nodes：
      readyNum：9
      totalNum：10
    resources：
      allocatable: // sum of all nodes's Allocatable resource，include notReady nodes
        cpu: 79100m
        ephemeral-storage: "949983693280"
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 144649880Ki
        pods: "757"
      notReady: // sum of all notReady nodes's Allocatable resource
        cpu: 2000m
        memory: xxxxx
        ephemeral-storage: "xxx"
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        pods: "xx"
      pending： // sum of pods's Request resource which has not been scheduled
        cpu：3200m
        memory: "3567284900"
      used: // sum of pods's Request resource which has been bound on Node
        cpu: 3350m
        memory: "3895603968"
```

1. Increase various resource statistics to cover all used resources:

   Member Cluster available resources = allocatable - notReady - used -pending
   _Note: Long-term pending resources may result in fewer available resources calculated_

2. Due to resource fragmentation, there may be a problem that the Manager cluster judges that the total resources are sufficient, and the actual scheduling cannot be done in the Member cluster. To deal with this problem, we can do two things:

  - Set a certain degree of redundancy for the available resources of the Member cluster, such as ‘Scheduler available resources = actual idle resources*90%’, which means that a 10% gap can be tolerated;
  - If there are still some parts that cannot be scheduled after being scheduled to the Member cluster, the insufficient resources will be rescheduled through the Re-balance mechanism;

## Scheduling strategy configuration
Merging ReplicaSchedulingPolicy and PropagationPolicy, the advantages of merging:

1. Simplify user policy configuration;
2. The total configured replicas are based on the user's configuration in the native workload, reducing the cost of understanding;

**Implementation instructions:**

1. Add ReplicaSchedulingStategy to PropagationPolicy.Placement, apply this strategy for GKRs with Replicas, and ignore this strategy for GKRs without Replicas.
2. Apply this strategy in the filtering and optimization process of scheduling. Cluster selection and replicas allocation are all done in the scheduler.
3. Expand the scheduling strategy in ReplicaSchedulingStategy, such as the ResourcesPreferences scheduled according to the available resources of the cluster.

```
// Placement represents the rule for select clusters.
type Placement struct {
   ClusterAffinity *ClusterAffinity `json:"clusterAffinity,omitempty"`
   ClusterTolerations []corev1.Toleration `json:"clusterTolerations,omitempty"`
   SpreadConstraints []SpreadConstraint `json:"spreadConstraints,omitempty"`
   
   // +options
   ReplicaSchedulingStategy 
}

type ReplicaSchedulingStategy struct {
   // +options
   WeightPreferences ClusterPreferences `json:"weightPreferences"`
   
   // default ReplicaSchedulingStategy. if there is no stategy be set expicitly
   // +options
   ResourcesPreferences AggregationPattern `json:"resourcesPreferences"`
}

//AggregationPattern represents the aggregation pattern in select clusters
type AggregationPattern struct {
    //IsAggregated represents whether use the aggregation in scheduler.
    //If it is true, minimum number of clusters will be selected.
    //If it is false, maximum number of clusters will be selected
    IsAggregated bool `json:"isAggregated,omitempty"`
    // MaxGroups restricts the maximum number of cluster groups to be selected when IsAggregated is false.
    // +optional
    MaxGroups int `json:"maxGroups,omitempty"`
}

```

## Scheduling process
![Image of schedule-2](https://raw.githubusercontent.com/lynnsong/pictures/main/schedule-2.png)

1. Create

Just add support for new scheduling strategies.

2. Expansion

Note: Because the available resources of the Member cluster are constantly changing with use. Therefore, when the Deployment Replicas is increased, the result of the rematch may be quite different from the initial creation, which may lead to unnecessary deletions and creations, so only the incremental part of the expansion needs to be scheduled.

3. Shrink

Note: As with capacity expansion, there should be as few meaningless deletion and creation operations as possible.

4. Delete

The current implementation is satisfied, no need to modify

**Comment by mrlihanbo** [comment]
![image](https://user-images.githubusercontent.com/74236054/119074956-8e100100-ba22-11eb-8237-a1422f99d6b2.png)     
@lynnsong  Can WeightPreferences  co-exist with ResourcesPreferences?

**Comment by pigletfly** [comment]
Totally agree with the design of "Schedule according to the replicas in the user workload, not the replicas in ReplicaSchedulingPolicy" and "Merging ReplicaSchedulingPolicy and PropagationPolicy". so we don't need `ResourceSelectors` in ReplicaSchedulingPolicy anymore ? There is still a problem, how to find and replace in a CRD ? let's assume we have a CRD below

```
apiVersion: core.test.com/v1beta1
kind: Application
metadata:
  name: test-rolling
  namespace: default
spec:
  components:
  - name: webserver
    properties:
      cmd:
      - sleep
      - "999999999"
      image: busybox:lastest
      port: 8080
      replicas: 10
    type: webservice
  - name: frontend
    properties:
      cmd:
      - sleep
      - "999999999"
      image: busybox:lastest
      port: 8080
      replicas: 20
    type: webservice
```
xref: https://github.com/karmada-io/karmada/issues/319

**Comment by lynnsong** [comment]
> ![image](https://user-images.githubusercontent.com/74236054/119074956-8e100100-ba22-11eb-8237-a1422f99d6b2.png)
> @lynnsong Can WeightPreferences co-exist with ResourcesPreferences?

Now WeightPreferences and ResourcesPreferences will not co-exist. This is the strategy we currently consider appropriate, but I think we can get  more discussion or continuous optimization

**Comment by lynnsong** [comment]
> Totally agree with the design of "Schedule according to the replicas in the user workload, not the replicas in ReplicaSchedulingPolicy" and "Merging ReplicaSchedulingPolicy and PropagationPolicy". So we don't need `ResourceSelectors` in ReplicaSchedulingPolicy anymore which may cause conflicts if it exists in both ReplicaSchedulingPolicy and PropagationPolicy.But,there is still a problem, how to find and replace the Replicas in a CRD ? let's assume we have a CRD below
> 
> ```
> apiVersion: core.test.com/v1beta1
> kind: Application
> metadata:
>   name: test-rolling
>   namespace: default
> spec:
>   components:
>   - name: webserver
>     properties:
>       cmd:
>       - sleep
>       - "999999999"
>       image: busybox:lastest
>       port: 8080
>       replicas: 10
>     type: webservice
>   - name: frontend
>     properties:
>       cmd:
>       - sleep
>       - "999999999"
>       image: busybox:lastest
>       port: 8080
>       replicas: 20
>     type: webservice
> ```
> 
> we should provide a flexible way to patch replicas in ReplicaSchedulingStategy.
> xref: #319

we should provide a flexible way to patch replicas in ReplicaSchedulingStategy.
——————
Yes, I very much agree with your proposal. Currently, we need to get replicas information for each type of workload.
My thinking about CRD here is not complete enough, maybe we can use the method of structural analysis to get replicas from CRD. But because CRD is too flexible, the problem is not only to get replicas, but scheduling may also be affected.

**Comment by pigletfly** [comment]
we should assume the workloads applied with a same ReplicaSchedulingStategy should be the same Kind,otherwise it's too complicated to find Replicas in different CRDS.

**Comment by RainbowMango** [comment]
Indeed, it's complicated. We should more focus on the user story and API design.

**Comment by RainbowMango** [comment]
For the `Cluster` status API change [on above](https://github.com/karmada-io/karmada/issues/344#issuecomment-844127304), I think `clusterResources` is better than `NodeSummary`. @kevin-wangzefeng How do you think?

**Comment by RainbowMango** [comment]
Another idea brings to my mind:
Maybe we can separate nodes and resources like this:
```yaml
status:
  nodes:
    totalNum: 100 // Nodes number
    readyNum: 99 // .status.condition.ready=true
  resource: // (TBD: How to ignore master node's resource, using a flag? define a .spec.xxx filed?)
    allocatable: // sum of all ready node's .status.allocatable
      cpu: "4"
      ephemeral-storage: 123722284Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 16265856Ki
      pods: "110"
    allocating: //sum of pods's Request resource which has not been scheduled
      cpu：3200m
      memory: "3567284900"
    allocated: // sum of pods's Request resource which has been bound on Node
      cpu: 850m
      memory: 190Mi
```
