### ISSUE TITLE
How to use HPA in member cluster

### ISSUE THREAD

**Issue by fusongke100** [karmada-io/karmada#3458]
karmada version :1.5.0
Kubernetes version : 1.21.0

Hello, I want to use HPA in the member cluster ,so when I set Configure Controllers as below , the propagation policy is invalidate.
![image](https://user-images.githubusercontent.com/3871556/233927654-3e4f96be-5702-4a81-9653-1c9dcfb353fe.png)

How can I use HPA and do not influence the propagation policy.

**Comment by fusongke100** [comment]
Thank you ,let me try.

**Comment by fusongke100** [comment]
change config to `--controllers=*,hpa` , the propagation policy can work well, but the HPA is not available.
when up to the metric of HPA and start two pods  , they shutdown immediately.
![image](https://user-images.githubusercontent.com/3871556/234552457-a912de5d-f0f1-4d7a-9352-b0b6080d304c.png)

**Comment by RainbowMango** [comment]
That is because Karmada will override the replica after HPA is scaled up.
You can try to customize the behavior by following yaml:
```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-example
spec:
  target:
    apiVersion: apps/v1
    kind: Deployment
  customizations:
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          desiredObj.spec.replicas = observedObj.spec.replicas
          return desiredObj
        end
```

See [Customizing Resource Interpreter](https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter) for more details.

**Comment by fusongke100** [comment]
Could you please give an example to show how to use `ResourceInterpreterCustomization` to support `HPA`.

**Comment by RainbowMango** [comment]
I don't think you need to use `ResourceInterpreterCustomization` to customize `HPA`. If the `.spec.scaleTargetRef` of `HPA` is Deployment, you have to customize `Deployment` with resource interpreter as [mentioned above](https://github.com/karmada-io/karmada/issues/3458#issuecomment-1524390568).

If you can describe your requirements in detail, we may be able to give a more detailed solution.

**Comment by fusongke100** [comment]
Yes, the HPA yaml file like this,  please give a more detailed solution.
![image](https://user-images.githubusercontent.com/3871556/236379279-6f7f0dcc-56a0-4f9d-8366-86254e042473.png)

**Comment by RainbowMango** [comment]
Please share the PropagationPolicy as well.

**Comment by fusongke100** [comment]
This is the PropagationPolicy:
![image](https://user-images.githubusercontent.com/3871556/236386795-90d774a3-0a25-495d-bf14-a8a42c27f4a0.png)

**Comment by RainbowMango** [comment]
@jwcesign Please help to take a look.

**Comment by jwcesign** [comment]
Hi, @fusongke100 , from the HPA yaml and the PropagationPolicy yaml.

I think the solution could be:
1. Create one file called `resource-interpreter-customization.yaml`:
```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-example
spec:
  target:
    apiVersion: apps/v1
    kind: Deployment
  customizations:
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          desiredObj.spec.replicas = observedObj.spec.replicas
          return desiredObj
        end
```

2. Apply it to karmada control plane.

3. Please try to request the deployment and verify if it will be scaled up.

**Comment by fusongke100** [comment]
Thanks a lot, I will try!

**Comment by fusongke100** [comment]
I have tested it, it work well. but if the `propagation policy ` like this, it does not work.
![image](https://user-images.githubusercontent.com/3871556/236407449-a24284e6-cfc0-4f7d-b9ab-d10bd60878c0.png)

**Comment by jwcesign** [comment]
Can you show me the following information.
1.The ResoruceBinding of this deployment.
2.The result of karmadactl get deployment
3.The result of karmadactl get hpa

**Comment by fusongke100** [comment]
If delete the HPA in `spec.resourceSelectors` , how two set `targetCPUUtilizationPercentage`

**Comment by jwcesign** [comment]
`targetCPUUtilizationPercentage` is set in:
![image](https://user-images.githubusercontent.com/19745536/236413881-bb9aaaa3-3c54-4c53-94a2-55cb7ad6fcd8.png)

And the component `karmada-controller-manager` will sync it to the member clusters with the same template yaml.

So just set `targetCPUUtilizationPercentage` as the value you want.

Do I understand your question correctly?

**Comment by fusongke100** [comment]
> Can you show me the following information. 1.The ResoruceBinding of this deployment. 2.The result of karmadactl get deployment 3.The result of karmadactl get hpa
> 
> By the way, please delete the HPA in `spec.resourceSelectors`, the HPA will be propagated by controller.

I mean, If delete the HPA in `spec.resourceSelectors` , the HPA resource can not propagation to member cluster.

**Comment by jwcesign** [comment]
Hi, @fusongke100 
If you enable hpa controller by setting the parameter `--controllers=*,hpa` in component `karmada-controller-manager`, the  HPA resource will be propagated to the member cluster.

**Comment by fusongke100** [comment]
Another question，why `propagation policy` set the `replicaScheduling` ,the HPA can not work well.

**Comment by jwcesign** [comment]
For HPA, If propagate it with policy, the replicas couldn't be parsed, so the next steps couldn't be processed(propagate to member clusters).
But if you didn't set `replicaScheduling`, the replicas parse logic will not be executed(default is duplication), and directly sync the original yaml to member clusters.

By the way, with `replicaScheduling` configuration, did you set the parameter `--controllers=*,hpa`?  If set, it should work

**Comment by fusongke100** [comment]
Yes ,I have set  `--controllers=*,hpa` , and  if  the `propagation policy` set the `replicaScheduling` ,the `ResourceInterpreterCustomization`  can not work well. I don`t konw the reason.

**Comment by jwcesign** [comment]
Hi, @fusongke100 I tested in my environment, it works fine:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 0.5
          requests:
            cpu: 0.5
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
    - apiVersion: autoscaling/v1
      kind: HorizontalPodAutoscaler
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    clusterTolerations:
      - effect: NoExecute
        key: fail-test
        operator: Exists
        tolerationSeconds: 10
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
---
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-example
spec:
  target:
    apiVersion: apps/v1
    kind: Deployment
  customizations:
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          desiredObj.spec.replicas = observedObj.spec.replicas
          return desiredObj
        end
```

When watch pods in member clusters, the pods could be scaled up:
```yaml
root@karmada [10:33:52 AM] [~]
-> # k get pods --watch
NAME                     READY   STATUS    RESTARTS   AGE
nginx-79c955657f-2dbs9   1/1     Running   0          85s
nginx-79c955657f-6q2sz   1/1     Running   0          11s
nginx-79c955657f-pmp74   1/1     Running   0          10s
```

Can you show me your rb?
```sh
k get rb -A
```
