### ISSUE TITLE
How to disable scheduler in Karmada Cluster, while using HPA in Member Clusters?

### ISSUE THREAD

**Issue by watermeion** [karmada-io/karmada#3460]
When I create a hpa in karmada cluster, the Hpa is susscefully propagated to member clusers indeed. But when hpa controller in member cluster changes replicas of target deployment,  it will conflict with karmada scheduler. Both of them are reconciling replicas according to theirselves configs, that makes replicas scalingUp and scalingDown  simultaneously. 
Is there a way to disable scheduler reconcile loop while using hpa ?

**Comment by chaunceyjiang** [comment]
Perhaps this YAML file can help you.

```
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: retention-deployment-test
spec:
  target:
    apiVersion: apps/v1
    kind: Deployment
    name: test
  customizations:
    retention:
      luaScript: >
          function Retain(desiredObj, observedObj)
            desiredObj.spec.replicas = observedObj.spec.replicas
            return desiredObj
          end

```
