### ISSUE TITLE
ClusterResourceBinding Fullyapplied failed when unjoin cluster

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3474]
**What happened**:

When I unjoin a cluster from karmada, the `ClusterResourceBinding` Fullyapplied status become failed.

**What you expected to happen**:

The `ClusterResourceBinding` Fullyapplied status is true when unjoin cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the follow cpp:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: serviceexport-policy
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - member2
      - member3
      - member1
  resourceSelectors:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: serviceexports.multicluster.x-k8s.io
```

And then unjoin `member1` from the karmada.

**Anything else we need to know?**:

**Environment**:
- Karmada version: master branch latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): master branch latest
- Others:
