### ISSUE TITLE
Propagating CR to new cluster failed when joining new cluster.

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#3479]
**What happened**:

```yaml

 spec:
   placement:
     clusterTolerations:
     - effect: NoExecute
       key: cluster.karmada.io/not-ready
       operator: Exists
       tolerationSeconds: 30
     - effect: NoExecute
       key: cluster.karmada.io/unreachable
       operator: Exists
       tolerationSeconds: 30
   priority: 0
   resourceSelectors:
   - apiVersion: webapp.my.domain/v1
     kind: Guestbook
     namespace: default
   schedulerName: default-scheduler


---

 spec:
   placement:
     clusterTolerations:
     - effect: NoExecute
       key: cluster.karmada.io/not-ready
       operator: Exists
       tolerationSeconds: 30
     - effect: NoExecute
       key: cluster.karmada.io/unreachable
       operator: Exists
       tolerationSeconds: 30
   priority: 0
   resourceSelectors:
   - apiVersion: apiextensions.k8s.io/v1
     kind: CustomResourceDefinition
     name: guestbooks.webapp.my.domain
   schedulerName: default-scheduler
```

When I use Karmada to propagate a CRD and CR to some member clusters, when I join a new member cluster, **only the CRD** is present in the newly joined member cluster, but not the CR.

**What you expected to happen**:

I found the following information in the log:

``` shell
1 cluster(s) didn't have the API resource, 

```

I guess that CR was scheduled before CRD, which caused the CR to not be propagated properly to the new cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
