### ISSUE TITLE
When EnableEmptyWorkloadPropagation flag is false zero deployment should not be propagated to member cluster

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3495]
**What happened**:

When I didn't set `karmada-sechduler` `EnableEmptyWorkloadPropagation` flag, the default value is false, which means that  `workload with 0 replicas could not be propagated to member clusters.`:

https://github.com/karmada-io/karmada/blob/0e10088974b65184dd2ff344ee46639980ec7f0e/cmd/scheduler/app/options/options.go#L59

But when I deploy a application like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - name: serve
        image: jeremyot/serve:0a40de8
        args:
        - "--message='hello from cluster member1 (Node: {{env \"NODE_NAME\"}} Pod: {{env \"POD_NAME\"}} Address: {{addr}})'"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: serve
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mcs-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: serve
    - apiVersion: v1
      kind: Service
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
```

I can get a zero replicas deployment in the member2 cluster:

![image](https://user-images.githubusercontent.com/78244870/236599650-f6349347-d9d6-4975-bc15-2926061c2be2.png)

**What you expected to happen**:

When EnableEmptyWorkloadPropagation flag is false zero deployment **should not** be propagated to member cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: release-1.5 & master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
