### ISSUE TITLE
workload placement feature request: fallback clusters 

### ISSUE THREAD

**Issue by tedli** [karmada-io/karmada#3540]
**What would you like to be added**:

For some workloads which not intent to be high available, but consume massive cpu, memory. For example, pods of training jobs.
Such pods (for karmada it's the controller resource object) may prefer to schedule to some less important member clusters, if all of those clusters not suit, then try some other member clusters (important production clusters).

But, strategies provided by karmada, seemed no way to achieve this. It's because it calculates replicas with weight in a `floor` logic, it will anyway assign replicas to all specified cluster if replicas greater than clusters, no mater how to config the weight.

https://github.com/karmada-io/karmada/blob/db3a907c24cfd54b5364ba879c206e8ede3e90d9/pkg/util/helper/binding.go#L105-L123

Let's say there are three member clusters, two of them is something like staging cluster, or dev cluster, the rest one is the production one. All of the 3 clusters joined to the karmada.

Now I want to divide replicas to the staging or dev ones, both of them fail then try the production one, if the two except the production are ok, never assign replicas to production.

**Why is this needed**:

It's a common case, we have some clusters, each of them have idle resources. Karmada can manage those cluster and workloads with propagation policis.
So, we need a way to define a placement fallback behaviour.

**Some thoughts**:

Let's say the staging, dev cluster as class A, production cluster as class B.
It could be calculated in a `ceil` logic, along with cluster weight difference grater enough between class A and B. Like weight of A is 1000, B is 1. Then in the code above, replicas will goes to class A clusters. It will gose to class B only if all class A clusters not able to schedule.
And add a field or annotation to Cluster object, to indicate it will be calculated in floor or ceil. or field in policy.placement.

**Comment by RainbowMango** [comment]
Hi @tedli , 

The feature `multi-scheduling-group` might fit your scenario, sorry that we still not update the document, but you can get the API and design details from the proposal: https://github.com/karmada-io/karmada/tree/master/docs/proposals/scheduling/multi-scheduling-group

**Comment by tedli** [comment]
Hi @RainbowMango ,

Thanks for reply, multi-scheduling-group is a great feature. I will use this feature to cover my cases.

But, I also noticed this [#3069](https://github.com/karmada-io/karmada/discussions/3069), one of my case is same with @XMingG99, that affect target clusters of resource binding by label of cluster, and it should be reconciled if label of cluster changed.

The story of mine is, many departments have their own k8s cluster, by joining to karmada, to share their computility (cpu, memory, gpu) for ai training.

The owner of member cluster can decide resource in which namespace (tenant, department, group) can propagate resources to their cluster. To achieve this, labels the cluster with a key represant for a namespace, then use lable selector in placement of propagate policy to propagate resource to selected clusters. If the label changed, the selected cluster set changed, so resource binding should also reschedule to new cluster set.

e.g.

Like below, cluster one allows resources from `kaifa` to schedule to, along with selector in placement of policy. If owner of cluster one decide not to allow resources from `kaifa` to schedule to, just remove the kaifa label.

```yaml
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  name: one
  labels:
    ns.some.com/kaifa: "true"
    ns.some.com/xingzheng: "true"
    ns.some.comshangwu: "true"
```

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: lalala
spec:
  propagateDeps: true
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    labelSelector:
        matchLabels:
          app: lalala
  placement:
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              labelSelector:
                matchExpressions:
                - key: ns.some.com/kaifa
                  operator: Exists
```

Currently, I'm working on a out of tree controller to achieve this (watch cluster, update resource binding). I'm wondering whether I went into a wrong way.
