### ISSUE TITLE
karmada scheduler can support fixed strategy?

### ISSUE THREAD

**Issue by mathlsj** [karmada-io/karmada#3558]
**What would you like to be added**:
ReplicaDivisionPreference add new type: Fixed

**Why is this needed**:
In many time, we hope the workload replicas in cluster do not change. 

deploy a worload, deliver to multiple clusters.
whatever increase or decrease cluster and  the cluster is ready or not, the origin cluster replicas do not change.

fixed eg:

```yaml
placement:
clusterAffinity:
  clusterNames:
    - member1
    - member2
replicaScheduling:
  replicaDivisionPreference: Fixed
  replicaSchedulingType: Divided
  weightPreference:
    staticWeightList:
      - targetCluster:
          clusterNames:
            - member1
        weight: 2
      - targetCluster:
          clusterNames:
            - member2
        weight: 3
```

it means that the cluster member1 have 2 replicas and the cluster member2 have 3 replicas.we do not care the origin workload replicas
