### ISSUE TITLE
Member cluster resources are created in advance,  and Karmda control cluster resources status is not synchronized

### ISSUE THREAD

**Issue by wxuedong** [karmada-io/karmada#3597]
**Environment**:
- Karmada version:  v1.5.0
- Kubernetes version:  v1.20.8

The first step is to create a Deployment in the member cluster

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: karmada-nginx-demo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

```
View result is successful

<img width="847" alt="image" src="https://github.com/karmada-io/karmada/assets/15843627/5e8670df-b025-4376-8b7a-9489236068a2">

The second step is to create karmada-nginx-demo in the karmada control cluster

`k describe deploy karmada-nginx-demo`

```
Events:
  Type    Reason                  Age                From                  Message
  ----    ------                  ----               ----                  -------
  Normal  ApplyPolicySucceed      25s                resource-detector     Apply policy(default/vela-example-policy) succeed
  Normal  SyncWorkSucceed         25s (x5 over 25s)  binding-controller    Sync work of resourceBinding(default/karmada-nginx-demo-deployment) successful.
  Normal  AggregateStatusSucceed  25s (x5 over 25s)  binding-controller    Update resourceBinding(default/karmada-nginx-demo-deployment) with AggregatedStatus successfully.
  Normal  ScheduleBindingSucceed  25s                default-scheduler     Binding has been scheduled
  Normal  SyncSucceed             25s                execution-controller  Successfully applied resource(default/karmada-nginx-demo) to cluster member-1
```

` k describe work karmada-nginx-demo-78dfc455df`

```
Status:
  Conditions:
    Last Transition Time:  2023-05-29T06:55:16Z
    Message:               Manifest has been successfully applied
    Reason:                AppliedSuccessful
    Status:                True
    Type:                  Applied
Events:
  Type    Reason       Age    From                  Message
  ----    ------       ----   ----                  -------
  Normal  SyncSucceed  7m19s  execution-controller  Sync work (karmada-nginx-demo-78dfc455df) to cluster(member-1) successful.
```
Definition of propagationpolicy

`k get propagationpolicy vela-example-policy -o yaml`

```

apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: vela-example-policy
  namespace: default
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - member-1
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
  priority: 0
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    namespace: default
  schedulerName: default-scheduler
```
At this time, check the status of the deployments karmada-nginx-demo of the karmada control cluster is actually not synchronized

<img width="780" alt="image" src="https://github.com/karmada-io/karmada/assets/15843627/99cd69de-6ee3-4be3-9f4f-c78feb5d7c6c">

The desired result is that when the resources of the member clusters exist, the state can still be synchronized to the karmada control cluster.
