### ISSUE TITLE
registries not reconciled when clusters changed (add, update, del)

### ISSUE THREAD

**Issue by tedli** [karmada-io/karmada#3669]
A `ResourceRegistry` like below, works, and it should be:

```yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: default-global-search
spec:
  targetCluster:
    labelSelector:
      matchExpressions:
      - key: karmada-cluster.k8s.some.com/managed
        operator: Exists 
  resourceSelectors:
  - apiVersion: v1
    kind: Pod
  - apiVersion: events.k8s.io/v1
    kind: Events
```

It intended to act as a default global registry. However, if a new cluster joined to karmada with a matching label, nothing can be retrieved through search api.

Here, the cluster handler of search controller, test if cluster registry exist, if false, it just returned, without checking labels with any exist registries' label selector:

https://github.com/karmada-io/karmada/blob/4e4bfffc61067ddbde6b287cdb338bea2f5647df/pkg/search/controller.go#L166-L172

**What would you like to be added**:

Clusters add, updated (label add, remove), could trigger reconcile with matching registries.

**Why is this needed**:

By design.
