### ISSUE TITLE
strict decoding error: unknown field "spec.failover"

### ISSUE THREAD

**Issue by whoisfisher** [karmada-io/karmada#3680]
**What happened**:
An error occurred when I apply the yaml in karmada-control-plane
```
Error from server (BadRequest): error when creating "test-pvc2.yaml": PropagationPolicy in version "v1alpha1" cannot be handled as a PropagationPolicy: strict decoding error: unknown field "spec.failover"
```

**What you expected to happen**:

I hope to be able to apply yaml correctly

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable it in karmada-controller-manager
```
      containers:
      - command:
        - /bin/karmada-controller-manager
        - --kubeconfig=/etc/kubeconfig
        - --bind-address=0.0.0.0
        - --cluster-status-update-frequency=10s
        - --secure-port=10357
        - --leader-elect-resource-namespace=karmada-system
        - --v=2
        - --feature-gates=PropagateDeps=true,Failover=true,GracefulEviction=true
```
2.  Change context to karmada-apiserver
```
oot@node2:~/karmada-test# kubecm s
😸 Select:karmada-apiserver
「/root/.kube/config」 write successful!
+------------+-----------------------------------+-----------------------------+----------------------+------------------------------+--------------+
|   CURRENT  |                NAME               |           CLUSTER           |         USER         |            SERVER            |   Namespace  |
+============+===================================+=============================+======================+==============================+==============+
|      *     |         karmada-apiserver         |      karmada-apiserver      |   karmada-apiserver  |   https://172.30.1.60:32457  |    default   |
+------------+-----------------------------------+-----------------------------+----------------------+------------------------------+--------------+
|            |   kubernetes-admin@cluster.local  |        cluster.local        |   kubernetes-admin   |   https://172.30.1.60:6443   |    default   |
+------------+-----------------------------------+-----------------------------+----------------------+------------------------------+--------------+
|            |       member77@cluster.local      |   cluster.local-875m77694h  |       member77       |   https://172.30.1.77:6443   |    default   |
+------------+-----------------------------------+-----------------------------+----------------------+------------------------------+--------------+
|            |       member82@cluster.local      |   cluster.local-tt6bc4cm8h  |       member82       |   https://172.30.1.82:6443   |    default   |
+------------+-----------------------------------+-----------------------------+----------------------+------------------------------+--------------+
|            |       member95@cluster.local      |   cluster.local-cb8c7m222g  |       member95       |   https://172.30.1.95:6443   |    default   |
+------------+-----------------------------------+-----------------------------+----------------------+------------------------------+--------------+

Switched to context 「karmada-apiserver」
```
3. Apply yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 1000 
      containers:
      - image: harbor.xian.rdev.tech/mysql/mysql:5.7.39
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Def@u1tpwd"
        ports:
        - containerPort: 3306
          name: mysql
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: mysql-storage
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc2
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - nodePort: 30433
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: NodePort
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mysql-propagation
spec:
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 120
      purgeMode: Never
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: mysql
    - apiVersion: v1
      kind: Service
      name: mysql
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: mysql-pvc2
  placement:
    clusterAffinity:
      clusterNames:
        - member82
        - member77
        - member95
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
        spreadByField: cluster
```
4. The error is as follows
```
root@node2:~/karmada-test# kubectl apply -f  test-pvc2.yaml 
persistentvolumeclaim/mysql-pvc2 unchanged
deployment.apps/mysql unchanged
service/mysql unchanged
Error from server (BadRequest): error when creating "test-pvc2.yaml": PropagationPolicy in version "v1alpha1" cannot be handled as a PropagationPolicy: strict decoding error: unknown field "spec.failover"
```
**Anything else we need to know?**:
```
root@node2:~/karmada-test# kubectl get pod -n karmada-system 
NAME                                               READY   STATUS    RESTARTS       AGE
etcd-0                                             1/1     Running   1 (5d6h ago)   5d23h
karmada-aggregated-apiserver-975f898b5-6qdbd       1/1     Running   6 (5d6h ago)   5d23h
karmada-apiserver-5dfc7646c4-qd4fp                 1/1     Running   2 (5d6h ago)   5d23h
karmada-controller-manager-b8cc5c6bd-jkxxd         1/1     Running   4 (5d1h ago)   5d4h
karmada-descheduler-7c46b85f8f-2dw95               1/1     Running   1 (5d6h ago)   5d23h
karmada-descheduler-7c46b85f8f-cfftg               1/1     Running   1 (5d6h ago)   5d23h
karmada-kube-controller-manager-77d49f4dcf-xvqzx   1/1     Running   6 (5d6h ago)   5d23h
karmada-scheduler-8478c9584d-ckw8t                 1/1     Running   1 (5d6h ago)   5d23h
karmada-webhook-75779f4f7f-nlrn4                   1/1     Running   6 (5d6h ago)   5d23h
```
**Environment**: ```kubernetesv1.24.9```
- Karmada version: ```v1.5.0```
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): ```kubectl karmada version: version.Info{GitVersion:"v1.5.0", GitCommit:"51fbbb055d47331e83a6ca2e90b8a5312d6a7986", GitTreeState:"clean", BuildDate:"2023-02-28T12:02:42Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}```
- Others:
