### ISSUE TITLE
don't reconcile resourcebinding when change resourceselector of propagation policy

### ISSUE THREAD

**Issue by olderTaoist** [karmada-io/karmada#3681]
**What happened**:
change the resourceselector of propagation policy,  the resourcebinding of old match resource doesn't be deleted

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      labelSelector:
        matchLabels:
          app: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - paas-federal-user1-master1
        - paas-federal-user2-master1
```

**What you expected to happen**:
the resourcebinding of old match resource  be deleted

**How to reproduce it (as minimally and precisely as possible)**:

propagaion policy is mentioned above.  the resource as fellow:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
  labels:
    app: nginx-1
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
```
**Anything else we need to know?**:

**Environment**:
- Karmada version:
```
kubectl karmada version: version.Info{GitVersion:"v1.3.0", GitCommit:"12e8f01d01571932e6fe45cb7f0d1bffd2e40fd9", GitTreeState:"clean", BuildDate:"2022-08-31T13:09:24Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```
