### ISSUE TITLE
GracefulEviction Have not waiting the workload healthy

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#3736]
**What happened**:

Here is talking about application-failover.

Eviction cluster  before the workload healthy.

**What you expected to happen**:

Waiting the workload is healthy before eviction cluster.

**How to reproduce it (as minimally and precisely as possible)**:

1. kubectl apply nginx.yaml
2. waiting the workload is working
3. mark node "member1-control-plane" as unschedulable in cluster member1

like:

```shell
$ kubectl --context member1 cordon member1-control-plane
$ kubectl --context member1 delete pod -l app=nginx
```
4. waiting the application schedule to the new cluster
5.  start scheduling and evicted member1 cluster, the application is healthy   **problem **
5.   evicted member1 cluster   after the application is healthy   **expect **

Here is the nginx.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
        - name: busybox
          image: busybox:1.34.0
          command: [ 'sh',"-c","sleep 99999" ]
---
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  propagateDeps: true
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 120
      gracePeriodSeconds: 600
      purgeMode: Graciously
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: default
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    spreadConstraints:
      - minGroups: 1
        maxGroups: 3
        spreadByField: cluster
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
```

**Anything else we need to know?**:

### Question  step1

```
Status:
  Aggregated Status:
    Applied:       true
    Cluster Name:  member1
    Health:        Unhealthy
    Status:
      Replicas:              1
      Unavailable Replicas:  1
      Updated Replicas:      1
    Applied:                 true
    Cluster Name:            member2
    Health:                  Healthy
    Status:
      Available Replicas:  1
      Ready Replicas:      1
      Replicas:            1
      Updated Replicas:    1
    Applied:               true
    Cluster Name:          member3
    Health:                Healthy
    Status:
      Available Replicas:  1
      Ready Replicas:      1
      Replicas:            1
      Updated Replicas:    1
```

### Question  Step2

```
Status:
  Aggregated Status:
    Applied:       true
    Cluster Name:  member2
    Health:        Unhealthy
    Status:
      Available Replicas:    1
      Ready Replicas:        1
      Replicas:              2
      Unavailable Replicas:  1
      Updated Replicas:      2
    Applied:                 true
    Cluster Name:            member3
    Health:                  Healthy
    Status:
      Available Replicas:  1
      Ready Replicas:      1
      Replicas:            1
      Updated Replicas:    1
```

### Expect  step1
Same with question step1
### Expect  step2

```
Status:
  Aggregated Status:
    Applied:       true
    Cluster Name:  member1
    Health:        Unhealthy
    Status:
      Replicas:              1
      Unavailable Replicas:  1
      Updated Replicas:      1
    Applied:                 true
    Cluster Name:            member2
    Health:                  Unhealthy
    Status:
      Available Replicas:  1
      Ready Replicas:      1
      Replicas:            2
      Updated Replicas:    2
    Applied:               true
    Cluster Name:          member3
    Health:                Healthy
    Status:
      Available Replicas:  1
      Ready Replicas:      1
      Replicas:            1
      Updated Replicas:    1
```

### Expect  step3

```
Status:
  Aggregated Status:
    Applied:       true
    Cluster Name:  member2
    Health:        Healthy
    Status:
      Available Replicas:    2
      Ready Replicas:        2
      Replicas:              2
      Updated Replicas:      2
    Applied:                 true
    Cluster Name:            member3
    Health:                  Healthy
    Status:
      Available Replicas:  1
      Ready Replicas:      1
      Replicas:            1
      Updated Replicas:    1
```

**Environment**:
- Karmada version:  latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaunceyjiang** [comment]
> GracefulEviction Have not waiting the workload healthy

Hi, I didn't understand where the problem is occurring now. Can you remind me what kind of issues are caused by `GracefulEviction Have not waiting the workload healthy`?

**Comment by Poor12** [comment]
Sorry, I didn't understand the issue either. Could you give me some details?

**Comment by liangyuanpeng** [comment]
@chaunceyjiang @Poor12  

Compared Question step2 and Expect step2,    member2 is Unhealthy and should evicted  member1?  may help?

Looking forward to your reply :)

**Comment by chaunceyjiang** [comment]
```
# Question Step2
Status:
  Aggregated Status:
    Applied:       true
    Cluster Name:  member2
    Health:        Unhealthy
    Status:
      Available Replicas:    1
      Ready Replicas:        1
      Replicas:              2
      Unavailable Replicas:  1
      Updated Replicas:      2
    Applied:                 true
    Cluster Name:            member3
    Health:                  Healthy
    Status:
      Available Replicas:  1
      Ready Replicas:      1
      Replicas:            1
      Updated Replicas:    1

```


The "Question Step2" you described in the issue is just a `temporary state `of the `ResourceBinding`. The `ResourceBinding`'s state will eventually stabilize into the following form.


```
status:
  aggregatedStatus:
  - applied: true
    clusterName: member2
    health: Healthy
    status:
      availableReplicas: 2
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
  - applied: true
    clusterName: member3
    health: Healthy
    status:
      availableReplicas: 1
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1


```
