### ISSUE TITLE
When application failover is enabled but propagateDeps is set to false, the failover has no effect.

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#3738]
**What happened**:

When I was trying to reproduce the issue described in https://github.com/karmada-io/karmada/issues/3736, I forgot to set `propagateDeps` to `true`. As a result, the application was not being evicted and it took me a long time to troubleshoot before realizing that `propagateDeps` must be set to `true`.

When application failover is enabled but propagateDeps is set to false, the failover has no effect.

**What you expected to happen**:

From the [definition](https://github.com/karmada-io/karmada/blob/master/pkg/apis/policy/v1alpha1/propagation_types.go#L173-L174) of the  Application Failover API, it is clear that application failover relies on `propagateDeps` being set to `true`. 

Therefore, when enabling `application failover`, it should be ensured that `propagateDeps` is set to true.

**How to reproduce it (as minimally and precisely as possible)**:
```
export KUBECONFIG=/Users/chauncey/.kube/karmada.config

kubeclt apply -f failover.yaml 
```

![image](https://github.com/karmada-io/karmada/assets/17962021/be4e91b6-f844-4fa2-9206-6f28b8b4fc8b)

failover.yaml : 
``` yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
        - name: busybox
          image: busybox:1.34.0
          command: [ 'sh',"-c","sleep 99999" ]
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  propagateDeps: false
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 120
      gracePeriodSeconds: 600
      purgeMode: Graciously
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: default
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    spreadConstraints:
      - minGroups: 1
        maxGroups: 3
        spreadByField: cluster
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided

```
**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
