### ISSUE TITLE
Karmada instance has been created, but the status of CR is abnormal

### ISSUE THREAD

**Issue by junfsir** [karmada-io/karmada#3770]
**What happened**:
Using Karmada operator to create Karmada instance, the instance is created, but the CR status is always failed, and in a loop between `karmada init job is in progressing` and ```
'failed to install etcd component, err: error when creating etcd client service, err: Service "karmada-demo-etcd" is invalid: metadata.resourceVersion: Invalid value: "": must be specified for an update'```

![image](https://github.com/karmada-io/karmada/assets/16758455/b1fc808e-973d-4394-88c7-69dbe323a3d5)
![image](https://github.com/karmada-io/karmada/assets/16758455/a3606b3e-2631-4f89-b481-1ebe63f1350d)

**Environment**:
- Karmada operator version: docker.io/karmada/karmada-operator:latest
- logs of karmada operator

![image](https://github.com/karmada-io/karmada/assets/16758455/4be6a550-a8c9-4829-b358-f94cf9c38bff)

- Karmadas CR:
```
spec:
  components:
    etcd:
      local:
        imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd
        imageTag: 3.5.3-0
        replicas: 1
        resources: {}
        volumeData:
          emptyDir: {}
    karmadaAPIServer:
      imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver
      imageTag: v1.25.4
      replicas: 1
      resources: {}
      serviceSubnet: 10.96.0.0/12
      serviceType: ClusterIP
    karmadaAggregatedAPIServer:
      imageRepository: docker.io/karmada/karmada-aggregated-apiserver
      imageTag: v1.6.0
      replicas: 1
      resources: {}
    karmadaControllerManager:
      imageRepository: docker.io/karmada/karmada-controller-manager
      imageTag: v1.6.0
      replicas: 1
      resources: {}
    karmadaScheduler:
      imageRepository: docker.io/karmada/karmada-scheduler
      imageTag: v1.6.0
      replicas: 1
      resources: {}
    karmadaWebhook:
      imageRepository: docker.io/karmada/karmada-webhook
      imageTag: v1.6.0
      replicas: 1
      resources: {}
    kubeControllerManager:
      imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager
      imageTag: v1.25.4
      replicas: 1
      resources: {}
  hostCluster:
    networking:
      dnsDomain: cluster.local
```
