### ISSUE TITLE
can't upgrade karmada controller manager deployment with Helm upgrade 

### ISSUE THREAD

**Issue by wu0407** [karmada-io/karmada#3813]
**What happened**:
override controllerManager.extraCommandArgs not effect on Helm upgrade 

**What you expected to happen**:
I can override controllerManager.extraCommandArgs

**How to reproduce it (as minimally and precisely as possible)**:
1. helm install
2. helm upgrade -n karmada-system karmada . -f value-override.yml 
```
controllerManager:
  image:
    tag: v1.6.1
  extraCommandArgs:
    skipped-propagating-namespaces: namespace1,namespace2
```

**Anything else we need to know?**:
The root case is helm post-install hook only apply deployment in install
https://github.com/karmada-io/karmada/blob/d27faeac953043c2274bb8787bbbaaafa7d0dcd6/charts/karmada/templates/karmada-controller-manager.yaml#L12

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
