### ISSUE TITLE
Will PP support status propagation?

### ISSUE THREAD

**Issue by xgp01** [karmada-io/karmada#3870]
I know that in usual cases, the status of a resource should be reconcile by the controller. However, assuming there are some "stateful resources", is it possible to add a mechanism that allows users to choose whether to propagate the status? In some scenarios, the status of these "stateful resources" does not depend on the cluster but comes from external sources such as S3 storage.
A "stateful resource"'s status may like:
```
status:
  completionTimestamp: "2023-07-26T17:01:33Z"
  phase: Completed
  result:
    bucket: "some bucket"
    path: "path/to/resource"
    size: 1024
  startTimestamp: "2023-07-26T17:00:53Z"
```
Let's call this "stateful resource" backup. A backup reconciled by controller, and status is set when backup is completed. Obviously, the status of this backup is only related to S3. When backup is propagated to another cluster, I don't want it be reconciled again because data has already exist in S3.
