### ISSUE TITLE
delete PropagationPolicy and OverridePolicy at the same time, lead to workload recover to origin state

### ISSUE THREAD

**Issue by wu0407** [karmada-io/karmada#3873]
**What happened**:
I want to clean the member resource, so I delete `OverridePolicy` and `PropagationPolicy`  on the same time.
The OverridePolicy is to Override deployment spec.replicas to 0. 
Many pod create by deployment controller on member cluster after delete action.

rule.yaml:
```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: workload-propagation-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: apps/v1
      kind: StatefulSet
  propagateDeps: true
  placement:
    clusterAffinity:
      clusterNames:
        - sh5-online
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterOverridePolicy
metadata:
  name: workload-override-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: apps/v1
      kind: StatefulSet
  overrideRules:
  - overriders:  
      plaintext:
      - path: /spec/replicas
        operator: replace
        value: 0
      - path: /spec/template/spec/tolerations
        operator: add
        value:
        - key: "eks.tke.cloud.tencent.com/eklet"
          operator: "Exists"
          effect: "NoSchedule"
      - path: /spec/template/spec/schedulerName
        operator: replace
        value: "tke-scheduler"
```

**What you expected to happen**:
no pod be created and deployment is deleted.
**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl apply -f rule.yaml
2. wait resouce is synced
3. kubectl delete -f rule.yaml
4. kubectl get pod -w -A
**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

```
kubectl karmada version: version.Info{GitVersion:"v1.6.1", GitCommit:"fdc7ac62c70b571d091a795cbe9b9fceac5f1c2c", GitTreeState:"clean", BuildDate:"2023-07-06T03:35:37Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by wu0407** [comment]
Similar behavior also occurs during creation OverridePolicy and PropagationPolicy.

**Comment by XiShanYongYe-Chang** [comment]
Hi @wu0407 Thank you for your feedback.

The deletion of `PropagationPolicy` and the deletion of `OverridePolicy` may need to be considered separately.

When users delete `PropagationPolicy`, Karmada will disconnect the resource template from pp, but `ResourceBinding` will still exist. At this time, when users delete op again, `ResourceBinding` will still synchronize down to the member cluster. Therefore, the resources in the member cluster will remain consistent with the template.

I would like to understand why you need to delete `PropagationPolicy` and `OverridePolicy`, but keep the resource template.

**Comment by wu0407** [comment]
I don't want deployment running on that cluster, but continue run on karmada cluster. Because karmada apiserver is reuese exist apiserver.

relate issue:
The deployment will be sync to member cluster after cluster is rejoin,  but that cluster not have any `PropagationPolicy`.
The reason is that `ResourceBinding` has been retained when `PropagationPolicy` is be deleted even the cluster is removed.

**Comment by wu0407** [comment]
`ResourceBinding` should be delete or relate info need to be clean. 
```
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - sh5-online
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 300
```

**Comment by XiShanYongYe-Chang** [comment]
@wu0407 @chaunceyjiang Thanks~, Your discussion has provided me with a new perspective. In fact, this issue has been discussed before, #3681 

One previous conclusion was:

>  I'm thinking if we can take a step forward and consider how to make this behavior more in line with user expectations. For example, can we give control of this behavior to users and let them decide whether rb needs to be synchronized and deleted?

I think now we can further optimize this conclusion. The lifecycle of rb and resource templates remains consistent, and users can decide whether to clean up the scheduling results on rb with pp information so that they will no longer be synchronized. What do you think?

**Comment by whitewindmills** [comment]
> I think now we can further optimize this conclusion. The lifecycle of rb and resource templates remains consistent, and users can decide whether to clean up the scheduling results on rb with pp information so that they will no longer be synchronized. What do you think?

if users choose to clean up the previous scheduling results, should the resource template be matched by other new appropriate policies? I think cleanup conflicts with rescheduling. it would be great if you could explain it to me.

**Comment by chaunceyjiang** [comment]
> I think now we can further optimize this conclusion. The lifecycle of rb and resource templates remains consistent, and users can decide whether to clean up the scheduling results on rb with pp information so that they will no longer be synchronized. What do you think?

```
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - sh5-online
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 300

```


I don't think these are **scheduling results.** I believe they are **scheduling information**. Since the PP has already been deleted, the related information should also be cleaned up.
