### ISSUE TITLE
unable add annotation use plaintext overide whether annotation fileld is exist

### ISSUE THREAD

**Issue by wu0407** [karmada-io/karmada#3923]
**What happened**:
I want to add annotation to `spec.template.metadata.annotation`  whether annotation fileld is exist, but plaintext overide unable to achieve this goal.

### direct add annotation
configuration:
```
spec:
 overrideRules:
  - overriders:
      plaintext:
      - path: /spec/template/metadata/annotations/test
        operator: add
        value: "test-value"
```

It is ok on spec.template.metadata.annotations is exist.
```
                        {"spec": {
				"template": {
					"metadata": {
						"annotations": {
							"c": "d"
						},
						"labels": {
							"a": "b"
						}
					}
				}
			}}
```
result
```
                            {"spec": {
				"template": {
					"metadata": {
						"annotations": {
							"c": "d",
                                                        "test": "test-value"
						},
						"labels": {
							"a": "b"
						}
					}
				}
			}}
```
It is not ok on  spec.template.metadata.annotations is not exist.

```
                        {"spec": {
				"template": {
					"metadata": {
						"labels": {
							"a": "b"
						}
					}
				}
			}}
```
result:
```
E0809 07:50:41.625787       1 controller.go:329] "Reconciler error" err="add operation does not apply: doc is missing path: \"/spec/template/metadata/annotations/test\": missing value" controller="resourcebinding" controllerGroup="work.karmada.io" controllerKind="ResourceBinding" ResourceBinding="xxxxx/xxxxx-deployment" namespace="xxxxx" name="xxxx-deployment" reconcileID=b87a1530-c398-4393-82fa-82bef68ac8cb
```
### Another way is add annotation field first, then add annotation. But It is not work.

configuration:
```
spec:
 overrideRules:
  - overriders:
      plaintext:
      - path: /spec/template/metadata/annotations
        operator: add
        value: {}
      - path: /spec/template/metadata/annotations/test
        operator: add
        value: "test-value"
```
It is not ok on spec.template.metadata.annotations is exist.
```
                        {"spec": {
				"template": {
					"metadata": {
						"annotations": {
							"c": "d"
						},
						"labels": {
							"a": "b"
						}
					}
				}
			}}
```
result
```
                            {"spec": {
				"template": {
					"metadata": {
						"annotations": {
                                                        "test": "test-value"
						},
						"labels": {
							"a": "b"
						}
					}
				}
			}}
```
It is ok on  spec.template.metadata.annotations is not exist.

```
                        {"spec": {
				"template": {
					"metadata": {
						"labels": {
							"a": "b"
						}
					}
				}
			}}
```
result:
```
{"spec": {
				"template": {
					"metadata": {
						"annotations": {
                                                        "test": "test-value"
						},
						"labels": {
							"a": "b"
						}
					}
				}
			}}
```
### the last method is one deployment one configuration, so inconvenient.

**What you expected to happen**:
add new annotation successed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
```
kubectl karmada version: version.Info{GitVersion:"v1.6.1", GitCommit:"fdc7ac62c70b571d091a795cbe9b9fceac5f1c2c", GitTreeState:"clean", BuildDate:"2023-07-06T03:35:37Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```
