### ISSUE TITLE
karmada not work well

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3961]
**What happened**:
[karmada.zip](https://github.com/karmada-io/karmada/files/12393248/karmada.zip)
上面是我的karmada chart
helm  install karmada . -n karmada-system --create-namespace --dependency-update       --set components={"search,descheduler"}
用上面命令安装
kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d >~/kube-karmada
导出配置
karmadactl join cluster1  --kubeconfig ~/kube-karmada --karmada-context karmada-apiserver --cluster-kubeconfig=/root/153config --cluster-context=context-cluster1
加入集群失败：Error from server (ServiceUnavailable): the server is currently unable to handle the request (get clusters.cluster.karmada.io)
[root@localhost ~]# kubectl get cluster -A --kubeconfig kube-karmada 
error: the server doesn't have a resource type "cluster"
无法获取cluster
karmada-system   karmada-controller-manager-5597d7c666-6p5qq        0/1     CrashLoopBackOff   11 (2m22s ago)   60m
这个老是重启：
日志：
```
I0821 06:43:15.866021       1 internal.go:581] "Stopping and waiting for caches"
I0821 06:43:15.866138       1 internal.go:585] "Stopping and waiting for webhooks"
I0821 06:43:15.866146       1 internal.go:589] "Wait completed, proceeding to shutdown the manager"
E0821 06:43:15.866158       1 controllermanager.go:166] controller manager exits unexpectedly: failed to wait for cluster caches to sync: timed out waiting for cache to be synced
E0821 06:43:15.866166       1 run.go:74] "command failed" err="failed to wait for cluster caches to sync: timed out waiting for cache to be synced"
```

docker 版本：
```
[root@localhost karmada]# docker version
Client:
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:03:22 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:07:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
helm 版本：
```
[root@localhost karmada]# helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @chaosi-zju, can you help take a look?

**Comment by 13567436138** [comment]
![10bce7cc02892b44fb6367e19bdea7a](https://github.com/karmada-io/karmada/assets/31508490/ebbf09a0-15c5-414a-a233-a898c369e76b)
kube-apiserver貌似有报错

**Comment by 13567436138** [comment]
v1alpha1.cluster.karmada.io.yaml

```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cluster.karmada.io
  labels:
    app: karmada-aggregated-apiserver
    apiserver: "true"
spec:
  insecureSkipTLSVerify: true
  group: cluster.karmada.io
  groupPriorityMinimum: 2000
  service:
    name: karmada-aggregated-apiserver
    namespace: karmada-system
  version: v1alpha1
  versionPriority: 10
```

kubectl apply -f karmada-aggregated-apiserver.yaml -n karmada-system --kubeconfig ~/kube-karmada

```
apiVersion: v1
kind: Service
metadata:
  name: karmada-aggregated-apiserver
  namespace: karmada-system
spec:
  type: ExternalName
  externalName: karmada-aggregated-apiserver.karmada-system.svc.cluster.local
```
执行上面两个crd问题解决，注意上面这个在kube-apiserver执行，下面这个在karmada-apiserver执行
