### ISSUE TITLE
1.4.2karmada 采用external etcd karmada-search报错

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3964]
**What happened**:
## 
![image-20230821171739994](https://github.com/karmada-io/karmada/assets/31508490/93c4dda5-b25b-4433-af73-08656270dcbc)

证书来源，用k8s的

![image-20230821165241011](https://github.com/karmada-io/karmada/assets/31508490/3992253b-c8ba-4e6b-b856-f03a1a83a1e7)

遇到无法删除名称空间

![image-20230821170457087](https://github.com/karmada-io/karmada/assets/31508490/7600b060-ac87-49bc-9c3c-1e3818ee3f4f)

```
kubectl get namespace karmada-system -o json > devtesting.json
打开devtesting.json把finalizers里的内容删掉
kubectl proxy --port 8080
curl -k -H "Content-Type: application/json" -X PUT --data-binary @devtesting.json http://127.0.0.1:8080/api/v1/namespaces/karmada-system/finalize


[root@localhost ~]# kubectl get ns
NAME              STATUS   AGE
default           Active   3h26m
kube-node-lease   Active   3h26m
kube-public       Active   3h26m
kube-system       Active   3h26m
```

执行安装

```
helm  install karmada . -n karmada-system --create-namespace --dependency-update       --set components={"search,descheduler"}

kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d >~/kube-karmada
```

执行下面两个crd

kubectl apply -f v1alpha1.cluster.karmada.io.yaml

```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cluster.karmada.io
  labels:
    app: karmada-aggregated-apiserver
    apiserver: "true"
spec:
  insecureSkipTLSVerify: true
  group: cluster.karmada.io
  groupPriorityMinimum: 2000
  service:
    name: karmada-aggregated-apiserver
    namespace: karmada-system
  version: v1alpha1
  versionPriority: 10
```

kubectl apply -f karmada-aggregated-apiserver.yaml -n karmada-system --kubeconfig ~/kube-karmada

```
apiVersion: v1
kind: Service
metadata:
  name: karmada-aggregated-apiserver
  namespace: karmada-system
spec:
  type: ExternalName
  externalName: karmada-aggregated-apiserver.karmada-system.svc.cluster.local
```

报错

```
karmada-system   karmada-search-6f4c657b85-l2zpj                    0/1     CrashLoopBackOff   8 (11s ago)     18m
karmada-system   karmada-search-6f4c657b85-44l4s                    0/1     CrashLoopBackOff   8 (9s ago)      18m

Err: connection error: desc = "transport: Error while dialing dial tcp: lookup etcd-client.karmada-system.svc.cluster.local on 169.254.20.10:53: no such host"
```

手动创建etcd-client和etcd

kubectl apply -f svc-etcd-etcd-client.yaml -n karmada-system

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-client
  namespace: karmada-system
spec:
  ports:
    - name: etcd-client-port
      port: 2379
      protocol: TCP
      targetPort: 2379

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: karmada-system
spec:
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: server
      port: 2380
      protocol: TCP
      targetPort: 2380
```

kubectl apply -f endpoints-etcd-etcd-client.yaml -n karmada-system

```
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd
  labels:
    app: etcd
subsets:
  - addresses:
      - ip: 192.168.229.148
      - ip: 192.168.229.151
      - ip: 192.168.229.152
    ports:
      - port: 2379
        name: client
      - port: 2380
        name: server
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-client
  labels:
    app: etcd
subsets:
  - addresses:
      - ip: 192.168.229.148
      - ip: 192.168.229.151
      - ip: 192.168.229.152
    ports:
      - port: 2379
        name: etcd-client-port

```
报错：
}. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate is not valid for any names, but wanted to match etcd-client.karmada-system.svc.cluster.local"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.4.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
