### ISSUE TITLE
1.4.2karmada-aggregated-apiserver error log

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3969]
```
E0822 05:18:03.638601       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=656881357682436358163989480975398362341508819005, SKID=C9:B8:80:FA:8D:13:E1:26:B6:83:78:20:12:08:5B:9F:2F:AC:68:FB, AKID=4C:2B:3A:EA:A7:7A:DD:BD:06:3D:25:11:7F:71:CF:5C:0F:10:8E:A3 failed: x509: certificate signed by unknown authority]"
E0822 05:18:03.638732       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=656881357682436358163989480975398362341508819005, SKID=C9:B8:80:FA:8D:13:E1:26:B6:83:78:20:12:08:5B:9F:2F:AC:68:FB, AKID=4C:2B:3A:EA:A7:7A:DD:BD:06:3D:25:11:7F:71:CF:5C:0F:10:8E:A3 failed: x509: certificate signed by unknown authority]"
E0822 05:18:03.638973       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=656881357682436358163989480975398362341508819005, SKID=C9:B8:80:FA:8D:13:E1:26:B6:83:78:20:12:08:5B:9F:2F:AC:68:FB, AKID=4C:2B:3A:EA:A7:7A:DD:BD:06:3D:25:11:7F:71:CF:5C:0F:10:8E:A3 failed: x509: certificate signed by unknown authority]^
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:1.4.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
@13567436138 Can you tell us how to reproduce it?
I can't get a clue about what happened.

**Comment by 13567436138** [comment]
## 


[karmada.zip](https://github.com/karmada-io/karmada/files/12407201/karmada.zip)

```
cd karmada/
host模式
helm  install karmada . -n karmada-system --create-namespace --dependency-update       --set components={"search,descheduler"}




kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d >~/kube-karmada
kubectl get all --kubeconfig ~/kube-karmada --context karmada-apiserver -n karmada-system

[root@localhost ~]# vi /etc/resolv.conf 
# Generated by NetworkManager
#search localdomain cluster.local
#nameserver 192.168.229.2
search cluster.local
nameserver 10.68.0.2
 
 
[root@localhost ~]# chmod +x karmadactl
[root@localhost ~]# mv karmadactl /usr/local/bin/
```

如果报couldn't get resource list for cluster.karmada.io/v1alpha1: the server is currently unable to handle the request

kubectl apply -f karmada-aggregated-apiserver.yaml -n karmada-system --kubeconfig ~/kube-karmada

```
apiVersion: v1
kind: Service
metadata:
  name: karmada-aggregated-apiserver
  namespace: karmada-system
spec:
  type: ExternalName
  externalName: karmada-aggregated-apiserver.karmada-system.svc.cluster.local
```



安装karmada search需要部署opensearch

```
 kubectl apply -f karmada-opensearch.yaml -n karmada-system
 kubectl apply -f karmada-opensearch-dashboards.yaml -n karmada-system 
```

部署search apiservice

kubectl apply -f search-apiservice.yaml

```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.search.karmada.io
  labels:
    app: karmada-search
    apiserver: "true"
spec:
  insecureSkipTLSVerify: true
  group: search.karmada.io
  groupPriorityMinimum: 2000
  service:
    name: karmada-search
    namespace: karmada-system
  version: v1alpha1
  versionPriority: 10
```

kubectl apply -f karmada-search-apiserver.yaml -n karmada-system --kubeconfig ~/kube-karmada

```
apiVersion: v1
kind: Service
metadata:
  name: karmada-search
  namespace: karmada-system
spec:
  type: ExternalName
  externalName: karmada-search.karmada-system.svc.cluster.local
```



## 6.2加入集群

```
karmadactl join cluster1  --kubeconfig ~/kube-karmada --karmada-context karmada-apiserver --cluster-kubeconfig=/root/153config --cluster-context=context-cluster1

karmadactl join cluster2  --kubeconfig ~/kube-karmada --karmada-context karmada-apiserver --cluster-kubeconfig=/root/156config --cluster-context=context-cluster1

[root@localhost ~]# kubectl get cluster --kubeconfig kube-karmada --context karmada-apiserver 
NAME       VERSION   MODE   READY   AGE
cluster1   v1.23.1   Push   True    48s
cluster2   v1.23.1   Push   True    39s
```

## 问题

1

x509：使用`karmadactl init`时报`certificate signed by unknown authority`

使用`karmadactl init`命令安装Karmada时，在init安装日志中发现以下报错信息：

```log
deploy.go:55] Post "https://192.168.24.211:32443/api/v1/namespaces": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "karmada")
```



问题原因：之前在集群上安装过Karmada，karmada-etcd使用`hostpath`方式挂载本地存储，卸载时数据有残留，需要清理默认路径`/var/lib/karmada-etcd`下的文件。如果使用了karmadactl [[--etcd-data](https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/cmdinit/cmdinit.go#L119)](https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/cmdinit/cmdinit.go#L119)参数，请删除相应的目录。

2

[root@localhost ~]# karmadactl join cluster1  --kubeconfig ~/kube-karmada --karmada-context karmada-apiserver --cluster-kubeconfig=/root/153config --cluster-context=context-cluster1
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get clusters.cluster.karmada.io)

执行下面两个crd

kubectl apply -f v1alpha1.cluster.karmada.io.yaml

```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cluster.karmada.io
  labels:
    app: karmada-aggregated-apiserver
    apiserver: "true"
spec:
  insecureSkipTLSVerify: true
  group: cluster.karmada.io
  groupPriorityMinimum: 2000
  service:
    name: karmada-aggregated-apiserver
    namespace: karmada-system
  version: v1alpha1
  versionPriority: 10
```

kubectl apply -f karmada-aggregated-apiserver.yaml -n karmada-system --kubeconfig ~/kube-karmada

```
apiVersion: v1
kind: Service
metadata:
  name: karmada-aggregated-apiserver
  namespace: karmada-system
spec:
  type: ExternalName
  externalName: karmada-aggregated-apiserver.karmada-system.svc.cluster.local
```
