### ISSUE TITLE
member cluster is unknown,push pull mode both

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3973]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
```
[root@localhost karmada]# kubectl get cluster --kubeconfig ~/kube-karmada 
NAME       VERSION   MODE   READY     AGE
cluster1             Pull   Unknown   89m
cluster2             Pull   Unknown   23m
```
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by chaosi-zju** [comment]
could you please try:

1. excute `kubectl describe cluster cluster1`
2. how did you install your raw k8s cluster? Can you show me your kubeconfig of karmada cluster and cluster1?
3. does the network between karmada cluster and cluster1 is ok? Or the public network is ok but you specified a local ip in some steps?

**Comment by SeekerRook** [comment]
Hello. I have the same problem as @13567436138 . 
```
># kubectl get clusters --kubeconfig=karmada-config                                                                  
NAME       VERSION   MODE   READY     AGE
cluster1             Pull   Unknown   17d
cluster2             Pull   Unknown   121m
```
As an answer to @chaosi-zju  Here are the specs for my personal case:

- Cluster 1 description:
```
Name:         cluster1
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  cluster.karmada.io/v1alpha1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2023-08-14T14:21:47Z
  Generation:          1
  Resource Version:    38301
  UID:                 0a69b34d-3e9c-4cdf-ac4e-dee901f8f4c1
Spec:
  Id:  e0c27a42-0594-4d70-b5dd-883b2f90453b
  Impersonator Secret Ref:
    Name:       cluster1-impersonator
    Namespace:  karmada-cluster
  Resource Models:
    Grade:  0
    Ranges:
      Max:   1
      Min:   0
      Name:  cpu
      Max:   4Gi
      Min:   0
      Name:  memory
    Grade:   1
    Ranges:
      Max:   2
      Min:   1
      Name:  cpu
      Max:   16Gi
      Min:   4Gi
      Name:  memory
    Grade:   2
    Ranges:
      Max:   4
      Min:   2
      Name:  cpu
      Max:   32Gi
      Min:   16Gi
      Name:  memory
    Grade:   3
    Ranges:
      Max:   8
      Min:   4
      Name:  cpu
      Max:   64Gi
      Min:   32Gi
      Name:  memory
    Grade:   4
    Ranges:
      Max:   16
      Min:   8
      Name:  cpu
      Max:   128Gi
      Min:   64Gi
      Name:  memory
    Grade:   5
    Ranges:
      Max:   32
      Min:   16
      Name:  cpu
      Max:   256Gi
      Min:   128Gi
      Name:  memory
    Grade:   6
    Ranges:
      Max:   64
      Min:   32
      Name:  cpu
      Max:   512Gi
      Min:   256Gi
      Name:  memory
    Grade:   7
    Ranges:
      Max:   128
      Min:   64
      Name:  cpu
      Max:   1Ti
      Min:   512Gi
      Name:  memory
    Grade:   8
    Ranges:
      Max:   9223372036854775807
      Min:   128
      Name:  cpu
      Max:   9223372036854775807
      Min:   1Ti
      Name:  memory
  Secret Ref:
    Name:       cluster1
    Namespace:  karmada-cluster
  Sync Mode:    Pull
Status:
Events:  <none>

```
- Cluster2 description:
```
Name:         cluster2
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  cluster.karmada.io/v1alpha1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2023-09-01T07:58:40Z
  Generation:          1
  Resource Version:    41556
  UID:                 19159559-0ab6-4f2f-8166-acb545d4cf70
Spec:
  Id:  2b06157f-a7b7-4905-bf33-5b38582fc74e
  Impersonator Secret Ref:
    Name:       cluster2-impersonator
    Namespace:  karmada-cluster
  Resource Models:
    Grade:  0
    Ranges:
      Max:   1
      Min:   0
      Name:  cpu
      Max:   4Gi
      Min:   0
      Name:  memory
    Grade:   1
    Ranges:
      Max:   2
      Min:   1
      Name:  cpu
      Max:   16Gi
      Min:   4Gi
      Name:  memory
    Grade:   2
    Ranges:
      Max:   4
      Min:   2
      Name:  cpu
      Max:   32Gi
      Min:   16Gi
      Name:  memory
    Grade:   3
    Ranges:
      Max:   8
      Min:   4
      Name:  cpu
      Max:   64Gi
      Min:   32Gi
      Name:  memory
    Grade:   4
    Ranges:
      Max:   16
      Min:   8
      Name:  cpu
      Max:   128Gi
      Min:   64Gi
      Name:  memory
    Grade:   5
    Ranges:
      Max:   32
      Min:   16
      Name:  cpu
      Max:   256Gi
      Min:   128Gi
      Name:  memory
    Grade:   6
    Ranges:
      Max:   64
      Min:   32
      Name:  cpu
      Max:   512Gi
      Min:   256Gi
      Name:  memory
    Grade:   7
    Ranges:
      Max:   128
      Min:   64
      Name:  cpu
      Max:   1Ti
      Min:   512Gi
      Name:  memory
    Grade:   8
    Ranges:
      Max:   9223372036854775807
      Min:   128
      Name:  cpu
      Max:   9223372036854775807
      Min:   1Ti
      Name:  memory
  Secret Ref:
    Name:       cluster2
    Namespace:  karmada-cluster
  Sync Mode:    Pull
Status:
Events:  <none>

```
I installed kubernetes using [K3s](https://docs.k3s.io/) and karmada using Helm.  Here are the kubeconfigs
-  Cluster-Manager
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1C...tLS0K
    server: https://192.168.56.110:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1C...BVEUtLS0tLQo=
    client-key-data: LS0tL...0tLQo=

```

-  Cluster 1
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1C...RJRklDQVRFLS0tLS0K
    server: https://192.168.56.103:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS...RJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS...ktLS0tLQo=

```

As for the network connection all 3 clusters are in VMs on the same host connected using a Host-Only Adapter and a NAT adapter to connect to the Internet (the IPs on the kubeconfigs are the IPs of the Host-Only Adater).

Thanks in advance!
