### ISSUE TITLE
先创建 pp-1 和 pp-2，再创建 deploy，再删除 pp-1，deploy 是否会自动 match 到 pp-2 ?

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#3982]
**Please provide an in-depth description of the question you have**:

1. 先创建 pp-1 (preemption: Always, priority: 5) 和 pp-2 (preemption: Never, priority: 5)
2. 再创建匹配的 deployment
3. 再删除 pp-1

该deployment是否会自动重新匹配 pp-2，为什么?

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: dp-test-pp1
  namespace: namespace-lijunhui
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: namespace-lijunhui
      name: dp-test-pp
    - apiVersion: v1
      kind: Service
      namespace: namespace-lijunhui
      name: test-svc-01
  placement:
    clusterAffinity:
      clusterNames:
        - ljh-turbo-123
    clusterTolerations:
      - key: cluster.karmada.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: cluster.karmada.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
    replicaScheduling:
        replicaSchedulingType: Duplicated
  preemption: Always
  priority: 5
```

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: dp-test-pp2
  namespace: namespace-lijunhui
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: namespace-lijunhui
      name: dp-test-pp
  placement:
    clusterAffinity:
      clusterNames:
        - turbo6
    clusterTolerations:
      - key: cluster.karmada.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: cluster.karmada.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
    replicaScheduling:
        replicaSchedulingType: Duplicated
  preemption: Never
  priority: 5
```

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dp-test-pp
  namespace: namespace-lijunhui
  labels:
    app: dp-test-pp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-test-pp
  template:
    metadata:
      labels:
        app: dp-test-pp
    spec:
      containers:
        - name: container-1
          image: swr.cn-north-7.myhuaweicloud.com/image1/nginx:multiport
          env:
            - name: PAAS_APP_NAME
              value: mcp-nginx2
            - name: PAAS_NAMESPACE
              value: default
            - name: PAAS_PROJECT_ID
              value: 6273e04835934c0dbb47c1e7b6f5625f
          resources:
            limits:
              cpu: 10m
              memory: 15Mi
            requests:
              cpu: 10m
              memory: 15Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:
