### ISSUE TITLE
feature: moving Karmada resource key information from labels to annotations

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4000]
**What would you like to be added**:
Now, Karmada puts the resource owner information into labels, which could cause the label value longer than 63 chars. 

So first, let's figure out what's the current situation:

**PropagationPolicy**
max_len(name) = 63
max_len(namespace)=63

**Deployment**
max_len(name)=253
max_len(namespace)=63

After find the matched PP, there will be two labels:
```yaml
propagationpolicy.karmada.io/name: PropagationPolicy name
propagationpolicy.karmada.io/namespace: PropagationPolicy namespace
```

**ResourceBinding**
max_len(name)=Deployment's name+kind > 253  **(1)**
max_len(namespace)=Deployment's namespace < 63

After matched, there will be two labels:
```yaml
propagationpolicy.karmada.io/name: PropagationPolicy name
propagationpolicy.karmada.io/namespace: PropagationPolicy namesapce
````

**Work**
max_len(name)=Deplyment's name + hash(namepsace-name-kind) > 253 **(2)**
max(namespace)=Deployment's namespace < 63

There will be one label:
```yaml
resourcebinding.karmada.io/key: hash(binding namspace/name)
```

**Deployment in member clusters**
max_len(name)=253
max_len(namesapce)=63

There will be following labels:
```yaml
karmada.io/managed: "true"
propagationpolicy.karmada.io/name: PropagationPolicy name
propagationpolicy.karmada.io/namespace: PropagationPolicy namespace
resourcebinding.karmada.io/key: hash(binding namspace/name)
work.karmada.io/name: Deployment name+hash(namespace-name-kind) (3)
work.karmada.io/namespace: work's ns
```

(1) It couldn't be longer than 253, there will be errors.
(2) It couldn't be longer than 253, there will be errors.
(3) It couldn't be longer than 63, there will be errors.

For (1)/(2), there are few possibilities of users using excessively long deployment names. We should provide documentation that indicates the maximum length for workload names.

To address (3), the solution is to transfer all relevant owner information to annotations and include a unique identifier label there(uid), which will be used for label selection during coding, like following:
```yaml
resourcebinding.karmada.io/uid: 93162d3c-ee8e-4995-9034-05f4d5d2c2b9
```

The changes roadmap:
- v1.7.0: Add uid label into the resource to show the owner information, and add owner information into the annotations.
- v1.8.0: Do not add the owner information label to the resource labels.

**Why is this needed**:

If users create a workload with a name longer than 63 characters, the workload may not be synchronized to member clusters because of the webhook validation.

/cc @RainbowMango
