### ISSUE TITLE
confusing karmada-apiserver address auto generated by `helm install`

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4013]
**What happened**:

follow this [doc](https://github.com/karmada-io/karmada/tree/master/charts/karmada), when finished `helm install`：

> Get kubeconfig from the cluster:
>
> ```console
> kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d
> ```

you will see kubeconfig of `karmada-apiserver` like this：

```
kind: Config
clusters:
  - cluster:
      certificate-authority-data: LS0tLS.......
      insecure-skip-tls-verify: false
      server: https://karmada-apiserver.karmada-system.svc.cluster.local:5443
```

My question is：**why karmada auto generated apiserver address like `karmada-apiserver.karmada-system.svc.cluster.local`?**

As you known, kubeconfig will be placed in my local machine, and `karmada-apiserver.karmada-system.svc.cluster.local` is just a service name, in some term, this address is invalid on my local machine, I have to add execute：

```shell
echo "172.18.0.2    karmada-apiserver.karmada-system.svc.cluster.local" >> /etc/hosts
systemd-resolve --flush-caches
```

but is so tricky and roundabout.

**What you expected to happen**:

maybe we can just copy server address from kubeconfig of `karmada-host`?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaosi-zju** [comment]
So far, you may evade this problem by two methods:

**1）add local dns host**

```
echo "172.18.0.2    karmada-apiserver.karmada-system.svc.cluster.local" >> /etc/hosts
systemd-resolve --flush-caches
```

**2）change kubeconfig of apiserver into `insecure-skip-tls-verify`**

```yaml
kind: Config
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://172.18.0.2:5443
```
as you see, you should delete `certificate-authority-data` line, and update `insecure-skip-tls-verify` to `true`.

Note: The special IP `172.18.0.2` in both methods is the host IP of `karmada-apiserver`, like:

![image](https://github.com/karmada-io/karmada/assets/30589999/ff93fcd6-28ac-4a0e-85d6-b01733913668)

you should ensure `karmada-apiserver` is `hostNetwork`, and the `172.18.0.2` refer to its host-network IP.
