### ISSUE TITLE
OverridePolicy can not overwrite annotations

### ISSUE THREAD

**Issue by HuckOps** [karmada-io/karmada#4014]
**Please provide an in-depth description of the question you have**:
This is a service:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/nks-load-balancer-disabled: "False"
    service.beta.kubernetes.io/nks-load-balancer-platform: nks
  creationTimestamp: "2023-08-29T13:34:01Z"
  labels:
    app: testing-app
    propagationpolicy.karmada.io/name: testing-app-service
    propagationpolicy.karmada.io/namespace: testing
  name: app
  namespace:testing
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: testing-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

when i use overridepolicy to inject an annotations named ```service.beta.kubernetes.io/nks-load-balancer-set-vpcid: TEMP``` like this:
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  annotations:
  creationTimestamp: "2023-08-29T13:34:01Z"
  name: testing-app-service-cluster1
  namespace: testing
spec:
  overrideRules:
  - overriders:
      plaintext:
      - operator: add
        path: /metadata/annotations/"service.beta.kubernetes.io/nks-load-balancer-set-vpcid"
        value: xxxxxxxxxxxxxxx
    targetCluster:
      clusterNames:
      - cluster1
  overriders: {}
  resourceSelectors:
  - apiVersion: v1
    kind: Service
    name: app
    namespace: testing
```

But resourcebinding return an event log:

```
  Warning  SyncWorkFailed          6s (x4 over 29m)      binding-rb-controller  add operation does not apply: doc is missing path: "/metadata/annotations/"service.beta.kubernetes.io/nks-load-balancer-set-vpcid"": missing value
```
So, how can i modify overridepolicy？

**What do you think about this question?**:

Maybe format error

**Environment**:
- Karmada version: 
- Kubernetes version: 1.17
- Others:
