### ISSUE TITLE
resourcebinding not rescheduler after unlabel cluster 

### ISSUE THREAD

**Issue by huiwq1990** [karmada-io/karmada#4028]
**What happened**:

When cluster label change, scheduler will not reconcile resourcebinding.

**What you expected to happen**:

When cluster label change, scheduler will reconcile resourcebinding.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: xxx
spec:
  conflictResolution: Abort
  placement:
    clusterAffinities:
    - affinityName: group1
      labelSelector:
        matchLabels:
          cluster.io/all: "true"
```

```yaml
apiVersion: work.karmada.io/v1alpha2
kind: ResourceBinding
metadata:
  name: xxx
spec:
  clusters:
  - name: mock-cluster-01
    replicas: 1
  - name: edge-cluster-01
    replicas: 600
  conflictResolution: Abort
  placement:
    clusterAffinities:
    - affinityName: group1
      labelSelector:
        matchLabels:
          cluster.io/all: "true"
```

```shell
bash-5.0# kubectl --kubeconfig=/root/.kube/karmada.config --context=karmada-apiserver get cluster --show-labels
NAME              VERSION      MODE   READY   AGE   LABELS
edge-cluster-01   v1.19.9  Push   True    22h   cluster.io/all=true
mock-cluster-01   v1.19.9  Push   True    22h   cluster.io/all=true
```

**Anything else we need to know?**:

For the latest version of karmada, it's reasonable not reconcile. I wonder it is a feature or a bug of karmada.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
