### ISSUE TITLE
No policy match for resource

### ISSUE THREAD

**Issue by MolisXYliu** [karmada-io/karmada#4039]
![image](https://github.com/karmada-io/karmada/assets/49862384/643f245f-ea0e-428f-8837-b0931d3e41b2)
the pv yaml
````yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: iscis-demo
    name: os-iscsi-pv
  name: os-iscsi-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  iscsi:
    fsType: ext4
    iqn: iqn.2019-12.com.redhat:11-2g
    iscsiInterface: default
    lun: 0
    targetPortal: 10.125.28.164:3260
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
````
policy yaml:
````yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  generation: 1
  name: os-iscsi-pv-persistentvolume
  namespace: default
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - test-karmada
  priority: 0
  propagateDeps: true
  resourceSelectors:
  - apiVersion: v1
    kind: PersistentVolume
    name: os-iscsi-pv
    namespace: default
  schedulerName: default-scheduler
````
请问为什么匹配不上？ 谢谢
