### ISSUE TITLE
karmadactl apply operations will traverse all APIs every time, but kubectl doesn't

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4047]
**Please provide an in-depth description of the question you have**:

I have the following yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

Apply one deployment yaml with karmadctl, the request logs:
![image](https://github.com/karmada-io/karmada/assets/19745536/15572c74-b171-4883-8eed-09f09ac6e091)

Apply one deployment yaml with kubectl, the request logs:
![image](https://github.com/karmada-io/karmada/assets/19745536/4f3549ec-ad10-4b56-a635-748760b679d8)

I tried many times, and
* karmadactl will traverse all the APIs that exist in karmada-apiserver every time.
* kubectl will not traverse all the APIs that exist every time, but sometimes.
![img](https://user-images.githubusercontent.com/19745536/265647611-ab4a5d69-afb7-42b5-ac0b-f85be0a5c499.png)

**What do you think about this question?**:

I check the code of karmadactl apply, It utilizes the same code as kubectl.
https://github.com/karmada-io/karmada/blob/bd37e7472bb055aeb220cfe56e10492eb49d900a/pkg/karmadactl/apply/apply.go#L149

This may be because the cache: https://github.com/kubernetes/kubernetes/blob/c4d752765b3bbac2237bf87cf0b1c2e307844666/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L59

But I deleted it and tried the apply operation again with kubectl, but it still did not traverse all the APIs.
I am unsure in what situation kubectl will traverse the APIs and why karmadactl will do it every time.

Do you have any idea about this? @lonelyCZ 

**Environment**:
- Karmada version: v1.7.0
- Kubernetes version: v1.27.3
- Others: none
