### ISSUE TITLE
How to achieve schedule replicas of a custom resource to exactly one cluster

### ISSUE THREAD

**Issue by wengyao04** [karmada-io/karmada#4049]
**Please provide an in-depth description of the question you have**:
Hi, we want to use karmada to schedule [kubeflow.PytorchJob](https://github.com/kubeflow/training-operator/blob/master/pkg/apis/kubeflow.org/v1/pytorch_types.go) on our multi cluster groups. We have implemented a customresouce interpreter webhook like this example https://github.com/karmada-io/karmada/tree/master/examples/customresourceinterpreter

But we have a question about how to set propagationPolicy properly. For example, my kubeflow.Pytorhjob have 1 master + 2 workers, each of which requests 1 cpu and 10Gi memory. The replicas are returned as 3 in `configv1alpha1.InterpreterOperationInterpretReplica`

We need to schedule these 3 replicas on one same cluster because we don't support cross cluster communications. if the master and workers are deployed to two clusters, they cannot communicate with each other.
For example, if we only register two clusters (cluster 1 and 2)
cluster 1: still have 1 available cpu, 20 Gi memory
cluster 2: still have 2 available cpu, 40 Gi memory
We expect karmada not schedule this pytorch job on any clusters.

Divide + Aggregated cannot help achieve it. Then how could we properly set propagation policy to achieve it ?

BTW: I don't want to set this pytorch job as one replica and the adds up all workers and master requested resources as a total resource because we want to enable-cluster-resource-modeling to avoid cpu/memory fragmentation issue.

If we treat one pytorch job as one replica, the total resources might be huge, and
may not fit into any node in the resource mode grade
or it is always schedule to nodes with more cpu/memory (our clusters have different cpu boxes)  

**What do you think about this question?**:

**Environment**:
- Karmada version: latest
- Kubernetes version: 1.24
- Others:

**Comment by RainbowMango** [comment]
Let me try to understand your use, You expect Karmada to select `one` cluster for each `PyTorchJob` based on available resources, am I right?
If yes, maybe you can have a try with `SpreadConstraints` as below:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: kubeflow.org/v1
      kind: PyTorchJob
      name: foo
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
    replicaScheduling:
      replicaDivisionPreference: Aggregated    # declares that want to aggregate the replicas
      replicaSchedulingType: Divided
    spreadConstraints:                         # but restrict to use only 1 cluster
      - spreadByField: cluster
        minGroups: 1
        maxGroups: 1
```
Declaring `minGroups` and `maxGroups` to `1` guarantees Karmada would select at most `1` cluster, and if no cluster has enough resources, then no cluster would be selected(I get it from [code here](https://github.com/karmada-io/karmada/blob/bd37e7472bb055aeb220cfe56e10492eb49d900a/pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go#L69-L70)).  

This approach seems a little bit tricky though, as I don't have much experience about how to schedule training workloads. @Garrybest is the expert in this area and I believe he has a lot of experience in it.

**Comment by wengyao04** [comment]
Thanks @RainbowMango, it meets our requirement. 
I test it, for example, our cluster1 has 8 Gpus, cluster2 has 4 Gpus, when I schedule a job requested 9 Gpus, karmada gives me this message
```
status:
  conditions:
  - lastTransitionTime: "2023-09-11T13:42:56Z"
    message: 'failed to select clusters: no enough resource when selecting 1 clusters'
    reason: SchedulerError
    status: "False"
    type: Scheduled
```

Thanks again !!
