### ISSUE TITLE
resourceModels supports extended resources 

### ISSUE THREAD

**Issue by wengyao04** [karmada-io/karmada#4050]
**Please provide an in-depth description of the question you have**:
I am able to register clusters with push mode, and use default resourceModel which only supports cpu, memory, ephemeral-storage and storage.
When I add extended resources like gpu in the resourceModels in the cluster like
```
  resourceModels:
  - grade: 0
    ranges:
    - max: "72"
      min: "0"
      name: cpu
    - max: 560Gi
      min: "0"
      name: memory
    - max: "0"
      min: "0"
      name: nvidia.com/gpu
    - max: "0"
      min: "0"
      name: myexample.com/gpu-v100
  - grade: 1
    ranges:
    - max: "96"
      min: "72"
      name: cpu
    - max: 1.6Ti
      min: 560Gi
      name: memory
    - max: "4"
      min: "0"
      name: nvidia.com/gpu
    - max: "4"
      min: "0"
      name: myexample.com/gpu-v100
```
I get
```
Unsupported value: "nvidia.com/gpu": supported values: "cpu", "ephemeral-storage", "memory", "storage"
```

My understanding is that [General Cluster Modeling](https://karmada.io/docs/userguide/scheduling/cluster-resources#general-cluster-modeling) use the resourceSummary to check the allocatable/allocated to schedule the pod.
But we also want to have GPU in [Customized Cluster Modeling](https://karmada.io/docs/userguide/scheduling/cluster-resources#customized-cluster-modeling), I don't think gpu will have the fragmentation issues like gpu/memory when using general cluster modeling, as ppl cannot claim partial gpu. But it would be still preferred to have extended resources in the customized cluster modeling just make it consistent with cluster  resources ?
I also run Karmada dashboard, it shows cpu, memory and storage. But it would be nice to show extended resources ?
**What do you think about this question?**:

**Environment**:
- Karmada version: latest
- Kubernetes version: 1.24
- Others:

**Comment by RainbowMango** [comment]
> Unsupported value: "nvidia.com/gpu": supported values: "cpu", "ephemeral-storage", "memory", "storage"

That's because the validation rules restrict the supported resources [here](https://github.com/karmada-io/karmada/blob/244c73c4e999978b046431ff4f85e3b85ec80790/pkg/apis/cluster/validation/validation.go#L195-L197). I might need to ask several questions when thinking if we can extend it for introducing another resource, like `nvidia.com/gpu`.

> I don't think gpu will have the fragmentation issues like gpu/memory when using general cluster modeling, as ppl cannot claim partial gpu. But it would be still preferred to have extended resources in the customized cluster modeling just make it consistent with cluster resources ?

I think the GPU also might have the fragmentation issue if you are saying [General Cluster Modeling](https://karmada.io/docs/userguide/scheduling/cluster-resources#general-cluster-modeling), for example, we have 3 nodes and each nodes has 1 GPU left, Karmada would think the cluster has 3 GPU, thus could assign a job that requires 2 or 3 GPU. Am I right?

**Comment by wengyao04** [comment]
Hi @RainbowMango:
You are right, we also have GUP fragmentation. In the example, we have 4 nodes and each nodes has 1 GPU left, if we require one master and one worker each of which requires 2 GPU, it won't work. It would be helpful to support extended resource in the the resouceModel

**Comment by RainbowMango** [comment]
Hi @wengyao04 I believe it's a reasonable feature. And I asked @chaosi-zju to help with this. He will sync the progress here.

**Comment by wengyao04** [comment]
Hi @chaosi-zju thank you for your demon in the community meetup. Do we have a nightly build version of Karmda schedule image and we can try it out on our platform ?

**Comment by RainbowMango** [comment]
I just talked to @chaosi-zju this morning, he will send the PR this week. Hopefully, it can be included in the coming v1.8 releases by the end of this month.

**Comment by chaosi-zju** [comment]
> Hi @chaosi-zju thank you for your demon in the community meetup. Do we have a nightly build version of Karmda schedule image and we can try it out on our platform ?

Hi @wengyao04, sorry for delay, I will submit the PR as soon as possible~

**Comment by RainbowMango** [comment]
Hi @wengyao04 This feature(#4307) has been merged, you can test it with the `latest` image now.
Thanks for spotting this, your feedback means a lot to the community.

This feature will be released in release-1.8 by the end of this month. If you want a preview release before the release, please feel free to let me know.

**Comment by wengyao04** [comment]
Hi @RainbowMango and @chaosi-zju Thank you very much to provide this feature ! We will sync the latest images and test it out

**Comment by wengyao04** [comment]
Hi @RainbowMango and @chaosi-zju we test out the latest image and it can categorize our gpu nodes correctly. But we find that the resoucesModel causes potential resources waste (underutilization) because the node is categorized also by the lowest resources. This resources underutilization is even worse if our cluster is mixed with gpu and cpu boxes. 

Let me give an simple example. Suppose there are 3 nodes in my cluster
- node 1: 72 CPUs, 512Gi Memory, 4 GPUs
- node 2: 72 CPUs, 512Gi Memory, 4 GPUs
- node 3: 72 CPUs, 512Gi Memory, 0 GPUs

If we define resoucesModel like the following. 
```
resourceModels:
- grade: 0
 ranges:
  - min: "0"
    max: "4"
    name: cpu
  - min: "0"
    max: 16Gi
    name: memory
  - min: "0"
    max: "1"
    name: nvidia.com/gpu
- grade: 1
  ranges:
  - min: "4"
    max: "16"
    name: cpu
  - min: 16Gi
    max: 128Gi
    name: memory
  - min: "1"
    max: "2"
    name: nvidia.com/gpu
- grade: 2
  ranges:
  - min: "16"
    max: "32"
    name: cpu
  - min: 128Gi
    max: 256Gi
    name: memory
  - min: "2"
    max: "3"
    name: nvidia.com/gpu
- grade: 3
  ranges:
  - min: "32"
    max: "48"
    name: cpu
  - min: 256Gi
    max: 384Gi
    name: memory
  - min: "3"
    max: "4"
    name: nvidia.com/gpu
- grade: 4
  ranges:
  - min: "48"
    max: "9223372036854775807"
    name: cpu
  - min: 384Gi
    max: "9223372036854775807"
    name: memory
  - min: "4"
    max: "9223372036854775807"
    name: nvidia.com/gpu
```
Then two gpu nodes are in grade 4 and the cpu node is in grade 0. If our two GPU nodes are fully occupied, and users submit a CPU workload requires 10 CPU and 100 Gi memory. This workload cannot be scheduled because the Karmada scheduler think the the cpu node is in grade 0 and don't have enough resources although the cluster summary shows there are enough allocatable resources.

I can put more cpu/memory in grade 0 and resources underutilization always exists. Could we have suggestion from the community to properly set the resourcesModel ?

Thank you !

**Comment by RainbowMango** [comment]
> Then two gpu nodes are in grade 4 and the cpu node is in grade 0.

I'm surprised that, given 72 CPUs on each node, I suppose the CPU node should be in grade `4` （[48, ~).
Can you share the status of the testing cluster? Including the resource module configuration in `.spec.resourceModels` and the `resourceSummary` in `.status.resourceSummary`?

**Comment by wengyao04** [comment]
Hi @RainbowMango In our real clusters we have total 6 nodes: 4 gpu and 2 cpu boxes, this is the summary from cluster status
```
  kubernetesVersion: v1.24.13
  nodeSummary:
    readyNum: 6
    totalNum: 6
  resourceSummary:
    allocatable:
      cpu: "432"
      ephemeral-storage: "16767979331679"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 3236824812Ki
      nvidia.com/gpu: "8"
      pods: "660"
      rdma/hca_shared_devices_a: "0"
    allocatableModelings:
    - count: 4
      grade: 0
    - count: 0
      grade: 1
    - count: 0
      grade: 2
    - count: 0
      grade: 3
    - count: 2
      grade: 4
    allocated:
      cpu: 51835m
      memory: 36420050Ki
      pods: "145"
```
The 4 CPU nodes are categorized at grade 0. I see you have this logic https://github.com/karmada-io/karmada/blob/master/pkg/modeling/modeling.go#L123 but cpu node always have GPU quantity 0 and cannot be categorized to other grade.

I can increase the grade 0 cpu/memory but it will cause GPU resource waste.
For a simple example if my resourcesModel is like
```
resourceModels:
- grade: 0
 ranges:
  - min: "0"
    max: "32"
    name: cpu
  - min: "0"
    max: 256Gi
    name: memory
  - min: "0"
    max: "1"
    name: nvidia.com/gpu
- grade: 1
  ranges:
  - min: "32"
    max: "40"
    name: cpu
  - min: 256Gi
    max: 320Gi
    name: memory
  - min: "1"
    max: "2"
    name: nvidia.com/gpu
- grade: 2
  ranges:
  - min: "40"
    max: "48"
    name: cpu
  - min: 320Gi
    max: 384Gi
    name: memory
  - min: "2"
    max: "3"
    name: nvidia.com/gpu
- grade: 3
  ranges:
  - min: "48"
    max: "56"
    name: cpu
  - min: 384Gi
    max: 464Gi
    name: memory
  - min: "3"
    max: "4"
    name: nvidia.com/gpu
- grade: 4
  ranges:
  - min: "56"
    max: "9223372036854775807"
    name: cpu
  - min: 464Gi
    max: "9223372036854775807"
    name: memory
  - min: "4"
    max: "9223372036854775807"
    name: nvidia.com/gpu
```
Then I will have 4 cpu nodes in grade 0 and 2 gpu nodes in grade 4
If I have two gpu workloads each of them using 1 GPU but 40 cpu and 260 Gi memory. Although each gpu node still have 3 GPUs, 32 cpu and 452 Gi memory, the gpu nodes is still categorized as grade 0 and cause gpu resource under utilization.
