### ISSUE TITLE
Schedule ingress resource to clusters with different GroupVersion.

### ISSUE THREAD

**Issue by cepaallium** [karmada-io/karmada#4081]
My Karmada Controller Plane has two member clusters, but have different k8s version. the first one has an ingress resource whose GroupVersion is extensions/v1beta1, and another one is networking.k8s.io/v1, How can i spreed one Ingress Object In My Karmada to the two member?

**Comment by cepaallium** [comment]
@calvin0327
@RainbowMango
thanks！

**Comment by liangyuanpeng** [comment]
@cepaallium  Try to match two version resource?

```yaml
  resourceSelectors:
    - apiVersion: extensions/v1beta1
      kind: XXX
      name: foo
      namespace: default
    - apiVersion: networking.k8s.io/v1
      kind: XXX
      name: foo
      namespace: default
```
