### ISSUE TITLE
upgrade karmada by operator error

### ISSUE THREAD

**Issue by MolisXYliu** [karmada-io/karmada#4083]
when i use this commad to upgrade karmada version in an offline env
````yaml
kubectl patch karmada karmada -n karmada-system --type merge -p '
{
  "spec": {
    "components": {
      "karmadaAggregatedAPIServer": {
	    "imageRepository": "harbor/karmada-aggregated-apiserver",
        "imageTag": "v1.7.0"
      },
      "karmadaControllerManager": {
		"imageRepository": "harbor/karmada-controller-manager",
        "imageTag": "v1.7.0"
      },
      "karmadaScheduler": {
		"imageRepository": "harbor/karmada-scheduler",
        "imageTag": "v1.7.0"
      },
      "karmadaWebhook": {
		"imageRepository": "harbor/karmada-webhook",
        "imageTag": "v1.7.0"
      }
    }
  }
}'
````
the cr condition is:
ditions:
  - lastTransitionTime: "2023-09-22T07:56:48Z"
    message: 'failed to install etcd component, err: error when creating etcd client
      service, err: Service "karmada-etcd" is invalid: metadata.resourceVersion: Invalid
      value: "": must be specified for an update'
    reason: Failed
