### ISSUE TITLE
When using karmada-operator, can I use loadbalancer type?

### ISSUE THREAD

**Issue by sykim-etri** [karmada-io/karmada#4099]
**Please provide an in-depth description of the question you have**:
I want to expose a karmada-apiserver by loadbalancer after deploying karmada-operator.
I succeeded to expose a karmada-apiserver by loadbalancer by using remote-up-karmada.sh.

I tried to create a karmada instance with following script, but it's not working.
```
kubectl create namespace test
kubectl apply -f - <<EOF
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada-demo
  namespace: test
spec:
  components:
    karmadaAPIServer:
      serviceType: LoadBalancer
EOF
```

Do you have a solution to do this?
**What do you think about this question?**:
I guess it's not implemented yet.

**Environment**:
- Karmada version: v1.7.0
- Kubernetes version: v1.27.3
- Others:
