### ISSUE TITLE
bug: workflow stays pending for a long time

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4137]
**What happened**:
The workflow creates deployment and HPA and they are propagated to member clusters. But it takes a long time pending. And I check the reason, find it's because deployment's `metadata.generation` != `status.observedGeneration`.

**What you expected to happen**:
`metadata.generation` == `status.observedGeneration`.

**How to reproduce it (as minimally and precisely as possible)**:
For reproduce the problem, your can do as follows:
1.Launch Karmada with `hack/local-up-karmada.sh`
2.Create `ResourceInterpreterCustomization`
  ```
  apiVersion: config.karmada.io/v1alpha1
  kind: ResourceInterpreterCustomization
  metadata:
    name: declarative-configuration-example
  spec:
    target:
      apiVersion: apps/v1
      kind: Deployment
    customizations:
      retention:
        luaScript: >
          function Retain(desiredObj, observedObj)
            desiredObj.spec.replicas = observedObj.spec.replicas
            return desiredObj
          end
  ```
3. Create PropagationPolicy
  ```yaml
  apiVersion: policy.karmada.io/v1alpha1
  kind: PropagationPolicy
  metadata:
    name: nginx-propagation
  spec:
    propagateDeps: true
    failover:
      application:
        decisionConditions:
          tolerationSeconds: 30
        gracePeriodSeconds: 30
        purgeMode: Graciously
    resourceSelectors:
      - apiVersion: apps/v1
        kind: Deployment
        name: nginx
    placement:
      clusterAffinity:
        clusterNames:
          - member1
      replicaScheduling:
        replicaDivisionPreference: Weighted
        replicaSchedulingType: Divided
        weightPreference:
          staticWeightList:
            - targetCluster:
                clusterNames:
                  - member1
              weight: 1
  ```
4.Create deployment
  ```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
  ```
5.Update deployment's replicas to 3 in member clusters(simulate HPA scales up)
6.Update deployment's replicas to 3 in karmada control plane(simulate hapreplicassyncer's behavior)

**Anything else we need to know?**:
none

**Environment**: Ubuntu 22.04
- Karmada version: master branch latest code
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): none
- Others: none
