### ISSUE TITLE
bug: cannot access ResourceRegistry  with its singularName

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#4141]
**What happened**:
when executing ```kubectl get ResourceRegistry``` will failed with ```doesn't have a resource type "ResourceRegistry"```, but executing ```kubectl get resourceregistries``` will success.
```bash
➜  /home export KUBECONFIG=~/.kube/karmada.config                                               
➜  /home ka get ResourceRegistry   
error: the server doesn't have a resource type "ResourceRegistry"
➜  /home ka get ResourceRegistries
NAME                CREATED AT
deployment-search   2023-09-28T03:07:10Z

```

**What you expected to happen**:
when executing ```kubectl get ResourceRegistry``` should also succeed.

**How to reproduce it (as minimally and precisely as possible)**:
For reproduce the problem, your can do as follows:
1.Launch Karmada with hack/local-up-karmada.sh
2.Create ResourceRegistry with command ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver create -f deployment-search.yaml```
```
### deployment-search.yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: deployment-search
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
```
3.Execute ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry```

**Anything else we need to know?**:
none
**Environment**: Ubuntu 22.04
- Karmada version: master branch latest code
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): none
- Others: none
