### ISSUE TITLE
test ReplicaSchedulingPolicy failed

### ISSUE THREAD

**Issue by teijinyer** [karmada-io/karmada#416]
**What happened**:
I use the replicasschedulingpolicy , but the deployment's replicas is error
```
# kubectl  get deploy 
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   6/3     6            6           63m
```
replicas is 3 in the member1 cluster 
replicas is 3 in the member2 cluster 
**What you expected to happen**:
replicas is 1 in the member1 cluster 
replicas is 2 in the member2 cluster 
**How to reproduce it (as minimally and precisely as possible)**:
deployment yaml 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```
propagationpolicy.yaml
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```
ReplicaSchedulingPolicy.yaml
```
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  totalReplicas: 3
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: 
          - member1
        weight: 1
      - targetCluster:
          clusterNames: 
          - member2
        weight: 2
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:  master branch .
- Others:
