### ISSUE TITLE
Multi-target ResourceInterpreterCustomization support

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#4195]
**What would you like to be added**:

allow ResourceInterpreterCustomization to target multiple resources

```
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-example
spec:
  targetSelector:
    apiVersion: *.custom.foo
    # no `kind`
```

**Why is this needed**:

Atm we plan to copy our ResourceInterpreterCustomization (that does "copy spec and status")
for every custom-resource that we have, it would be nice to make that generic so every newly added custom-resource "just works".

In case there are multiple RIC defined I'd suggest to trigger only the most specific (alternatively trigger all)

current RIC:
```
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: example
spec:
  target:
    apiVersion: foo.bar.com/v1alpha1
    kind: FooBar
  customizations:
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          desiredObj.spec = observedObj.spec
          desiredObj.status = observedObj.status
          return desiredObj
        end
```
