### ISSUE TITLE
Cannot scale deployment among clusters using "scheduler-estimator"

### ISSUE THREAD

**Issue by rostrzycki-7bc** [karmada-io/karmada#4216]
**What happened**:

I deployed Karmada on three local clusters on Minikube. I tried to test "cloud bursting" scenario, when one deployment is scaled out. I followed instructions placed on the page https://karmada.io/docs/userguide/scheduling/scheduler-estimator.
"Divided" "weighted" PODs allocation from one deployment worked ok (so I assume that Karmada was installed properly).

However, I noticed that when I deployed sample application with scale set to high value (3 or above), Karmada was not able to allocate PODs in any of available clusters managed by Karmada. But when I incrementally scaled deployment from 1 to N (in my case: 8), Karmada was able to properly allocate PODs. PODs were allocates at first on the 1st cluster, then (when resources on the 1st were exhausted) on the 2nd one.

The problem was that Karmada was not able to allocate any PODs when scale is set to final value (in my case 8).

There was a warning event reported by K8s: "ScheduledBindngFailed" from "default-scheduler" with message"failed to assign replicas: failed to scale up: Clusters available replicas 2 are not enough to schedule".

**What you expected to happen**:

I expected all PODs should have been created when I creaste deployment with set scale to 8.

**How to reproduce it (as minimally and precisely as possible)**:

Create K9s local clusters in one network:

> minikube start --cpus=2 --disk-size='10000mb' --memory='4gb' -p karmada-main --driver='kvm2' 
> minikube start --cpus=2 --disk-size='2000mb' --memory='2gb' -p karmada-local1 --driver='kvm2'
> minikube start --cpus=2 --disk-size='2000mb' --memory='2gb' -p karmada-local2 --driver='kvm2'
> 
> minikube addons enable metrics-server -p karmada-local1
> minikube addons enable metrics-server -p karmada-local2

Then initialize Karmada in the karmada-main and join karmada-local1 and karmada-local2 clusters.

Then apply this deloyemnt and placement using Karmada API:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-test-aggr
  labels:
    app: hello-test-aggr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-test-aggr
  template:
    metadata:
      labels:
        app: hello-test-aggr
    spec:
      containers:
      - image: nginxdemos/hello:plain-text
        name: hello-test-aggr
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 64Mi
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: hello-test-aggr-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: hello-test-aggr
  placement:
    clusterAffinity:
      clusterNames:
        - karmada-local1
        - karmada-local2
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided

```

**Anything else we need to know?**:

**Environment**:
- Karmada version: 
- kubectl-karmada or karmadactl version: v1.7.1
