### ISSUE TITLE
Add CRDs to describe Member-Clusters

### ISSUE THREAD

**Issue by maaft** [karmada-io/karmada#4248]
**What would you like to be added**:

CRD for Member-Cluster config so I can manage my member-clusters using GitOps.

**Why is this needed**:

Because bootstrapping a cluster without CRDs/GitOps currently involves too much manual invocations of karmada-cli.

**Comment by RainbowMango** [comment]
Can you explain in more detail what kind of CRD you want and how it be used by GitOps?

**Comment by maaft** [comment]
Oh, I realized that I didn't find the CRDs that I'm looking for because I interacted with my host-cluster and not with karmada-api-server.

To clarify, I was looking for
```yaml
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
  - karmada.io/cluster-controller
  generation: 3
  name: member1
spec:
  apiEndpoint: ...
```

With this I can now:
1. Add Karmada as Target-Cluster to ArgoCD in declarative way
2. Add member-clusters to karmada using argocd in host-cluster

Thanks anyway, and sorry for the confusion!
