### ISSUE TITLE
Job not propagated to member-cluster

### ISSUE THREAD

**Issue by maaft** [karmada-io/karmada#4255]
My job is not propgated to the member cluster.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: samples-tf-mnist-demo
  name: samples-tf-mnist-demo
spec:
  template:
    metadata:
      labels:
        app: samples-tf-mnist-demo
    spec:
      containers:
      - name: samples-tf-mnist-demo
        image: mcr.microsoft.com/azuredocs/samples-tf-mnist-demo:gpu
        args: ["--max_steps", "500"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           nvidia.com/gpu: 1
      restartPolicy: OnFailure
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
```

```yaml
---
# propagationpolicy.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy # The default namespace is `default`.
spec:
  resourceSelectors:
    - apiVersion: batch/v1
      kind: Job
      name: samples-tf-mnist-demo
      namespace: karmada-cluster
      # name: samples-tf-mnist-demo # If no namespace is specified, the namespace is inherited from the parent object scope.
```

Logs from controller-manager show:
```
I1116 10:34:44.689794       1 detector.go:904] PropagationPolicy(karmada-cluster/example-policy) has been added.
I1116 10:34:44.690099       1 detector.go:1148] Matched 0 resources by policy(karmada-cluster/example-policy)
```

But Job exists:
```shell
kubectl --kubeconfig karmadaconfig.yaml -n karmada-cluster get jobs.batch 
NAME                    COMPLETIONS   DURATION   AGE
samples-tf-mnist-demo   0/1                      42m
```

```shell
kubectl --kubeconfig karmadaconfig.yaml -n karmada-cluster get propagationpolicies.policy.karmada.io 
NAME              AGE
example-policy    32m
```
