### ISSUE TITLE
How to expose karmada api server via ingress?

### ISSUE THREAD

**Issue by maaft** [karmada-io/karmada#4256]
Basically title.

I tried the following:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: karmada-apiserver-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`<domain>`)
    kind: Rule
    services:
    - name: karmada-apiserver
      port: 5443
  tls:
    passthrough: true 
```
//kubeconfig
```yaml
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: <data>
      insecure-skip-tls-verify: false
      server: https://<domain>
    name: karmada-apiserver
```

```shell
kubectl --kubeconfig karmadaconfig.yaml -n karmada-cluster get pods
```

> certificate: x509: certificate is valid for kubernetes.default.svc, *.etcd.karmada-system.svc.cluster.local, *.karmada-system.svc.cluster.local, *.karmada-system.svc, localhost, not <domain>

when I change <domain> in kubeconfig to 127.0.0.1 and use `kubectl port-forward` to forward to api-server, everyhing works as expected.

Is there a setting to set extra SAN for Karmada API-Server?

Or am I doing something fundamentally wrong? I cannot quite believe that I'm the first person here to ask for an option how to setup additional SAN?

Reason for exposing is, that I need a public endpoint so I can register my member cluster in "Pull" mode. How else would this be possible? Docs do not mention how to expose apiserver correctly.
