### ISSUE TITLE
Support splitting hpa.spec.minReplicas when using the Divided replicaSchedulingType

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4258]
**What would you like to be added**:
Support splitting hpa.spec.minReplicas when using the Divided replicaSchedulingType

**Why is this needed**:
The scenario is as follows:
Users utilize K8s native HPA and PP to scale the deployment in member clusters. However, currently, Karmada only supports propagating the original minReplicas of HPA to member clusters, which leads to the following issue:
1. Users set minReplicas as 2.
2. The HPA and deployment are propagated to 4 clusters.
3. Despite no traffic, there are 8 replicas (2*4), whereas I desire it to be 2 (=minReplicas).

To address this problem, I request that Karmada support splitting hpa.spec.minReplicas when utilizing the Divided replicaSchedulingType.

By the way, it's fine to keep the original value for maxReplicas as it ensures that there are enough instances to handle actual traffic. However, keeping original minReplicas would result in wastage of resources.

**Comment by jwcesign** [comment]
/cc @chaunceyjiang @RainbowMango 

I configure the following ResourceInterpreterCustomization:
```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-hpa
spec:
  target:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
  customizations:
    replicaResource:
      luaScript: >
        function GetReplicas(obj)
          replica = obj.spec.minReplicas
          return replica, nil
        end
    replicaRevision:
      luaScript: >
        function ReviseReplica(obj, desiredReplica)
          obj.spec.minReplicas = desiredReplica
          return obj
        end
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      name: sample-app-hpa
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
          - targetCluster:
              clusterNames:
                - member3
            weight: 1
```

And it works perfectly:
![image](https://github.com/karmada-io/karmada/assets/19745536/8f788072-dfe7-4730-aba1-974f230608df)
