### ISSUE TITLE
After a resource is deleted, the resource fails to be delivered again. The work corresponding to the resource is not in the synchronization failure state.

### ISSUE THREAD

**Issue by CuiDengdeng** [karmada-io/karmada#4282]
**What happened**:
I created a service on the federation and successfully delivered a cluster. I limit the number of services in the default  namespace to 0. I deleted the service from the member cluster. Failed to deliver the service.
![image](https://github.com/karmada-io/karmada/assets/30014633/a5c766dc-abf1-4d16-9a7e-6f8be789bac6)

**What you expected to happen**:
Controller synchronization service status
**How to reproduce it (as minimally and precisely as possible)**:
Create a service on the federation and successfully delivered a cluster.
Occupy the port configured for the service
Delete the service from the cluster.
Failed to deliver the federated data again.
**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.8.0-preview1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaunceyjiang** [comment]
> Failed to deliver the federated data again.

What does this mean?

Do you mean that after deleting a successfully created `svc`, you cannot create another `svc` with the same name?

**Comment by CuiDengdeng** [comment]
When you delete the service of a member cluster, karmada's controller will re-deliver the service.

**Comment by RainbowMango** [comment]
> I limit the number of services in the default namespace to 0.

How did you do that? I don't understand how to limit the number of services, do you mean remove the service from Karmada control plane?

Question from the reproduce step:
> Delete the service from the cluster.

Do you mean delete the service from the member cluster, instead of remove from Karmada control plane?

Can you share more details about how to reproduce it? Such as provide some yamls and command you run?

**Comment by RainbowMango** [comment]
I talked to @CuiDengdeng to clarify the issue:

**How to reproduce it?**
1. Propagate a Service to a cluster by `PropagationPolicy`:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    foo: bar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```

This works well, and the service status will be collected to ResourceBinding:
```yaml
status:
  aggregatedStatus:
  - applied: true
    clusterName: member1
    health: Unhealthy
    status:
      loadBalancer: {}  // No loadBalancer IP in this example as there is no ELB on my Machine.
```

In @CuiDengdeng case, he will get the loadBalancer IP from ResourceBinding and register to an ELB server.

2. Apply a ResourceQuota to `member1`, to limit the Service count to `0`:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    services: "0"
```
With this ResourceQuota, you can't create any more Services.

3. Delete the Service from `member1`:
```bash
-bash-5.0# kubectl delete service my-service 
service "my-service" deleted
```
After the service is deleted , the `work status controller` will try to `recreate` the Service, but failed due to exceed quota:
```
I1128 07:15:55.143691       1 work_status_controller.go:293] recreating cluster=member1, v1, kind=Service, default/my-service
E1128 07:15:55.157459       1 objectwatcher.go:103] Failed to create resource(kind=Service, default/my-service) in cluster member1, err is services "my-service" is forbidden: exceeded quota: compute-resources, requested: services=1, used: services=1, limited: services=0
```

**What happened:**

This issue that @CuiDengdeng is trying to tell us is the status in ResourceBinding not reflect the real status:
```yaml
  aggregatedStatus:
  - applied: true
    clusterName: member1
    health: Unhealthy
    status:
      loadBalancer: {}
```
