### ISSUE TITLE
OverridePolicy 和 ClusterOverridePolicy的ImageOverrider无法覆盖到Deployment的initContainers容器

### ISSUE THREAD

**Issue by 370569218** [karmada-io/karmada#4283]
版本：v1.7
覆盖策略
OverridePolicy 和 ClusterOverridePolicy的ImageOverrider无法覆盖到Deployment的initContainers容器

**Comment by RainbowMango** [comment]
This might be a known issue. cc @chaunceyjiang for confirmation.

**Comment by chaunceyjiang** [comment]
By default, ImageOverrider is not supported, but we can customize ImageOverrider to make it supported.

```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: example
spec:
  #...
  overrideRules:
    - overriders:
        imageOverrider:
          - component: Registry
            predicate: /spec/template/spec/initContainers/<N>/image
            operator: add
            value: test-repo

```
