### ISSUE TITLE
Job always scheduled on first cluster although resources are exhausted

### ISSUE THREAD

**Issue by maaft** [karmada-io/karmada#4284]
**What happened**:

I have two member clusters:
1. `on-prem`: cluster with 1 GPU node
2. `cloud`: cluster with 0 GPU node (but auto-scaling enabled -> scheduling here will spawn a new GPU node)
3. I scheduled a job that successfully run on `on-prem` cluster.
4. I scheduled another job. This also gets scheduled to `on-prem`. Now the 2nd job is in `Pending` state (until completion of the first)
5. `cloud` cluster will **never** receive any work

This is my job I want to schedule:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: samples-tf-mnist-demo
  name: samples-tf-mnist-demo
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: samples-tf-mnist-demo
    spec:
      containers:
      - name: samples-tf-mnist-demo
        image: mcr.microsoft.com/azuredocs/samples-tf-mnist-demo:gpu
        args: ["--max_steps", "500"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           nvidia.com/gpu: 1
      restartPolicy: OnFailure
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
```

Here is my propagation policy:
```yaml
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: batch/v1
      kind: Job
      namespace: default
  placement:
    clusterAffinities:
    - affinityName: on-prem
      clusterNames:
        - on-prem
    - affinityName: cloud
      clusterNames:
        - cloud
```

**What you expected to happen**:

The first scheduling of this Job allocates a GPU on `on-prem` cluster and the pod runs until completion.
Therefore, the `on-prem` cluster is (in theory) now full and cannot accept more work.
If I now schedule the Job a 2nd time, I'd expect that Karmada also tries the 2nd cluster for scheduling (and waits for fulfillment).

**How to reproduce it (as minimally and precisely as possible)**:
1. have 2 member clusters, one with fixed number of GPUs, another with auto-scalable GPUs.
2. schedule aboves job two times
3. job will be scheduled both times on `on-prem` cluster and will remain in `Pending` state until the first job completes
4. succeeding jobs will **never** be scheduled on `cloud` cluster

Am I missing something?
