### ISSUE TITLE
PropagateDeps does not propagate Service

### ISSUE THREAD

**Issue by lorenzogio97** [karmada-io/karmada#4285]
**What happened**:
When I try to use application Failover (https://karmada.io/docs/userguide/failover/application-failover), using `propagateDeps: true`, the Service related to the Deployment is not migrated on the new cluster. Without Service, application on Destination node cannot be used correctly.

**What you expected to happen**:
To propagate to the other cluster all resources in specified in the same PropagationPolicy of the Deployment. 

**How to reproduce it (as minimally and precisely as possible)**:
Follow this guide (https://karmada.io/docs/userguide/failover/application-failover/#example), but put a also a Service for that nginx Deployment. Put the Service resource inside the same propagationPolicy. Cordon and delete the pod and wait for `tolerationSeconds`. 
At this moment, Deployment should be moved to another cluster, but the related Service remain on the old cluster. 

**Anything else we need to know?**:
I have tried with config map (not mounted in the Deployment, just added to the same PropagationPolicy) and I obtain the same behaviour. 

**Environment**:
- Karmada version: 1.7.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by whitewindmills** [comment]
Only the Configmap, Secret, ServiceAccount and PersistentVolumeClaim used by the Deployment will be propagated along with the Deployment. You can implement the `InterpretDependency` interface instead of specifying dependent resources in the PropagationPolicy to achieve this goal. More info: https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter/#declarative-configuration

**Comment by chaunceyjiang** [comment]
Here is an example for reference.

https://github.com/karmada-io/karmada/pull/3811#issuecomment-1670766563

**Comment by lorenzogio97** [comment]
> Here is an example for reference.
> 
> [#3811 (comment)](https://github.com/karmada-io/karmada/pull/3811#issuecomment-1670766563)

This example, changing only the target cluster, does not work. I would to propagate together all resources that has a specific label, regardless of apiVersion or Kind. In case a resource is necessary for more than one deployment, the ideal is to replicate it where the related Deployments are.

**Comment by lorenzogio97** [comment]
> Only the Configmap, Secret, ServiceAccount and PersistentVolumeClaim used by the Deployment will be propagated along with the Deployment. You can implement the `InterpretDependency` interface instead of specifying dependent resources in the PropagationPolicy to achieve this goal. More info: https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter/#declarative-configuration

Thank you for the reply. I didn't understand well how to select the object I want to propagate. I have to specify all object values, or I can leave some property empty? For example: given the example: 
```
    dependencyInterpretation:
      luaScript: >
        function GetDependencies(desiredObj)
          dependentSas = {}
          refs = {}
          if desiredObj.spec.template.spec.serviceAccountName ~= '' and desiredObj.spec.template.spec.serviceAccountName ~= 'default' then
            dependentSas[desiredObj.spec.template.spec.serviceAccountName] = true
          end
          local idx = 1
          for key, value in pairs(dependentSas) do
            dependObj = {}
            dependObj.apiVersion = 'v1'
            dependObj.kind = 'ServiceAccount'
            dependObj.name = key
            dependObj.namespace = desiredObj.metadata.namespace
            refs[idx] = dependObj
            idx = idx + 1
          end
          return refs
        end
```
 It there any documentation related to dependObj object? How does it should be made? For example, if I want to match all resources that have a specific label, but I don't want to specify kind (I want to match all kinds), is it technically possible?

**Comment by chaunceyjiang** [comment]
> It there any documentation related to dependObj object?

https://github.com/karmada-io/karmada/blob/master/pkg/apis/config/v1alpha1/interpretercontext_types.go#L155-L181

**Comment by chaunceyjiang** [comment]
> What you expected to happen:
To propagate to the other cluster all resources in specified in the same PropagationPolicy of the Deployment.

You can write all your resources into a single PropagationPolicy.

**Comment by chaunceyjiang** [comment]
> Follow this guide (https://karmada.io/docs/userguide/failover/application-failover/#example), but put a also a Service for that nginx Deployment. Put the Service resource inside the same propagationPolicy. Cordon and delete the pod and wait for tolerationSeconds.
At this moment, Deployment should be moved to another cluster, but the related Service remain on the old cluster.

Can you share your PropagationPolicy?

**Comment by lorenzogio97** [comment]
``> > Follow this guide (https://karmada.io/docs/userguide/failover/application-failover/#example), but put a also a Service for that nginx Deployment. Put the Service resource inside the same propagationPolicy. Cordon and delete the pod and wait for tolerationSeconds.
> > At this moment, Deployment should be moved to another cluster, but the related Service remain on the old cluster.
> 
> Can you share your PropagationPolicy?

Sure, no problem! In this moment I changed it to match the one proposed [here ](https://github.com/karmada-io/karmada/pull/3811#issuecomment-1670766563)(but, as I wrote, still not work). This is previous version, I put also service into the same PropagationPolicy but still not work.

```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: nginx-propagation
spec:
  propagateDeps: true
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 10
      purgeMode: Graciously
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: nginx-service
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          dr: ok
  placement:
    clusterAffinities:
    - affinityName: primary-clusters
      clusterNames:
        - service-a
    - affinityName: backup-clusters
      clusterNames:
        - service-b
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 0
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    dr: ok
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
```

**Comment by chaunceyjiang** [comment]
/assign 

I will research this issue.

**Comment by lorenzogio97** [comment]
> Only the Configmap, Secret, ServiceAccount and PersistentVolumeClaim used by the Deployment will be propagated along with the Deployment. You can implement the `InterpretDependency` interface instead of specifying dependent resources in the PropagationPolicy to achieve this goal. More info: https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter/#declarative-configuration

I have made other tests: even if I do not reimplement `InterpretDependency`, ConfigMaps are not propagated with the corresponding Deployment. This is the resources I used for this test:

**Comment by chaunceyjiang** [comment]
Your question is: When the cluster `service-A` goes down, the Deployment migrated to `service-B`, but the resources it depends on do not migrate to `service-B` (sa, cm, svc...), right? @lorenzogio97

**Comment by lorenzogio97** [comment]
> Your question is: When the cluster `service-A` goes down, the Deployment migrated to `service-B`, but the resources it depends on do not migrate to `service-B` (sa, cm, svc...), right? @lorenzogio97

Exactly. But the last test I made is not related to migration and fail over, it's simply the propagation. If I propagate the Deployment, even if I set the `propagateDeps: true`, cm is not propagated as it should be.

**Comment by chaunceyjiang** [comment]
> Exactly. But the last test I made is not related to migration and fail over, it's simply the propagation. If I propagate the Deployment, even if I set the propagateDeps: true, cm is not propagated as it should be.

Ah? The cm is also not in the `service-A` cluster ?

Can you upload the log of karmada-scheduler?


```
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap1
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>This is Deployment One</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-index-file-1
              mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index-file-1
        configMap:
          name: html-configmap1
          items: 
            - key: index.html
              path: index.html
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: nginx1-propagation
spec:
  propagateDeps: true
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 10 
      purgeMode: Graciously
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx1
  placement:
    clusterAffinities:
    - affinityName: primary-clusters
      clusterNames:
        - service-A
    - affinityName: backup-clusters
      clusterNames:
        - service-B
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 0
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 0
```


I tested this scenario, cm can be normally propagated to `service-A`. When nginx1 fails, cm is also being migrated to `service-B`.
