### ISSUE TITLE
My test deplolyment is only propagated to the first cluster.

### ISSUE THREAD

**Issue by icy** [karmada-io/karmada#4325]
**Please provide an in-depth description of the question you have**:

I have a simple test-deployment, with the following `ClusterPropagation` policy. My expection is to have a duplication of the deployment on both clusters. However, only can I see the deployment on the first cluster `staging-sg`. Nothing would happen on the other cluster `dr3c1`

```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: cluster-propagation-test2
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
      - dr3c1
      - staging-sg
    replicaScheduling:
      replicaSchedulingType: Duplicated
      weightPreference: {}
  propagateDeps: true

---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterOverridePolicy
metadata:
  name: override-test2
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
  overrideRules:
  - targetCluster:
      clusterNames:
      - dr3c1
    overriders:
      plaintext:
      - operator: replace
        value: 0
        path: /spec/replicas

```

**What do you think about this question?**:

**Environment**:   `dr3c1` is the host cluster of `karmada` control plane, aka the `karmada` services are installed within namespace `karmada-system` from the original cluster `dr3c1`.

- Karmada version: installed from helm-chart, with source tree is `v1.7.1`
- Kubernetes version: `dr3c1        v1.25.12   Push   True` and  `staging-sg   v1.23.4    Push   True`
- Others: Before getting into this issue, I used promote function to propagate the existing testdeployment from `staging-sg` to both clusters and that was working well. Then I deleted all deployments and policies. Then I create new deployment within `karmada` system.
