### ISSUE TITLE
istio crd无法下发到member集群

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4426]
准备certs

```
kubectl create namespace istio-system --kubeconfig ~/kube-karmada
kubectl create secret generic cacerts  --kubeconfig ~/kube-karmada -n istio-system \
    --from-file=certs/primary/ca-cert.pem \
    --from-file=certs/primary/ca-key.pem \
    --from-file=certs/primary/root-cert.pem \
    --from-file=certs/primary/cert-chain.pem
```

```
cat <<EOF | kubectl apply --kubeconfig ~/kube-karmada -f -
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: cacerts-propagation
  namespace: istio-system
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      name: cacerts
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
EOF
```

在karmada安装crd

```
kubectl apply -f istio-crd-all.gen.yaml --kubeconfig ~/kube-karmada
```

集群1部署文件

```
cat <<EOF > cluster1.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
EOF

```

部署集群1

```
istioctl install  -f cluster1.yaml --set profile=demo  --kubeconfig ~/.kube/182config
```

集群2部署文件

```
cat <<EOF > cluster2.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network1
EOF
```

部署集群2

```
istioctl install  -f cluster2.yaml --set profile=demo --kubeconfig ~/.kube/185config

```

启用端点发现

```
 istioctl create-remote-secret \
    --context=cluster2 \
    --name=cluster1 | \
    kubectl apply -f - --context=cluster3
```

```
istioctl create-remote-secret \
    --context=cluster3 \
    --name=cluster2 | \
    kubectl apply -f - --context=cluster2

```

## 

```
kubectl create namespace istio --kubeconfig ~/kube-karmada

kubectl label namespace istio istio-injection=enabled --kubeconfig ~/kube-karmada
```

```
kubectl apply -f bookinfo.yaml -n istio --kubeconfig ~/kube-karmada
```

bookinfo-pp.yaml

kubectl apply -f bookinfo-pp.yaml -n istio --kubeconfig ~/kube-karmada

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: service-propagation
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: productpage
    - apiVersion: v1
      kind: Service
      name: details
    - apiVersion: v1
      kind: Service
      name: reviews
    - apiVersion: v1
      kind: Service
      name: ratings
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: produtpage-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: productpage-v1
    - apiVersion: v1
      kind: ServiceAccount
      name: bookinfo-productpage
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: details-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: details-v1

    - apiVersion: v1
      kind: ServiceAccount
      name: bookinfo-details
  placement:
    clusterAffinity:
      clusterNames:
        - cluster2
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: reviews-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: reviews-v1
    - apiVersion: apps/v1
      kind: Deployment
      name: reviews-v2
    - apiVersion: apps/v1
      kind: Deployment
      name: reviews-v3
    - apiVersion: v1
      kind: ServiceAccount
      name: bookinfo-reviews
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: ratings-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: ratings-v1
    - apiVersion: v1
      kind: ServiceAccount
      name: bookinfo-ratings
  placement:
    clusterAffinity:
      clusterNames:
        - cluster2
```

host：

```
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml  -n istio --kubeconfig ~/kube-karmada
```

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

kubectl apply -f gw-vs-propagation.yaml -n istio --kubeconfig ~/kube-karmada

gw-vs-propagation.yaml

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: gw-vs-propagation
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      name: bookinfo-gateway
    - apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      name: bookinfo
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
