### ISSUE TITLE
The service can't be propagated to the newly joined cluster  if the cluster is unjoined 1 minute agao

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4430]
**What happened**:
1.Launch Karmada with hack/local-up-karmada.sh
2.Deploying multiclusterservice with the following yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 81
    targetPort: 8080
  selector:
    app: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mci-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
---
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
   name: nginx
spec:
  types:
    - CrossCluster
```
3.Check service
![image](https://github.com/karmada-io/karmada/assets/19745536/b6b0f034-3edf-412f-a3f4-cedd303ff25c)

They are propagated to member clusters.

4.Unjoin cluster member2

cluster_controller.go will add following taints to cluster object.
```yaml
      min: 1Ti
      name: memory
  secretRef:
    name: member2
    namespace: karmada-cluster
  syncMode: Push
  taints:
  - effect: NoExecute
    key: cluster.karmada.io/terminating
    timeAdded: "2023-12-15T07:09:41Z"
status:
  apiEnablements:
  - groupVersion: admissionregistration.k8s.io/v1
```

5.The taint manager will add EvicationTask to RB.
![image](https://github.com/karmada-io/karmada/assets/19745536/2d39f15d-b65e-4503-8a9a-c5951b2654bf)

6.The gracefulevication controller could not parse the service's health status, the EvicationTask will be kept for 10min.
https://github.com/karmada-io/karmada/blob/31b83d14e4067352a99d225c0b27989378f5cb6e/pkg/controllers/gracefuleviction/evictiontask.go#L112

7.When the member2 cluster joins again, the scheduler will filter it out because of EvicationTask.

**What you expected to happen**:
The service will be propagated to member2 cluster

**How to reproduce it (as minimally and precisely as possible)**:
As described before

**Anything else we need to know?**:
None

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
