### ISSUE TITLE
A deploy with a GPU request can still be deployed to a cluster without a GPU.

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#4435]
**What would you like to be added**:

I hope that a deployment with GPU resources can only be deployed to member clusters with GPU nodes.

**Why is this needed**:

A deployment with a GPU request cannot start normally on a cluster without GPU nodes.

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/issues/3318

Perhaps we can filter out clusters without GPU nodes at the `preFilter` stage.

**Comment by chaosi-zju** [comment]
I have tested and confirmed as a problem.

besides, you gave a good scenario for #3318

**Comment by tedli** [comment]
Hi all,

FYI,

We met the same problem.

https://github.com/karmada-io/karmada/blob/7395a8bdf5e6ef934c49358b0536edbd0f794f34/pkg/util/resource.go#L52-L73

tried to make line `68` `lifted.IsScalarResourceName(rName)` happy, can fix this issue.

**Comment by chaunceyjiang** [comment]
Hi, @tedli Can you attend the meeting tomorrow afternoon (December 19th, at 2:30 PM)? I hope to discuss the current issue with you.

**Comment by tedli** [comment]
Hi @chaunceyjiang ,
I will be there until 3:00 PM, unfortunately after 3:00, there is another meeting that I have to attend.

**Comment by RainbowMango** [comment]
@zhzhuang-zju can you help to double confirm if this issue still exists? And try to dig into the root cause?

**Comment by zhzhuang-zju** [comment]
I just did a local deployment test, and the results depend on the `replicaScheduling` configuration:
- if the `replicaScheduling` configuration is 
```yaml
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
```
results: Deployment `device-plugin` will be propagated to `member1` and `member2`, even none of them has GPU nodes.
```yaml
  clusters:
  - name: member1
    replicas: 1
  - name: member2
    replicas: 1
```

- if the `replicaScheduling` configuration is 
```yaml
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
```
results: Karmada scheduler failed to assign replicas of the Deployment `device-plugin`.
```yaml
status:
  conditions:
  - lastTransitionTime: "2025-12-04T08:45:16Z"
    message: 'failed to assign replicas: failed to scale up: Clusters available replicas
      0 are not enough to schedule.'
    reason: SchedulerError
    status: "False"
    type: Scheduled
```

**root cause**: Actually, this is because the two `replicaScheduling` configurations have different semantics: the former is recognized as `staticWeight` and ignores available resource calculation during `assignReplicas`, while the latter is recognized as `dynamicWeight` and takes available resources into account during `assignReplicas`. I believe this behavior is expected.

WDYT? @RainbowMango @chaunceyjiang
