### ISSUE TITLE
apply CloneSet  yaml : Internal error occurred: failed calling webhook "mcloneset.kb.io": could not get REST client: unable to load root certificates: unable to parse bytes as PEM block

### ISSUE THREAD

**Issue by linuxme** [karmada-io/karmada#4439]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
1. helm --kubeconfig /etc/karmada/karmada-apiserver.config  install kruise kruise
2. test.yaml
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      volumes:
        - name: configmap
          configMap:
            name: my-sample-config
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-sample-config
data:
  nginx.properties: |
    proxy-connect-timeout: "10s"
    proxy-read-timeout: "10s"
    client-max-body-size: "2m"
```
3. kubectl --kubeconfig /etc/karmada/karmada-apiserver.config apply -f test.yaml
but, error:
```
configmap/my-sample-config created
**Error from server (InternalError): error when creating "test.yaml": Internal error occurred: failed calling webhook "mcloneset.kb.io": could not get REST client: unable to load root certificates: unable to parse bytes as PEM block**
```

4. kubectl --kubeconfig /etc/karmada/karmada-apiserver.config -n kruise-system get pod
No resources found in kruise-system namespace.

5. kubectl --kubeconfig /etc/karmada/karmada-apiserver.config -n kruise-system get svc
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kruise-webhook-service   ClusterIP   10.103.163.247   <none>        443/TCP   27m

"Also installed the OpenKruise CRD, why am I encountering errors when deploying CloneSet YAML resources? Could someone please help me take a look? Thank you!"

**Environment**:
- Karmada version: v1.8
- Kubernetes version: 1.26.5
- Others: openKruise 1.5.0
