### ISSUE TITLE
1.4更新到1.5报错

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4488]
![image](https://github.com/karmada-io/karmada/assets/31508490/cccf949d-93a6-4ffb-ae68-9bab5ea4044f)
rb没有生成placement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by 13567436138** [comment]
```
root@karmada-01-b:~/karmada-teaching/propagationPolicy# cat pp-1.5-placement.yam 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinities:
    - clusterNames:
        - cluster1
        - cluster2
root@karmada-01-b:~/karmada-teaching/propagationPolicy# cat nginx-deploy.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```
这是执行的源码
