### ISSUE TITLE
Status.apiEnablements.resources invalid when join member cluster

### ISSUE THREAD

**Issue by lfbear** [karmada-io/karmada#450]
**What happened**:
When I joined a member cluster in karmada with `karmadactl join`, I got a dead member cluster like this:
```
NAME     VERSION            MODE   READY   AGE
member1                     Push          2m16s
```
I can't send any workload to this member cluster and the logs in karmada-controller-manager said:
```
E0618 08:23:34.449058       1 cluster_status_controller.go:179] Failed to update health status of the member cluster: member1, err is : Cluster.cluster.karmada.io "member1" is invalid: status.apiEnablements.resources: Invalid value: "null": status.apiEnablements.resources in body must be of type array: "null"
```
**What you expected to happen**:

member cluster status will appear, the workload will be sent to the member cluster

**How to reproduce it (as minimally and precisely as possible)**:

the member cluster has a kind of resource that is empty `APIResources` in `APIResourceList`, such as this:
```
v1.APIResourceList{
  TypeMeta: v1.TypeMeta{
    Kind:       "APIResourceList",
    APIVersion: "v1",
  },
  GroupVersion: "external.metrics.k8s.io/v1beta1",
  APIResources: []v1.APIResource{},
}
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:  v0.6.0
- Others:  Karmada API Server in a standalone cluster v1.18.8 and member too

**Comment by lfbear** [comment]
https://github.com/karmada-io/karmada/blob/3f99da3024cd63cd5cec3c43cd782b37d30a96fa/pkg/controllers/status/cluster_status_controller.go#L329-L333

I traced code and find `apiResource` may be equal `nil` when APIResources is empty, so I suggest replacing Line 329 with `apiResource := make([]string,0)` that is a 0-length slice and no longer equal `nil`. 
If it's workable I will submit a PR

**Comment by XiShanYongYe-Chang** [comment]
Further, apply for fixed capacity in advance，because the length of `list.APIResources` is known. 

Modify like this: `apiResource := make([]string, 0, len(list.APIResources))`

**Comment by RainbowMango** [comment]
I see. This should be fixed.
/assign @lfbear 

>  so I suggest replacing Line 329 with apiResource := make([]string,0) that is a 0-length slice and no longer equal nil.

This will work. We've another idea.
The [Resources](https://github.com/karmada-io/karmada/blob/3f99da3024cd63cd5cec3c43cd782b37d30a96fa/pkg/apis/cluster/v1alpha1/types.go#L142) should not be a `mandatory` field.

**Comment by RainbowMango** [comment]
I reproduced on my side:

1. Create an `APIService` object as follows:
```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.3.0
  name: v1beta1.external.metrics.k8s.io
spec:
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: keda-metrics-apiserver
    namespace: keda
  version: v1beta1
  versionPriority: 100
```
This might happen if people installed `KEDA` in the member cluster, more details please refer to [Deploying using the deployment YAML files](https://keda.sh/docs/2.3/deploy/#yaml)

2. Wait for a while the log will present at `karmada-controller-manager`(for push mode) or `karmada-agent`(for pull mode).
```
I0621 06:47:26.442159       1 cluster_status_controller.go:195] Start to update cluster status: member3
E0621 06:47:26.451379       1 cluster_status_controller.go:199] Failed to update health status of the member cluster: member3, err is : Cluster.cluster.karmada.io "member3" is invalid: status.apiEnablements.resources: Invalid value: "null": status.apiEnablements.resources in body must be of type array: "null"
```
As meanwhile, you can check the resource list by:
```
# kubectl get --raw=/apis/external.metrics.k8s.io/v1beta1 
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"external.metrics.k8s.io/v1beta1","resources":[]}
```
There are no `resources` in the `external.metrics.k8s.io/v1beta1` group.
