### ISSUE TITLE
labels not cleaned when updating ResourceTemplate which resulting in it no longer match a Policy

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4516]
**What happened**:

When updating ResourceTemplate and which result in it no longer match a Policy, the corresponding behavior should be consistent with the behavior of deleting the policy, like deleting the label `propagationpolicy.karmada.io/name: xxx` from ResourceTemplate. But the actual corresponding label has not been deleted.

**What you expected to happen**:

the label `propagationpolicy.karmada.io/name: xxx` should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

1. write a deployment (pay attention to it has two labels):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    region: cn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            limits:
              cpu: 25m
              memory: 64Mi
```

2. write two policy:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-pp
spec:
  priority: 2
  placement:
    clusterAffinity:
      clusterNames:
        - member1
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-pp2
spec:
  priority: 1
  placement:
    clusterAffinity:
      clusterNames:
        - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          region: cn
```

3. remove the label `app: nginx` in `Deployment/nginx`, it will no longer match `nginx-pp`:
    * we should remove the label `propagationpolicy.karmada.io/name: nginx-pp` from `Deployment/nginx`, but it doesn't.
    * the `Deployment/nginx` should be propagated by `nginx-pp2`, but it doesn't.

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
