### ISSUE TITLE
Can't re-schedule the replicas to new clusters within updating PP

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4560]
**What happened**:
1. Create following PP and Deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
```
2. The 2 replicas will be launched in member1
3. Update PP, and change member1 to member2
```yaml
...
  placement:
    clusterAffinity:
      clusterNames:
      - member2
...
```
4. The replicas are not launch in member2 cluster
```sh
root@karmada [02:14:19 PM] [~/workspace/git/karmada/samples/nginx] [master *]
-> # karmadactl get po
NAME                     CLUSTER   READY   STATUS    RESTARTS   AGE
nginx-77b4fdf86c-t9z5h   member1   1/1     Running   0          143m
nginx-77b4fdf86c-vtztd   member1   1/1     Running   0          143m
```

**What you expected to happen**:

The replicas in member1 will be deleted and relaunched in member2

**How to reproduce it (as minimally and precisely as possible)**:

as described before

**Anything else we need to know?**:

Related code: https://github.com/karmada-io/karmada/blame/0e501b607a95bccf909efcaef95a694244ef4feb/pkg/scheduler/core/assignment.go#L166

**Environment**:
- Karmada version: master branch
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): master branch
- Others:none
