### ISSUE TITLE
1.8多clusterAffinities，前面集群资源不足，不会调度到后面集群

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4569]
nginx-deploy.yaml

kubectl apply -f nginx-deploy.yaml -n karmada --kubeconfig ~/kube-karmada

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 0.1
            memory: 200Mi
```

pp-nginx.yaml

kubectl apply -f pp-nginx.yaml -n karmada --kubeconfig ~/kube-karmada

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinities:
      - affinityName: local-clusters
        clusterNames:
          - cluster1
          - cluster2
      - affinityName: cloud-clusters
        clusterNames:
          - cluster3
```

集群做了cordon
```
root@karmada-03-a:~# kubectl get node
NAME                 STATUS                        ROLES        AGE   VERSION
karmada-03-edge-01   NotReady,SchedulingDisabled   agent,edge   5d    v1.24.17-kubeedge-v1.14.4
master-01            Ready,SchedulingDisabled      master       43d   v1.28.1
worker-01            Ready,SchedulingDisabled      node         43d   v1.28.1
worker-02            Ready,SchedulingDisabled      node         43d   v1.28.1
worker-03            Ready                         <none>       31d   v1.28.1
```

```
root@karmada-03-a:~# kubectl get pod -n karmada 
NAME                    READY   STATUS    RESTARTS   AGE
nginx-7bf7d798d-8t5r8   0/1     Pending   0          25s
nginx-7bf7d798d-b6nvj   1/1     Running   0          25s
nginx-7bf7d798d-d7pzn   1/1     Running   0          26s
nginx-7bf7d798d-wcfp5   1/1     Running   0          25s
nginx-7bf7d798d-zx8tv   1/1     Running   0          25s
```
有pending的pod，说明资源是不足的，在考虑资源是否充足有没有考虑节点是不可调度的

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by zhzhuang-zju** [comment]
Thank you for your question. Following your reproduction method, I have also discovered the same phenomenon.
refer to https://github.com/karmada-io/karmada/blob/4ddc87a85704fe8613f047202778e3c9dc96f624/pkg/scheduler/scheduler.go#L502-L510
When Karmada schedules with ClusterAffinities, it will iterate and execute `s.Algorithm.Schedule` until this method does not throw an error.
refer to https://github.com/karmada-io/karmada/blob/4ddc87a85704fe8613f047202778e3c9dc96f624/pkg/scheduler/core/generic_scheduler.go#L131-L142
Function `s.Algorithm.Schedule` will run different filter plugins to filter clusters, but currently there is no support for filtering by cluster resources.

**Comment by zhzhuang-zju** [comment]
@13567436138 The above question can actually be divided into two parts:
- The schedule depends on available resources.

If we want to use this capability, we need to install component `karmada-scheduler-estimator` and configure pp properly, like
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
    spreadConstraints:
      - spreadByField: cluster
        maxGroups: 1
        minGroups: 1
    clusterAffinities:
      - affinityName: local-clusters
        clusterNames:
          - cluster1
          - cluster2
      - affinityName: cloud-clusters
        clusterNames:
          - cluster3
```
After this configuration, when clusterAffinity `local-clusters` does not have enough resources, it will cause function `s.Algorithm.Schedule` to fail and then be scheduled to the next clusterAffinity.
- Will the availability of nodes be taken into account when calculating available resources?

Through experiments, `SchedulerEstimator` sets the available replica count of unschedulable nodes to 0 when calculating. So, the availability of nodes will be taken into account when calculating available resources.
refer to https://github.com/karmada-io/karmada/blob/d508417a1e9b6be048a181ae89adbb94e1b08fbb/pkg/estimator/server/estimate.go#L81-L88 confirmed this point.
