### ISSUE TITLE
Lazy CPP takes effect immediately when propagating into two clusters and changing weights of two cluster

### ISSUE THREAD

**Issue by wm775825** [karmada-io/karmada#4587]
**What happened**:

First, we create a CPP according the following YAML:

```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: demo-cpp
spec:
  activationPreference: Lazy
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
  priority: 0
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
      - ucs-pytest-cce-003
      - ucs-pytest-cce-004
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
        - targetCluster: # 目标集群
            clusterNames:
             - ucs-pytest-cce-003
          weight: 3
        - targetCluster: # 目标集群
            clusterNames:
             - ucs-pytest-cce-004
          weight: 1
    clusterTolerations:
    - key: cluster.karmada.io/not-ready
      operator: Exists
      effect: NoExecute
    - key: cluster.karmada.io/unreachable
      operator: Exists
      effect: NoExecute
```

Then, we create a deployment.
```
kubectl create deploy my-deploy --replicas=4 --image=nginx
```

As you can see, there are three pods in ucs-pytest-cce-003 and one pod in ucs-pytest-cce-004, which meets our expectations.

However, after we change weights of CPP to 2:2, there are two pods in each cluster, which means  lazy CPP takes effect immediately.

**What you expected to happen**:

After we change weights of CPP to 2:2, there are still three pods in ucs-pytest-cce-003 and one pod in ucs-pytest-cce-004, until we change the deployment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0-preview4
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
