### ISSUE TITLE
MultiClusterService is not effact for statefulset

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4604]
sts-nginx.yaml

kubectl apply -f sts-nginx.yaml --kubeconfig ~/kube-karmada

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-svc
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-svc-headless
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: nginx-headless
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  ordinals:
    start: 0
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx-headless"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ceph-rbd"
      resources:
        requests:
          storage: 10Mi
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-deploy
spec:
  propagateDeps: true
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 300
      gracePeriodSeconds: 10
      purgeMode: Graciously
  resourceSelectors:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: web
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
---
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: nginx-member2
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: web
  targetCluster:
    clusterNames:
      - cluster2
  overriders:
    plaintext:
      - path: "/spec/ordinals/start"
        operator: replace
        value: 3
```

cluster1

```
root@karmada-02-a:~# kubectl get pod -w
NAME    READY   STATUS    RESTARTS   AGE
web-0   1/1     Running   0          4m18s
web-1   1/1     Running   0          3m45s
web-2   1/1     Running   0          3m3s
```

cluster2

```
root@karmada-03-a:~# kubectl get pod -w
NAME    READY   STATUS    RESTARTS   AGE
web-3   1/1     Running   0          5m20s
web-4   1/1     Running   0          4m53s
web-5   1/1     Running   0          4m40s
```

multiClusterService-nginx.yaml

kubectl apply -f multiClusterService-nginx.yaml  --kubeconfig ~/kube-karmada

```
---
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
   name: nginx
spec:
   types:
   - CrossCluster
   serviceProvisionClusters:
   - cluster1
   - cluster2
   serviceConsumptionClusters:
   - cluster1
   - cluster2
```

cluster1

```
kubectl exec web-0 -- sh -c 'echo web-0 > /usr/share/nginx/html/index.html'
kubectl exec web-1 -- sh -c 'echo web-1 > /usr/share/nginx/html/index.html'
kubectl exec web-2 -- sh -c 'echo web-2 > /usr/share/nginx/html/index.html'
```

cluster2

```
kubectl exec web-3 -- sh -c 'echo web-3 > /usr/share/nginx/html/index.html'
kubectl exec web-4 -- sh -c 'echo web-4 > /usr/share/nginx/html/index.html'
kubectl exec web-5 -- sh -c 'echo web-5 > /usr/share/nginx/html/index.html'
```

```
root@karmada-02-a:~# curl 10.69.240.105
web-2
root@karmada-02-a:~# curl 10.69.240.105
web-1
root@karmada-02-a:~# curl 10.69.240.105
web-0
root@karmada-02-a:~# curl 10.69.240.105
web-2
root@karmada-02-a:~# curl 10.69.240.105
web-1
root@karmada-02-a:~# curl 10.69.240.105
web-0
root@karmada-02-a:~# curl 10.69.240.105
web-2
```
```
root@karmada-02-a:~# kubectl get endpointslices.discovery.k8s.io 
NAME                   ADDRESSTYPE   PORTS   ENDPOINTS                         AGE
kubernetes             IPv4          6443    192.168.229.182                   23h
nginx-h2m6q            IPv4          80      10.2.1.192,10.2.0.16,10.2.2.112   24m
nginx-headless-q697g   IPv4          80      10.2.1.192,10.2.0.16,10.2.2.112   24m
```
the endpointslice is not generated for annothor cluster
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by jwcesign** [comment]
Hi, there are a few updates recently(bug fix related), can you try with the latest version(master branch).

I try the following yaml, and it works fine:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-svc
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-svc-headless
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: nginx-headless
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  ordinals:
    start: 0
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx-headless"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-deploy
spec:
  propagateDeps: true
  failover:
    application:
      decisionConditions:
        tolerationSeconds: 300
      gracePeriodSeconds: 10
      purgeMode: Graciously
  resourceSelectors:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: web
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
---
#apiVersion: policy.karmada.io/v1alpha1
#kind: OverridePolicy
#metadata:
#  name: nginx-member2
#spec:
#  resourceSelectors:
#    - apiVersion: apps/v1
#      kind: StatefulSet
#      name: web
#  targetCluster:
#    clusterNames:
#      - member2
#  overriders:
#    plaintext:
#      - path: "/spec/ordinals/start"
#        operator: replace
#        value: 3
---
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
   name: nginx
spec:
   types:
   - CrossCluster
   providerClusters:
   - name: member1
   - name: member2
   consumerClusters:
   - name: member1
   - name: member2
```

The endpointslice:
```sh
root@karmada [02:31:26 PM] [~/workspace/demo/mcs/mcs-serviceexport]
-> # karmadactl get endpointslice
NAME                   CLUSTER   ADDRESSTYPE   PORTS   ENDPOINTS                          AGE     ADOPTION
kubernetes             member2   IPv4          6443    172.18.0.4                         4d22h   N
member1-nginx-h54rm    member2   IPv4          80      10.10.0.92,10.10.0.93,10.10.0.94   7m45s   Y
nginx-headless-hpddj   member2   IPv4          80      10.12.0.38,10.12.0.39,10.12.0.40   7m45s   Y
nginx-hgbfs            member2   IPv4          80      10.12.0.38,10.12.0.39,10.12.0.40   7m45s   Y
kubernetes             member1   IPv4          6443    172.18.0.5                         4d22h   N
member2-nginx-hgbfs    member1   IPv4          80      10.12.0.38,10.12.0.39,10.12.0.40   7m45s   Y
nginx-h54rm            member1   IPv4          80      10.10.0.92,10.10.0.93,10.10.0.94   7m45s   Y
nginx-headless-2xx96   member1   IPv4          80      10.10.0.92,10.10.0.93,10.10.0.94   7m45s   Y
kubernetes             member3   IPv4          6443    172.18.0.3                         4d22h   N
kubernetes             member4   IPv4          6443    172.18.0.7                         3d19h   N
```

**Comment by 13567436138** [comment]
I update to latest version,the same no generated endpointslice
```
root@karmada-01-b:~/karmada-teaching/sts# karmadactl get endpointslice --kubeconfig ~/kube-karmada 
NAME                   CLUSTER    ADDRESSTYPE   PORTS   ENDPOINTS                         AGE   ADOPTION
kubernetes             cluster1   IPv4          6443    192.168.229.182                   47h   N
nginx-headless-k9fzk   cluster1   IPv4          80      10.2.1.141,10.2.0.131,10.2.3.54   12m   Y
nginx-wh5pl            cluster1   IPv4          80      10.2.1.141,10.2.0.131,10.2.3.54   12m   Y
kubernetes             cluster2   IPv4          6443    192.168.229.185                   56d   N
nginx-5dnr4            cluster2   IPv4          80      10.2.2.118,10.2.1.112,10.2.0.99   12m   Y
nginx-headless-lhcgm   cluster2   IPv4          80      10.2.2.118,10.2.1.112,10.2.0.99   12m   Y
kubernetes             cluster3   IPv4          6443    192.168.229.202                   13d   N
```

**Comment by jwcesign** [comment]
Can you show me the result of the following commands?
`kubectl get mcs -oyaml`

`kubectl get work -A`

**Comment by 13567436138** [comment]
你用的是什么网络

**Comment by 13567436138** [comment]
```
root@karmada-01-b:~/karmada-teaching/sts# kubectl get mcs -oyaml --kubeconfig ~/kube-karmada 
apiVersion: v1
items:
- apiVersion: networking.karmada.io/v1alpha1
  kind: MultiClusterService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.karmada.io/v1alpha1","kind":"MultiClusterService","metadata":{"annotations":{},"name":"nginx","namespace":"default"},"spec":{"serviceConsumptionClusters":["cluster1","cluster2","cluster3"],"serviceProvisionClusters":["cluster1","cluster2","cluster3"],"types":["CrossCluster"]}}
    creationTimestamp: "2024-02-03T05:40:00Z"
    generation: 1
    labels:
      multiclusterservice.karmada.io/permanent-id: 6e9ac7c4-5477-46a6-b075-22b46e5aee70
    name: nginx
    namespace: default
    resourceVersion: "8715"
    uid: 6d78afa2-755f-45bb-aa1a-fb74547f923e
  spec:
    range: {}
    serviceConsumptionClusters:
    - cluster1
    - cluster2
    - cluster3
    serviceProvisionClusters:
    - cluster1
    - cluster2
    - cluster3
    types:
    - CrossCluster
kind: List
metadata:
  resourceVersion: ""
```
```
root@karmada-01-b:~/karmada-teaching/sts# kubectl get work -A --kubeconfig ~/kube-karmada 
NAMESPACE             NAME                              WORKLOAD-KIND        APPLIED   AGE
karmada-es-cluster1   karmada-impersonator-7cbb6bd5c9   ClusterRole          True      23h
karmada-es-cluster1   karmada-impersonator-84f8c8f8c6   ClusterRoleBinding   True      23h
karmada-es-cluster1   nginx-64b7849b5                   Service              True      23m
karmada-es-cluster1   nginx-headless-5ffd8b4dbc         Service              True      23m
karmada-es-cluster2   karmada-impersonator-7cbb6bd5c9   ClusterRole          True      23h
karmada-es-cluster2   karmada-impersonator-84f8c8f8c6   ClusterRoleBinding   True      23h
karmada-es-cluster2   nginx-64b7849b5                   Service              True      23m
karmada-es-cluster2   nginx-headless-5ffd8b4dbc         Service              True      23m
karmada-es-cluster2   web-7754dc7556                    StatefulSet          True      23m
karmada-es-cluster3   karmada-impersonator-7cbb6bd5c9   ClusterRole          True      23h
karmada-es-cluster3   karmada-impersonator-84f8c8f8c6   ClusterRoleBinding   True      23h
karmada-es-cluster3   web-7754dc7556                    StatefulSet          True      7m34s
```

multiClusterService-nginx.yaml

kubectl apply -f multiClusterService-nginx.yaml  --kubeconfig ~/kube-karmada

```
---
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
   name: nginx
spec:
   types:
   - CrossCluster
   serviceProvisionClusters:
   - cluster1
   - cluster2
   - cluster3
   serviceConsumptionClusters:
   - cluster1
   - cluster2
   - cluster3
```
