### ISSUE TITLE
Does karmada-search support customresource ?

### ISSUE THREAD

**Issue by wengyao04** [karmada-io/karmada#4621]
**What happened**:
We want to track the resources we created on the managed cluster from the karmada control plane. We use a custom resource to represent our workload and implement the resource-interpreter webhook. The workload is able to dispatched to the managed cluster. 

We also want to track our workload created on the managed cluster, so we follow https://karmada.io/docs/tutorials/karmada-search to install karmada search and create `ResourceRegistry`

```
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: deployment-search
spec:
  targetCluster:
    clusterNames:
      - cluster-1
      - cluster-2
  resourceSelectors:
    - apiVersion: <our-api-group>/v1
      kind: ComputeJob
```

However when I query api endpoint in karmada-api context
```
kubectl get --raw /apis/search.karmada.io/v1alpha1/search/cache/<our-api-group>/v1/computejobs
Error from server: k8s native Request URL(<our-api-group>/v1/computejobs) is not a resource request
```

but the following call is fine, so I guess karmada-search might not support customresources or my endpoint is wrong ?
```
k get --raw /apis/search.karmada.io/v1alpha1/search/cache/apis/apps/v1/deployments
{"kind":"DeploymentList","apiVersion":"apps/v1","metadata":{},"items":[]}
```

**What you expected to happen**:
Using karmada search, I suppose to see the list of computejobs

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I use the latest karmada images/charts 

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
