### ISSUE TITLE
Removing resources from propagation policy does not remove their work objects

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#4633]
**What would you like to be added**:
We use labels to mark resources for propagation, but removing the labels does not make them stop propagating
since the work resource is already created and not being removed

```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: duplicate
spec:
  conflictResolution: Overwrite
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    labelSelector:
      matchLabels:
        duplicate: "true"
```

**Why is this needed**:
it gets the cluster into an unexpected state and breaks rollbacks
