### ISSUE TITLE
Bump Prow to v20240517-ea10bd814

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#4637]
**Why is this needed**:
We want the feature that triggers failed workflow which was introduced since v20220105-8e97316bf9.
See the discussion https://github.com/karmada-io/karmada/issues/3421#issuecomment-1751961909 for more details.

**Migration progress**:
- [x] [karmada-io/karmada](https://github.com/karmada-io/karmada)
- [x] [karmada-io/website](https://github.com/karmada-io/website)
- [x] [karmada-io/community](https://github.com/karmada-io/community)
- [x] [karmada-io/kubernetes](https://github.com/karmada-io/kubernetes)
- [x] [karmada-io/multicluster-cloud-provider](https://github.com/karmada-io/multicluster-cloud-provider)
- [x] [karmada-io/api](https://github.com/karmada-io/api)
- [x] [karmada-io/dashboard](https://github.com/karmada-io/dashboard)
- [x] [karmada-io/multi-cluster-ingress-nginx](https://github.com/karmada-io/multi-cluster-ingress-nginx)
- [x] [karmada-io/playground](https://github.com/karmada-io/playground)

All images can be found here: https://console.cloud.google.com/gcr/images/k8s-prow

**Comment by RainbowMango** [comment]
I tested the basic functionality against the https://github.com/karmada-io/website/pull/563 and it works well.
The next step is to test the `retest` function.

Here is the main configuration update(add the `triggers`):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: karmada-prowbot
  name: config
data:
  config.yaml: |
    triggers:
    - repos:
      - karmada-io/karmada
      - karmada-io/website
      # JoinOrgURL is a link that redirects users to a location where they
      # should be able to read more about joining the organization in order
      # to become trusted members.
      join_org_url: "https://github.com/karmada-io/community/blob/main/community-membership.md#member"
      only_org_members: true
      # TriggerGitHubWorkflows enables workflows run by github to be triggered by prow.
      trigger_github_workflows: true
```

**Comment by jwcesign** [comment]
I tried it in my env and it works fine: https://github.com/jwcesign/kubectl-proxy-demo/pull/3

My config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: plugins
data:
  plugins.yaml: |
    triggers:
    - repos:
      - jwcesign/kubectl-proxy-demo
      trigger_github_workflows: true
    plugins:
      jwcesign/kubectl-proxy-demo:
        plugins:
        - approve
        - assign
        - blunderbuss
        - cat
        - dog
        - help
        - heart
        - hold
        - label
        - lgtm
        - trigger
        - verify-owners
        - wip
        - yuks
```

Did the relevant components restart after the configuration update? @RainbowMango
