### ISSUE TITLE
the server doesn't have a resource type "clusters"

### ISSUE THREAD

**Issue by Tanc010** [karmada-io/karmada#4641]
**Please provide an in-depth description of the question you have**:
参考文档https://karmada.io/zh/docs/installation/#%E4%B8%BA%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85-karmada，使用脚本“hack/local-up-karmada.sh”部署后，执行kubectl get clusters --kubeconfig=/$HOME/.kube/karmada.config。报错：”the server doesn't have a resource type "clusters"。

**What do you think about this question?**:

**Environment**:
- Karmada version: release-1.8.0
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Hi @Tanc010 Thanks for spotting. 
There are two contexts in the `karmada.config`, and unfortunately the `current-context` is `karmada-host`:
```yaml
contexts:
- context:
    cluster: karmada-apiserver
    user: karmada-apiserver
  name: karmada-apiserver
- context:
    cluster: kind-karmada-host
    user: kind-karmada-host
  name: karmada-host
current-context: karmada-host
```
You might need to switch the context before access karmada-apiserver:
```
-bash-5.0# export KUBECONFIG=/root/.kube/karmada.config
-bash-5.0# kubectl config use-context karmada-apiserver
Switched to context "karmada-apiserver".
-bash-5.0# kubectl get clusters
NAME      VERSION   MODE   READY   AGE
member1   v1.27.3   Push   True    22m
member2   v1.27.3   Push   True    22m
member3   v1.27.3   Pull   True    22m
```

By the way, It'd be great if the generated `karmada.config` took the `karmada-apiserver` as the default(`current-context`) context.
