### ISSUE TITLE
Remove sub-resources from cluster api enablement list

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#465]
**What would you like to be added**:
Remove the redundant API resources from the [API Resoruces](https://github.com/karmada-io/karmada/blob/c053b6c8b324fe48f70bd88c970074de9fd0df7f/pkg/apis/cluster/v1alpha1/types.go#L143).

E.g, the `namespaces/finalize`, `namespaces/status`, etc are not the real API resources that we are caring about.
```
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: "2021-06-24T06:18:12Z"
  finalizers:
  - karmada.io/cluster-controller
  name: member1
  resourceVersion: "319"
  selfLink: /apis/cluster.karmada.io/v1alpha1/clusters/member1
  uid: a30fb780-6b20-4535-8a86-d5a64c415ff9
spec:
  apiEndpoint: https://172.18.0.5:6443
  secretRef:
    name: member1
    namespace: karmada-cluster
  syncMode: Push
status:
  apiEnablements:
  - groupVersion: v1
    resources:
    - kind: Namespace
      name: namespaces
    - kind: Namespace
      name: namespaces/finalize
    - kind: Namespace
      name: namespaces/status
    - kind: Node
      name: nodes
    - kind: NodeProxyOptions
      name: nodes/proxy
    - kind: Node
      name: nodes/status
    - kind: PersistentVolumeClaim
      name: persistentvolumeclaims
    - kind: PersistentVolumeClaim
      name: persistentvolumeclaims/status
    - kind: PersistentVolume
      name: persistentvolumes
    - kind: PersistentVolume
      name: persistentvolumes/status
    ...
```

**Why is this needed**:
Removing redundant info for clean and tidy.

In contrast, the `kubectl api-resources` ignored all the sub-resources:
```
# kubectl api-resources | grep -i namespaces
namespaces                        ns                                          false        Namespace
```

**Comment by RainbowMango** [comment]
After a quick investigation, maybe we can filter the sub-resource according to [here](https://github.com/kubernetes/kubernetes/blob/b0010c2d9ea8f2d20ffca20da7846eb4bba6e456/staging/src/k8s.io/client-go/discovery/discovery_client.go#L316-L320)
```golang
if strings.Contains(apiResource.Name, "/") {
	continue
}
```

**Comment by shinytang6** [comment]
Let me have a try.
/assign @shinytang6

**Comment by RainbowMango** [comment]
Thanks, go for it!

**Comment by RainbowMango** [comment]
Just post the testing result from my side.

Before the patch we have `123` resources:
<details>
<summary>Before the patch</summary>

```
  apiEnablements:
  - groupVersion: v1
    resources:
    - kind: Binding
      name: bindings
    - kind: ComponentStatus
      name: componentstatuses
    - kind: ConfigMap
      name: configmaps
    - kind: Endpoints
      name: endpoints
    - kind: Event
      name: events
    - kind: LimitRange
      name: limitranges
    - kind: Namespace
      name: namespaces
    - kind: Namespace
      name: namespaces/finalize
    - kind: Namespace
      name: namespaces/status
    - kind: Node
      name: nodes
    - kind: NodeProxyOptions
      name: nodes/proxy
    - kind: Node
      name: nodes/status
    - kind: PersistentVolumeClaim
      name: persistentvolumeclaims
    - kind: PersistentVolumeClaim
      name: persistentvolumeclaims/status
    - kind: PersistentVolume
      name: persistentvolumes
    - kind: PersistentVolume
      name: persistentvolumes/status
    - kind: Pod
      name: pods
    - kind: PodAttachOptions
      name: pods/attach
    - kind: Binding
      name: pods/binding
    - kind: Eviction
      name: pods/eviction
    - kind: PodExecOptions
      name: pods/exec
    - kind: Pod
      name: pods/log
    - kind: PodPortForwardOptions
      name: pods/portforward
    - kind: PodProxyOptions
      name: pods/proxy
    - kind: Pod
      name: pods/status
    - kind: PodTemplate
      name: podtemplates
    - kind: ReplicationController
      name: replicationcontrollers
    - kind: Scale
      name: replicationcontrollers/scale
    - kind: ReplicationController
      name: replicationcontrollers/status
    - kind: ResourceQuota
      name: resourcequotas
    - kind: ResourceQuota
      name: resourcequotas/status
    - kind: Secret
      name: secrets
    - kind: ServiceAccount
      name: serviceaccounts
    - kind: Service
      name: services
    - kind: ServiceProxyOptions
      name: services/proxy
    - kind: Service
      name: services/status
  - groupVersion: apiregistration.k8s.io/v1
    resources:
    - kind: APIService
      name: apiservices
    - kind: APIService
      name: apiservices/status
  - groupVersion: apiregistration.k8s.io/v1beta1
    resources:
    - kind: APIService
      name: apiservices
    - kind: APIService
      name: apiservices/status
  - groupVersion: extensions/v1beta1
    resources:
    - kind: Ingress
      name: ingresses
    - kind: Ingress
      name: ingresses/status
  - groupVersion: apps/v1
    resources:
    - kind: ControllerRevision
      name: controllerrevisions
    - kind: DaemonSet
      name: daemonsets
    - kind: DaemonSet
      name: daemonsets/status
    - kind: Deployment
      name: deployments
    - kind: Scale
      name: deployments/scale
    - kind: Deployment
      name: deployments/status
    - kind: ReplicaSet
      name: replicasets
    - kind: Scale
      name: replicasets/scale
    - kind: ReplicaSet
      name: replicasets/status
    - kind: StatefulSet
      name: statefulsets
    - kind: Scale
      name: statefulsets/scale
    - kind: StatefulSet
      name: statefulsets/status
  - groupVersion: events.k8s.io/v1
    resources:
    - kind: Event
      name: events
  - groupVersion: events.k8s.io/v1beta1
    resources:
    - kind: Event
      name: events
  - groupVersion: authentication.k8s.io/v1
    resources:
    - kind: TokenReview
      name: tokenreviews
  - groupVersion: authentication.k8s.io/v1beta1
    resources:
    - kind: TokenReview
      name: tokenreviews
  - groupVersion: authorization.k8s.io/v1
    resources:
    - kind: LocalSubjectAccessReview
      name: localsubjectaccessreviews
    - kind: SelfSubjectAccessReview
      name: selfsubjectaccessreviews
    - kind: SelfSubjectRulesReview
      name: selfsubjectrulesreviews
    - kind: SubjectAccessReview
      name: subjectaccessreviews
  - groupVersion: authorization.k8s.io/v1beta1
    resources:
    - kind: LocalSubjectAccessReview
      name: localsubjectaccessreviews
    - kind: SelfSubjectAccessReview
      name: selfsubjectaccessreviews
    - kind: SelfSubjectRulesReview
      name: selfsubjectrulesreviews
    - kind: SubjectAccessReview
      name: subjectaccessreviews
  - groupVersion: autoscaling/v1
    resources:
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers/status
  - groupVersion: autoscaling/v2beta1
    resources:
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers/status
  - groupVersion: autoscaling/v2beta2
    resources:
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers/status
  - groupVersion: batch/v1
    resources:
    - kind: Job
      name: jobs
    - kind: Job
      name: jobs/status
  - groupVersion: batch/v1beta1
    resources:
    - kind: CronJob
      name: cronjobs
    - kind: CronJob
      name: cronjobs/status
  - groupVersion: certificates.k8s.io/v1
    resources:
    - kind: CertificateSigningRequest
      name: certificatesigningrequests
    - kind: CertificateSigningRequest
      name: certificatesigningrequests/approval
    - kind: CertificateSigningRequest
      name: certificatesigningrequests/status
  - groupVersion: certificates.k8s.io/v1beta1
    resources:
    - kind: CertificateSigningRequest
      name: certificatesigningrequests
    - kind: CertificateSigningRequest
      name: certificatesigningrequests/approval
    - kind: CertificateSigningRequest
      name: certificatesigningrequests/status
  - groupVersion: networking.k8s.io/v1
    resources:
    - kind: IngressClass
      name: ingressclasses
    - kind: Ingress
      name: ingresses
    - kind: Ingress
      name: ingresses/status
    - kind: NetworkPolicy
      name: networkpolicies
  - groupVersion: networking.k8s.io/v1beta1
    resources:
    - kind: IngressClass
      name: ingressclasses
    - kind: Ingress
      name: ingresses
    - kind: Ingress
      name: ingresses/status
  - groupVersion: policy/v1beta1
    resources:
    - kind: PodDisruptionBudget
      name: poddisruptionbudgets
    - kind: PodDisruptionBudget
      name: poddisruptionbudgets/status
    - kind: PodSecurityPolicy
      name: podsecuritypolicies
  - groupVersion: rbac.authorization.k8s.io/v1
    resources:
    - kind: ClusterRoleBinding
      name: clusterrolebindings
    - kind: ClusterRole
      name: clusterroles
    - kind: RoleBinding
      name: rolebindings
    - kind: Role
      name: roles
  - groupVersion: rbac.authorization.k8s.io/v1beta1
    resources:
    - kind: ClusterRoleBinding
      name: clusterrolebindings
    - kind: ClusterRole
      name: clusterroles
    - kind: RoleBinding
      name: rolebindings
    - kind: Role
      name: roles
  - groupVersion: storage.k8s.io/v1
    resources:
    - kind: CSIDriver
      name: csidrivers
    - kind: CSINode
      name: csinodes
    - kind: StorageClass
      name: storageclasses
    - kind: VolumeAttachment
      name: volumeattachments
    - kind: VolumeAttachment
      name: volumeattachments/status
  - groupVersion: storage.k8s.io/v1beta1
    resources:
    - kind: CSIDriver
      name: csidrivers
    - kind: CSINode
      name: csinodes
    - kind: StorageClass
      name: storageclasses
    - kind: VolumeAttachment
      name: volumeattachments
  - groupVersion: admissionregistration.k8s.io/v1
    resources:
    - kind: MutatingWebhookConfiguration
      name: mutatingwebhookconfigurations
    - kind: ValidatingWebhookConfiguration
      name: validatingwebhookconfigurations
  - groupVersion: admissionregistration.k8s.io/v1beta1
    resources:
    - kind: MutatingWebhookConfiguration
      name: mutatingwebhookconfigurations
    - kind: ValidatingWebhookConfiguration
      name: validatingwebhookconfigurations
  - groupVersion: apiextensions.k8s.io/v1
    resources:
    - kind: CustomResourceDefinition
      name: customresourcedefinitions
    - kind: CustomResourceDefinition
      name: customresourcedefinitions/status
  - groupVersion: apiextensions.k8s.io/v1beta1
    resources:
    - kind: CustomResourceDefinition
      name: customresourcedefinitions
    - kind: CustomResourceDefinition
      name: customresourcedefinitions/status
  - groupVersion: scheduling.k8s.io/v1
    resources:
    - kind: PriorityClass
      name: priorityclasses
  - groupVersion: scheduling.k8s.io/v1beta1
    resources:
    - kind: PriorityClass
      name: priorityclasses
  - groupVersion: coordination.k8s.io/v1
    resources:
    - kind: Lease
      name: leases
  - groupVersion: coordination.k8s.io/v1beta1
    resources:
    - kind: Lease
      name: leases
  - groupVersion: node.k8s.io/v1beta1
    resources:
    - kind: RuntimeClass
      name: runtimeclasses
  - groupVersion: discovery.k8s.io/v1beta1
    resources:
    - kind: EndpointSlice
      name: endpointslices
```

</details>

After the path we have `79` resources:

<details>
<summary>After the path</summary>

```yaml
apiEnablements:
  - groupVersion: v1
    resources:
    - kind: Binding
      name: bindings
    - kind: ComponentStatus
      name: componentstatuses
    - kind: ConfigMap
      name: configmaps
    - kind: Endpoints
      name: endpoints
    - kind: Event
      name: events
    - kind: LimitRange
      name: limitranges
    - kind: Namespace
      name: namespaces
    - kind: Node
      name: nodes
    - kind: PersistentVolumeClaim
      name: persistentvolumeclaims
    - kind: PersistentVolume
      name: persistentvolumes
    - kind: Pod
      name: pods
    - kind: PodTemplate
      name: podtemplates
    - kind: ReplicationController
      name: replicationcontrollers
    - kind: ResourceQuota
      name: resourcequotas
    - kind: Secret
      name: secrets
    - kind: ServiceAccount
      name: serviceaccounts
    - kind: Service
      name: services
  - groupVersion: apiregistration.k8s.io/v1
    resources:
    - kind: APIService
      name: apiservices
  - groupVersion: apiregistration.k8s.io/v1beta1
    resources:
    - kind: APIService
      name: apiservices
  - groupVersion: extensions/v1beta1
    resources:
    - kind: Ingress
      name: ingresses
  - groupVersion: apps/v1
    resources:
    - kind: ControllerRevision
      name: controllerrevisions
    - kind: DaemonSet
      name: daemonsets
    - kind: Deployment
      name: deployments
    - kind: ReplicaSet
      name: replicasets
    - kind: StatefulSet
      name: statefulsets
  - groupVersion: events.k8s.io/v1
    resources:
    - kind: Event
      name: events
  - groupVersion: events.k8s.io/v1beta1
    resources:
    - kind: Event
      name: events
  - groupVersion: authentication.k8s.io/v1
    resources:
    - kind: TokenReview
      name: tokenreviews
  - groupVersion: authentication.k8s.io/v1beta1
    resources:
    - kind: TokenReview
      name: tokenreviews
  - groupVersion: authorization.k8s.io/v1
    resources:
    - kind: LocalSubjectAccessReview
      name: localsubjectaccessreviews
    - kind: SelfSubjectAccessReview
      name: selfsubjectaccessreviews
    - kind: SelfSubjectRulesReview
      name: selfsubjectrulesreviews
    - kind: SubjectAccessReview
      name: subjectaccessreviews
  - groupVersion: authorization.k8s.io/v1beta1
    resources:
    - kind: LocalSubjectAccessReview
      name: localsubjectaccessreviews
    - kind: SelfSubjectAccessReview
      name: selfsubjectaccessreviews
    - kind: SelfSubjectRulesReview
      name: selfsubjectrulesreviews
    - kind: SubjectAccessReview
      name: subjectaccessreviews
  - groupVersion: autoscaling/v1
    resources:
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers
  - groupVersion: autoscaling/v2beta1
    resources:
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers
  - groupVersion: autoscaling/v2beta2
    resources:
    - kind: HorizontalPodAutoscaler
      name: horizontalpodautoscalers
  - groupVersion: batch/v1
    resources:
    - kind: Job
      name: jobs
  - groupVersion: batch/v1beta1
    resources:
    - kind: CronJob
      name: cronjobs
  - groupVersion: certificates.k8s.io/v1
    resources:
    - kind: CertificateSigningRequest
      name: certificatesigningrequests
  - groupVersion: certificates.k8s.io/v1beta1
    resources:
    - kind: CertificateSigningRequest
      name: certificatesigningrequests
  - groupVersion: networking.k8s.io/v1
    resources:
    - kind: IngressClass
      name: ingressclasses
    - kind: Ingress
      name: ingresses
    - kind: NetworkPolicy
      name: networkpolicies
  - groupVersion: networking.k8s.io/v1beta1
    resources:
    - kind: IngressClass
      name: ingressclasses
    - kind: Ingress
      name: ingresses
  - groupVersion: policy/v1beta1
    resources:
    - kind: PodDisruptionBudget
      name: poddisruptionbudgets
    - kind: PodSecurityPolicy
      name: podsecuritypolicies
  - groupVersion: rbac.authorization.k8s.io/v1
    resources:
    - kind: ClusterRoleBinding
      name: clusterrolebindings
    - kind: ClusterRole
      name: clusterroles
    - kind: RoleBinding
      name: rolebindings
    - kind: Role
      name: roles
  - groupVersion: rbac.authorization.k8s.io/v1beta1
    resources:
    - kind: ClusterRoleBinding
      name: clusterrolebindings
    - kind: ClusterRole
      name: clusterroles
    - kind: RoleBinding
      name: rolebindings
    - kind: Role
      name: roles
  - groupVersion: storage.k8s.io/v1
    resources:
    - kind: CSIDriver
      name: csidrivers
    - kind: CSINode
      name: csinodes
    - kind: StorageClass
      name: storageclasses
    - kind: VolumeAttachment
      name: volumeattachments
  - groupVersion: storage.k8s.io/v1beta1
    resources:
    - kind: CSIDriver
      name: csidrivers
    - kind: CSINode
      name: csinodes
    - kind: StorageClass
      name: storageclasses
    - kind: VolumeAttachment
      name: volumeattachments
  - groupVersion: admissionregistration.k8s.io/v1
    resources:
    - kind: MutatingWebhookConfiguration
      name: mutatingwebhookconfigurations
    - kind: ValidatingWebhookConfiguration
      name: validatingwebhookconfigurations
  - groupVersion: admissionregistration.k8s.io/v1beta1
    resources:
    - kind: MutatingWebhookConfiguration
      name: mutatingwebhookconfigurations
    - kind: ValidatingWebhookConfiguration
      name: validatingwebhookconfigurations
  - groupVersion: apiextensions.k8s.io/v1
    resources:
    - kind: CustomResourceDefinition
      name: customresourcedefinitions
  - groupVersion: apiextensions.k8s.io/v1beta1
    resources:
    - kind: CustomResourceDefinition
      name: customresourcedefinitions
  - groupVersion: scheduling.k8s.io/v1
    resources:
    - kind: PriorityClass
      name: priorityclasses
  - groupVersion: scheduling.k8s.io/v1beta1
    resources:
    - kind: PriorityClass
      name: priorityclasses
  - groupVersion: coordination.k8s.io/v1
    resources:
    - kind: Lease
      name: leases
  - groupVersion: coordination.k8s.io/v1beta1
    resources:
    - kind: Lease
      name: leases
  - groupVersion: node.k8s.io/v1beta1
    resources:
    - kind: RuntimeClass
      name: runtimeclasses
  - groupVersion: discovery.k8s.io/v1beta1
    resources:
    - kind: EndpointSlice
      name: endpointslices
```

</details>
