### ISSUE TITLE
Cannot delete karmada-search component, when the karmada has been deleted.

### ISSUE THREAD

**Issue by laihezhao** [karmada-io/karmada#4672]
**What happened**:
the karmada-search can not be delete
<img width="735" alt="9066c518a48719202e2839d9e7bbaa88" src="https://github.com/karmada-io/karmada/assets/24719400/e9f4feb2-b6d9-453e-895d-bd2764437394">

**What you expected to happen**:
the deployment and service of the karmada-search component will be deleted, when the karmada CR is deleted

**How to reproduce it (as minimally and precisely as possible)**:
karmada.yaml
```

apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: demo
  namespace: karmada-system
spec:
  components:
    etcd:
      local:
        replicas: 1
        imageRepository: 172.22.96.158/system_containers/etcd
        imageTag: 3.5.9-0
        volumeData:
          hostPath:
            type: DirectoryOrCreate
            path: /var/lib/karmada/etcd/karmada-demo
    karmadaAPIServer:
      imageRepository: 172.22.96.158/system_containers/kube-apiserver
      imageTag: v1.26.12
      replicas: 1
      serviceType: NodePort
    karmadaAggregatedAPIServer:
      imageRepository: 172.22.96.158/system_containers/karmada-aggregated-apiserver
      imageTag: v1.9.0
      replicas: 1
    karmadaControllerManager:
      imageRepository: 172.22.96.158/system_containers/karmada-controller-manager
      imageTag: v1.9.0
      replicas: 1
    karmadaScheduler:
      imageRepository: 172.22.96.158/system_containers/karmada-scheduler
      imageTag: v1.9.0
      replicas: 1
    karmadaWebhook:
      imageRepository: 172.22.96.158/system_containers/karmada-webhook
      imageTag: v1.9.0
      replicas: 1
    kubeControllerManager:
      imageRepository: 172.22.96.158/system_containers/kube-controller-manager
      imageTag: v1.26.12
      replicas: 1
    karmadaMetricsAdapter:
      imageRepository: 172.22.96.158/system_containers/karmada-metrics-adapter
      imageTag: v1.9.0
      replicas: 1
    karmadaSearch:
      imageRepository: 172.22.96.158/system_containers/karmada-search
      imageTag: v1.9.0
      replicas: 1
  hostCluster:
    networking:
      dnsDomain: cluster.local
```

kubectl delete -f karmada.yaml

I got the result 

<img width="735" alt="9066c518a48719202e2839d9e7bbaa88" src="https://github.com/karmada-io/karmada/assets/24719400/125d4740-b1d3-4166-880b-a9d34283b714">

the log of karmada-operator is:
<img width="947" alt="a2315fb2a59e21140103331b2841bca7" src="https://github.com/karmada-io/karmada/assets/24719400/9edca8ba-4e0e-47e5-9db1-5b372ba0d5cb">

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
