### ISSUE TITLE
Does Karmada search support pod log from managed clusters ?

### ISSUE THREAD

**Issue by wengyao04** [karmada-io/karmada#4678]
**Please provide an in-depth description of the question you have**:

Does Karmada search support pod logs from managed clusters ?

**What do you think about this question?**:

We deploy  `ResourceRegistry` to karmada-api (context)
```
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: search-resource-registry
spec:
  targetCluster:
    clusterNames:
      - <cluster-1>
      - <cluster-2>
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
```

And try
```
k get --raw /apis/search.karmada.io/v1alpha1/search/cache/api/v1/namespaces/<namespace>/pods/<pod-name>/log
```
and get
```
Error from server: invalid request parts([pods toymodel-8nwlq-1709082764-master-0 log]) for k8s native request URL
```

**Environment**:
- Karmada version: `v1.9.0-preview5`
- Kubernetes version: `1.26`
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @wengyao04, the cache capability of Karmada Search cannot be used to access the log subresource of a pod.

You can use the capability of [Proxy Global Resource](https://karmada.io/docs/next/userguide/globalview/proxy-global-resource/) provided by karmada-search.

**Comment by wengyao04** [comment]
Thank you ! I will try it out.

**Comment by wengyao04** [comment]
Thanks @XiShanYongYe-Chang ! I test the proxy, it works, I am able to get logs using proxy.
But it would be nice to instruct users to add `impersonatorSecretRef` in their cluster spec when using `Push` mode. I find that I miss this configuration and get error from proxy. :D

**Comment by wengyao04** [comment]
close the issue

**Comment by XiShanYongYe-Chang** [comment]
Hi @wengyao04, thanks for your feedback, based on your response, we may be able to refine the documentation.

> But it would be nice to instruct users to add impersonatorSecretRef in their cluster spec when using Push mode.

I'd like to know how you add the cluster to Karmada. I looked at the code and the `karmadactl join` command will set the `impersonatorSecretRef ` field.

**Comment by RainbowMango** [comment]
/reopen
Seems this is a great chance to improve the documents.

At least, when I tried this feature as per https://karmada.io/docs/next/userguide/globalview/proxy-global-resource/#step3-define-resource-to-be-proxied, I found we have to create the `ResourceRegistry` yaml to karmada-apiserver, which might be confusing.

**Comment by wengyao04** [comment]
@XiShanYongYe-Chang we use `Push` mode, when we register a cluster we apply 
```
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  name: <cluster-name>
spec:
  apiEndpoint: https://api.<cluster-name>.dev.bloomberg.com:6443
  secretRef:
    name: secret-<cluster-name>
    namespace: karmada-cluster
  impersonatorSecretRef:
    name: secret-<cluster-name>
    namespace: karmada-cluster
  syncMode: Push
```
