### ISSUE TITLE
Ability to suspend work

### ISSUE THREAD

**Issue by a7i** [karmada-io/karmada#4688]
**What would you like to be added**:
Ability to suspend work to ensure that changes are not being reconciled.

**Why is this needed**:

User Story 1: As a cluster admin, we may get stuck in a reconciliation loop where karmada controller-manager will update a resource but due to some unknown reason (perhaps a controller on the member cluster) the resource is reverted. The operator can decide to suspend work while debugging the issue.

User Story 2: We're using Karmada to migrate workload from one blue cluster to a green cluster. Once we move a workload, we want to suspend any updates from blue to green until we cut over to green.

### Persona
Cluster Admin who is oncall and has permission to modify karmada resources

### Implementation Details
There are three ways that we can go about this:

#### 1.  Expose `suspend` on `Work` CRD
This is the simplest approach but requires the Cluster Admin to identify `Work` in the `karmada-es-${cluster}` namespace before patching them. Once the field is set, the controller will get out early. In the code here https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/work_status_controller.go#L93-L96, we would add the following:

```go
	if work.Susped {
		return controllerruntime.Result{}, nil
	}
```

Effort: Low

#### 2.  Expose `suspend` on `ResourceBinding` CRD
This requires the `suspend` field on `ResourceBinding` which will also get updated to `Work`. The Cluster Admin will have to identify the `ResourceBinding` in the workload namespace before patching them. The name of resource binding is more predictable than `Work`.

Effort: Medium

#### 3.  Expose `suspend` on `PropagationPolicy` and `ClusterPropagationPolicy` CRD
The Cluster Admin will have to know the PP or CPP with the highest priority and decide to suspend them. Changes to`suspend` will have to get updated to `ResourceBinding` and `Work`.

Effort: X-Large

**Comment by a7i** [comment]
Created a PR to get feedback: https://github.com/karmada-io/karmada/pull/4689

**Comment by chaunceyjiang** [comment]
Related to it https://github.com/karmada-io/karmada/pull/1859

**Comment by RainbowMango** [comment]
> User Story 1: As a cluster admin, we may get stuck in a reconciliation loop where karmada controller-manager will update a resource but due to some unknown reason (perhaps a controller on the member cluster) the resource is reverted. The operator can decide to suspend work while debugging the issue.

+1 on this user story.
This feature would be helpful for debugging. 

> User Story 2: We're using Karmada to migrate workload from one blue cluster to a green cluster. Once we move a workload, we want to suspend any updates from blue to green until we cut over to green.

May I ask for more detailed info about how you do the migration? I don't understand how can the workload be synced from `blue` to `green`, I understand both the `blue` and `green` clusters are taking `karmada-apiserver` as the source.

 Just a guess, the process of migrating a workload would be something like:

Step 1: Create a PropagationPolicy to take over an application from `blue` cluster, like
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - blue
```

Step 2: Add `green` cluster to the same PropagationPolicy, so that the application can be synced:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - blue
        - green
```

Step 3: Testing against the `green` cluster. 

Step 4: Remove the application from the `blue` cluster by removing `blue` from the `PropagationPolicy`:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - green
```
