### ISSUE TITLE
Node resources are not taken into considering during scheduling

### ISSUE THREAD

**Issue by jdartigalongue** [karmada-io/karmada#4694]
**What happened**:  Pods are only scheduled on the first cluster defined in the `PropagationPolicy`  clusterAffinities even when the cluster doesn't have enough resources.

**What you expected to happen**: The scheduler to dispatch pod the second cluster when the first cluster runs out of resources

**How to reproduce it (as minimally and precisely as possible)**:
1. Run `local-up-karmada.sh`
2. Created following `PropagationPolicy`
``` apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy 
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
  placement:
    clusterAffinities:
     - affinityName: primary-clusters
       clusterNames:
        - member3
     - affinityName: secondary-clusters
       clusterNames:
        - member2
```
 3. Create a pod with 3 CPU request / limit (it will be scheduled to member3)
 ```
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        cpu: "3"
      limits:
        cpu: "3"
```
4. Create an additional pod using the above YAML (just change the resource name). The pod will also be scheduled on member3 even though it doesn't have enough resources. 

**Anything else we need to know?**:

**Environment**:
- Karmada version: Master (6fae04eb242165490a8eaec9b1b34184f58c510a)
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.9.0
- Others: Macbook Pro (Apple Silicon)

**Comment by zhzhuang-zju** [comment]
Hi @jdartigalongue Thanks for raising this issue. In fact, it's the current scheduling mechanism, not a bug, so I'll modify the label a bit.
/remove kind-bug
/kind-question
 
refer to https://github.com/karmada-io/karmada/blob/45eaa7b5f3cb98a073e0c29d42e78b72bf5c5d14/pkg/scheduler/core/assignment.go#L31-L38
Only when ```placement.ReplicaSchedulingType``` is `Aggregated` or `DynamicWeight` , the available resources of the cluster will be taken into account.
So, if you need to schedule pods to clusters with matching resources, you could try this PropagationPolicy.
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy 
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
  placement:
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Aggregated
    clusterAffinities:
     - affinityName: primary-clusters
       clusterNames:
        - member3
     - affinityName: secondary-clusters
       clusterNames:
        - member2
```

I think the current scheduling mechanism can be optimized as the scenarios and desired outcomes provided by this issue are reasonable.  @XiShanYongYe-Chang  @chaosi-zju 

Do you have any suggesetions? Or are you interested in contributing? @jdartigalongue
