### ISSUE TITLE
Configure PropagationPolicy/ClusterPropagationPolicy priority is not work

### ISSUE THREAD

**Issue by weidalin** [karmada-io/karmada#4697]
**Please provide an in-depth description of the question you have**:
Hello, I Install Karmada1.8 by Karmada command line tool. According to the [Configure PropagationPolicy/ClusterPropagationPolicy priority](https://karmada.io/zh/docs/userguide/scheduling/resource-propagating#configure-propagationpolicyclusterpropagationpolicy-priority) section in the official document, it was found that multiple different priority PropagationPolicies/ClusterPropagationPolicies were configured in a yaml file, and only the first PropagationPolicy/ClusterPropagationPolicy would be used instead of the higher priority PropagationPolicy/ClusterPropagationPolicy. For example, creating two PropagationPolicies simultaneously in a. yaml file, where the first propagation1 has a priority of 0 and the second propagation2 has a priority of 1
propagation1 that will be used (not as expected)
After deleting the currently used propagation1 strategy,
Switching to propagation strategy propagation2 (as expected)
Create a propagation1 propagation strategy with priority 4
Will not automatically switch to higher priority propagation strategy propagation1 (not as expected)
**What do you think about this question?**:
 Is this the version or is my installation method incorrect？
**Environment**:
- Karmada version: 1.8.1
- Kubernetes version: v1.25.6
- Others:

**Comment by weidalin** [comment]
# highexplicitpriority.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: propagation-high-explicit-priority
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx
  priority: 0
  placement:
    clusterAffinity:
      clusterNames:
        - member1
---
# lowexplicitpriority.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: propagation-low-explicit-priority
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx
  priority: 1
  placement:
    clusterAffinity:
      clusterNames:
        - member2

**Comment by zhzhuang-zju** [comment]
> it was found that multiple different priority PropagationPolicies/ClusterPropagationPolicies were configured in a yaml file, and only the first PropagationPolicy/ClusterPropagationPolicy would be used instead of the higher priority PropagationPolicy/ClusterPropagationPolicy.

Hi~ @weidalin  Can you help confirm if you apply deployment first or apply  PropagationPolicy/ClusterPropagationPolicy first.
- If apply deployment first
  The result that only the first PropagationPolicy/ClusterPropagationPolicy would be used instead of the higher priority PropagationPolicy/ClusterPropagationPolicy is normal. Because when applying a yaml file that contains multiple different priority PropagationPolicies/ClusterPropagationPolicies,  propagationPolicy would be created one by one in sequential order. So the deployment will match the first propagationPolicy. And by default, `PropagationPolicyPreemption` is disabled in karmada-controller-manager, so later generated higher-priority propagationPolicy could not preempt the deployment that has been matched by a low-priority propagationPolicy. More infomation can refer to https://karmada.io/docs/tutorials/resource-migration/.

- If apply PropagationPolicies/ClusterPropagationPolicies first
  In this scenario, the post-generated deployment will match the highest-priority propagationPolicy/ClusterPropagationPolicy  from the existing matchable PropagationPolicies/ClusterPropagationPolicies.

**Comment by weidalin** [comment]
thank @zhzhuang-zju. I apply deployment first

**Comment by weidalin** [comment]
Sorry to bother you again, does it support automatic matching of high priority PropagationPolicy/ClusterPropagationPolicy when -- feature gates=PropagationPolicyPreemption=true is enabled? I tried to apply deployment first and then apply  PropagationPolicy/ClusterPropagationPolicy when I enabled -- feature gates=PropagationPolicyPreemption=true. However, I did not actively select a higher priority PropagationPolicy/ClusterPropagationPolicy. Is this normal?  
conflictResolution: Overwrite is add

**Comment by zhzhuang-zju** [comment]
@weidalin  Never mind~ Can you show me your higher priority PropagationPolicy/ClusterPropagationPolicy?

**Comment by weidalin** [comment]
PropagationPolicy yaml
```
# highexplicitpriority.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: propagation-low-explicit-priority
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx
  priority: 1
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
        - atms-01
        - member1
---
# lowexplicitpriority.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: propagation-high-explicit-priority
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      labelSelector:
        matchLabels:
          app: nginx
  priority: 4
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```
nginx yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lwd-nginx
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```
