### ISSUE TITLE
propagation policy for schedule-based-on-customized-cluster-resource-models

### ISSUE THREAD

**Issue by snimje** [karmada-io/karmada#4700]
**Please provide an in-depth description of the question you have**:
I've two clusters and I would like to deploy workloads on the clusters using [feature](https://karmada.io/docs/userguide/scheduling/cluster-resources#schedule-based-on-customized-cluster-resource-models)

for this I've prepared a propagation policy that looks like this:
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
  placement:
    clusterAffinity:
      clusterNames:
        - usa
        - india
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - usa
                - india
            weight: 1
```
Now when I deployed some deployments they all landed in the same cluster. 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "512Mi"
            cpu: "5m"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "512Mi"
            cpu: "5m"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx3
  labels:
    app: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "512Mi"
            cpu: "5m"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx4
  labels:
    app: nginx4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx4
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "4096Mi"
            cpu: "5m"
```

After deploying the above deployments.
```
bash-3.2$ kctl get deploy
NAME      CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE     ADOPTION
nginx1    usa       1/1     1            1           10m     Y
nginx2    usa       1/1     1            1           10m     Y
nginx3    usa       1/1     1            1           9m54s   Y
nginx4    usa       0/1     1            0           7m18s   Y
```

on india cluster:
```
    Allocatable Modelings:
      Count:  1
      Grade:  0
      Count:  0
      Grade:  1
      Count:  0
      Grade:  2
      Count:  0
      Grade:  3
      Count:  0
      Grade:  4
      Count:  0
      Grade:  5
      Count:  0
      Grade:  6
      Count:  0
      Grade:  7
      Count:  0
      Grade:  8
    Allocated:
      Cpu:     1936m
      Memory:  2728Mi
      Pods:    20
    Allocating:
      Cpu:     110m
      Memory:  562Mi
      Pods:    1
```
on usa cluster:
```
    Allocatable Modelings:
      Count:  1
      Grade:  0
      Count:  0
      Grade:  1
      Count:  0
      Grade:  2
      Count:  0
      Grade:  3
      Count:  0
      Grade:  4
      Count:  0
      Grade:  5
      Count:  0
      Grade:  6
      Count:  0
      Grade:  7
      Count:  0
      Grade:  8
    Allocated:
      Cpu:     1951m
      Memory:  4264Mi
      Pods:    22
    Allocating:
      Cpu:     120m
      Memory:  8754Mi
      Pods:    3
```

The use case runs thousands of deployment on four clusters. Each deployment has 1 pod with resource requests and limits. The deployments should not overload one cluster and karmada scheduler to select the cluster with optimal free resources as described in customized-cluster-resource-models for deployment scheduling. Considering my use case can you share some examples of propagation policy for this feature ?
Are there any alternate approaches to achieve this objective ?

**What do you think about this question?**:

**Environment**:  
- Karmada version: 1.9.0
- Kubernetes version: 1.26.10
- Others:
