### ISSUE TITLE
Stop update krew for release-1.7, release-1.8

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#4703]
**What would you like to be added**:
- [x] Remove [update-krew-index](https://github.com/karmada-io/karmada/blob/11fac252b618dd26de530293e60b9faab9872507/.github/workflows/release.yml#L39-L46) from branch `release-1.7`. (#4767)
- [x] Remove [update-krew-index](https://github.com/karmada-io/karmada/blob/e2bc251e7079dea0b517d163c773b8cb8d024cf3/.github/workflows/release.yml#L81-L88) from branch `release-1.8`. (#4768)

**Why is this needed**:
Since [krew ](https://github.com/kubernetes-sigs/krew) only caches the `latest` release, so we don't need to update it for v1.7.x/1.8.x releases. Otherwise, it will open an invalid PR, like https://github.com/kubernetes-sigs/krew-index/pull/2809.

Sample PR: https://github.com/karmada-io/karmada/pull/4023

**Comment by ahmetb** [comment]
Instead, consider adding a tag filter to the workflow to only run on non-prerelease + v* tags.

**Comment by RainbowMango** [comment]
Yeah, I'm still thinking this. 
I guess this might be a common issue for Krew, do you know where I can find an example about how to add the filter?

I'm not sure if it will work if add a filter something like:
```yaml
  update-krew-index:
    if: <latest release>   // Not sure how to write the logic yet.
    needs: release-assests
    name: Update krew-index
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.40
```
