### ISSUE TITLE
karmada 1.9.0 pod scheduling based on resource availability

### ISSUE THREAD

**Issue by snimje** [karmada-io/karmada#4705]
**Please provide an in-depth description of the question you have**:

I've four large clusters in one region. I would like schedule the workload (A deployment pod with one replica) on only one cluster out of four which would have resources to run this pod. Could you please suggest the propagation policy placement for such requirement?

Example of the workload that will be run on only one cluster out of four:

```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mywork-${COUNTER}
  labels:
    region: usa
spec: {}
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-${COUNTER}
  namespace: mywork-${COUNTER}
data:
  secret.file: |
    c2VjcmV0RxxxxxxE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mywork-${COUNTER}
  name: mywork-${COUNTER}
  namespace: mywork-${COUNTER}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mywork-${COUNTER}
    region: usa
  name: mywork-${COUNTER}
  namespace: mywork-${COUNTER}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywork-${COUNTER}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mywork-${COUNTER}
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            requests:
              memory: "4096Mi"
              cpu: "500m"
          volumeMounts:
            - name: local-path-volume
              mountPath: /mydata
            - name: secrets-files
              mountPath: "/mnt/secret.file"
              subPath: secret.file
      volumes:
        - name: local-path-volume
          persistentVolumeClaim:
            claimName: mywork-${COUNTER}
        - name: secrets-files
          secret:
            secretName: mysecret-${COUNTER}
status: {}
---
```
  

**What do you think about this question?**:

**Environment**:
- Karmada version: 1.9.0
- Kubernetes version: 1.26.10
- Others:

**Comment by zhzhuang-zju** [comment]
@snimje Hi~Your usage scenario actually includes two points:
- How to propagate relevant resources?
  set `spec.PropagateDeps=true` 
- How to propagate based on resource availability?
  First, the component `karmada-scheduler-estimator` is needed, and it can be installed by running `hack/deploy-scheduler-estimator.sh <HOST_CLUSTER_KUBECONFIG> <HOST_CLUSTER_NAME> <MEMBER_CLUSTER_KUBECONFIG> <MEMBER_CLUSTER_NAME>`. Then, only when `placement.ReplicaSchedulingType` is `Aggregated` or `DynamicWeight` , the available resources of the cluster will be taken into account

So, you can try the propagationPolicy as follow:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy 
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: mywork-${COUNTER}
      name: mywork-${COUNTER}
  placement:
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Aggregated
    clusterAffinities:
     - affinityName: primary-clusters
       clusterNames:
        - member1
     - affinityName: secondary-clusters
       clusterNames:
        - member2
     - affinityName: third-clusters
       clusterNames:
        - member3
     - affinityName: forth-clusters
       clusterNames:
        - member4
```
