### ISSUE TITLE
DynamicWeight scheduling pods on already overloaded cluster

### ISSUE THREAD

**Issue by snimje** [karmada-io/karmada#4708]
**What happened**:
I've two clusters india and usa. 

resources on india cluster before deploying the new deployments:

```
    Allocated:
      Cpu:     1936m
      Memory:  6088Mi
      Pods:    62
    Allocating:
      Cpu:     110m
      Memory:  562Mi
      Pods:    1
```

resources on usa cluster before deploying the new deployments:
```
    Allocated:
      Cpu:     1936m
      Memory:  2728Mi
      Pods:    22
    Allocating:
      Cpu:     110m
      Memory:  562Mi
      Pods:    1
```

Now I've following placement in karmada cpp:
```
  placement:
    clusterAffinity:
      labelSelector:
        matchLabels:
          cni: calico
    replicaScheduling:
      replicaDivisionPreference: Weighted
      weightPreference:
        dynamicWeight: AvailableReplicas
      replicaSchedulingType: Divided
```
deployment manifest :
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mywork-${COUNTER}
    region: usa
  name: mywork-${COUNTER}
  namespace: mywork-${COUNTER}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywork-${COUNTER}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mywork-${COUNTER}
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            requests:
              memory: "80Mi"
          volumeMounts:
            - name: local-path-volume
              mountPath: /mydata
            - name: secrets-files
              mountPath: "/mnt/secret.file"
              subPath: secret.file
      volumes:
        - name: local-path-volume
          persistentVolumeClaim:
            claimName: mywork-${COUNTER}
        - name: secrets-files
          secret:
            secretName: mysecret-${COUNTER}
```
Before creating 50 new deployments:
```
bash-3.2$ kctl get deploy -A -C india|grep mywork|wc  -l
      42
bash-3.2$ kctl get deploy -A -C usa|grep mywork|wc  -l
      0
```
When I create 50 new deployments I see that 
```
bash-3.2$ kctl get deploy -A -C india|grep mywork|wc  -l
      72
bash-3.2$ kctl get deploy -A -C usa|grep mywork|wc  -l
      20
```
Although the usa cluster has more free memory than india cluster, more replicas are scheduled on india cluster. 

Total nine replicas are in pending state on india cluster:
```
$ k get pods -A |grep Pending
mywork-140             mywork-140-5dd9876c9d-2zvpn                 0/1     Pending     0               6m2s
mywork-143             mywork-143-777cdd9489-5gx79                 0/1     Pending     0               5m36s
mywork-144             mywork-144-647d4478b-lqjt5                  0/1     Pending     0               5m27s
mywork-145             mywork-145-79ff6785c9-hprdv                 0/1     Pending     0               5m18s
mywork-146             mywork-146-6f7c65f784-fklww                 0/1     Pending     0               5m10s
mywork-147             mywork-147-86bd5c74b9-nxv6h                 0/1     Pending     0               5m1s
mywork-148             mywork-148-6df8b7bf86-g97vk                 0/1     Pending     0               4m52s
mywork-149             mywork-149-7745f75dc-2ddxd                  0/1     Pending     0               4m43s
mywork-150             mywork-150-774c94ff69-vs9j6                 0/1     Pending     0               4m34s
```
final resource consumption on india cluster shows the nine replicas in allocating:
```
    Allocated:
      Cpu:     1936m
      Memory:  7768Mi
      Pods:    83
    Allocating:
      Cpu:     110m
      Memory:  1282Mi
      Pods:    10
```

**What you expected to happen**:

I expected the usa cluster to run more replicas than india cluster as it has more free memory compared to india cluster (as I had defined DynamicWeight in my cluster propagation policy)

**How to reproduce it (as minimally and precisely as possible)**:

I'm including the manifest file I used for creating cpp and deployment. both cluster's describe. 
I create 100 replicas initially to load both clusters with DynamicWeight.  Karmada distributed replicas on both clusters.
I deleted all replicas on usa cluster (total: 58 of 80MiB each) . Then scheduled 50 replicas to see how the replicas are distributed.

**Anything else we need to know?**:
How AvailableReplicas is computed by Karmada. 

**Environment**:
- Karmada version: 1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 1.9.0
- Others: kubernetes version: 1.26.10
[env.txt](https://github.com/karmada-io/karmada/files/14586406/env.txt)
