### ISSUE TITLE
pod scheduling based nodeAffinity and node's grading in karmada 

### ISSUE THREAD

**Issue by snimje** [karmada-io/karmada#4710]
**Please provide an in-depth description of the question you have**:

Considering two clusters each with 20 BareMetal nodes. Capacity wise these nodes are sized equally. Two nodes from each clusters have SSD disks. These two nodes are labelled as "disktype=ssd".

Following is the pod's manifest :

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
```
As you can see this pod will land on specific node labelled as "disktype=ssd".
I would like schedule this pod through deployment (replica=1).
Many such pod deployments will be scheduled through karmada.

I would like to know - Is there a feature in karmada that can take into account the availability of resource on the nodes labelled as "disktype=ssd" and schedule the pod on the nodes with higher grading out of the two clusters ?

can I derive cluster weight based on available resources on specific nodes labelled as "disktype=ssd" ?

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:
