### ISSUE TITLE
Manifest to Ingress a Cluster

### ISSUE THREAD

**Issue by msfidelis** [karmada-io/karmada#4724]
I'm looking for a solution to a problem where I need to work on replicating some deployments between ephemeral clusters to split workloads between N sites in an agnostic manner. The applications have the same API and don't require parameter rewriting.

These clusters are of short/medium lifecycle, and I would like to dynamically enroll them in replication policies as they are created.

In my pipelines, I would like the manifests to be applied to some agnostic cluster and replicated.

My main question is: in the documentation, the enrollment of clusters is done via CLI. Is there any way to perform this registration through a manifest that can be applied by some automation via API or terraform Kubernetes provider?

**Comment by XiShanYongYe-Chang** [comment]
Hi @msfidelis, thanks for your feedback!

> Is there any way to perform this registration through a manifest that can be applied by some automation via API or terraform Kubernetes provider?

Is it possible to directly apply a Cluster object?

**Comment by msfidelis** [comment]
II'm looking for something like this:

```yaml
apiVersion: cluster.karmada.io/******
kind: ClusterRegistration
metadata:
  name: member1
spec:
# ...
  syncMode: "Push"
```

Instead of that:

```
kubectl karmada join member1 --kubeconfig=<karmada kubeconfig> --cluster-kubeconfig=<member1 kubeconfig>
```

Is possible?

**Comment by msfidelis** [comment]
I was looking for internal references at docs and came across this possibility, is it correct?

```yaml
---
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    displayName: cluster-01
  name: cluster-01
  namespace: karmada-system
spec:
  syncMode: Push
  apiEndpoint: https://CF3A52EFCA2AADF925DD3B986B2AC8D9.yl4.us-east-1.eks.amazonaws.com
  secretRef:
    namespace: karmada-system
    name: cluster-01-kubeconfig # My Base64 kubeconfig 
  provider: aws
  region: us-east-1
```
