### ISSUE TITLE
Propagate Service Account Token Secret

### ISSUE THREAD

**Issue by jklaw90** [karmada-io/karmada#4752]
**What happened**:
I made a PropagationPolicy for a secret with type `kubernetes.io/service-account-token` and it's ServiceAccount.
It appears [PR 1525](https://github.com/karmada-io/karmada/pull/1525) was made to ignore the secret. However, since 1.24 these secrets aren't automatically created anymore. 

**What you expected to happen**:
I'd expect for karmada to copy my secret and use my ResourceInterpreterCustomization to not copy the secret data.
Additionally i'd like karmada to handle this case and and always remove the cluster specific secret data.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl create ns test
kubectl apply -n test -f - <<EOF
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: secret-propagation
  namespace: test
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      namespace: test
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
EOF 
kubectl create sa -n test sa-test
kubectl get secrets -n test  # NOTE no secrets different functionality from the pr linked above due to 1.24
kubectl apply -n test -f - <<EOF
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sa-test-token
  annotations:
    kubernetes.io/service-account.name: sa-test
EOF
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
