### ISSUE TITLE
Feat: defining value by CEL in overriders 

### ISSUE THREAD

**Issue by Patrick0308** [karmada-io/karmada#4799]
**What would you like to be added**:
Supporting defining value by [CEL](https://github.com/google/cel-go) in overriders.
The target k8s resource is been exposed by `self` object in CEL expression.

- Plaintext Overrider: 
```
        plaintext:
          - path: /data/example
            operator: replace
            expression: self.spec.data
```
- Label Overrider: 
```
        labelsOverrider:
          - operator: add
             expression: 
               bar: self.label['arr']
```
- Annotation Overrider: 
```
        annotationsOverrider:
          - operator: add
             expression: 
               bar: self.labels['arr']
```
- Image Overrider: 
```
        imageOverrider:
          - component: Registry
            operator: add
            expression: self.annotations['registry']
```
- Command Overrider: 
```
        commandOverrider:
          - containerName: myapp
            operator: add
            expression:
              - self.annotations['arg1']
```

**Why is this needed**:
CEL is a single line language.  It's simple to written in yaml config . And It's been used on k8s validation.

**Comment by Patrick0308** [comment]
https://playcel.undistro.io/ This is a cel playground.

**Comment by chaunceyjiang** [comment]
A question: is 'self' referring to the OP themselves or the object chosen by the OP?

**Comment by Patrick0308** [comment]
> A question: is 'self' referring to the OP themselves or the object chosen by the OP?

The k8s resource chosen by the OP

**Comment by chaunceyjiang** [comment]
I believe this is a very good solution. 

My only concern at the moment is whether Karmada's simultaneous support for `Lua` and `CEL` will increase the learning cost for end users.

**Comment by Patrick0308** [comment]
> My only concern at the moment is whether Karmada's simultaneous support for Lua and CEL will increase the learning cost for end users.

Lua is not good for expression evaluation. 
If you only wanna using Lua on karmada, pls adding a ScriptOverrider feature:
```yaml
overrideRules:
    - targetCluster:
        clusterNames:
          - member1
          - member2
      overriders:
        scriptOverrider:
           raw_string: >
               function modifyObj(self)
                    //...
               end
```
