### ISSUE TITLE
Scheduler: support the ability to automatically assign replicas evenly

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#4805]
**What would you like to be added**:
### Background
We want to introduce a new replica assignment strategy in the scheduler, which supports an even assignment of the target replicas across the currently selected clusters.

### Explanation
After going through the filtering, prioritization, and selection phases, three clusters(`member1`, `member2`, `member3`) were selected. We will automatically assign 9 replicas equally among these three clusters, the result we expect is `[{member1: 3}, {member2: 3}, {member3: 3}]`.

**Why is this needed**:
### User Story
As a developer, we have a deployment with 2 replicas that needs to be deployed with high availability across AZs. We hope Karmada can schedule it to two AZs and ensure that there is a replica on each AZ.
![2AZ](https://github.com/karmada-io/karmada/assets/89241565/982ace7d-449e-4583-891e-08095bb44c1c)

Our PropagationPolicy might look like this:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo
  namespace: bar
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: foo
  placement:
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        dynamicWeight: AvailableReplicas
    spreadConstraints:
    - spreadByField: zone
      maxGroups: 2
      minGroups: 2
    - spreadByField: cluster
      maxGroups: 2
      minGroups: 2
```
But unfortunately, the strategy `AvailableReplicas` does not guarantee that our replicas are evenly assigned.

### Any ideas?
We can introduce a new replica assignment strategy like `AvailableReplicas`, maybe we can name it `AverageReplicas`. It is essentially different from static weight assignment, because it does not support spread constraints and is mandatory. When assigning replicas, it does not consider whether the cluster can place so many replicas.

**Comment by XiShanYongYe-Chang** [comment]
If the weights are set to the same, I understand that's the effect.

I understand that sometimes the number of replicas is not divisible by the number of clusters. In this case, there must be some clusters with one more replica.

**Comment by whitewindmills** [comment]
> In this case, there must be some clusters with one more replica.

For general scenarios, we can only achieve the maximum approximate average assignment. This is an unchangeable fact.

**Comment by XiShanYongYe-Chang** [comment]
How about describing it in detail at a community meeting?

**Comment by whitewindmills** [comment]
cc @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
Given the plausibility of this feature, and the fact that the difficulty of implementing it is not very complicated, how about we do this requirement as an [OSPP project](https://github.com/karmada-io/karmada/issues/4817) @RainbowMango @whitewindmills

**Comment by Vacant2333** [comment]
if user specified it the strategy, will it ignore the result of `score` step?

**Comment by whitewindmills** [comment]
> if user specified it the strategy, will it ignore the result of score step?

@Vacant2333
Great to hear your thoughts. I don't think this strategy has something to do with cluster scores. Cluster scores only are used to select clusters based on the cluster spread constraint.

**Comment by Vacant2333** [comment]
hello, i wonder know that when will be different with when we use `AverageReplicas`, at my understanding, static weight assignment will consider the cluster can create so many replicas, but `AverageReplcias` will just assign the replicas, any other situation will cause different schdule result?

(( thanks for your answer @whitewindmills 

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  #...
  placement:
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
```
