### ISSUE TITLE
Avoid pod rebuilding when scale up/down deployment under lazy mode PropagationPolicy/ClusterPropagationPolicy

### ISSUE THREAD

**Issue by sysucjl** [karmada-io/karmada#4931]
**Please provide an in-depth description of the question you have**:
There is two cluster `member-a` and `member-b` under karmada. We have PropagationPolicy `default-all-policy` (for all deploys) and `nginx-test-policy` (only for deploy `nginx-test`) as follow:
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: default-all-policy
  namespace: default
spec:
  activationPreference: Lazy
  priority: 0
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    namespace: default
  placement:
    clusterAffinity:
      clusterNames:
      - member-a
      - member-b
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member-a
            weight: 1
          - targetCluster:
              clusterNames:
                - member-b
            weight: 1
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-test-policy
  namespace: default
spec:
  activationPreference: Lazy
  priority: 100
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    namespace: default
    name: nginx-test
  placement:
    clusterAffinity:
      clusterNames:
      - member-a
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
```
At first, deploy `nginx-test` has 10 replicas and is matched by `nginx-test-policy`, so all replicas are propagated to member-a cluster.

Then we delete `nginx-test-policy`, and deploy `nginx-test` will be re-matched by `default-all-policy`. Because `default-all-policy` is enable lazy mode, so deploy `nginx-test` will not be rescheduled until there is an update on it.

If we scale up deploy `nginx-test` from 10 replicas to 12 replicas now,   half of the pods will be rescheduled to member-b and rebuilt, which is not what we expected. In this case , we hope that only the 2 new pod is scheduled to member-b ,instead of rescheduling the existing pods from member-a to member-b

**What do you think about this question?**:
Generally speaking, we hope to avoid rebuilding pods when scale up/down deployment, so karmada have any way to solve the above problem?

**Environment**:
- Karmada version: 1.9.0
- Kubernetes version: 1.20.7
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Ask the feature owner to help take a look~
/cc @chaosi-zju

**Comment by chaosi-zju** [comment]
hi @sysucjl, since you used static weight 1:1 schedule type, so half of the pods will be rescheduled to member-b and rebuilt, otherwise it will not meets the 1:1 weight.

if you want to avoid rebuilding, you ought to use dynamic weight schedule type like:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: default-all-policy
  namespace: default
spec:
  activationPreference: Lazy
  priority: 0
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    namespace: default
  placement:
    clusterAffinity:
      clusterNames:
      - member-a
      - member-b
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
```
