### ISSUE TITLE
NoSchedule taint for Cluster object not works

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4952]
**What happened**:

I add a `NoSchedule` taint to member1 Cluster as:
```yaml
taints:
- effect: NoExecute
  key: workload-rebalancer-test
  timeAdded: "2024-05-16T12:21:31Z"
```

Then I create a new deployment and propagate it to member1 and member2 cluster by a dynamic weight Policy whose `clusterTolerations` is defined as:
```yaml
clusterTolerations:
- effect: NoSchedule
  key: workload-rebalancer-test
  operator: Exists
  tolerationSeconds: 0
```

Since member1 cluster has `NoSchedule` taint, it should be all propagated to member2 cluster, but the actual result is both member1 and member2 cluster been propagated.

**What you expected to happen**:

the replicas should be all propagated to member2 cluster.

**How to reproduce it (as minimally and precisely as possible)**:

1）add `NoSchedule` taint to member1 cluster

```shell
kubectl --context karmada-apiserver patch cluster member1 --type='json' -p '[{"op": "replace", "path": "/spec/taints", "value": [{"key": "workload-rebalancer-test", "effect": "NoSchedule"}]}]'
```

2）write following yaml to local file `resource.yaml`

<details>
<summary>resource.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy-1
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-deploy-1
  template:
    metadata:
      labels:
        app: demo-deploy-1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - image: nginx
          name: demo-deploy-1
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: default-pp
spec:
  placement:
    clusterTolerations:
      - effect: NoSchedule
        key: workload-rebalancer-test
        operator: Exists
        tolerationSeconds: 0
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: demo-deploy-1
      namespace: default
```
</details>

3）check the schedule result in binding.

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaosi-zju** [comment]
We can take a look together

CC @XiShanYongYe-Chang

**Comment by dominicqi** [comment]
I don't quite understand. Isn't this saying that the taint is tolerated? Scheduling it should be a normal situation, right? If we don't declare tolerance, everything will be scheduled to member2.

**Comment by chaosi-zju** [comment]
No, the policy is:

```yaml
clusterTolerations:
- effect: NoSchedule
  key: workload-rebalancer-test
  operator: Exists
  tolerationSeconds: 0
```

In here, `tolerationSeconds: 0` means we do not tolerate the `workload-rebalancer-test:NoSchedule` taint.

Since cluster member1 has `workload-rebalancer-test:NoSchedule` taint, and we do not tolerate it, so all replicas should be schedule to member2. However, now, we still schedule replicas to member1 cluster, which means the taint is not work, and it is not expected.
