### ISSUE TITLE
Does Karmada support between different workloads?

### ISSUE THREAD

**Issue by mszacillo** [karmada-io/karmada#4968]
**Please provide an in-depth description of the question you have**:

Hello! I was looking over Karmada documentation and I wasn't able to find more information in this specific use-case. Essentially, in our use-case, each workload will have a unique job id defined in the job manifest which will be static and persisted when rescheduled to different clusters. However, we have cases where tenants want their workload to be duplicated across different clusters for HA purposes - in those cases, each workload will need to have their own id and manifest as well.

Is it possible to set a scheduling rule (via a label perhaps?) that would prevent two different workloads from being on the same cluster together? 

**Desired Use-case Example**

Let's assume we have 3 member clusters (Cluster X, Cluster Y, and Cluster Z).

1. Manifest A (with a label denoting the project) is applied to Karmada control-plane, a ResourceBinding is generated, and Manifest A's workload is scheduled on Cluster X.

2. Manifest B is applied to Kamada control-plane with the same label as Manifest A.

3.  Karmada scheduler sees the label, notices that there is already a resourcebinding that has bound Manifest A to Cluster X, and decides to schedule Manifest B to one of Cluster Y or Cluster Z. 

**Environment**:
- Karmada version: v1.9.0
- Kubernetes version: v1.29

**Comment by mszacillo** [comment]
Added note - this would be similar to the concept of pod antiAffinity in Kubernetes.

**Comment by whitewindmills** [comment]
do you require workloads to be spread across the same area? for example:
```yaml
spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - foo
            topologyKey: zone/beijing
```
the above example requires application `foo` to be spread across these nodes labeled `zone/beijing`.

**Comment by whitewindmills** [comment]
I gave the above example to clarify whether there is a situation similar to `podAntiAffinity`, that is, maybe you need to propagate CRDs to clusters with the same label. Currently, Karmada does not support features like `podAntiAffinity`. so I feel like it's a reasonable use case. in addition, do you require a CRD is only placed on one member cluster?

**Comment by mszacillo** [comment]
Ah yes, exactly! For now we are only scheduling the CRD on one member cluster, but it is possible for tenants to deploy other jobs that they'd like spread across different clusters. In that case this feature would be helpful.

**Comment by mszacillo** [comment]
Hi @whitewindmills ! I believe I saw you mention this issue in one of the previous Karmada community meetings. Is there a plan to add this support in the near future?

**Comment by whitewindmills** [comment]
> Is there a plan to add this support in the near future?

yes, extractly, I'm working on it. do you want to work with me on this design?

**Comment by mszacillo** [comment]
> yes, extractly, I'm working on it. do you want to work with me on this design?

Awesome! 

Happy to help if that would expedite the feature. Do you already have a design in mind that I could review?

**Comment by mszacillo** [comment]
> Not ready yet. if you have time, you can work on it yourself. I think we will end up with a great design.

Sounds good. I can think about this and create a document. Perhaps you can help review for the next community meeting?

**Comment by mszacillo** [comment]
Hi @RainbowMango @kevin-wangzefeng, do you have any opinions on the suggested changes for supporting this feature?

**Comment by RainbowMango** [comment]
Working on it, and I will talk to @kevin-wangzefeng maybe he doesn't see the notification.

**Comment by kevin-wangzefeng** [comment]
Thanks @mszacillo for initiating the discussion, sorry for replying late.
It seems you are looking for "inter-workload antiaffinity at clusters level", I would like to know the real world usecase and how are you going to map it as a configuration to the workloads.

**Comment by mszacillo** [comment]
Hi @kevin-wangzefeng, no worries at all. Thanks for taking a look!

Broadly speaking the jobs our users deploy can be divided into two groups:
1. Jobs that are handle a short amount of downtime (~5-10 minutes), for which regular application failover is generally sufficient. 
2. Jobs that are critical and require very strict uptime (can tolerate 5 seconds of downtime maximum).

This feature primarily relates to the 2nd category of jobs, for which having a single application will not be sufficient. Instead, we deploy two active jobs that are processing the same exact data. In the event that one application goes down, there will be another identical job running in a different cluster that can continue processing, while it waits for the other application to failover. 

We currently can achieve this by using a group of 4 clusters (2 clusters in data center A, 2 clusters in data center B). We can deploy two identical applications that are labeled A and B, and will be routed to their respective datacenter by a related propagationpolicy using clusteraffinity rules. However, this arrangement requires 4x total hardware to make sure each active application can fully failover. By supporting something like workload antiaffinity, we won't need to subdivide clusters by data center, but rather rely on the scheduler to make sure that two applications processing the same data are never scheduled to the same cluster. That way, we could just use a cluster group of 3 clusters (2 clusters with scheduled applications, 1 cluster for failover). 

I'll add this use-case and a diagram explaining the use-case more in the document. 

> how are you going to map it as a configuration to the workloads

I was planning on configuring the inter-workload antiaffinity within the related propagationpolicy. The drawback here is that we'd need 1 propagationpolicy per application group, but I ultimately believe progationpolicy is the most sensible place to define this behavior. This would mirror the way antiaffinity is defined on a resource like deployment which contains pod information.

**Comment by mszacillo** [comment]
Hi @RainbowMango @kevin-wangzefeng,

I've updated the doc to be clearer with the motivation and related use-case. Please let me know if you have questions. I'll be reviewing this document in the community meeting later this week.

**Comment by RainbowMango** [comment]
Hi @mszacillo @kevin-wangzefeng 
Good news!
As a follow-up action from the last community meeting, I ran a test with spread constraint capacity provided by PropagationPolicy, and found that seems to work. Here is what I found:

S1: Create one workload(Deployment) on Karmada
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

S2: Create a PropagationPolicy on Karmada:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    replicaScheduling:
      replicaSchedulingType: Duplicated
    spreadConstraints:
      - spreadByField: cluster
        maxGroups: 2
        minGroups: 2
```
The configuration above instructs Karmada to select 2 clusters from 3 clusters to deploy the referencing workload in `Deplicated` mode. 

S3: Check the result:
```
-bash-5.0# karmadactl get deployments.apps --operation-scope=members 
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   member1   2/2     2            2           14m   Y
nginx   member2   2/2     2            2           14m   Y
```
It shows that the workload was spread to `2` clusters instead of `3`.

In addition, the logs of `karmada-scheduler` also confirm this behavior:
```
I0221 08:31:58.171872       1 generic_scheduler.go:89] Feasible clusters found: [member1 member2 member3]
I0221 08:31:58.252832       1 generic_scheduler.go:101] Selected clusters: [member1 member2]
```

@mszacillo Let me know if this approach fits your case.
