### ISSUE TITLE
请问如何使用Karmada的控制平面直接在子集群中根据yaml创建pod

### ISSUE THREAD

**Issue by 1029219814** [karmada-io/karmada#500]
**What would you like to be added**:

**Why is this needed**:
目前业务，想要直接通过karmada在多个集群中来管理创建，删除，查询pod。网上搜索了下文档，以及使用了下demo，都是通过polic来分发deploy。
我通过yaml，直接在控制平面中创建pod。
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80        
      hostPort: 80 
```

pod的状态一直是pending
![image](https://user-images.githubusercontent.com/16161403/124571702-9e692780-de7a-11eb-80f1-620555562942.png)
然后我参考demo，弄了一个propagationpolicy，发现也并没有分发下去。
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Pod
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - minikube
        - kubernetes-admin
```
