### ISSUE TITLE
Upgrading karmada from v1.9 to v1.10 may cause karmada to lose management of member cluster resources

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#5003]
**What happened**:
When karmada upgrades from v1.9 to v1.10, if `karmada-controller-manager` is upgraded before `karmada-webhook`, karmada will lose the management of member resources.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Building a karmada cluster with release-1.9 images
- Use a PropagationPolicy and propagate deployment `nginx` to `member1`
```bash
(base) ➜  karmada git:(master) ✗ karmadactl get deployment
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   member1   2/2     2            2           65m   Y
```
- upgrade the image verson of `karmada controller manager` to v1.10(built with the latest code from the master branch)
- upgrade the image verson of `karmada webhook` to v1.10(built with the latest code from the master branch)
- You can see in the logs of "karmada controller manager":
```bash
I0530 02:54:03.474570       1 recorder.go:104] "Failed to sync work(karmada-es-member1/nginx-687f7fb96f) to cluster(member1), err: resource(kind=Deployment, default/nginx) already exists in the cluster member1 and the work.karmada.io/conflict-resolution strategy value is empty, Karmada will not manage this resource" logger="events" type="Warning" object={"kind":"Work","namespace":"karmada-es-member1","name":"nginx-687f7fb96f","uid":"6df74394-f776-4b42-b665-c384a3248a8d","apiVersion":"work.karmada.io/v1alpha1","resourceVersion":"211388"} reason="SyncFailed"
```
- The label ` karmada.io/managed: "true"` of deployment  `nginx` in member1 will be lost 
```yaml
        labels:
          app: nginx
          propagationpolicy.karmada.io/name: nginx
          propagationpolicy.karmada.io/namespace: default
          propagationpolicy.karmada.io/permanent-id: e0f71209-7209-4d69-9eb9-b73c95f555d3
          resourcebinding.karmada.io/permanent-id: 2d061c1b-9f56-4b93-bfed-dcbb8c21780e
          work.karmada.io/permanent-id: be2d1218-0326-4092-9eb8-73a4157ad432
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
