### ISSUE TITLE
To show the process of applying on resourcebinding status.

### ISSUE THREAD

**Issue by Patrick0308** [karmada-io/karmada#5019]
**What would you like to be added**:
To show the process of applying on resourcebinding status.

##### New Status Field:

`CurrentResourceVersion`:  the current resource version need to be applied.
`LastResourceVersion`：the last applied success resource version
`aggregatedStatus[].appliedResourceVersion`: the applied resource version on a cluster.

##### FullyApplied Condition Reason

FullyApplied: Applying current resource version successfully
FullyAppliedFailed: Applying failed
Applying:  In process of applying current resource version

#### Example
if in process of applying resource: 
```
  CurrentResourceVersion: "123"
  LastResourceVersion: "122"
  aggregatedStatus:
  - applied: true
    clusterName: cluster1
    appliedResourceVersion: "122"
    health: Unknown
  - applied: true
    clusterName: cluster2
    appliedResourceVersion: "122"
    health: Unknown
  conditions:
  - lastTransitionTime: "2024-06-03T06:42:29Z"
    message: Binding has been scheduled successfully.
    reason: Success
    status: "True"
    type: Scheduled
  - lastTransitionTime: "2024-06-03T06:42:29Z"
    message: Applying resource on cluster1
    reason: Applying
    status: "False"
    type: FullyApplied
  schedulerObservedGeneration: 7
```

 if a cluster applied failed: 
```
  CurrentResourceVersion: "123"
  LastResourceVersion: "122"
  aggregatedStatus:
  - applied: true
    clusterName: cluster1
    appliedResourceVersion: "123"
    health: Unknown
  - appliedMessage: "error message"
    clusterName: cluster2
    appliedResourceVersion: "122"
    health: Unknown
  conditions:
  - lastTransitionTime: "2024-06-03T06:42:29Z"
    message: Binding has been scheduled successfully.
    reason: Success
    status: "True"
    type: Scheduled
  - lastTransitionTime: "2024-06-03T06:42:29Z"
    message: error message
    reason: FullyAppliedFailed
    status: "False"
    type: FullyApplied
  schedulerObservedGeneration: 7
```

 if all clusters applied success: 
```
  CurrentResourceVersion: "123"
  LastResourceVersion: "123"
  aggregatedStatus:
  - applied: true
    clusterName: cluster1
    appliedResourceVersion: "123"
    health: Unknown
  - applied: true
    clusterName: cluster2
    appliedResourceVersion: "123"
    health: Unknown
  conditions:
  - lastTransitionTime: "2024-06-03T06:42:29Z"
    message: Binding has been scheduled successfully.
    reason: Success
    status: "True"
    type: Scheduled
  - lastTransitionTime: "2024-06-03T06:42:29Z"
    message: All works have been successfully applied
    reason: FullyAppliedSuccess
    status: "True"
    type: FullyApplied
  schedulerObservedGeneration: 7
```

**Why is this needed**:

Although the client updated resource, and checked  FullyApplied condition status which is true, the client not sure that new resource was applied to each cluster successfully. Because maybe that's in process of applying.
