### ISSUE TITLE
How does Karmada manage namespaces on member clusters ?

### ISSUE THREAD

**Issue by wengyao04** [karmada-io/karmada#5032]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Karmada version: Karmada v1.9.0
- Kubernetes version: 1.29.x
- Others:

Our platform are multi tenant platform and have an internal system to manage the onboarding clients. 
For example, we have dev-01-tier (two k8s clusters in different datacenter) and dev-02-tier (two k8s clusters in different datacenter). 
- Team A only onboard dev-01-tier, we create a namespace team-a on two clusters of dev-01-tier 
- Team B only onboard dev-02-tier, we create a namespace team-b on two clusters of dev-01-tier 

When we use Karmada to mange dev-01-tier and dev-02-tier, users need to submit jobs from Karmda control plane. We sync both team-a and team-b namespaces to Karmada control plane. But we find that 
- team-b namespace is created on dev-01-tier by Karmada
- team-a namespace is created on dev-02-tier by Karmada

How could we avoid this issue, should I use a ClusterPropagationPolicy for namespaces like

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    tier: dev-01-tier
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
spec:
  conflictResolution: Abort
  placement:
    clusterAffinity:
      clusterNames:
      - dev-01-tier-pw
      - dev-01-tier-ob
    replicaScheduling:
      replicaDivisionPreference: Duplicated
  resourceSelectors:
  - apiVersion: v1
    kind: Namespace
    labelSelector:
      matchLabels:
        tier: dev-01-tier
```
