### ISSUE TITLE
Any tutorial on how to use external metrics with karmada FHPA?

### ISSUE THREAD

**Issue by Orfeasfil** [karmada-io/karmada#5035]
I think it would be helpful a tutorial on how to scale with external metrics. Currently by just adding metrics type External in a `fhpa.yaml` file, like the following:

```
apiVersion: autoscaling.karmada.io/v1alpha1
kind: FederatedHPA
metadata:
  name: nephele-monitor-g
  namespace: nephele-monitor-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nephele-monitor-g
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
    scaleUp:
      stabilizationWindowSeconds: 10
  metrics:
    - type: External
      external:
        metric:
          name: sample_gauge
        target:
          type: AverageValue
          averageValue: 100
```

Results in the following error:
```
Error from server (Forbidden): error when creating "fhpa-g.yml": admission webhook "federatedhpa.karmada.io" denied the request: spec.metrics[0].type: Unsupported value: "External": supported values: "ContainerResource", "Object", "Pods", "Resource"
```

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.8
- Kubernetes version: 1.27.12

**Comment by chaosi-zju** [comment]
Hi @Orfeasfil, is this tutorial what you need?

**https://karmada.io/docs/tutorials/autoscaling-with-custom-metrics**

I'm not sure what you said about external metrics and our custom metrics are the same thing, just like demo of custom metrics `http_requests`

```yaml
apiVersion: autoscaling.karmada.io/v1alpha1
kind: FederatedHPA
metadata:
  name: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
    scaleUp:
      stabilizationWindowSeconds: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests
        target:
          averageValue: 700m
          type: Value
```

**Comment by chaosi-zju** [comment]
> In a similar situation in a single kubernetes cluster I managed to overcome this using the `external-metrics-api` like here:

Is here any document about how to achieve this effect?

In the `nginx-hpa` demo, I don't quite understand where `nginx-hpa` can find `sample_gauge` indicator in a single kubernetes cluster?

I mean, for example, besides `nginx-deployment`, here is a `foo-deployment` has `sample_gauge` indicator and another `buzz-deployment` also has `sample_gauge` indicator. How will `nginx-hpa` find `sample_gauge` indicator?

**Comment by OrfeasfilMLAB** [comment]
Sure, in a kubernetes cluster these are the steps I followed to do this:

1. Install `prometheus stack` using helm from [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)
2. Install `prometheus adapter` using helm from [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-adapter) with the following `values.yaml` file:
```
rules:
 default: false
 custom:
  - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
    resources:
      template: <<.Resource>>
    name:
      as: ""
      # matches: ^(.*)_total
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>) 
 external:
  - seriesQuery: '{namespace!="",__name__!~"^container_.*"}'
    resources:
      namespaced: false
    name:
      as: ""
      # matches: ^(.*)_total
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
prometheus:
   url: http://prom-stack-kube-prometheus-prometheus.monitor.svc.cluster.local
```
In this way the prometheus adapter forwards the metrics in both `custom-metrics-api` and `external-metrics-api`. In external metrics the field `namespaced: false` means that the metrics are without namespaces and for this reason the `HPA` that is configured e.g. in `default` namespace can scale based on metrics that have different namespace.

3. Install custom and external metrics api. For this reason apply the following yaml files:
- `external-metrics-api`:
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: prom-adapter-prometheus-adapter
    namespace: monitor
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```
   - `custom-metrics-api`:
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prom-adapter-prometheus-adapter
    namespace: monitor
  version: v1beta2
  versionPriority: 100
```

After this step you scale based on the `sample_gauge` metric.


**Note:** I assume that only a single deployment exports a metric to prometheus called `sample_gauge` (and this is actually my case). If other pods though export this metric, I think that this is not a problem because it will scale based on the `sample_gauge` metric from all pods from all deployments (e.g. based on the Average Value).

The goal here is to autoscale based on a metric that a different deployment exports in prometheus. In my case this worked, in a single kubernetes cluster.

Thank you for your time!
