### ISSUE TITLE
replace namespace controller with a clusterpropagation policy

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#5098]
**What would you like to be added**:

delete the namespace controller and replace it with a clusterpropagationpolicy

**Why is this needed**:

will simplify the setup and make it easy to change something about the policy

we had to do this since we wanted some customization and also did not like the "magic" namespace propagation

```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  labels:
    role: namespace
  name: namespace
spec:
  conflictResolution: Overwrite
  placement:
    clusterAffinity:
      clusterNames:
      - to-be-replaced
  resourceSelectors:
  - apiVersion: v1
    kind: Namespace
    labelSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kube-public
        - kube-node-lease
        - default
        - karmada-system
        - karmada-cluster
      - key: karmada.io/managed
        operator: NotIn
        values:
        - "true"

```

I'm not sure how the clusternames would work to be "all clusters", but otherwise I kind like what we ended up with
