### ISSUE TITLE
Improve the user experience of Failover

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#5150]
**What would you like to be added**:

Improve the user experience of Failover

**Why is this needed**:

The `Failover` and `GracefulEviction` features are currently in the Beta phase, which means they are enabled by default. 

There is a scenario where users propagate configuration resources by directly specifying the cluster names. When a cluster is disconnected from the Karmada control plane for several hours, it is identified as `NotReady`. Once the cluster recovers, the configuration resources on that cluster are deleted unexpectedly. If this occurs in a production environment, it could lead to serious consequences. 

Therefore, we need to optimize the Failover feature for this scenario to provide users with a more stable and reliable experience.

**Comment by whitewindmills** [comment]
are you saying that resources on unhealthy member clusters will be deleted cause they're migrated to other member clusters? if so, how to improve it?

**Comment by XiShanYongYe-Chang** [comment]
> are you saying that resources on unhealthy member clusters will be deleted cause they're migrated to other member clusters? 

That's it. One thing to note is that it's not migrated to another cluster, it's just moved out of the failed cluster.

>  if so, how to improve it?

I hope to hear everyone's opinion.

**Comment by whitewindmills** [comment]
> One thing to note is that it's not migrated to another cluster, it's just moved out of the failed cluster.

let me guest how it happened, no fit cluster?

**Comment by XiShanYongYe-Chang** [comment]
In other words, the clusters that need to be distributed have been listed, and these clusters will be distributed with configuration resources.

**Comment by whitewindmills** [comment]
does it look like this? if the cluster `foo` becomes unhealthy, the configuration will be stuck in the cluster until the cluster becomes healthy and then it is deleted. am I right?
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-pp
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: conf
  placement:
    clusterAffinity:
      clusterNames:
      - foo
      - bar
  ...

```
