### ISSUE TITLE
sa token cannot work with karmada proxy

### ISSUE THREAD

**Issue by warjiang** [karmada-io/karmada#5163]
**What happened**:
karamda provide a aggregated apisever for `cluster/proxy` subresources,  i created a service account and bind it to cluster role `cluster-admin`, i can visite member cluster resource throught karmadactl like `karmadactl -C member1 get pod -n default`.
But when it try to get secrect which correspond to the services account just created
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: karmada-dashboard-secret
  namespace: karmada-system
  annotations:
    kubernetes.io/service-account.name: karmada-dashboard
type: kubernetes.io/service-account-token
```
and generate a new kubeconfig with the jwt token like:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: karmada-apiserver
  cluster:
    server: https://172.18.0.2:5443
    insecure-skip-tls-verify: true
users:
- name: karmada-apiserver
  user:
    token: `kubectl --context=karmada-apiserver -n karmada-system get secret/karmada-dashboard-secret -ojsonpath='{.data.token}' | base64 -d && echo`
contexts:
- name: karmada-apiserver
  context:
    cluster: karmada-apiserver
    user: karmada-apiserver
current-context: karmada-apiserver
```

<img width="895" alt="image" src="https://github.com/karmada-io/karmada/assets/6478745/71e2b2d5-ef61-4b79-8759-d4ac46a6df6e">

**What you expected to happen**:
since the same effect of jwt token, the jwt token should work around.
<img width="935" alt="image" src="https://github.com/karmada-io/karmada/assets/6478745/f3f97f60-9c56-40f5-8a18-f8bf26521a41">

**How to reproduce it (as minimally and precisely as possible)**:
1. create a sa following the steps metioned in： https://github.com/karmada-io/dashboard/blob/main/docs/user-guide.md
    <img width="1251" alt="image" src="https://github.com/karmada-io/karmada/assets/6478745/2fbfb877-6d9d-4894-8934-f66053c0cd61">
2. use the token contet to fullfile the kubeconfig file like:
    
```yaml
apiVersion: v1
kind: Config
clusters:
- name: karmada-apiserver
  cluster:
    server: https://172.18.0.2:5443
    insecure-skip-tls-verify: true
users:
- name: karmada-apiserver
  user:
    token: `kubectl --context=karmada-apiserver -n karmada-system get secret/karmada-dashboard-secret -ojsonpath='{.data.token}' | base64 -d && echo`
contexts:
- name: karmada-apiserver
  context:
    cluster: karmada-apiserver
    user: karmada-apiserver
current-context: karmada-apiserver
```

and name the file as `token.config`
3.  execute cmd `karmadactl --kubeconfig ~/.kube/token.config -C member1 get pod -n default`

**Anything else we need to know?**:

After dive into the `cluster/proxy`,  i found that the user、group and the token used to access member cluster is not mathcing with each other.

for the file `pkg/util/proxy/proxy.go`
https://github.com/karmada-io/karmada/blob/625d8a5b779ee7f97ab03ff86239614a58157c69/pkg/util/proxy/proxy.go#L80C1-L117C2

the `authenticationv1.ImpersonateUserHeader` and `authenticationv1.ImpersonateGroupHeader` is set according to the request, however the bear token is set with the `impersonateToken` for target member cluster

i add some log to print the request info including user/group and token:
![image](https://github.com/karmada-io/karmada/assets/6478745/1abdf173-3b0f-4ee2-8c02-b6540e96326e)

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.9.0
- Others: the cluster is set by kind using the `hack/local-up-karmada.sh`
