### ISSUE TITLE
Karmada-scheduler will patch rb twice and there is higher latency

### ISSUE THREAD

**Issue by LivingCcj** [karmada-io/karmada#5203]
During the scheduling period, karmada-scheduler will patch the result of divided replicas to `rb.spec.clusters`, and then the scheduling status will be patched to `rb.status.Conditions`. the latency of two patch request will accounts for more of scheduler e2e scheduling latency. As shown below：
![image](https://github.com/user-attachments/assets/dd202fdc-9ba8-4b82-b658-7d771ad538da)
![image](https://github.com/user-attachments/assets/4f4d31db-26e0-40d7-bb93-e6fc80f025fb)

karmada scheduler e2e p50 latency：20.8ms
- patch rb.spec.cluster p50 latency：7.05ms
- patch rb.status.Conditions p50 lantency：8.6ms

---
testing tools: clusterload2
testing config (create workload qps is 50):
```
name: test

namespace:
  number: 2
  enableExistingNamespaces: true
  deleteAutomanagedNamespaces: false
  deleteStaleNamespaces: false
  prefix: test-perf
tuningSets:
  - name: Uniformtinyqps
    qpsLoad:
     qps: 50
  - name: Uniform1qps
    qpsLoad:
      qps: 50
steps:
  - name: Create deployment
    phases:
      - namespaceRange:
          min: 1
          max: 2
        replicasPerNamespace: 1000
        tuningSet: Uniformtinyqps
        objectBundle:
          - basename: test-deployment
            objectTemplatePath: "deployment.yaml"
            templateFillMap:
              Replicas: 20
      - namespaceRange:
          min: 1
          max: 2
        replicasPerNamespace: 1
        tuningSet: Uniform1qps
        objectBundle:
          - basename: test-policy
             objectTemplatePath: "policy.yaml"

```
