### ISSUE TITLE
failed to create job

### ISSUE THREAD

**Issue by mrlihanbo** [karmada-io/karmada#527]
**What happened**:
execution controller failed to dispatch job. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
E0714 14:03:39.426857       1 execution_controller.go:236] Failed to create resource in the given member cluster member2, err is Job.batch "pi" is invalid: [spec.template.metadata.labels[controller-uid]: Invalid value: map[string]string{"controller-uid":"7ade503c-dc0b-416e-8939-e5e1e4bc6b15", "job-name":"pi"}: must be '8b65be30-5875-4c11-89f3-c9f50e8da2e7', spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"controller-uid":"7ade503c-dc0b-416e-8939-e5e1e4bc6b15"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated]
E0714 14:03:39.426863       1 execution_controller.go:180] Failed to create resource(default/pi) in the given member cluster member2, err is Job.batch "pi" is invalid: [spec.template.metadata.labels[controller-uid]: Invalid value: map[string]string{"controller-uid":"7ade503c-dc0b-416e-8939-e5e1e4bc6b15", "job-name":"pi"}: must be '8b65be30-5875-4c11-89f3-c9f50e8da2e7', spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"controller-uid":"7ade503c-dc0b-416e-8939-e5e1e4bc6b15"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated]
```

**Anything else we need to know?**:
job template:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```
propagation policy:
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: job-propagation
spec:
  resourceSelectors:
    - apiVersion: batch/v1
      kind: Job
      name: pi
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```
