### ISSUE TITLE
Support json or yaml plaintext field overriding

### ISSUE THREAD

**Issue by Patrick0308** [karmada-io/karmada#5330]
**What would you like to be added**:
Support overriding a json or yaml  field value.
ConfigMap data's always has yaml or json value. For example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  #...
data:
  test.json:  |
   {"key": {"test": "value"}, {"key1": "value"}}
```
We need a overrider to modify test's value.
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: example
spec:
  #...
  overrideRules:
    - overriders:
        plaintextObjectOverrider:
          - path: /data/test.json 
            plaintext: 
            - path: /key/test
               operator: replace
               value: value1
```

**Why is this needed**:

When configmap data is very big, this feature is powerful.
