### ISSUE TITLE
suspension dispatching vs scale subresource

### ISSUE THREAD

**Issue by a7i** [karmada-io/karmada#5397]
**Please provide an in-depth description of the question you have**:
Scaling a Deployment in member-cluster for a Propagation Policy that has suspended dispatching still scales back to what the ResourceTemplate is. 

I need guidance on whether this is expected behavior or whether it needs to be fixed (and where). Providing steps below:

1. Quick start / Context
```
./hack/local-up-karmada.sh

export KUBECONFIG=/Users/amiralavi/.kube/karmada.config
kubectl config use-context karmada-apiserver
```

2. Create a PropagationPolicy

```
cat <<EOF | kubectl apply -f -
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
EOF
````

3. Create a Deployment with 1 replica
```
kubectl create deployment nginx --image nginx
```

4. Observe that you have a Deployment with 1 replica
```
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           13m
```

5. Suspend dispatching on PropagationPolicy
```
kubectl patch pp example-policy --type='json' -p='[{"op": "add", "path": "/spec/suspension", "value": {dispatching: true}}]'
```

6. Observe that ResourceBinding and Work are suspended
```
kubectl get rb nginx-deployment -ojsonpath='{.spec.suspension}'
{"dispatching":true}
```

```
kubectl get work -n karmada-es-member1  nginx-687f7fb96f -ojsonpath='{.spec.suspendDispatching}'
true
```

7. Scale deployment in member cluster
```
export KUBECONFIG=/Users/amiralavi/.kube/members.config
kubectl config use-context member1

kubectl scale deploy/nginx --replicas=2
```

8. Observe that it scales back down to 1
```
kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           16m
```

```
kubectl get events

79s         Normal   ScalingReplicaSet         deployment/nginx              Scaled up replica set nginx-77b4fdf86c to 2 from 1
79s         Normal   ScalingReplicaSet         deployment/nginx              Scaled down replica set nginx-77b4fdf86c to 1 from 2
```

**What do you think about this question?**:

**Environment**:
- Karmada version: latest on main
- Kubernetes version: `1.27.3` -- what comes with quick-start
- Others:
