### ISSUE TITLE
Add more info in resourcebinding status

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#575]
**What would you like to be added**:
add `synced` and `message` in resourcebinding status, an example

```
status:
  aggregatedStatus:
  - Status: null
    clusterName: qa-cloud-u02
    message: 'Failed to apply all manifests (0/1): resource(kind=Deployment, demo)
      already exist in cluster qa-cloud-u02 but not managed by karamda'
    synced: false
```

`synced` is added so that we can know whether the workload is distributed correctly, if failed `message` tells why it fails.Now work object has workload status from member cluster ,but work object is stored in karmada-es-CLUSTERNAME, if we want get status from work object ,we have to know which cluster the workload is distributed to first.

**Why is this needed**:
