### ISSUE TITLE
Is there any setting or feature that can prevent karmada reconciling resources in cluster

### ISSUE THREAD

**Issue by maoyangLiu** [karmada-io/karmada#5756]
For example, when I create a deployment in karmada, it will be deployed to cluster-a and cluster-b. When I edit the spec property of the deployment in cluster-a, karmada will reconcile the deployment in cluster-a with the data in karmada. Is there any setting or feature that can prevent karmada from reconciling the corresponding changes?

Thanks a lot

**Comment by zhzhuang-zju** [comment]
@maoyangLiu You can use Karmada's custom resource interpreter `Retain` to resolve control conflicts between the control plane and member clusters.

**Comment by zhzhuang-zju** [comment]
To facilitate understanding, we can use the `maxSurge` field of the `Deployment nginx` as an example.
```yaml
# nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

The `Deployment nginx` has been propagated to member clusters `member1` and `member2`. To modify the `spec.strategy.rollingUpdate.maxSurge` field of the `Deployment nginx` in `member1` without being overridden by the control plane, you can achieve this using the following `retain` strategy.

```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: nginx-deployment-maxsurge-retention
spec:
  target:
    apiVersion: apps/v1
    kind: Deployment
  customizations:
    retention:
      luaScript: >
        function Retain(desiredObj, observedObj)
          desiredObj.spec.strategy.rollingUpdate.maxSurge = observedObj.spec.strategy.rollingUpdate.maxSurge
          return desiredObj
        end
```

The `target` is used to match the target resource. The `Retain` function is a Lua script, where `desiredObj` is the object expected by the control plane, and `observedObj` is the object observed from the member cluster. The final effect is that the `maxSurge` field of the `Deployment nginx` in the member cluster is controlled by the member cluster.
