### ISSUE TITLE
Cannot access karmada-interpreter-webhook by configuring Service in ResourceInterpreterWebhookConfiguration

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#5958]
**What happened**:

It was found that since v1.6, users cannot access `karmada-interpreter-webhook` component by configuring Service in ResourceInterpreterWebhookConfiguration according to the guidance in https://github.com/karmada-io/karmada/tree/master/examples/customresourceinterpreter, such as configuration:

```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterWebhookConfiguration
metadata:
  name: examples
webhooks:
- clientConfig:
    caBundle: {{CABundle}}
    service:
      namespace: karmada-system
      name: karmada-interpreter-webhook-example
      port: 443
      path: /interpreter-workload
  interpreterContextVersions:
  - v1alpha1
  name: workloads.example.com
  rules:
  - apiGroups:
    - workload.example.io
    apiVersions:
    - v1alpha1
    kinds:
    - Workload
    operations:
    - InterpretReplica
    - ReviseReplica
    - Retain
    - AggregateStatus
    - InterpretHealth
    - InterpretStatus
    - InterpretDependency
  timeoutSeconds: 3
```

**What you expected to happen**:

Can access karmada-interpreter-webhook by configuring Service in ResourceInterpreterWebhookConfiguration.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This issue was introduced by #2999

**Environment**:
- Karmada version: After v1.6
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
After analysis, I found two possible ways.
Method 1: Deploy a Service of type ExternalName in karmada-apiserver, pointing to kube-apiserver in the host cluster:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: karmada-interpreter-webhook-example
  namespace: karmada-system
spec:
  type: ExternalName
  externalName: karmada-interpreter-webhook-example.karmada-system.svc.cluster.local
```
Method 2: Modify CustomizedInterpreter's Service resolver ServiceResolver. When the error returned by ClusterIPServiceResolver is 404, that is Service is not found, use DefaultServiceResolver instead.

What do you think? @RainbowMango @lxtywypc @chaosi-zju

**Comment by lxtywypc** [comment]
Well...I didn't get it.  

If the user specify the service in `ResourceInterpreterWebhookConfiguration`, why the service couldn't be found? Is it a mistake during deployment the workload and configuration?

**Comment by XiShanYongYe-Chang** [comment]
Hi @lxtywypc https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/README.md?plain=1#L1

According to the current document, the target service is not deployed in karmada-apiserver. The target service exists only in the host cluster. Therefore, the message "Service Not Found" is displayed.

**Comment by lxtywypc** [comment]
Okay, I got it.   

In my opinion, I prefer the Method 2, falling back seems to be a common way when access resources or server failed.  

And more, how about using host configs to access karmada-related components? They seems to be deployed in host cluster only and can't be propagated to member clusters.

**Comment by XiShanYongYe-Chang** [comment]
@lxtywypc thanks for your reply!

> And more, how about using host configs to access karmada-related components? They seems to be deployed in host cluster only and can't be propagated to member clusters.

I'm sorry, I'm a little confused. Can you explain it a little bit?

**Comment by lxtywypc** [comment]
Sure.   

Now we have two apiservers, one is kube-apiserver which is used to deploy control-plane components, and another is karmada-apiserver which is used to operate the resources to be propagated to member clustrers, right?   

Then, for this example, the service as well as the interpreter deployment are both created through kube-apiserver, and they are unnecessary, or even can't be propagated to member clusters, so the karmada-apiserver couldn't find the service, right?  

So I mean that when the karmada-apiserver try to access to the karmada system(or related) components, especially the webhook interpreter, if we could use kube-apiserver configs?

**Comment by XiShanYongYe-Chang** [comment]
Thanks for the reply. I see what you mean.

> So I mean that when the karmada-apiserver try to access to the karmada system(or related) components, especially the webhook interpreter, if we could use kube-apiserver configs?

Doing so would introduce a new kubeconfig for karmada components, such as karmada-controller-manager, to access karmada-host exclusively, which would be a big change. Therefore, I recommend deploying a service of the ExternalName type in karmada-apiserver and directing the service to the service in karmada-host.

**Comment by lxtywypc** [comment]
Another question, interpreter webhook seems no different with other kubernetes webhooks in accessing ways, and of course karmada-webhook works well, do they deployed in different ways? Or the behavior of apiserver and interpreter accessor are different?

**Comment by XiShanYongYe-Chang** [comment]
Good question, as you say, I modified the propagationpolicy configuration in validatingwebhookconfigurations:

```
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {caBundle}
    service:
      name: karmada-webhook
      namespace: karmada-system
      path: /validate-propagationpolicy
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: propagationpolicy.karmada.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - policy.karmada.io
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - propagationpolicies
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 3
```

When I apply a new pp resource, it reports:

```log
Error from server (InternalError): error when creating "samples/nginx/propagationpolicy.yaml": Internal error occurred: failed calling webhook "propagationpolicy.karmada.io": failed to call webhook: Post "https://karmada-webhook.karmada-system.svc:443/validate-propagationpolicy?timeout=3s": service "karmada-webhook" not found
```

It can be seen that the error report is the same.  The only difference between them, what comes to mind is that the validatingwebhookconfigurations are defined by the Karmada system, which clarifies the way to use the url; while the resource interpreter webhook is defined by the user, we give suggestions, not requirements.
