### ISSUE TITLE
Will SpreadConstraints make effect when replicaSchedulingType is Divided?

### ISSUE THREAD

**Issue by vie-serendipity** [karmada-io/karmada#5986]
**Please provide an in-depth description of the question you have**:
When I test `SpreadConstraints`, I found it will not make effect when replicaSchedulingType is Divided. I have two clusters, where one cluster has significantly more resources than the other, and all replicas are scheduled to the larger cluster. I expect to add `SpreadConstraints` to make sure the smaller cluster will get at least one replica. However, it seems not both for dynamic and static.

**What do you think about this question?**:
I'm not sure my use case is correct. If it is, I think `SpreadConstraints` should be supported even replicaSchedulingType is Divided.

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by XiShanYongYe-Chang** [comment]
In theory, it should be in effect. Can you share how your PropagationPolicy is set?

**Comment by vie-serendipity** [comment]
The pp is as following:
```  yaml
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: whoami
      namespace: test
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    spreadConstraints:
      - maxGroups: 2
        minGroups: 2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        dynamicWeight: AvailableReplicas
```
