### ISSUE TITLE
I have deployed multiple PropagationPolicies and now I want to create pods, how do I specify which PropagationPolicy to use in yaml

### ISSUE THREAD

**Issue by Schwarao** [karmada-io/karmada#6001]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by zhzhuang-zju** [comment]
@Schwarao 
https://github.com/karmada-io/karmada/blob/cac020e238da85ee598a144e7f5796b5cd96d38e/pkg/apis/policy/v1alpha1/propagation_types.go#L62-L69
The `ResourceSelectors` in `PropagationPolicy` are used to filter resources, for example,
```yaml
# PropagationPolicy
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: pod-propagation
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
      name: foo

#pod
apiVersion: v1
kind: Pod
metadata:
  name: foo
```

You can also share the YAML of your Pod, and then we can take a look at how to properly configure the `ResourceSelectors`.

**Comment by Schwarao** [comment]
@zhzhuang-zju 
I have two propagationpolicies here, followed by pods, how to specify which propagationpolicy is adopted for different pods
![image](https://github.com/user-attachments/assets/b304e015-bb96-487a-9680-78b6a5ad4fff)
![image](https://github.com/user-attachments/assets/cb9532fe-d580-4c98-bdf6-ddcb535722a6)

**Comment by zhzhuang-zju** [comment]
If you want to use propagationpolicy `test-propagation` to propagate  pod `test1`, you can config your propagationpolicy `test-propagation` as

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
      name: test1
```

By distinguishing between the `resourceSelectors` of different `propagationpolicy`, you can achieve the purpose of a propagationpolicy matching a specific pod or a certain class of pods.

**Comment by Schwarao** [comment]
> If you want to use propagationpolicy `test-propagation` to propagate pod `test1`, you can config your propagationpolicy `test-propagation` as
> 
> ```yaml
> apiVersion: policy.karmada.io/v1alpha1
> kind: PropagationPolicy
> metadata:
>   name: test-propagation
>   namespace: default
> spec:
>   resourceSelectors:
>     - apiVersion: v1
>       kind: Pod
>       name: test1
> ```
> 
> By distinguishing between the `resourceSelectors` of different `propagationpolicy`, you can achieve the purpose of a propagationpolicy matching a specific pod or a certain class of pods.

Can I do this by being given a different namespace?

**Comment by zhzhuang-zju** [comment]
you mean the namespace of PropagationPolicy？

**Comment by zhzhuang-zju** [comment]
Sure. For example:
there are four pods 
```yaml
# pod1
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: foo1

# pod2
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: foo1

# pod3
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: foo2

# pod4
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  namespace: foo2
```

and two PropagationPolicies
```yaml
# foo1-pp
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo1-pp
  namespace: foo1
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod

# foo2-pp
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: foo2-pp
  namespace: foo2
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
```

Then, `pod1` and `pod2` will bind to `foo1-pp`, while `pod3` and `pod4` will bind to `foo2-pp`.
