### ISSUE TITLE
Proposal: Improve TargetCluster and Overriders in OverridePolicy

### ISSUE THREAD

**Issue by lfbear** [karmada-io/karmada#603]
**What would you like to be added**:
- If there needs override for a resource, I hope that can be described in only one CR
- I can define `TargetCluster` / `Overriders` separately and custom combination them
- expandable `overriders` across resources  if possible (https://github.com/karmada-io/karmada/issues/540#issuecomment-886013591)

**Why is this needed**:

**background:**
   We have many workloads that have different commands in member clusters, now we must create so many 'Overriders' CRs for each member cluster and each workload, such as 10 deployments and 10 member clusters that will be 100 CRs typed 'Overriders', that will increase management costs.

**Comment by lfbear** [comment]
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: example-override
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  
  targetClusters:
    m1:
      clusterNames:
        - member1
    m2:
      labelSelector:
        matchLabels:
          role: x-members
        
  overridersItems:
    o1:
      plaintext:
        - path: "/metadata/annotations"
          operator: add
          value:
            foo: bar
    o2:
      imageOverrider:
      - component: Registry
        operator: replace
        value: ghcr.io

  rules:
    - m1: o1  # the key is the title of 'targetClusters' items and the value can be the title of 'overridersItems' or a slice of them
    - m2: o2
```
