### ISSUE TITLE
karmada-search ResourceRegistry resourceSelectors can not merge the same GVK's namespace

### ISSUE THREAD

**Issue by JimDevil** [karmada-io/karmada#6064]
**What happened**:
I have two yaml config of resourceregistry,they just namespace different
```yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: secret-search-ns1
spec:
  targetCluster:
    clusterNames:
      - cluster-1
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      namespace: ns1
```
```yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: secret-search-ns2
spec:
  targetCluster:
    clusterNames:
      - cluster-1
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      namespace: ns2
```
when I apply them ,karmada-search just cached one namespace resource,the latter one override the previous one namespace
get ResourceRegistry:
![Image](https://github.com/user-attachments/assets/ad2bf19c-f2fd-475f-87f5-5d410224b73f)
get secret,juet get ns1's secret:
![Image](https://github.com/user-attachments/assets/5f4b9680-4ca9-49dc-8639-7ef2e28bb5ff)

**What you expected to happen**:
I think karmada-search should merge these namespace,
it should cached ns1 and ns2,this should be a bug.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.12.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
