### ISSUE TITLE
register a cluster with pull mode failed

### ISSUE THREAD

**Issue by hl8086** [karmada-io/karmada#6114]
**What happened**:
failed to register a cluster with pull mode via karmadactl, error:
```go
I0213 15:23:17.208857    5584 register.go:922] Signing certificate of csr agent-rbac-generator-cls-jy2j754p49z successfully 
[karmada-agent-start] Waiting to check cluster 
W0213 15:23:17.273389    5584 cluster.go:191] Failed to retrieve cluster(cls-jy2j75). error: clusters.cluster.karmada.io "cls-jy2j75" is forbidde
n: User "system:karmada:agent:rbac-generator" cannot get resource "clusters" in API group "cluster.karmada.io" at the cluster scope
```

**How to reproduce it (as minimally and precisely as possible)**:
reference [here](https://karmada.io/docs/userguide/clustermanager/cluster-registration/#register-cluster-with-pull-mode) to register a cluster
```
karmadactl register <masterip>:31360 --token=<TOKEN> --discovery-token-ca-cert-hash=<CA> --kubeconfig=xxx --ca-cert-path=xxx --karmada-agent-image=xxx --v=6
```

**Anything else we need to know?**:
need to create a clusterrole and clusterrolebinding for User "system:karmada:agent:rbac-generator" first ?

**Environment**:
-  karmadactl version:
```
v1.12.0
```
- Others:

**Comment by zhzhuang-zju** [comment]
@hl8086 Hi, how did you install your Karmada cluster? Helm, local-up, or karmada-operator?

**Comment by zhzhuang-zju** [comment]
The `karmadactl register` command has undergone significant changes in version v1.12.0, which restricts the member clusters' permissions to access control-plane resources. If your Karmada is version v1.11.0 and you use the `karmadactl` of version v1.12.0 to execute the `register` command, then you need to:
- Configure appropriate RBAC resources.
agent-rbac.yaml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:bootstrap-signer-clusterinfo
  namespace: kube-public
rules:
- apiGroups:
  - ""
  resourceNames:
  - cluster-info
  resources:
  - configmaps
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:bootstrap-signer-clusterinfo
  namespace: kube-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:karmada:bootstrap-signer-clusterinfo
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:agent-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-bootstrapper
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:bootstrappers:karmada:default-cluster-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:certificatesigningrequest:autoapprover
rules:
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/clusteragent
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:agent-autoapprove-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:karmada:certificatesigningrequest:autoapprover
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:bootstrappers:karmada:default-cluster-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:certificatesigningrequest:selfautoapprover
rules:
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/selfclusteragent
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:agent-autoapprove-certificate-rotation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:karmada:certificatesigningrequest:selfautoapprover
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:karmada:agents

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:agent-rbac-generator
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    karmada.io/bootstrapping: rbac-defaults
  name: system:karmada:agent-rbac-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:karmada:agent-rbac-generator
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:karmada:agent:rbac-generator
```

```bash
kubectl --kubeconfig path/to/{your-karmada-kubeconfig-file} --context  karmada-apiserver apply -f agent-rbac.yaml
```

- During the execution of `karmadactl register`, you need to manually approve the CSR (Certificate Signing Request).
In release v1.12.0, the `agentcsrapproving` controller was introduced to automatically approve the agent CSR. However, if you are using v1.11.0, you can approve it manually.
```bash
kubectl --kubeconfig path/to/{your-karmada-kubeconfig-file} --context  karmada-apiserver certificate approve {csrname}
```
You can pay attention to the output logs of `karmadactl register`, as this step will be prompted within them.
