### ISSUE TITLE
请问如何分发CRD资源

### ISSUE THREAD

**Issue by yanlingsishao** [karmada-io/karmada#612]
1、是否支持分发crd
2、是否支持分发crd下的资源

这两种我直接用PropagationPolicy测试都不成功

**Comment by RainbowMango** [comment]
支持的。可以把你操作过程和捕获到的日志信息贴出来。

**Comment by yanlingsishao** [comment]
```
[root@mopaas-wang-01 yaml]# kubectl get crd
NAME                                           CREATED AT
clusteroverridepolicies.policy.karmada.io      2021-08-06T03:46:23Z
clusterpropagationpolicies.policy.karmada.io   2021-08-06T03:46:23Z
clusterresourcebindings.work.karmada.io        2021-08-06T03:46:24Z
clusters.cluster.karmada.io                    2021-08-06T03:46:22Z
dewebs.myapp.ops.com                           2021-08-16T06:40:11Z
overridepolicies.policy.karmada.io             2021-08-06T03:46:23Z
propagationpolicies.policy.karmada.io          2021-08-06T03:46:23Z
replicaschedulingpolicies.policy.karmada.io    2021-08-06T03:46:23Z
resourcebindings.work.karmada.io               2021-08-06T03:46:24Z
serviceexports.multicluster.x-k8s.io           2021-08-06T03:46:24Z
serviceimports.multicluster.x-k8s.io           2021-08-06T03:46:24Z
works.work.karmada.io                          2021-08-06T03:46:24Z
```
1、这里面有一个我自定义的crd dewebs.myapp.ops.com，首先我先针对crd进行分发
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: crd-propagation
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: dewebs.myapp.ops.com
  placement:
    clusterAffinity:
      clusterNames:
        - member4
```
针对crd的分发是失败的
![image](https://user-images.githubusercontent.com/28887713/129657252-a8a8f339-320a-41c2-bfde-f1261743fb89.png)

2、然后我针对crd的资源进行分发
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: crd-propagation
spec:
  resourceSelectors:
    - apiVersion: myapp.ops.com/v1
      kind: Deweb
      name: deweb-sample
  placement:
    clusterAffinity:
      clusterNames:
        - member4
```
如果我已经在member4安装过crd了，资源就可以分发成功，如果没有，就分发失败

**Comment by RainbowMango** [comment]
从报错信息看，你已经创建了PropagationPolicy（crd-propagation），接着apply是失败的，原因是resource selector不允许修改。

把PropagationPolicy删除重建就可以了

**Comment by yanlingsishao** [comment]
目前：我删除重建，没有发生报错，但是crd并没有分发到其他集群
期待：CustomResourceDefinition部署的controller也可以分发么，就是创建该crd所用的controller-manager等等会分发么，还是只支持通过这个crd创建的资源进行分发

**Comment by RainbowMango** [comment]
> 目前：我删除重建，没有发生报错，但是crd并没有分发到其他集群

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: crd-propagation
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: dewebs.myapp.ops.com
  placement:
    clusterAffinity:
      clusterNames:
        - member4
```
如果创建这个Policy，并且在karmada-apiserver中创建了CRD的情况下，应该是可以的。

如果不行，可以提供详细的复现步骤，我这边可以看一下。

**Comment by RainbowMango** [comment]
> 期待：CustomResourceDefinition部署的controller也可以分发么，就是创建该crd所用的controller-manager等等会分发么，还是只支持通过这个crd创建的资源进行分发

不确定我理解了你的意思。但我觉得没什么问题，不管处理CR资源的控制器是deployment还是Pod都是可以的。

**Comment by yanlingsishao** [comment]
集群分为karmada-apiserver、member4、member5
1、在karmada-apiserver创建crd
https://gitee.com/yanlingsishao/kubebuilder/raw/master/deweb/all-in-one.yaml
crd名称 dewebs.myapp.ops.com
![image](https://user-images.githubusercontent.com/28887713/129685081-0dd0da6e-c67d-40c2-8c4d-c52ff1396bc1.png)

2、在karmada-apiserver上创建policy
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: crd-propagation
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: dewebs.myapp.ops.com
  placement:
    clusterAffinity:
      clusterNames:
        - member4
        - member5
```
3、在member4、member5上未创建crd dewebs.myapp.ops.com
![image](https://user-images.githubusercontent.com/28887713/129684985-bc57a78c-667e-40d6-9003-3bae2f0691f8.png)

**Comment by RainbowMango** [comment]
@mrlihanbo 
Can you help reproduce this on your side?

**Comment by mrlihanbo** [comment]
> @mrlihanbo
> Can you help reproduce this on your side?

ok, I will reproduce this on my side

**Comment by mrlihanbo** [comment]
你好，使用ClusterPropagationPolicy来分发，ClusterPropagationPolicy对象是cluster scope的。
```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: crd-propagation
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: dewebs.myapp.ops.com
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```
