### ISSUE TITLE
Override Policy misfunction: replace all object when using "add" operator

### ISSUE THREAD

**Issue by iamyeka** [karmada-io/karmada#6139]
**Please provide an in-depth description of the question you have**:
Step to reproduce the issue: 
1. apply a OverridePolicy
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: dev-gy-override-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: ReplicaSet
  overrideRules:
    - targetCluster:
        clusterNames:
          - dev-gy
      overriders:
        plaintext:
          - path: /spec/template/metadata/annotations
            operator: add
            value:
              Cloudnative.music.netease.com/zone: dev-gy
```
2. apply a ReplicaSet into karmada k8s
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: dev-2
spec:
  template:
    metadata:
      annotations:
         a: b
         c: d
```
3. query the rs scheduled into the true k8s, dev-gy
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: dev-2
spec:
  template:
    metadata:
      annotations:
       Cloudnative.music.netease.com/zone: dev-gy
```

What i expect is the output like:
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: dev-2
spec:
  template:
    metadata:
      annotations:
         a: b
         c: d
         Cloudnative.music.netease.com/zone: dev-gy
```

**What do you think about this question?**:
Look like the whole annotations field is replaced instead of being added a label.
Is the situation above meet the design requirements?

**Environment**:
- Karmada version: 1.12.3
- Kubernetes version: 1.19.3
- Others:

**Comment by iamyeka** [comment]
@RainbowMango Could you help confirm if it's designed like this on purpose?

**Comment by RainbowMango** [comment]
> Look like the whole annotations field is replaced instead of being added a label.

@chaunceyjiang Is this the expected behavior?  

@iamyeka It is recommended to use [AnnotationOverrider](https://github.com/karmada-io/karmada/blob/8ad4b5a989519b1ae841c94eac7f59af690a229d/pkg/apis/policy/v1alpha1/override_types.go#L123-L129), please have a try and let me know if it fits your expectation.

**Comment by iamyeka** [comment]
> > Look like the whole annotations field is replaced instead of being added a label.
> 
> [@chaunceyjiang](https://github.com/chaunceyjiang) Is this the expected behavior?
> 
> [@iamyeka](https://github.com/iamyeka) It is recommended to use [AnnotationOverrider](https://github.com/karmada-io/karmada/blob/8ad4b5a989519b1ae841c94eac7f59af690a229d/pkg/apis/policy/v1alpha1/override_types.go#L123-L129), please have a try and let me know if it fits your expectation.

I use karmada to schedule ReplicaSet to muitiple K8s and need to override pod's annotations in ReplicaSet. It looks like that cannot be done by [AnnotationOverrider](https://github.com/karmada-io/karmada/blob/8ad4b5a989519b1ae841c94eac7f59af690a229d/pkg/apis/policy/v1alpha1/override_types.go#L123-L129).

**Comment by RainbowMango** [comment]
Yeah, thanks for the reminder. 

Please try with this configuration:
```yaml
      overriders:
        plaintext:
          - path: /spec/template/metadata/annotations/zone  # PS: not sure what happens with `Cloudnative.music.netease.com/zone`
            operator: add
            value:
              dev-gy
```

Refer to #3923 where shows a similar example.

**Comment by iamyeka** [comment]
> Yeah, thanks for the reminder.
> 
> Please try with this configuration:
> 
>       overriders:
>         plaintext:
>           - path: /spec/template/metadata/annotations/zone  # PS: not sure what happens with `Cloudnative.music.netease.com/zone`
>             operator: add
>             value:
>               dev-gy
> Refer to [#3923](https://github.com/karmada-io/karmada/issues/3923) where shows a similar example.

Thanks for the solution, it works. By the way, using config below can set cloudnative.music.netease.com/zone: dev-gy into annotations.
```
      overriders:
        plaintext:
          - path: /spec/template/metadata/annotations/cloudnative.music.netease.com~1zone
            operator: add
            value:
              dev-gy
```

The issue can be closed.
