### ISSUE TITLE
ResourceRegistry namespace filed support slice

### ISSUE THREAD

**Issue by JimDevil** [karmada-io/karmada#6155]
**What would you like to be added**:
the namespace filed of ResourceRegistry's resourceSelectors support slice
for example
```
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: foo
spec:
  # ...
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: 
      - ns1
      - ns2
```
**Why is this needed**:
If i need selector two different namespace ,i must create two ResourceRegistry CR.
i think change the namespace to slice  is better.
