### ISSUE TITLE
The default resource interpreter should not fill clusterName to Hostname field when aggregating status

### ISSUE THREAD

**Issue by zach593** [karmada-io/karmada#6248]
**What happened**:

When we were using karmada to distribute `Service` resources recently, we found that when the lb entry of a loadBalancer type Service is of ip type, karmada's default resourceinterpreter would write the name of the member cluster in the `Hostname` field. The original intention was obviously to make it easier to identify when the member cluster returns two different lb ips, but the `Hostname` field clearly indicates that it should be a legal domain name that can be queried by dns. So we think that filling in the member cluster name is inappropriate.

In actual situations, it does have an impact. Since our karmada will connect to multiple provider of multiple AZs, some provider can provide domain names as lb entries , while others provide ip. When these two services are in the same list, it causes interference in UI display and program identification.

**What you expected to happen**:

When aggregate status for Service and Ingress, default resourceInterpreter should not fill `Hostname` field with cluster name.

**How to reproduce it (as minimally and precisely as possible)**:

- run a local up karmada
- propagate a service or ingress resource to member clusters
- use `kubectl edit --subresource=status` to update the resource status in the member cluster, manually fill in the ingress ip
- print the service/ingress in karmada cluster.

**Anything else we need to know?**:

At present, we have found 3 places with this behavior: the default interpreter of service, ingress and pdb. Since there may be pods with the same name in multiple clusters, I guess we can only temporarily not modify pdb. So I proposed a pr #6249 to remove the behavior of adding clusterName for service and ingress. If users still want to identify the lb domain name and ip for each member cluster, I think they should read the `ResourceBinding`.

But removing clusterName will expose another problem. Most cloud providers can provide the same lb entry for services with the same name in multiple clusters. It probably doesn't make sense to repeat the same information multiple times in the status, so I wrote another PR #6252 to deduplicate it, but the code implementation is very verbose, so I would very much welcome reviews that can help optimize the implementation.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by zhzhuang-zju** [comment]
As additional information:
Deploy a service of type LoadBalancer to the member cluster. The status of the service in the member cluster is as follows:
```yaml
status:
  loadBalancer:
    ingress:
    - ip: 0.0.0.0
      ipMode: VIP
    - hostname: user.example.com
      ip: 8.8.8.8
      ipMode: VIP
```
The status of the service on the control plane after the aggregation is: 
```yaml
status:
  loadBalancer:
    ingress:
    - hostname: member1
      ip: 0.0.0.0
      ipMode: VIP
    - hostname: user.example.com
      ip: 8.8.8.8
      ipMode: VIP
```
