### ISSUE TITLE
karmada-scheduler Keep restarting

### ISSUE THREAD

**Issue by songant** [karmada-io/karmada#6305]
**What happened**:

karmada-scheduler Keep restarting
**kubectl describe pod，info**：

![Image](https://github.com/user-attachments/assets/01dcd51e-d661-4454-91fd-fe9bba0d60f7)

kubectl logs [podname],info:

![Image](https://github.com/user-attachments/assets/24d9da86-0e15-479a-adac-023e3c516de9)

![Image](https://github.com/user-attachments/assets/d7abca39-1863-4a84-a023-eb35327cf5e4)

**karmada-scheduler removes the master election, add --leader-elect=false**,logs:

![Image](https://github.com/user-attachments/assets/70fca962-bb91-4969-8538-7f1a5144b24c)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
kubernetes cluster version:1.30.8
**Environment**:
- Karmada version: 1.13.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
How did you install the Karmada instance?

**Comment by songant** [comment]
@RainbowMango use helm deploy karmada operator and deploy karmada cr.

**Comment by RainbowMango** [comment]
> How to reproduce it (as minimally and precisely as possible)

Can you share how to reproduce it?

**Comment by songant** [comment]
```
deploy karmada oprator：
helm install karmada-operator \
        -n karmada-system  \
        --create-namespace \
        ./xxx.tgz \
        --set operator.replicaCount=1 \
        --set operator.image.registry=xxx \
        --set operator.image.repository=xxxx \
        --set operator.image.tag=xxxx 

deploy karmada cr：
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada
  namespace: karmada-system
spec:
  components:
    etcd:
      local:
        imageRepository: xxx/etcd
        imageTag: 3.4.13-3
        replicas: 3
        volumeData:
          volumeClaim:
            metadata:
              name: etcd-data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
              storageClassName: openebs-hostpath
    karmadaAPIServer:
      imageRepository: xxx/kube-apiserver-amd64
      imageTag: v1.30.8
      replicas: 2
      serviceType: NodePort
    karmadaAggregatedAPIServer:
      imageRepository: xxx/karmada-aggregated-apiserver
      imageTag: v1.13.1
      replicas: 2
    karmadaControllerManager:
      imageRepository: xxx/karmada-controller-manager
      imageTag: v1.13.1
      replicas: 2
      extraArgs:
        feature-gates: "PropagationPolicyPreemption=true"
    karmadaScheduler:
      imageRepository: xxx/karmada-scheduler
      imageTag: v1.13.1
      replicas: 2
    karmadaDescheduler:
      imageRepository: xxx/karmada-descheduler
      imageTag: v1.13.1
      replicas: 2
    karmadaWebhook:
      imageRepository: xxx/karmada-webhook
      imageTag: v1.13.1
      replicas: 2
    kubeControllerManager:
      imageRepository: xxx/kube-controller-manager
      imageTag: v1.30.8
      replicas: 2
    karmadaMetricsAdapter:
      imageRepository: xxx/karmada-metrics-adapter
      imageTag: v1.13.1
      replicas: 2
  hostCluster:
    networking:
      dnsDomain: cluster.local
```
