### ISSUE TITLE
Failed to propagate a kube-system secret to members

### ISSUE THREAD

**Issue by tomwang57** [karmada-io/karmada#6347]
**What happened**:
A Secret can't be propagated to members by PropagationPolicy or ClusterPropagationPolicy.

Relevant files:

`gc.secret.yaml`:
```yaml
apiVersion: v1
data:
  application_default_credentials.json: ewogICJ0eXBlIjogInN....
kind: Secret
metadata:
  creationTimestamp: "2025-04-30T12:46:10Z"
  name: gc-secret
  namespace: kube-system
  resourceVersion: "563107"
  uid: 2448f329-7d6a-46e6-96e2-b4bf67d8d69a
type: Opaque
```
`pp.yaml`:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: juicefs-pp
  namespace: kube-system
spec:
  resourceSelectors:
    - kind: Secret
      name: gc-secret
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
```

`cpp.yaml`:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: juicefs-cpp
spec:
  resourceSelectors:
    - kind: Secret
      name: gc-secret
      namespace: kube-system
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
```

I tried both the `pp.yaml` and `cpp.yaml`, but neither worked: the `gc-secret` is not propagated to any member.

**What you expected to happen**:
After applying the `gc.secret.yaml` in karmada-apiserver, either applying the above `pp.yaml` or `cpp.yaml` will propagate the secret to the members.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install local development env: https://karmada.io/docs/installation/#install-karmada-for-development-environment
2. In karmada-apiserver: 

```sh
kubectl apply -f gc.secret.yaml
kubectl apply -f pp.yaml or cpp.yaml
```
3. Check if the secret is propagated to member1
```sh
k get secrets -n kube-system --context member1 --kubeconfig ~/.kube/members.config
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
`karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitShortCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.23.8", Compiler:"gc", Platform:"darwin/arm64"}`
- Others: macOS/kind/docker destop
