### ISSUE TITLE
Cert expiry logic in helm installation method

### ISSUE THREAD

**Issue by ryanwuer** [karmada-io/karmada#6436]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.13
- Kubernetes version: v1.19.3
- Others:

I've used Helm to install Karmada. Now i have some concern about the cert stuff. Here i see the code:

https://github.com/karmada-io/karmada/blob/bd5692f08a259c1a959dc3fd1944071be9fda729/charts/karmada/templates/pre-install-job.yaml#L443

It looks like the expiry for server-ca.crt is fixed to be 365 days. While the expiry of karmada.crt issued by the server-ca.crt can be self-defined.

https://github.com/karmada-io/karmada/blob/bd5692f08a259c1a959dc3fd1944071be9fda729/charts/karmada/templates/pre-install-job.yaml#L445
```
certs:
  ## @param certs.mode "auto" and "custom" are provided
  ## "auto" means auto generate certificate
  ## "custom" means use user certificate
  mode: auto
  auto:
    ## @param certs.auto.expiry expiry of the certificate
    expiry: 43800h
```

So, if i set to expiry to like 50 years, can i use the kubeconfig generated by the Karmada for 1 year or 50 years?
