### ISSUE TITLE
karmada fail to delete completeply  pods in  some clusters

### ISSUE THREAD

**Issue by magnate3** [karmada-io/karmada#644]
**What happened**:
I create pods and delete pods like this : 
（1）kubectl create  -f samples/nginx/deployment.yaml 
deployment.apps/nginx-karmada created
 there are two clusters : clusterA 和clusterB
 （2）kubectl create  -f samples/nginx/replicaschedulingpolicy_simple.yaml 
replicaschedulingpolicy.policy.karmada.io/foo created
 （3）kubectl create  -f samples/nginx/propagationpolicy.yaml
 propagationpolicy.policy.karmada.io/nginx-propagation created
 clusterA  and clusterB  create separately pods successfully
 （4）kubectl delete  -f samples/nginx/deployment.yaml 
deployment.apps "nginx-karmada" deleted

 clusterB   delete  pod successfully ,  but clusterA fails to  delete 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
Could you please post your `yaml`s that I can try to reproduce it on my side?

**Comment by magnate3** [comment]
@RainbowMango  my yamls are like this :

[root@bogon nginx]# cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-karmada
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
[root@bogon nginx]# cat replicaschedulingpolicy_simple.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: default
      name: nginx-karmada
  totalReplicas: 3
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: [k8sA]
        weight: 1
      - targetCluster:
          clusterNames: [k8sB]
        weight: 2
[root@bogon nginx]# cat propagationpolicy.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-karmada
  placement:
    clusterAffinity:
      clusterNames:
        - k8sA
        - k8sB

**Comment by RainbowMango** [comment]
Hi @magnate3 
I formated your yaml and changed cluster names(k8sA-->member1, k8sB-->member2), and everything works as expected.

The `deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-karmada
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
```

The `replicaschedulingpolicy_simple.yaml`:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: default
      name: nginx-karmada
  totalReplicas: 3
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: [member1]
        weight: 1
      - targetCluster:
          clusterNames: [member2]
        weight: 2
```

The `propagationpolicy.yaml`:
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-karmada
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```
