### ISSUE TITLE
When the federated resource quota is insufficient, the workload scale-up will still succeed

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#6467]
**What happened**:
We introduced federatedresourcequota enforcement in v1.14 to achieve unified quota management across clusters. This is realized by intercepting modifications to workload requirements and the `spec.clusters` field of resource bindings. However, the federated resource quota mechanism fails when workloads scale up.

The root cause is that the binding controller synchronizes workload modifications to member clusters. When the replicas scheduling policy is set to "duplicated", the binding controller does not revise the workload's replicas according to the scheduling results in `bindingSpec.clusters`. As a result, the scale-up operations of workloads are directly synchronized to member clusters, rendering the federated resource quota ineffective.

The detailed process is as follows:
1. Edit the replicas of a workload.
2. The binding controller synchronizes the workload's replicas to member clusters.
3. Karmada-scheduler performs rescheduling, and the request to update `bindingSpec.clusters` is intercepted due to insufficient quota.

As described above, even though the update request for `bindingSpec.clusters` is blocked, the replicas of the workload in member clusters are still synchronized, leading to the failure of the federated resource quota.

**What you expected to happen**:
 When the federated resource quota is insufficient, the workload scale-up will be blocked.

**How to reproduce it (as minimally and precisely as possible)**:
step1: setup karmada env by `hack/local-up-karmada.sh`
step2: deploy a federatedresourcequota
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: FederatedResourceQuota
metadata:
  name: test
spec:
  overall:
    cpu: 50m
```
step3: deploy a deployment and propagate it to member1
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-6d7f8d5f5b
  namespace: default
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - member1
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
    name: nginx
    namespace: default
```
step4: scale up the deployement's replicas to 2
The final result:
```bash
$ karmadactl get deployments.apps nginx --operation-scope members --clusters member1 
NAME    CLUSTER   READY 
nginx   member1   2/2   
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.14.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
