### ISSUE TITLE
跨集群服务发现访问不通

### ISSUE THREAD

**Issue by yanlingsishao** [karmada-io/karmada#648]
**cluster:**
 member1
 member2

我在member1上有deploy和svc，想通过member2访问member1
下面是操作步骤

### 1、member1上，我创建deploy和svc
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
```
### 2、karmada上，我又创建了ServiceExport和policy
```
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: nginx
```
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-export-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceExport
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```
### 3、在karmada上，我创建了ServiceImport和policy
```
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  name: nginx
spec:
  type: ClusterSetIP
  ports:
  - port: 80
    protocol: TCP
```
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-import-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member2
```

### 4、在member2上出现derived-nginx的svc
我通过derived-nginx的clusterip去访问，访问不通，请问我的的测试有问题么

**Comment by XiShanYongYe-Chang** [comment]
@yanlingsishao  在步骤2、3之前，需要在成员集群上安装`ServiceExport`和`ServiceImport` CRD。

karmada在安装过程中默认安装了这两个CRD，因此可以通过创建`ClusterPropagationPolicy`将这两个CRD分发下去：

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: serviceexport-policy
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serviceexports.multicluster.x-k8s.io
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: serviceimport-policy
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serviceimports.multicluster.x-k8s.io
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```
