### ISSUE TITLE
Deployment desired READY replicas is different of realistic replicas 

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#689]
**What happened**:
When I put the deployment to two member cluster by one PropagationPolicy, the realistic pod replicas more than deployment template defined replicas.

**What you expected to happen**:
The realistic number of replica is equal to the derived number of replica.

**How to reproduce it (as minimally and precisely as possible)**:
```
[root@m2 ~]# kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   2/1     2            2           118m
```

```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - m2-cluster
        - m3-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx 
```

**Anything else we need to know?**:
This situation might brings confusion to users. 

**Environment**:
- Karmada version: v0.8.0
- Others:
