### ISSUE TITLE
Bug of aggregating status to resourcebinding

### ISSUE THREAD

**Issue by mrlihanbo** [karmada-io/karmada#706]
**What happened**:
I create a propagation policy to propagate a configmap to 3 member clusters. then, I change the placement in propagation policy. But the status in resource binding are not correct after I modify the placement.
```
spec:
  clusters:
  - name: member1
  - name: member3
  resource:
    apiVersion: v1
    kind: ConfigMap
    name: game-config
    namespace: default
    resourceVersion: "1744"
status:
  aggregatedStatus:
  - applied: true
    clusterName: member1
  - applied: true
    clusterName: member3
  - applied: true
    clusterName: member2
```

**What you expected to happen**:
The aggregatedStatus should not include the applied status of member2.

**How to reproduce it (as minimally and precisely as possible)**:
create a configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: default
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30 
```
create a propagation policy:
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: cm-propagation
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: game-config
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
```

delete member2 cluster in the placement field of propagation policy by follow command:
```
kubectl edit pp cm-propagation
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:
