### ISSUE TITLE
[lfx-mentorship-2022-summer]Cluster Resource modeling

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#772]
**What would you like to be added**:
We don't want to collect and store each node's resources in detail(That's a burden for Karmada to maintain the information), but we want to build a `resource model` for each cluster, something like:
```yaml
resourceModel:
  - grade:
      cpu: "1"
      memory: 2Gi
    count: 10
  - grade:
      cpu: "2"
      memory: 4Gi
    count: 6
  - grade:
      cpu: "4"
      memory: 8Gi
    count: 2
  - grade:
      cpu: "8"
      memory: 16Gi
    count: 1
```

**Why is this needed**:
In the scheduling progress, the `karmada-scheduler` makes decisions as per a bunch of factors, one of the factors is the resource details of the cluster.

We introduced [ResourceSummary](https://github.com/karmada-io/karmada/blob/b5af525b1969ee6040c27e0daefcac3c59c84d48/pkg/apis/cluster/types.go#L141) to the [Cluster API](https://github.com/karmada-io/karmada/blob/b5af525b1969ee6040c27e0daefcac3c59c84d48/pkg/apis/cluster/types.go#L15). For example:
```yaml
  resourceSummary:
    allocatable:
      cpu: "4"
      ephemeral-storage: 206291924Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 16265856Ki
      pods: "110"
    allocated:
      cpu: 950m
      memory: 290Mi
      pods: "11"
```
But the `ResourceSummary` is not precise enough, it mechanically counts the resources on all nodes, but ignores the fragment resources.(For example, a cluster with 2000 node, 1 core cpu left on each node, from the `ResourceSummary`, we get there are 2000 core CPU left for the cluster, that's not correct.)

## References
- LFX Mentorship: https://github.com/cncf/mentoring/tree/main/lfx-mentorship
- timeline: https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2022/02-Summer#timeline

**Comment by anutosh491** [comment]
Hello @RainbowMango  , hope you're doing well , this is Anutosh here from India . I'm an open source enthusiast and I'm currently involved with communities based on numerical and symbolic computations/algorithms in math and physics like numpy, sympy, networkx.

I am keen to take part in the LFX Mentorship program for the summer term and this project interests me. But being new to the project , I would be glad if you could share any relevant resources/links I should be going through for getting to know the project and the library better . Thank you !

**Comment by AALEKH** [comment]
> Hello @RainbowMango , hope you're doing well , this is Anutosh here from India . I'm an open source enthusiast and I'm currently involved with communities based on numerical and symbolic computations/algorithms in math and physics like numpy, sympy, networkx.
> 
> I am keen to take part in the LFX Mentorship program for the summer term and this project interests me. But being new to the project , I would be glad if you could suggest any relevant resources/links I should be going through as a beginner for getting to know the project and the library better . Thank you !

Hey @RainbowMango Any Update on this comment, I would like to volunteer to work on this issue under LFX Mentorship Program? Happy to send you a proposal about the same, Thanks!!

**Comment by RainbowMango** [comment]
@AALEKH @anutosh491 Thanks for reaching us. This task requires some basic knowledge about [Kubernetes](https://k8s.io), and after that, you can get started with [Karmada quick start](https://github.com/karmada-io/karmada#quick-start).
Here is [some documents](https://github.com/karmada-io/karmada/tree/master/docs/userguide) too that might be helpful to understand the project.

**Comment by anutosh491** [comment]
```
resourceModel:
  - grade:
      cpu: "1"
      memory: 2Gi
    count: 10
  - grade:
      cpu: "2"
      memory: 4Gi
    count: 6
```
Hello @RainbowMango , I've been framing my cover letter for the LFX mentorship program and had couple doubts regarding this proposed model.
1) What information does `grade` and `count` convey ? I realize that grade would be type `corev1.ResourceList` and would be carrying pairs of resources and quantity !
2) `resourceModel` would also be introduced in the `Cluster API` only right ?
3) I got this point but still what do you mean by fragment resources in the line below ?
 > But the ResourceSummary is not precise enough, it mechanically counts the resources on all nodes, but ignores the fragment resources
