### ISSUE TITLE
chart support multi-version conversion

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#776]
**What would you like to be added**:
Let chart apply CRD with multi-version conversion.

**Why is this needed**:
As #722 has enabled the API conversion. 
We can't apply the generated CRD directly anymore, we have to:
- 1. set CA to the patch file, e.g. https://github.com/karmada-io/karmada/blob/c4e22717dfff7e87301236cf218df7a636bc2164/hack/deploy-karmada.sh#L201-L202
- 2. apply the patch to the generated CRD, e.g.
https://github.com/karmada-io/karmada/blob/c4e22717dfff7e87301236cf218df7a636bc2164/hack/deploy-karmada.sh#L107

**Comment by RainbowMango** [comment]
Hi @algebra2k @jrkeen 
Can you help or share some instructions about how to do it?

**Comment by jrkeen** [comment]
I have a preliminary idea.
* 1. The `webhook_in_clusterresourcebindings.yaml` and `webhook_in_resourcebindings.yaml` need to convert to `_webhook_in_clusterresourcebindings.tpl` and `_webhook_in_resourcebindings.tpl` in templates.

For example:
_webhook_in_resourcebindings.tpl
```YAML
{{- define "karmada.webhook.resourcebindings" -}}
{{ $name :=  include "karmada.name" .}}
{{ $namespace := include "karmada.namespace" .}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcebindings.work.karmada.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        url: https://{{ $name }}-webhook.{{ $namespace }}.svc:443/convert
        {{- include "karmada.webhook.caBundle" . | nindent 6 }}
      conversionReviewVersions: ["v1beta1", "v1"]
```
* 2. Modify pre-install-job YAML.
1. crds-configmap.yaml

https://github.com/karmada-io/karmada/blob/c4e22717dfff7e87301236cf218df7a636bc2164/charts/templates/pre-install-job.yaml#L96-L104
Roughly:
```YAML
  crds-configmap.yaml: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ $name }}-crds
      namespace: {{ include "karmada.namespace" . }}
    data:
      {{- print "webhook_in_resourcebindings.yaml: " | nindent 6 }} |-
        {{- include "karmada.webhook.resourcebindings" . | nindent 8 }}
      ...
```
2. .volumes:

https://github.com/karmada-io/karmada/blob/c4e22717dfff7e87301236cf218df7a636bc2164/charts/templates/pre-install-job.yaml#L154-L165
Roughly:
```YAML
        volumeMounts:
        - name: mount
          mountPath: /opt/mount
        - name: configs
          mountPath: /opt/configs
      volumes:
      - name: mount
        configMap:
          name: {{ $name }}-config
          items: 
          - key: webhook_in_clusterresourcebindings.yaml
            path: patches/webhook_in_clusterresourcebindings.yaml
          - key: cluster.karmada.io_clusters.yaml
            path: bases/cluster.karmada.io_clusters.yaml
          - key: kustomization.yaml
            path: kustomization.yaml
          ...
```
3. install.sh

https://github.com/karmada-io/karmada/blob/c4e22717dfff7e87301236cf218df7a636bc2164/charts/templates/pre-install-job.yaml#L12-L21
Roughly:
```YAML
data:
  install.sh: |-
    #!/bin/bash
    set -ex
    kubectl kustomize "/opt/configs/_crds" | kubectl apply -f -
```
Some details need to be perfected.
