### ISSUE TITLE
Support Job Scheduling

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#893]
**What would you like to be added**:
Now karmada could only divide replicas with `Deployment`. I wanna add `Job` scheduling in scheduler.

**Why is this needed**:
Job is an important kind of native workload. We could divide replicas by `spec.parallelism`. And the `spec.completions` could be divided weighted by scheduling result.

/cc @RainbowMango @qianjun1993 @gf457832386

**Comment by RainbowMango** [comment]
Hi @Garrybest 
Can you list the user stories? Let's figure out if it is reasonable or do we have alternative solutions.

**Comment by Garrybest** [comment]
Hi @RainbowMango. This issue is very similar with deployment replica scheduling. 

Guess that we have a job with `spec.completions=100` and `spec.parallelism=10`, which means the job must be computed 100 times while there are up to 10 replicas running at the same time.

Maybe every replica needs large resources, like AI training Job. We may not have so much resource in one cluster. So it is reasonable to divide the job into member clusters. For example, we could divide it into 3 sub-jobs:

Cluster A: `spec.completions=50`, `spec.parallelism=5`
Cluster B: `spec.completions=30`, `spec.parallelism=3`
Cluster C: `spec.completions=20`, `spec.parallelism=2`

When all sub-jobs are done, the main job in `karmada` will be considered as success. Note that when we divide replicas, we only concern about `spec.parallelism`. Actually, this field represents the max desired replicas because there are up to `spec.parallelism` replicas running at the same time. So for load balance, we divide the `spec.completions` by the weight of `spec.parallelism`.

**Comment by gf457832386** [comment]
I get more information ~hhhhIs this an example of a real production environment?

**Comment by gf457832386** [comment]
get more interests~ A new type task: Batch Job , which differs from long-running tasks.
①This solution is simple and effective. The target is to minimize the job completion time, assuming that all clusters have sufficient resources at the same level of computing.
②I want to know more: Is this an example of a real production environment？ Do you know some specific questions need to solve?

**Comment by Garrybest** [comment]
> I want to know more: Is this an example of a real production environment？ Do you know some specific questions need to solve?

Hi @gf457832386, that's true. We have some huge AI training jobs and we would like to run those jobs by using resource as much as possible so that they could be trained more quickly.

**Comment by RainbowMango** [comment]
Thanks @Garrybest , it is reasonable to me.
I know @mrlihanbo used a lot `Job` in production, I'd like to ask him for comment.

**Comment by Garrybest** [comment]
Glad to hear that. Looking forward to your reply😄

**Comment by Garrybest** [comment]
Glad to hear that. Looking forward to your reply😄.

**Comment by RainbowMango** [comment]
Hi @Garrybest 
There are 3 main types of Jobs as mentioned in [Parallel execution for Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs).

Which type of Job is in your use case? `Parallel Jobs with a fixed completion count` or `Parallel Jobs with a work queue`, or both?

We can't presume both `.spec.completions` and `.spec.parallelism` are set properly, one of them might be unset.

**Comment by RainbowMango** [comment]
E.g. After apply following Job, the `.spec.completions` is null:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 10
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```
env: kubernetes v1.20

**Comment by Garrybest** [comment]
Hi @RainbowMango, I suppose to support both.
I didn't notice the 3rd kind. So I guess if the `.spec.completions` is not set, we should not divide the `.spec.completions`. However, `.spec.parallelism` will never be null since the default number is 1 if we don't set it.
Fortunately, `.spec.parallelism` is the `replicas` field that have a influence on replica division.

**Comment by Garrybest** [comment]
See [here](https://github.com/kubernetes/kubernetes/blob/dccaa29e1531b59f4b4b48d0e0c4777cb530c555/pkg/apis/batch/v1/defaults.go#L34-L41)

**Comment by RainbowMango** [comment]
@Garrybest 

I just tested this feature with the following yamls against the master, seems the job replica (`parallelism`) didn't divide into member clusters. Is there something wrong?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 10
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: job-propagation
spec:
  resourceSelectors:
    - apiVersion: batch/v1
      kind: Job
      name: pi
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
```

**Comment by Garrybest** [comment]
Hi @RainbowMango, I have tested your case and didn't find anything wrong. Here is my ResourceBinding object.

```yaml
spec:
  clusters:
  - name: member2
    replicas: 5
  - name: member1
    replicas: 5
  replicaRequirements:
    resourceRequest:
      cpu: "0"
      ephemeral-storage: "0"
      memory: "0"
      pods: "0"
  replicas: 10
  resource:
    apiVersion: batch/v1
    kind: Job
    name: pi
    namespace: default
    resourceVersion: "480"
status:
  aggregatedStatus:
  - applied: true
    clusterName: member2
    status:
      active: 5
      startTime: "2021-11-12T11:32:07Z"
  - applied: true
    clusterName: member1
    status:
      active: 5
      startTime: "2021-11-12T11:32:07Z"
```

**Comment by RainbowMango** [comment]
Let me test again.

**Comment by RainbowMango** [comment]
oh it's my bad. I just broke the function...

The fix is available now. #954 . What a stupid mistake!

**Comment by Garrybest** [comment]
Oh I see, I tested the function before `explorer` commit.

**Comment by RainbowMango** [comment]
By the way, the `resourceRequest` always exist in RB, even though no resource requirement in the resource template, like 
```yaml
    resourceRequest:
      cpu: "0"
      ephemeral-storage: "0"
      memory: "0"
      pods: "0"
```

I guess it'd be better to remove them. In addition, the resource `pod: 0` makes no sense. How do you think?
