### ISSUE TITLE
Add events or conditions for cluster object

### ISSUE THREAD

**Issue by mrlihanbo** [karmada-io/karmada#922]
**What would you like to be added**:
Add events or conditions in cluster object

**Why is this needed**:
I have met a scenario that cluster status controller failed to get the list of APIs installed in the member cluster which lead to empty status in cluster object.
```
E1104 09:33:49.516781      13 cluster_status_controller.go:160] Failed to get APIs installed in the member cluster: lhb-test, err is : unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
I suggest to add events or conditions for cluster object when collectting status failed.

**Comment by pigletfly** [comment]
ref https://github.com/karmada-io/karmada/issues/398

**Comment by mrlihanbo** [comment]
> ref #398

Events will disappear after --event-ttl time and can't be seen in status field. I think conditions is also needed, shown as below:
```
    conditions:
    - lastTransitionTime: "2021-11-05T05:57:40Z"
      message: cluster is reachable and health endpoint responded with ok
      reason: ClusterReady
      status: "True"
      type: Ready
    - lastTransitionTime: "2021-11-05T05:57:40Z"
      message: get the list of APIs installed in the member cluster succeed
      reason: GetAPIEnablements
      status: "True"
      type: APIEnablements
    - lastTransitionTime: "2021-11-05T05:57:40Z"
      message: get the kubernetes version of member cluster succeed
      reason: GetKubernetesVersion
      status: "True"
      type: KubernetesVersion
```
