### ISSUE TITLE
Pod resource leak when delete jobs

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#969]
**What happened**:
1. Create a Job in karmada and propagate it into member clusters.
2. Then delete the job from karmada control plane: `kubectl delete job pi`. 

You will see the pod in member clusters would not be deleted. Their ownerRef will be removed, while it has pointed to the job in member cluster before. 
It is noticed that if you delete the job from member cluster, the pod garbage collection would not have any problems. 
This issue is a little strange. May have something to do with the deletion approach of karmada.

**What you expected to happen**:
The job deletions will not cause any resource leak.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 10
  template:
    spec:
      containers:
        - name: pi
          image: perl:latest
          command: [ "perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)" ]
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
      restartPolicy: Never
  backoffLimit: 4
  completions: 30
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx
spec:
  resourceSelectors:
    - apiVersion: batch/v1
      kind: Job
      name: pi
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        dynamicWeight: AvailableReplicas
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:
